#pragma once

#include "common/primitives.h"

#include <cstddef>

namespace bmsx {

constexpr u32 APU_SAMPLE_RATE_HZ = 44100u;
constexpr u32 APU_SAMPLE_RAM_BASE = 0x40000000u;
constexpr u32 APU_SAMPLE_RAM_BYTES = 512u * 1024u;
constexpr u32 APU_SAMPLE_RAM_ADDRESS_MASK = APU_SAMPLE_RAM_BYTES - 1u;
constexpr u32 APU_TRANSFER_FIFO_WORD_CAPACITY = 16u;
constexpr u32 APU_TRANSFER_WORDS_PER_SECOND = APU_SAMPLE_RATE_HZ * 24u;
constexpr u32 APU_TRANSFER_MODE_STOP = 0u;
constexpr u32 APU_TRANSFER_MODE_MANUAL_WRITE = 1u;
constexpr u32 APU_TRANSFER_MODE_DMA_WRITE = 2u;
constexpr u32 APU_TRANSFER_MODE_DMA_READ = 3u;
constexpr u32 APU_TRANSFER_MODE_MASK = 0x3u;
constexpr u32 APU_RATE_STEP_Q16_ONE = 0x10000u;
constexpr u32 APU_GAIN_Q12_FRACTION_BITS = 12u;
constexpr u32 APU_GAIN_Q12_ONE = 1u << APU_GAIN_Q12_FRACTION_BITS;
constexpr u32 APU_COMMAND_FIFO_CAPACITY = 16u;

constexpr u32 APU_CMD_NONE = 0u;
constexpr u32 APU_CMD_PLAY = 1u;
constexpr u32 APU_CMD_STOP_SLOT = 2u;
constexpr u32 APU_CMD_SET_SLOT_GAIN = 3u;

constexpr u32 APU_SLOT_COUNT = 16u;
constexpr u32 APU_SLOT_INDEX_MASK = APU_SLOT_COUNT - 1u;
constexpr u32 APU_GENERATOR_NONE = 0u;
constexpr u32 APU_GENERATOR_SQUARE = 1u;
constexpr u32 APU_PARAMETER_REGISTER_COUNT = 21u;
constexpr u32 APU_PARAMETER_SOURCE_ADDR_INDEX = 0u;
constexpr u32 APU_PARAMETER_SOURCE_BYTES_INDEX = 1u;
constexpr u32 APU_PARAMETER_SOURCE_SAMPLE_RATE_HZ_INDEX = 2u;
constexpr u32 APU_PARAMETER_SOURCE_CHANNELS_INDEX = 3u;
constexpr u32 APU_PARAMETER_SOURCE_BITS_PER_SAMPLE_INDEX = 4u;
constexpr u32 APU_PARAMETER_SOURCE_FRAME_COUNT_INDEX = 5u;
constexpr u32 APU_PARAMETER_SOURCE_DATA_OFFSET_INDEX = 6u;
constexpr u32 APU_PARAMETER_SOURCE_DATA_BYTES_INDEX = 7u;
constexpr u32 APU_PARAMETER_SOURCE_LOOP_START_SAMPLE_INDEX = 8u;
constexpr u32 APU_PARAMETER_SOURCE_LOOP_END_SAMPLE_INDEX = 9u;
constexpr u32 APU_PARAMETER_SLOT_INDEX = 10u;
constexpr u32 APU_PARAMETER_RATE_STEP_Q16_INDEX = 11u;
constexpr u32 APU_PARAMETER_GAIN_Q12_INDEX = 12u;
constexpr u32 APU_PARAMETER_START_SAMPLE_INDEX = 13u;
constexpr u32 APU_PARAMETER_FILTER_CONTROL_INDEX = 14u;
constexpr u32 APU_PARAMETER_FILTER_B0_B1_INDEX = 15u;
constexpr u32 APU_PARAMETER_FILTER_B2_A1_INDEX = 16u;
constexpr u32 APU_PARAMETER_FILTER_A2_INDEX = 17u;
constexpr u32 APU_PARAMETER_FADE_SAMPLES_INDEX = 18u;
constexpr u32 APU_PARAMETER_GENERATOR_KIND_INDEX = 19u;
constexpr u32 APU_PARAMETER_GENERATOR_DUTY_Q12_INDEX = 20u;
constexpr u32 APU_SLOT_REGISTER_WORD_COUNT = APU_SLOT_COUNT * APU_PARAMETER_REGISTER_COUNT;
constexpr u32 APU_COMMAND_FIFO_REGISTER_WORD_COUNT = APU_COMMAND_FIFO_CAPACITY * APU_PARAMETER_REGISTER_COUNT;

constexpr auto apuSlotRegisterWordIndex(u32 slot, u32 parameterIndex) -> std::size_t {
	return (static_cast<std::size_t>(slot) * APU_PARAMETER_REGISTER_COUNT) + parameterIndex;
}

constexpr u32 APU_STATUS_FAULT = 1u << 0u;
constexpr u32 APU_STATUS_SELECTED_SLOT_ACTIVE = 1u << 1u;
constexpr u32 APU_STATUS_BUSY = 1u << 2u;
constexpr u32 APU_STATUS_CMD_FIFO_EMPTY = 1u << 5u;
constexpr u32 APU_STATUS_CMD_FIFO_FULL = 1u << 6u;
constexpr u32 APU_STATUS_DMA_REQUEST = 1u << 7u;
constexpr u32 APU_STATUS_DMA_READ_REQUEST = 1u << 8u;
constexpr u32 APU_STATUS_DMA_WRITE_REQUEST = 1u << 9u;
constexpr u32 APU_STATUS_TRANSFER_BUSY = 1u << 10u;

constexpr u32 APU_FAULT_NONE = 0u;
constexpr u32 APU_FAULT_BAD_CMD = 0x0001u;
constexpr u32 APU_FAULT_SOURCE_BYTES = 0x0101u;
constexpr u32 APU_FAULT_SOURCE_RANGE = 0x0102u;
constexpr u32 APU_FAULT_SOURCE_SAMPLE_RATE = 0x0103u;
constexpr u32 APU_FAULT_SOURCE_CHANNELS = 0x0104u;
constexpr u32 APU_FAULT_SOURCE_FRAME_COUNT = 0x0105u;
constexpr u32 APU_FAULT_SOURCE_DATA_RANGE = 0x0106u;
constexpr u32 APU_FAULT_SOURCE_BIT_DEPTH = 0x0107u;
constexpr u32 APU_FAULT_UNSUPPORTED_FORMAT = 0x0201u;

constexpr u32 APU_FILTER_CONTROL_ENABLE = 1u << 0u;
constexpr u32 APU_FILTER_COEFFICIENT_FRACTION_BITS = 14u;
constexpr u32 APU_FILTER_COEFFICIENT_ONE = 1u << APU_FILTER_COEFFICIENT_FRACTION_BITS;

constexpr u32 APU_EVENT_NONE = 0u;
constexpr u32 APU_EVENT_SLOT_ENDED = 1u;

} // namespace bmsx
