export const HZ_SCALE = 1_000_000;
export const DEFAULT_UFPS_SCALED = 50 * HZ_SCALE;
export const DEFAULT_UFPS = DEFAULT_UFPS_SCALED / HZ_SCALE;
export const DEFAULT_FRAME_TIME_SEC = HZ_SCALE / DEFAULT_UFPS_SCALED;
export const DEFAULT_FRAME_TIME_MS = 1000 * HZ_SCALE / DEFAULT_UFPS_SCALED;
