local syntax<const> = {
	chunk = 1,
	block = 2,
	assignment_statement = 3,
	return_statement = 4,
	function_expression = 5,
	identifier_expression = 6,
	member_expression = 7,
	index_expression = 8,
	number_literal_expression = 9,
	string_literal_expression = 10,
	boolean_literal_expression = 11,
	nil_literal_expression = 12,
	unary_expression = 13,
	binary_expression = 14,
	call_expression = 15,
	local_statement = 16,
	if_statement = 17,
	while_statement = 18,
	break_statement = 19,
	call_statement = 20,
	numeric_for_statement = 21,

	unary_negate = 1,
	unary_string_id = 2,
	unary_not = 3,
	unary_length = 4,

	binary_add = 1,
	binary_subtract = 2,
	binary_multiply = 3,
	binary_divide = 4,
	binary_floor_divide = 5,
	binary_modulus = 6,
	binary_equal = 7,
	binary_not_equal = 8,
	binary_less = 9,
	binary_less_equal = 10,
	binary_greater = 11,
	binary_greater_equal = 12,
	binary_and = 13,
	binary_or = 14,
	binary_bitwise_and = 15,
}

return syntax
