local token<const> = {
	left_parenthesis = 1,
	right_parenthesis = 2,
	left_bracket = 3,
	right_bracket = 4,
	minus = 5,
	plus = 6,
	star = 7,
	slash = 8,
	floor_divide = 9,
	percent = 10,
	ampersand = 11,
	equal = 12,
	comma = 13,
	dot = 14,
	semicolon = 15,
	string = 16,
	number = 17,
	identifier = 18,
	keyword_end = 19,
	keyword_false = 20,
	keyword_function = 21,
	keyword_nil = 22,
	keyword_return = 23,
	keyword_true = 24,
	eof = 25,
}

token.keyword_by_text = {
	['end'] = token.keyword_end,
	['false'] = token.keyword_false,
	['function'] = token.keyword_function,
	['nil'] = token.keyword_nil,
	['return'] = token.keyword_return,
	['true'] = token.keyword_true,
}

token.single_character_by_code = {
	[37] = token.percent,
	[38] = token.ampersand,
	[40] = token.left_parenthesis,
	[41] = token.right_parenthesis,
	[42] = token.star,
	[43] = token.plus,
	[44] = token.comma,
	[45] = token.minus,
	[46] = token.dot,
	[47] = token.slash,
	[59] = token.semicolon,
	[61] = token.equal,
	[91] = token.left_bracket,
	[93] = token.right_bracket,
}

token.name = {
	[token.left_parenthesis] = '(',
	[token.right_parenthesis] = ')',
	[token.left_bracket] = '[',
	[token.right_bracket] = ']',
	[token.minus] = '-',
	[token.plus] = '+',
	[token.star] = '*',
	[token.slash] = '/',
	[token.floor_divide] = '//',
	[token.percent] = '%',
	[token.ampersand] = '&',
	[token.equal] = '=',
	[token.comma] = ',',
	[token.dot] = '.',
	[token.semicolon] = ';',
	[token.string] = 'string',
	[token.number] = 'number',
	[token.identifier] = 'identifier',
	[token.keyword_end] = 'end',
	[token.keyword_false] = 'false',
	[token.keyword_function] = 'function',
	[token.keyword_nil] = 'nil',
	[token.keyword_return] = 'return',
	[token.keyword_true] = 'true',
	[token.eof] = 'end of input',
}

return token
