// Generated by scripts/rompacker/host_system_atlas.ts.
// Do not edit by hand.
#pragma once

#include <cstddef>
#include <cstdint>
#include <string_view>

namespace bmsx {

struct HostSystemAtlasGeneratedImage {
	std::string_view id;
	std::int32_t width = 0;
	std::int32_t height = 0;
	std::uint32_t u = 0;
	std::uint32_t v = 0;
	std::uint32_t w = 0;
	std::uint32_t h = 0;
};

std::int32_t generatedHostSystemAtlasWidth();
std::int32_t generatedHostSystemAtlasHeight();
std::string_view generatedHostSystemAtlasRgbaBase64();
const HostSystemAtlasGeneratedImage* generatedHostSystemAtlasImages();
std::size_t generatedHostSystemAtlasImageCount();

} // namespace bmsx
