local boekfoe_module = require('enemies/boekfoe')
local cloud_module = require('enemies/cloud')
local crossfoe_module = require('enemies/crossfoe')
local marspeinenaardappel_module = require('enemies/marspeinenaardappel')
local mijterfoe_module = require('enemies/mijterfoe')
local muziekfoe_module = require('enemies/muziekfoe')
local nootfoe_module = require('enemies/nootfoe')
local paperfoe_module = require('enemies/paperfoe')
local stafffoe_module = require('enemies/stafffoe')
local staffspawn_module = require('enemies/staffspawn')
local vlokfoe_module = require('enemies/vlokfoe')
local vlokspawner_module = require('enemies/vlokspawner')
local zakfoe_module = require('enemies/zakfoe')

local enemy_registry = {}

function enemy_registry.register_all()
	boekfoe_module.register_behaviour_tree('enemy.bt.boekfoe')
	cloud_module.register_behaviour_tree('enemy.bt.cloud')
	crossfoe_module.register_behaviour_tree('enemy.bt.crossfoe')
	marspeinenaardappel_module.register_behaviour_tree('enemy.bt.marspeinenaardappel')
	mijterfoe_module.register_behaviour_tree('enemy.bt.mijterfoe')
	muziekfoe_module.register_behaviour_tree('enemy.bt.muziekfoe')
	nootfoe_module.register_behaviour_tree('enemy.bt.nootfoe')
	paperfoe_module.register_behaviour_tree('enemy.bt.paperfoe')
	stafffoe_module.register_behaviour_tree('enemy.bt.stafffoe')
	staffspawn_module.register_behaviour_tree('enemy.bt.staffspawn')
	vlokfoe_module.register_behaviour_tree('enemy.bt.vlokfoe')
	vlokspawner_module.register_behaviour_tree('enemy.bt.vlokspawner')
	zakfoe_module.register_behaviour_tree('enemy.bt.zakfoe')

	boekfoe_module.register_enemy_definition()
	cloud_module.register_enemy_definition()
	crossfoe_module.register_enemy_definition()
	marspeinenaardappel_module.register_enemy_definition()
	mijterfoe_module.register_enemy_definition()
	muziekfoe_module.register_enemy_definition()
	nootfoe_module.register_enemy_definition()
	paperfoe_module.register_enemy_definition()
	stafffoe_module.register_enemy_definition()
	staffspawn_module.register_enemy_definition()
	vlokfoe_module.register_enemy_definition()
	vlokspawner_module.register_enemy_definition()
	zakfoe_module.register_enemy_definition()
end

return enemy_registry
