export const ADDRESS_BITS = 32;

export const SYSTEM_ROM_BASE = 0x00000000;
export const SYSTEM_ROM_SIZE = 0x01000000; // 16 MB

export const CART_ROM_BASE = 0x01000000;
export const CART_ROM_SIZE = 0x05000000; // 80 MB
export const CART_ROM_MAGIC_OFFSET = 0x00000000;
export const CART_ROM_MAGIC_ADDR = CART_ROM_BASE + CART_ROM_MAGIC_OFFSET;


export const RAM_BASE = 0x08000000;
export const MAX_RAM_SIZE = 0x08000000; // 128 MB address window
export const DEFAULT_RAM_SIZE = 0x00400000; // 4 MB

export const PROGRAM_ROM_BASE = 0x10000000;
export const PROGRAM_ROM_SIZE = 0x01000000; // 16 MB
export const IO_WORD_SIZE = 4;
export const CART_PROGRAM_START_OFFSET = 0x00080000;
export const CART_PROGRAM_START_ADDR = PROGRAM_ROM_BASE + CART_PROGRAM_START_OFFSET;
export const CART_PROGRAM_VECTOR_OFFSET = CART_PROGRAM_START_OFFSET - IO_WORD_SIZE;
export const CART_PROGRAM_VECTOR_ADDR = PROGRAM_ROM_BASE + CART_PROGRAM_VECTOR_OFFSET;

export const IO_REGION_SIZE = 0x00040000; // 256 KB

export const DEFAULT_GEO_SCRATCH_SIZE = 0x00080000; // 512 KB
export const MIN_RAM_SIZE = IO_REGION_SIZE
	+ DEFAULT_GEO_SCRATCH_SIZE;
export const BASE_RAM_USED_SIZE = DEFAULT_GEO_SCRATCH_SIZE;
export const PROGRAM_STATIC_RAM_BASE = RAM_BASE + MIN_RAM_SIZE;

export let RAM_SIZE = DEFAULT_RAM_SIZE;

export const IO_BASE = RAM_BASE;
export const GEO_SCRATCH_BASE = IO_BASE + IO_REGION_SIZE;
export const GEO_SCRATCH_SIZE = DEFAULT_GEO_SCRATCH_SIZE;
export let RAM_END = RAM_BASE + RAM_SIZE;

export function configureMemoryMap(ramBytes: number): void {
	RAM_SIZE = ramBytes;
	RAM_END = RAM_BASE + RAM_SIZE;
}

configureMemoryMap(DEFAULT_RAM_SIZE);
