module<const>

struct game_text_record
	death_screen: string
	victory_message: string
	end_demo_message: string
end

rodata game_text: game_text_record = {
	death_screen = 'PROBEER HET NOG EENS...',
	victory_message = '   NU KRIJG IK VAST OPSLAG!   ',
	end_demo_message = 'DAT HEB JE BEST REDELIJK GEDAAN! ',
}

rodata story_text: string[] = {
	'',
	'',
	'              STORY',
	'',
	'',
	' ZOALS IEDER JAAR KWAM DE       ',
	'',
	' GOEDHEILIGMAN MET ZIJN ZWARTE  ',
	'',
	' PIETEN NAAR DE NEDERLANDEN OM  ',
	'',
	' CADEAUTJES TE GEVEN AAN LIEVE  ',
	'',
	' KINDERTJES.                    ',
	'',
	'',
	' ECHTER BLEEK SINTERKLAAS DIT   ',
	'',
	' JAAR IN EEN VAL TE ZIJN GELOKT.',
	'',
	'',
	' DE KWAADAARDIGE EN OVERBETAALDE',
	'',
	' PIETIOUS HEEFT, IN AFWEZIGHEID ',
	'',
	' VAN DE SINT, KASTEEL NICOLAAS  ',
	'',
	' INGENOMEN!',
	'',
	'',
	' DAARBIJ HEEFT PIETIOUS         ',
	'',
	' DE HEILIGE ZAK VAN SINTERKLAAS ',
	'',
	' GEOPEND EN ZO EEN HORDE VAN    ',
	'',
	' SNOEPGOED EN SPEELGOED         ',
	'',
	' LOSGELATEN IN HET KASTEEL, WELK',
	'',
	' EEN GEVAAR VORMT VOOR IEDER DIE',
	'',
	' HET KASTEEL DURFT TE BETREDEN. ',
	'',
	'',
	' SINT NICOLAAS HEEFT BESLOTEN OM',
	'',
	' DE ALMACHTIGE PIETOLON HET     ',
	'',
	' KASTEEL TE LATEN BESTORMEN OM  ',
	'',
	' EEN EIND TE MAKEN AAN          ',
	'',
	' DE TERREUR VAN PIETIOUS!       ',
}

rodata epilogue_text: string[] = {
	'',
	'',
	'            EPILOGUE            ',
	'',
	'',
	'',
	'',
	' HET KASTEEL VAN DE SINT IS     ',
	'',
	' BEVRIJD VAN DE KWAADAARDIGE EN ',
	'',
	' OVERBETAALDE PIETIOUS!         ',
	'',
	' DUS KAN DE SINT ZONDER ZORGEN, ',
	'',
	' BEHALVE VAN ECONOMISCHE AARD,  ',
	'',
	' ZIJN RENTREE MAKEN IN SPANJE.  ',
	'',
	'',
	'',
	'',
	' UITERAARD WORDT PIETOLON       ',
	'',
	' OVERLADEN MET SNOEPGOED EN     ',
	'',
	' SPEELGOED VOOR ZIJN WERK EN ZAL',
	'',
	' HIJ EEN EXTRA DAG VRIJ KRIJGEN.',
	'',
	'',
	'',
	'',
	' ZO, DAT WAS WEER EEN HOOP WERK!',
	'',
	' HET BOUWEN VAN DEZE SPELLETJES ',
	'',
	' ZAL SINTERKLAAS NIET IEDER JAAR',
	'',
	' AAN ZIJN PIETEN VRAGEN.        ',
	'',
	'',
	'',
	'',
	' SINTERKLAAS WIL GRAAG IEDEREEN ',
	'',
	' BEDANKEN DIE HEEFT BIJGEDRAGEN ',
	'',
	' AAN HET TOTSTANDKOMEN VAN DEZE ',
	'',
	' FANTASTISCHE CREATIE...        ',
	'',
	'',
	'',
	'',
	'',
	' OORSPRONKELIJKE DESIGN EN BOUW ',
	'',
	'',
	'             KONAMI             ',
	'',
	'',
	'',
	'',
	'          PROGRAMMEREN          ',
	'',
	'',
	'       VISUAL STUDIO PIET       ',
	'',
	'           .NET PIET            ',
	'',
	'          CSHARP PIET           ',
	'',
	'            XNA PIET            ',
	'',
	'',
	'',
	'',
	'           GRAPHISCH            ',
	'',
	'',
	'          MSPAINT PIET          ',
	'',
	'         PAINT.NET PIET         ',
	'',
	'          BLUEMSX PIET          ',
	'',
	'',
	'',
	'',
	'             GELUID             ',
	'',
	'',
	'      NERO WAVE EDITOR PIET     ',
	'',
	'          BLUEMSX PIET          ',
	'',
	'',
	'',
	'',
	'          MORELE STEUN          ',
	'',
	'',
	'          HOCKEY PIET           ',
	'',
	'     BALLROOM EN LATIN PIET     ',
	'',
	'         SOMERTIJD PIET         ',
	'',
	'         TECNOMAN PIET          ',
	'',
	'         EREDIVISIE PIET        ',
	'',
	'',
	'',
	'',
	'         EN NATUURLIJK...       ',
	'',
	'',
	'   SINTERKLAAS EN ZWARTE PIET!  ',
	'',
	'',
	'',
	'',
	'',
	'',
	'           ...EN JULLIE!        ',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'',
	'     DAT WAS HET WEER! DOEI!    ',
}

return {
	game_text = game_text,
	story_text = story_text,
	epilogue_text = epilogue_text,
}
