import type { LuaBuiltinDescriptor } from '../../lua/semantic_contracts';

export const SYSTEM_LUA_BUILTIN_FUNCTIONS: ReadonlyArray<LuaBuiltinDescriptor> = [
	{ name: 'define_fsm', params: ['id', 'blueprint'], signature: 'define_fsm(id, blueprint)' },
	{ name: 'define_prefab', params: ['definition'], signature: 'define_prefab(definition)' },
	{ name: 'define_subsystem', params: ['definition'], signature: 'define_subsystem(definition)' },
	{ name: 'define_component', params: ['definition'], signature: 'define_component(definition)' },
	{ name: 'define_effect', params: ['definition', 'opts?'], signature: 'define_effect(definition [, opts])' },
	{ name: 'inst', params: ['definition_id', 'addons?'], signature: 'inst(definition_id [, addons])' },
	{ name: 'inst_subsystem', params: ['definition_id', 'addons?'], signature: 'inst_subsystem(definition_id [, addons])' },
	{ name: 'oget', params: ['id'], signature: 'oget(id)' },
	{ name: 'rget', params: ['id'], signature: 'rget(id)' },
	{ name: 'subsystem', params: ['id'], signature: 'subsystem(id)' },
	{ name: 'add_space', params: ['space_id'], signature: 'add_space(space_id)' },
	{ name: 'set_space', params: ['space_id'], signature: 'set_space(space_id)' },
	{ name: 'get_space', params: [], signature: 'get_space()' },
	{ name: 'attach_component', params: ['object_or_id', 'component_or_type'], signature: 'attach_component(object_or_id, component_or_type)' },
	{ name: 'update_world', params: [], signature: 'update_world()', description: 'Runs one world/game-logic phase without emitting the presentation VDP stream.' },
	{ name: 'draw_world', params: [], signature: 'draw_world()', description: 'Emits presentation VDP commands for the current world state without running game logic.' },
	{ name: 'reset', params: [], signature: 'reset()' },
	{ name: 'configure_ecs', params: ['nodes'], signature: 'configure_ecs(nodes)' },
	{ name: 'apply_default_pipeline', params: [], signature: 'apply_default_pipeline()' },
	{ name: 'enlist', params: ['value'], signature: 'enlist(value)' },
	{ name: 'delist', params: ['id'], signature: 'delist(id)' },
	{ name: 'grant_effect', params: ['object_id', 'effect_id'], signature: 'grant_effect(object_id, effect_id)' },
	{ name: 'trigger_effect', params: ['object_id', 'effect_id', 'options?'], signature: 'trigger_effect(object_id, effect_id [, options])' },
	{ name: 'vdp_load_slot', params: ['slot', 'atlas_id'], signature: 'vdp_load_slot(slot, atlas_id)', description: 'Starts an async atlas load into a VRAM slot; BIOS maps the slot on completion; returns a job id.' },
	{ name: 'vdp_load_system_slot', params: [], signature: 'vdp_load_system_slot()', description: 'Starts an async load of the system atlas into the system VRAM slot; returns a job id.' },
	{ name: 'vdp_blit_img_color', params: ['imgid', 'x', 'y', 'z', 'layer', 'scale_x', 'scale_y', 'flip_flags', 'color', 'parallax_weight'], signature: 'vdp_blit_img_color(imgid, x, y, z, layer, scale_x, scale_y, flip_flags, color, parallax_weight)', description: 'BIOS helper that translates an image id to raw VDP blit register/doorbell packets.' },
	{ name: 'vdp_glyph_color', params: ['glyph', 'x', 'y', 'z', 'layer', 'color'], signature: 'vdp_glyph_color(glyph, x, y, z, layer, color)', description: 'BIOS helper that emits one raw VDP blit for an already-resolved glyph.' },
	{ name: 'vdp_img_rect', params: ['imgid'], signature: 'vdp_img_rect(imgid)', description: 'Returns the BIOS-owned atlas rectangle for an image id.' },
	{ name: 'vdp_img_slot', params: ['rect'], signature: 'vdp_img_slot(rect)', description: 'Resolves a cached atlas rectangle to the current VDP slot.' },
	{ name: 'vdp_img_source', params: ['rect'], signature: 'vdp_img_source(rect)', description: 'Resolves a cached atlas rectangle to a transient VDP slot/u/v/w/h source.' },
	{ name: 'vdp_write_source', params: ['dst', 'rect'], signature: 'vdp_write_source(dst, rect)', description: 'Writes current slot/u/v/w/h payload for a cached atlas rectangle.' },
	{ name: 'vdp_pmu_write_bank', params: ['bank', 'x', 'y', 'scale_x', 'scale_y', 'control'], signature: 'vdp_pmu_write_bank(bank, x, y, scale_x, scale_y, control)', description: 'Programs a VDP PMU bank with raw Q16.16 offset/scale words and a control word.' },
	{ name: 'vdp_stream_claim', params: ['count'], signature: 'vdp_stream_claim(count)', description: 'Low-level software primitive that claims count raw VDP stream entries and returns the packet base address.' },
	{ name: 'vdp_stream_finish', params: [], signature: 'vdp_stream_finish()', description: 'Appends the raw VDP stream terminator word when the frame stream is non-empty.' },
	{ name: 'vdp_clear_color', params: ['color'], signature: 'vdp_clear_color(color)', description: 'Emits raw VDP register/doorbell packets for a clear command.' },
	{ name: 'vdp_fill_rect_color', params: ['x0', 'y0', 'x1', 'y1', 'z', 'layer', 'color'], signature: 'vdp_fill_rect_color(x0, y0, x1, y1, z, layer, color)', description: 'Emits raw VDP register/doorbell packets for a filled rectangle.' },
	{ name: 'vdp_draw_line_color', params: ['x0', 'y0', 'x1', 'y1', 'z', 'layer', 'color', 'thickness'], signature: 'vdp_draw_line_color(x0, y0, x1, y1, z, layer, color, thickness)', description: 'Emits raw VDP register/doorbell packets for a line command.' },
	{ name: 'rom_data', params: ['id'], signature: 'rom_data(id)', description: 'Decodes a data entry from the active mapped ROM.' },
	{ name: 'irq', params: ['flags'], signature: 'irq(flags)' },
	{ name: 'on_irq', params: ['mask', 'handler?'], signature: 'on_irq(mask [, handler])', description: 'Registers a per-bit IRQ handler; pass nil as handler to clear it.' },
	{ name: 'on_vdp_load', params: ['handler?'], signature: 'on_vdp_load(handler)', description: 'Registers a VDP load notification callback.' },
	{ name: 'bool01', params: ['value'], signature: 'bool01(value)', description: 'Converts a Lua value to 0 or 1; falsy values become 0, truthy values become 1.' },
	{ name: 'clear_map', params: ['map'], signature: 'clear_map(map)', description: 'Clears all keys from a table-style map by setting each key to nil.' },
	{ name: 'deep_clone', params: ['value'], signature: 'deep_clone(value)', description: 'Recursively clones a Lua value, including tables. Note that this does not handle cycles and will error if a cycle is encountered.' },
	{ name: 'consume_axis_accum', params: ['accum', 'speed_num', 'speed_den'], signature: 'consume_axis_accum(accum, speed_num, speed_den)' },
	{ name: 'set_velocity', params: ['target', 'speed_x_num', 'speed_y_num', 'speed_den'], signature: 'set_velocity(target, speed_x_num, speed_y_num, speed_den)' },
	{ name: 'move_with_velocity', params: ['target'], signature: 'move_with_velocity(target)' },
	{ name: 'rect_overlaps', params: ['ax', 'ay', 'aw', 'ah', 'bx', 'by', 'bw', 'bh'], signature: 'rect_overlaps(ax, ay, aw, ah, bx, by, bw, bh)' },
	{ name: 'clamp_int', params: ['value', 'min_value', 'max_value'], signature: 'clamp_int(value, min_value, max_value)' },
	{ name: 'div_toward_zero', params: ['value', 'divisor'], signature: 'div_toward_zero(value, divisor)' },
	{ name: 'round_to_nearest', params: ['value'], signature: 'round_to_nearest(value)' },
	{ name: 'rol8', params: ['value'], signature: 'rol8(value)' },
	{ name: 'swap_remove', params: ['array', 'index'], signature: 'swap_remove(array, index)' },
	{ name: 'objects_by_type', params: ['type_name'], signature: 'objects_by_type(type_name)', description: 'Returns an iterator over active world objects whose type_name matches.' },
	{ name: 'all_objects_by_type', params: ['type_name'], signature: 'all_objects_by_type(type_name)', description: 'Returns an iterator over all live world objects whose type_name matches.' },
	{ name: 'objects_by_tag', params: ['tag'], signature: 'objects_by_tag(tag)', description: 'Returns an iterator over active world objects carrying the given tag.' },
	{ name: 'all_objects_by_tag', params: ['tag'], signature: 'all_objects_by_tag(tag)', description: 'Returns an iterator over all live world objects carrying the given tag.' },
	{ name: 'find_by_type', params: ['type_name'], signature: 'find_by_type(type_name)', description: 'Returns the first active world object matching type_name, or nil.' },
	{ name: 'find_any_by_type', params: ['type_name'], signature: 'find_any_by_type(type_name)', description: 'Returns the first live world object matching type_name, or nil.' },
	{ name: 'find_by_tag', params: ['tag'], signature: 'find_by_tag(tag)', description: 'Returns the first active world object carrying the given tag, or nil.' },
	{ name: 'find_any_by_tag', params: ['tag'], signature: 'find_any_by_tag(tag)', description: 'Returns the first live world object carrying the given tag, or nil.' },
];

export const SYSTEM_LUA_BUILTIN_GLOBALS: ReadonlyArray<LuaBuiltinDescriptor> = [
	{ name: 'timeline', params: [], signature: 'timeline', description: 'Timeline module table (timeline.new, timeline.range, timeline.expand_frames, timeline.build_frame_sequence, timeline.build_pingpong_frames).' },
	{ name: 'eventemitter', params: [], signature: 'eventemitter', description: 'Event emitter module table (eventemitter, events_of).' },
	{ name: 'scratchbatch', params: [], signature: 'scratchbatch', description: 'Scratch batch module table (scratchbatch.new; batches support clear, push, get, reserve, for_each, iter).' },
	{ name: 'sorted_scratchbatch', params: [], signature: 'sorted_scratchbatch', description: 'Sorted scratch batch module table (sorted_scratchbatch.new; batches support clear, push, get, reserve, for_each, iter, set_compare, sort).' },
];

export const DEFAULT_LUA_BUILTIN_FUNCTIONS: ReadonlyArray<LuaBuiltinDescriptor> = [
	{ name: 'assert', params: ['value', 'message?'], signature: 'assert(value [, message])' },
	{ name: 'error', params: ['message', 'level?'], signature: 'error(message [, level])' },
	{ name: 'getmetatable', params: ['object'], signature: 'getmetatable(object)' },
	{ name: 'ipairs', params: ['table'], signature: 'ipairs(t)' },
	{ name: 'next', params: ['table', 'index?'], signature: 'next(table [, index])' },
	{ name: 'pairs', params: ['table'], signature: 'pairs(t)' },
	{ name: 'pcall', params: ['func', 'arg...'], signature: 'pcall(f, ...)' },
	{ name: 'print', params: ['...'], signature: 'print(...)' },
	{ name: 'loadstring', params: ['source', 'chunkname?'], signature: 'loadstring(source [, chunkname])', description: 'Compiles a restricted runtime Lua source subset into a chunk function; intended for small generated helpers.' },
	{ name: 'load', params: ['source', 'chunkname?', 'mode?', 'env?'], signature: 'load(source [, chunkname [, mode [, env]]])', description: 'Compiles the same restricted runtime Lua source subset as loadstring; only text mode is supported.' },
	{ name: 'clock_now', params: [], signature: 'clock_now()', description: 'Returns the current platform clock value.' },
	{ name: 'rawequal', params: ['v1', 'v2'], signature: 'rawequal(v1, v2)' },
	{ name: 'rawget', params: ['table', 'index'], signature: 'rawget(table, index)' },
	{ name: 'rawset', params: ['table', 'index', 'value'], signature: 'rawset(table, index, value)' },
	{ name: 'select', params: ['index', '...'], signature: 'select(index, ...)' },
	{ name: 'setmetatable', params: ['table', 'metatable'], signature: 'setmetatable(table, metatable)' },
	{ name: 'tonumber', params: ['value', 'base?'], signature: 'tonumber(value [, base])' },
	{ name: 'tostring', params: ['value'], signature: 'tostring(value)' },
	{ name: 'type', params: ['value'], signature: 'type(value)' },
	{ name: 'xpcall', params: ['func', 'msgh', 'arg...'], signature: 'xpcall(f, msgh, ...)' },
	{ name: 'require', params: ['moduleName'], signature: 'require(moduleName)' },
	{ name: 'font_for_each_glyph', params: ['font', 'line', 'fn'], signature: 'font_for_each_glyph(font, line, fn)', description: 'Runtime font helper that iterates UTF-8 glyph descriptors for a line.' },
	{ name: 'font_measure_line_width', params: ['font', 'line'], signature: 'font_measure_line_width(font, line)', description: 'Runtime font helper that measures a UTF-8 text line.' },
	{ name: 'table.concat', params: ['list', 'separator?', 'start?', 'end?'], signature: 'table.concat(list [, sep [, i [, j]]])' },
	{ name: 'table.insert', params: ['list', 'pos?', 'value'], signature: 'table.insert(list [, pos], value)' },
	{ name: 'table.pack', params: ['...'], signature: 'table.pack(...)' },
	{ name: 'table.remove', params: ['list', 'pos?'], signature: 'table.remove(list [, pos])' },
	{ name: 'table.sort', params: ['list', 'comp?'], signature: 'table.sort(list [, comp])' },
	{ name: 'table.unpack', params: ['list', 'i?', 'j?'], signature: 'table.unpack(list [, i [, j]])' },
	{ name: 'math.abs', params: ['x'], signature: 'math.abs(x)' },
	{ name: 'math.acos', params: ['x'], signature: 'math.acos(x)' },
	{ name: 'math.asin', params: ['x'], signature: 'math.asin(x)' },
	{ name: 'math.atan', params: ['y', 'x?'], signature: 'math.atan(y [, x])' },
	{ name: 'math.ceil', params: ['x'], signature: 'math.ceil(x)' },
	{ name: 'math.cos', params: ['x'], signature: 'math.cos(x)' },
	{ name: 'math.deg', params: ['x'], signature: 'math.deg(x)' },
	{ name: 'math.exp', params: ['x'], signature: 'math.exp(x)' },
	{ name: 'math.floor', params: ['x'], signature: 'math.floor(x)' },
	{ name: 'math.fmod', params: ['x', 'y'], signature: 'math.fmod(x, y)' },
	{ name: 'math.log', params: ['x', 'base?'], signature: 'math.log(x [, base])' },
	{ name: 'math.max', params: ['x', '...'], signature: 'math.max(x, ...)' },
	{ name: 'math.min', params: ['x', '...'], signature: 'math.min(x, ...)' },
	{ name: 'math.modf', params: ['x'], signature: 'math.modf(x)' },
	{ name: 'math.sin', params: ['x'], signature: 'math.sin(x)' },
	{ name: 'math.sign', params: ['x'], signature: 'math.sign(x)' },
	{ name: 'math.random', params: ['m?', 'n?'], signature: 'math.random([m [, n]])' },
	{ name: 'math.randomseed', params: ['seed?'], signature: 'math.randomseed([seed])' },
	{ name: 'math.sqrt', params: ['x'], signature: 'math.sqrt(x)' },
	{ name: 'math.rad', params: ['x'], signature: 'math.rad(x)' },
	{ name: 'math.tan', params: ['x'], signature: 'math.tan(x)' },
	{ name: 'math.tointeger', params: ['x'], signature: 'math.tointeger(x)' },
	{ name: 'math.type', params: ['x'], signature: 'math.type(x)' },
	{ name: 'math.ult', params: ['m', 'n'], signature: 'math.ult(m, n)' },
	{ name: 'math.huge', params: [], signature: 'math.huge' },
	{ name: 'math.maxinteger', params: [], signature: 'math.maxinteger' },
	{ name: 'math.mininteger', params: [], signature: 'math.mininteger' },
	{ name: 'easing.linear', params: ['t'], signature: 'easing.linear(t)' },
	{ name: 'easing.ease_in_quad', params: ['t'], signature: 'easing.ease_in_quad(t)' },
	{ name: 'easing.ease_out_quad', params: ['t'], signature: 'easing.ease_out_quad(t)' },
	{ name: 'easing.ease_in_out_quad', params: ['t'], signature: 'easing.ease_in_out_quad(t)' },
	{ name: 'easing.ease_out_back', params: ['t'], signature: 'easing.ease_out_back(t)' },
	{ name: 'easing.smoothstep', params: ['t'], signature: 'easing.smoothstep(t)' },
	{ name: 'easing.pingpong01', params: ['t'], signature: 'easing.pingpong01(t)' },
	{ name: 'easing.arc01', params: ['t'], signature: 'easing.arc01(t)' },
	{ name: 'string.byte', params: ['s', 'i?'], signature: 'string.byte(s [, i])' },
	{ name: 'string.char', params: ['...'], signature: 'string.char(...)' },
	{ name: 'string.find', params: ['s', 'pattern', 'init?'], signature: 'string.find(s, pattern [, init])' },
	{ name: 'string.match', params: ['s', 'pattern', 'init?'], signature: 'string.match(s, pattern [, init])' },
	{ name: 'string.gsub', params: ['s', 'pattern', 'repl', 'n?'], signature: 'string.gsub(s, pattern, repl [, n])' },
	{ name: 'string.gmatch', params: ['s', 'pattern'], signature: 'string.gmatch(s, pattern)' },
	{ name: 'string.format', params: ['format', '...'], signature: 'string.format(format, ...)' },
	{ name: 'string.pack', params: ['format', '...'], signature: 'string.pack(format, ...)' },
	{ name: 'string.packsize', params: ['format'], signature: 'string.packsize(format)' },
	{ name: 'string.unpack', params: ['format', 's', 'pos?'], signature: 'string.unpack(format, s [, pos])' },
	{ name: 'string.len', params: ['s'], signature: 'string.len(s)' },
	{ name: 'string.lower', params: ['s'], signature: 'string.lower(s)' },
	{ name: 'string.rep', params: ['s', 'n', 'sep?'], signature: 'string.rep(s, n [, sep])' },
	{ name: 'string.sub', params: ['s', 'i', 'j?'], signature: 'string.sub(s, i [, j])' },
	{ name: 'string.upper', params: ['s'], signature: 'string.upper(s)' },
	{ name: 'array', params: ['...'], signature: 'array(...)', description: 'Returns a Lua array table containing the provided values.' },
	{ name: 'wrap_text_lines', params: ['text', 'max_chars', 'first_prefix?', 'next_prefix?'], signature: 'wrap_text_lines(text, max_chars [, first_prefix [, next_prefix]])', description: 'Wraps UTF-8 text on word boundaries when possible and hard-wraps long words while preserving code points.' },
	{ name: 'u32_to_f32', params: ['value'], signature: 'u32_to_f32(value)', description: 'Reinterprets a 32-bit unsigned integer bit pattern as a float32.' },
	{ name: 'u64_to_f64', params: ['high', 'low'], signature: 'u64_to_f64(high, low)', description: 'Reinterprets a pair of 32-bit unsigned integers as a float64 bit pattern.' },
	{ name: 'os.clock', params: [], signature: 'os.clock()' },
	{ name: 'os.date', params: ['format?', 'time?'], signature: 'os.date([format [, time]])' },
	{ name: 'os.difftime', params: ['t2', 't1?'], signature: 'os.difftime(t2 [, t1])' },
	{ name: 'os.time', params: ['table?'], signature: 'os.time([table])' },
	{ name: '$', params: [], signature: '$', description: 'Native host core object.' },
	{ name: 'devtools', params: [], signature: 'devtools', description: 'Devtool-only runtime source inspection table (devtools.list_lua_resources, devtools.get_lua_entry_path, devtools.get_lua_resource_source).' },
	{ name: 'cart_manifest', params: [], signature: 'cart_manifest', description: 'Flattened cart manifest table, or nil when unavailable.' },
	{ name: 'machine_manifest', params: [], signature: 'machine_manifest', description: 'Flattened machine manifest table.' },
	{ name: 'cart_project_root_path', params: [], signature: 'cart_project_root_path', description: 'Workspace-relative cart project root path, or nil when unavailable.' },
	...SYSTEM_LUA_BUILTIN_FUNCTIONS,
	...SYSTEM_LUA_BUILTIN_GLOBALS,
	{ name: 'memwrite', params: ['base', '...'], signature: 'memwrite(base, ...)', description: 'Reserved compiler intrinsic for burst word writes. Lowers directly to a memory-write opcode and is not a first-class Lua value.' },
	{ name: 'mem', params: ['addr'], signature: 'mem[addr]', description: 'Reserved memory-mapped 32-bit word space for direct `mem[addr]` reads/writes. Not a first-class Lua value. Invalid or read-only writes raise a fault.' },
	{ name: 'mem8', params: ['addr'], signature: 'mem8[addr]', description: 'Reserved memory-mapped byte space for direct `mem8[addr]` reads/writes. Not a first-class Lua value.' },
	{ name: 'mem16le', params: ['addr'], signature: 'mem16le[addr]', description: 'Reserved memory-mapped little-endian 16-bit space for direct `mem16le[addr]` reads/writes. Not a first-class Lua value.' },
	{ name: 'mem32le', params: ['addr'], signature: 'mem32le[addr]', description: 'Reserved memory-mapped little-endian 32-bit space for direct `mem32le[addr]` reads/writes. Not a first-class Lua value.' },
	{ name: 'memf32le', params: ['addr'], signature: 'memf32le[addr]', description: 'Reserved memory-mapped little-endian 32-bit float space for direct `memf32le[addr]` reads/writes. Not a first-class Lua value. Invalid or read-only writes raise a fault.' },
	{ name: 'memf64le', params: ['addr'], signature: 'memf64le[addr]', description: 'Reserved memory-mapped little-endian 64-bit float space for direct `memf64le[addr]` reads/writes. Not a first-class Lua value. Invalid or read-only writes raise a fault.' },
	{ name: 'sys_boot_cart', params: [], signature: 'sys_boot_cart', description: 'System register address; write 1 to boot the cart.' },
	{ name: 'sys_bus_fault_code', params: [], signature: 'sys_bus_fault_code', description: 'System register address; sticky mapped bus fault code.' },
	{ name: 'sys_bus_fault_addr', params: [], signature: 'sys_bus_fault_addr', description: 'System register address; address captured for the first sticky mapped bus fault.' },
	{ name: 'sys_bus_fault_access', params: [], signature: 'sys_bus_fault_access', description: 'System register address; access flags captured for the first sticky mapped bus fault.' },
	{ name: 'sys_bus_fault_ack', params: [], signature: 'sys_bus_fault_ack', description: 'System register address; write nonzero to clear the sticky mapped bus fault.' },
	{ name: 'sys_bus_fault_none', params: [], signature: 'sys_bus_fault_none', description: 'Bus fault code meaning no bus fault is latched.' },
	{ name: 'sys_bus_fault_unmapped', params: [], signature: 'sys_bus_fault_unmapped', description: 'Bus fault code for an unmapped mapped-memory access.' },
	{ name: 'sys_bus_fault_unaligned_io', params: [], signature: 'sys_bus_fault_unaligned_io', description: 'Bus fault code for a non-word I/O mapped-memory access.' },
	{ name: 'sys_bus_fault_read_only', params: [], signature: 'sys_bus_fault_read_only', description: 'Bus fault code for a mapped-memory write to a read-only I/O register.' },
	{ name: 'sys_bus_fault_vram_range', params: [], signature: 'sys_bus_fault_vram_range', description: 'Bus fault code for a mapped VRAM access that is not contained in the VRAM aperture.' },
	{ name: 'sys_bus_fault_access_read', params: [], signature: 'sys_bus_fault_access_read', description: 'Bus fault access flag for reads.' },
	{ name: 'sys_bus_fault_access_write', params: [], signature: 'sys_bus_fault_access_write', description: 'Bus fault access flag for writes.' },
	{ name: 'sys_bus_fault_access_u8', params: [], signature: 'sys_bus_fault_access_u8', description: 'Bus fault access flag for byte accesses.' },
	{ name: 'sys_bus_fault_access_u16', params: [], signature: 'sys_bus_fault_access_u16', description: 'Bus fault access flag for little-endian 16-bit accesses.' },
	{ name: 'sys_bus_fault_access_u32', params: [], signature: 'sys_bus_fault_access_u32', description: 'Bus fault access flag for little-endian 32-bit accesses.' },
	{ name: 'sys_bus_fault_access_word', params: [], signature: 'sys_bus_fault_access_word', description: 'Bus fault access flag for Lua word accesses.' },
	{ name: 'sys_bus_fault_access_f32', params: [], signature: 'sys_bus_fault_access_f32', description: 'Bus fault access flag for little-endian 32-bit float accesses.' },
	{ name: 'sys_bus_fault_access_f64', params: [], signature: 'sys_bus_fault_access_f64', description: 'Bus fault access flag for little-endian 64-bit float accesses.' },
	{ name: 'sys_host_fault_flags', params: [], signature: 'sys_host_fault_flags', description: 'System register address; sticky host fault flags published by the host runtime during startup.' },
	{ name: 'sys_host_fault_stage', params: [], signature: 'sys_host_fault_stage', description: 'System register address; host-defined startup fault stage code.' },
	{ name: 'sys_host_fault_flag_active', params: [], signature: 'sys_host_fault_flag_active', description: 'Host fault flag bit indicating that a host fault is currently published.' },
	{ name: 'sys_host_fault_flag_startup_blocking', params: [], signature: 'sys_host_fault_flag_startup_blocking', description: 'Host fault flag bit indicating that the published fault should block startup.' },
	{ name: 'sys_host_fault_stage_none', params: [], signature: 'sys_host_fault_stage_none', description: 'Host fault stage constant meaning no stage is active.' },
	{ name: 'sys_host_fault_stage_startup_refresh', params: [], signature: 'sys_host_fault_stage_startup_refresh', description: 'Host fault stage constant for deferred startup audio refresh failures.' },
	{ name: 'sys_host_fault_message', params: [], signature: 'sys_host_fault_message()', description: 'Returns the current published host fault message as a string, or nil if no host fault message is present.' },
	{ name: 'sys_cart_magic_addr', params: [], signature: 'sys_cart_magic_addr', description: 'Cart ROM magic header address.' },
	{ name: 'sys_cart_magic', params: [], signature: 'sys_cart_magic', description: 'Cart ROM magic header value.' },
	{ name: 'sys_cart_rom_size', params: [], signature: 'sys_cart_rom_size', description: 'Maximum cart ROM size in bytes.' },
	{ name: 'sys_ram_size', params: [], signature: 'sys_ram_size', description: 'Total system RAM size in bytes.' },
	{ name: 'sys_max_cycles_per_frame', params: [], signature: 'sys_max_cycles_per_frame', description: 'Maximum cycles per frame.' },
	{ name: 'sys_vdp_dither', params: [], signature: 'sys_vdp_dither', description: 'VDP dither register; write to this register to control dithering. Values 0=off, 1=PSX, 2=RGB777 output, 3=MSX10' },
	{ name: 'sys_vdp_cmd', params: [], signature: 'sys_vdp_cmd', description: 'VDP submit register; write a command opcode here after filling the argument bank.' },
	{ name: 'sys_vdp_cmd_arg_count', params: [], signature: 'sys_vdp_cmd_arg_count', description: 'Number of VDP command argument slots.' },
	{ name: 'sys_vdp_arg_stride', params: [], signature: 'sys_vdp_arg_stride', description: 'Word stride between VDP command payload slots.' },
	{ name: 'sys_vdp_stream_base', params: [], signature: 'sys_vdp_stream_base', description: 'RAM base address of the CPU-side VDP command stream buffer.' },
	{ name: 'sys_vdp_stream_capacity', params: [], signature: 'sys_vdp_stream_capacity', description: 'Capacity of the CPU-side VDP command stream buffer.' },
		{ name: 'sys_vdp_fifo', params: [], signature: 'sys_vdp_fifo', description: 'VDP command FIFO write port for direct CPU or DMA streaming.' },
		{ name: 'sys_vdp_fifo_ctrl', params: [], signature: 'sys_vdp_fifo_ctrl', description: 'VDP FIFO control register; write sys_vdp_fifo_ctrl_seal to seal a direct CPU FIFO stream.' },
		{ name: 'sys_vdp_fifo_ctrl_seal', params: [], signature: 'sys_vdp_fifo_ctrl_seal', description: 'VDP FIFO control bit that seals the currently accumulated direct CPU FIFO stream.' },
		{ name: 'sys_vdp_pmu_bank', params: [], signature: 'sys_vdp_pmu_bank', description: 'VDP PMU bank select register.' },
		{ name: 'sys_vdp_pmu_x', params: [], signature: 'sys_vdp_pmu_x', description: 'VDP PMU selected-bank X offset register in signed Q16.16.' },
		{ name: 'sys_vdp_pmu_y', params: [], signature: 'sys_vdp_pmu_y', description: 'VDP PMU selected-bank Y offset register in signed Q16.16.' },
		{ name: 'sys_vdp_pmu_scale_x', params: [], signature: 'sys_vdp_pmu_scale_x', description: 'VDP PMU selected-bank X scale register in signed Q16.16.' },
		{ name: 'sys_vdp_pmu_scale_y', params: [], signature: 'sys_vdp_pmu_scale_y', description: 'VDP PMU selected-bank Y scale register in signed Q16.16.' },
		{ name: 'sys_vdp_pmu_ctrl', params: [], signature: 'sys_vdp_pmu_ctrl', description: 'VDP PMU selected-bank control register.' },
		{ name: 'sys_vdp_sbx_control', params: [], signature: 'sys_vdp_sbx_control', description: 'VDP skybox control register; bit 0 enables SBX sampling.' },
		{ name: 'sys_vdp_sbx_faces', params: [], signature: 'sys_vdp_sbx_faces', description: 'Base address of the VDP skybox face source register window.' },
		{ name: 'sys_vdp_sbx_commit', params: [], signature: 'sys_vdp_sbx_commit', description: 'VDP skybox commit doorbell register.' },
		{ name: 'sys_vdp_sbx_commit_write', params: [], signature: 'sys_vdp_sbx_commit_write', description: 'VDP skybox commit bit.' },
		{ name: 'sys_vdp_slot_primary_atlas', params: [], signature: 'sys_vdp_slot_primary_atlas', description: 'VDP MMIO word containing the atlas id currently resident in the primary slot.' },
		{ name: 'sys_vdp_slot_secondary_atlas', params: [], signature: 'sys_vdp_slot_secondary_atlas', description: 'VDP MMIO word containing the atlas id currently resident in the secondary slot.' },
		{ name: 'sys_vdp_atlas_none', params: [], signature: 'sys_vdp_atlas_none', description: 'Sentinel atlas id meaning no atlas is resident in a VDP slot.' },
		{ name: 'sys_vdp_slot_primary', params: [], signature: 'sys_vdp_slot_primary', description: 'VDP primary source slot id.' },
		{ name: 'sys_vdp_slot_secondary', params: [], signature: 'sys_vdp_slot_secondary', description: 'VDP secondary source slot id.' },
		{ name: 'sys_vdp_slot_system', params: [], signature: 'sys_vdp_slot_system', description: 'VDP system source slot id.' },
	{ name: 'sys_vdp_slot_none', params: [], signature: 'sys_vdp_slot_none', description: 'Sentinel slot id meaning no source.' },
	{ name: 'sys_vdp_rd_surface', params: [], signature: 'sys_vdp_rd_surface', description: 'VDP readback surface selector (0=system, 1=primary, 2=secondary).' },
	{ name: 'sys_vdp_rd_x', params: [], signature: 'sys_vdp_rd_x', description: 'VDP readback X coordinate (pixels).' },
	{ name: 'sys_vdp_rd_y', params: [], signature: 'sys_vdp_rd_y', description: 'VDP readback Y coordinate (pixels).' },
	{ name: 'sys_vdp_rd_mode', params: [], signature: 'sys_vdp_rd_mode', description: 'VDP readback mode register (0=RGBA8888).' },
	{ name: 'sys_vdp_rd_status', params: [], signature: 'sys_vdp_rd_status', description: 'VDP readback status register; READY/OVERFLOW bits.' },
	{ name: 'sys_vdp_rd_data', params: [], signature: 'sys_vdp_rd_data', description: 'VDP readback data register; read RGBA8888 per access.' },
	{ name: 'sys_vdp_status', params: [], signature: 'sys_vdp_status', description: 'VDP status register; read submit/vblank/fault bits.' },
	{ name: 'sys_vdp_fault_code', params: [], signature: 'sys_vdp_fault_code', description: 'VDP fault-code register for cart-visible device faults.' },
	{ name: 'sys_vdp_fault_detail', params: [], signature: 'sys_vdp_fault_detail', description: 'VDP fault-detail register for cart-visible device faults.' },
	{ name: 'sys_vdp_rd_mode_rgba8888', params: [], signature: 'sys_vdp_rd_mode_rgba8888', description: 'VDP readback mode constant for RGBA8888.' },
	{ name: 'sys_vdp_rd_status_ready', params: [], signature: 'sys_vdp_rd_status_ready', description: 'VDP readback status bit: ready.' },
	{ name: 'sys_vdp_rd_status_overflow', params: [], signature: 'sys_vdp_rd_status_overflow', description: 'VDP readback status bit: overflow.' },
	{ name: 'sys_vdp_status_vblank', params: [], signature: 'sys_vdp_status_vblank', description: 'VDP status bit: VBLANK level.' },
	{ name: 'sys_vdp_status_submit_busy', params: [], signature: 'sys_vdp_status_submit_busy', description: 'VDP status bit: submit path busy.' },
	{ name: 'sys_vdp_status_submit_rejected', params: [], signature: 'sys_vdp_status_submit_rejected', description: 'VDP status bit: most recent submit attempt was rejected.' },
	{ name: 'sys_vdp_status_fault', params: [], signature: 'sys_vdp_status_fault', description: 'VDP status bit: a cart-visible device fault is latched.' },
	{ name: 'sys_vdp_fault_none', params: [], signature: 'sys_vdp_fault_none', description: 'VDP fault code: no fault.' },
	{ name: 'sys_vdp_fault_rd_unsupported_mode', params: [], signature: 'sys_vdp_fault_rd_unsupported_mode', description: 'VDP fault code: unsupported readback mode.' },
	{ name: 'sys_vdp_fault_rd_surface', params: [], signature: 'sys_vdp_fault_rd_surface', description: 'VDP fault code: readback surface is not visible to the device.' },
	{ name: 'sys_vdp_fault_rd_oob', params: [], signature: 'sys_vdp_fault_rd_oob', description: 'VDP fault code: readback coordinate is outside the selected surface.' },
	{ name: 'sys_vdp_fault_vram_write_unmapped', params: [], signature: 'sys_vdp_fault_vram_write_unmapped', description: 'VDP fault code: VRAM write address has no mapped slot.' },
	{ name: 'sys_vdp_fault_vram_write_uninitialized', params: [], signature: 'sys_vdp_fault_vram_write_uninitialized', description: 'VDP fault code: VRAM write hit an uninitialized slot.' },
	{ name: 'sys_vdp_fault_vram_write_oob', params: [], signature: 'sys_vdp_fault_vram_write_oob', description: 'VDP fault code: VRAM write exceeds the selected slot surface.' },
	{ name: 'sys_vdp_fault_vram_write_unaligned', params: [], signature: 'sys_vdp_fault_vram_write_unaligned', description: 'VDP fault code: VRAM write is not 32-bit aligned.' },
	{ name: 'sys_vdp_fault_vram_slot_dim', params: [], signature: 'sys_vdp_fault_vram_slot_dim', description: 'VDP fault code: VRAM slot dimension register cannot be applied.' },
	{ name: 'sys_vdp_fault_stream_bad_packet', params: [], signature: 'sys_vdp_fault_stream_bad_packet', description: 'VDP fault code: FIFO/DMA packet stream is malformed.' },
	{ name: 'sys_vdp_fault_submit_state', params: [], signature: 'sys_vdp_fault_submit_state', description: 'VDP fault code: direct command doorbell does not match submit state.' },
	{ name: 'sys_vdp_fault_cmd_bad_doorbell', params: [], signature: 'sys_vdp_fault_cmd_bad_doorbell', description: 'VDP fault code: command doorbell opcode is not implemented.' },
	{ name: 'sys_vdp_fault_submit_busy', params: [], signature: 'sys_vdp_fault_submit_busy', description: 'VDP fault code: submit path rejected work while busy.' },
	{ name: 'sys_vdp_fault_dex_invalid_scale', params: [], signature: 'sys_vdp_fault_dex_invalid_scale', description: 'VDP fault code: DEX blit scale is invalid.' },
	{ name: 'sys_vdp_fault_dex_invalid_line_width', params: [], signature: 'sys_vdp_fault_dex_invalid_line_width', description: 'VDP fault code: DEX line width is invalid.' },
	{ name: 'sys_vdp_fault_dex_source_slot', params: [], signature: 'sys_vdp_fault_dex_source_slot', description: 'VDP fault code: DEX source slot is not sampleable.' },
	{ name: 'sys_vdp_fault_dex_source_oob', params: [], signature: 'sys_vdp_fault_dex_source_oob', description: 'VDP fault code: DEX source rectangle is zero-sized or out of bounds.' },
	{ name: 'sys_vdp_fault_sbx_source_oob', params: [], signature: 'sys_vdp_fault_sbx_source_oob', description: 'VDP fault code: SBX source rectangle is outside its surface.' },
	{ name: 'sys_vdp_fault_bbu_zero_size', params: [], signature: 'sys_vdp_fault_bbu_zero_size', description: 'VDP fault code: BBU billboard size is zero.' },
	{ name: 'sys_vdp_fault_bbu_overflow', params: [], signature: 'sys_vdp_fault_bbu_overflow', description: 'VDP fault code: BBU billboard FIFO is full.' },
	{ name: 'sys_vdp_fault_bbu_source_oob', params: [], signature: 'sys_vdp_fault_bbu_source_oob', description: 'VDP fault code: BBU source rectangle is outside its surface.' },
	{ name: 'sys_vdp_layer_world', params: [], signature: 'sys_vdp_layer_world', description: 'VDP layer id for world-space rendering.' },
	{ name: 'sys_vdp_layer_ui', params: [], signature: 'sys_vdp_layer_ui', description: 'VDP layer id for UI rendering.' },
	{ name: 'sys_vdp_layer_ide', params: [], signature: 'sys_vdp_layer_ide', description: 'VDP layer id for IDE/overlay rendering.' },
	{ name: 'sys_irq_flags', params: [], signature: 'sys_irq_flags', description: 'IRQ flags register address; read pending IRQ bits.' },
	{ name: 'sys_irq_ack', params: [], signature: 'sys_irq_ack', description: 'IRQ acknowledge register address; write bits to clear.' },
	{ name: 'sys_dma_src', params: [], signature: 'sys_dma_src', description: 'DMA source address register.' },
	{ name: 'sys_dma_dst', params: [], signature: 'sys_dma_dst', description: 'DMA destination address register.' },
	{ name: 'sys_dma_len', params: [], signature: 'sys_dma_len', description: 'DMA transfer length in bytes.' },
	{ name: 'sys_dma_ctrl', params: [], signature: 'sys_dma_ctrl', description: 'DMA control register; write dma_ctrl_start to begin.' },
	{ name: 'sys_dma_status', params: [], signature: 'sys_dma_status', description: 'DMA status register; busy/done/error/clipped/rejected bits.' },
	{ name: 'sys_dma_written', params: [], signature: 'sys_dma_written', description: 'DMA written byte count register.' },
	{ name: 'sys_geo_scratch_base', params: [], signature: 'sys_geo_scratch_base', description: 'Geometry scratch RAM base address.' },
	{ name: 'sys_geo_scratch_size', params: [], signature: 'sys_geo_scratch_size', description: 'Geometry scratch RAM size in bytes.' },
	{ name: 'sys_geo_src0', params: [], signature: 'sys_geo_src0', description: 'GEO source pointer register 0.' },
	{ name: 'sys_geo_src1', params: [], signature: 'sys_geo_src1', description: 'GEO source pointer register 1.' },
	{ name: 'sys_geo_src2', params: [], signature: 'sys_geo_src2', description: 'GEO source pointer register 2.' },
	{ name: 'sys_geo_dst0', params: [], signature: 'sys_geo_dst0', description: 'GEO destination pointer register 0.' },
	{ name: 'sys_geo_dst1', params: [], signature: 'sys_geo_dst1', description: 'GEO destination pointer register 1.' },
	{ name: 'sys_geo_count', params: [], signature: 'sys_geo_count', description: 'GEO record count register.' },
	{ name: 'sys_geo_cmd', params: [], signature: 'sys_geo_cmd', description: 'GEO command doorbell register; write after staging operands.' },
	{ name: 'sys_geo_ctrl', params: [], signature: 'sys_geo_ctrl', description: 'GEO control register; abort-only.' },
	{ name: 'sys_geo_status', params: [], signature: 'sys_geo_status', description: 'GEO status register; busy/done/error/rejected bits.' },
	{ name: 'sys_geo_param0', params: [], signature: 'sys_geo_param0', description: 'GEO command parameter register 0.' },
	{ name: 'sys_geo_param1', params: [], signature: 'sys_geo_param1', description: 'GEO command parameter register 1.' },
	{ name: 'sys_geo_stride0', params: [], signature: 'sys_geo_stride0', description: 'GEO byte stride register for src0.' },
	{ name: 'sys_geo_stride1', params: [], signature: 'sys_geo_stride1', description: 'GEO byte stride register for src1.' },
	{ name: 'sys_geo_stride2', params: [], signature: 'sys_geo_stride2', description: 'GEO byte stride register for src2.' },
	{ name: 'sys_geo_processed', params: [], signature: 'sys_geo_processed', description: 'GEO processed record count register.' },
	{ name: 'sys_geo_fault', params: [], signature: 'sys_geo_fault', description: 'GEO fault register: high 16 bits code, low 16 bits record index.' },
	{ name: 'sys_geo_fault_ack', params: [], signature: 'sys_geo_fault_ack', description: 'GEO fault acknowledge register; write one to clear the fault latch.' },
	{ name: 'sys_img_src', params: [], signature: 'sys_img_src', description: 'IMGDEC source address register.' },
	{ name: 'sys_img_len', params: [], signature: 'sys_img_len', description: 'IMGDEC source length in bytes.' },
	{ name: 'sys_img_dst', params: [], signature: 'sys_img_dst', description: 'IMGDEC destination address register.' },
	{ name: 'sys_img_cap', params: [], signature: 'sys_img_cap', description: 'IMGDEC destination capacity in bytes.' },
	{ name: 'sys_img_ctrl', params: [], signature: 'sys_img_ctrl', description: 'IMGDEC control register; write img_ctrl_start to begin.' },
	{ name: 'sys_img_status', params: [], signature: 'sys_img_status', description: 'IMGDEC status register; busy/done/error bits.' },
	{ name: 'sys_img_written', params: [], signature: 'sys_img_written', description: 'IMGDEC written byte count register.' },
	{ name: 'sys_inp_player', params: [], signature: 'sys_inp_player', description: 'Input Controller player index register (1-based).' },
	{ name: 'sys_inp_action', params: [], signature: 'sys_inp_action', description: 'Input Controller action-name register; write an action-name string before inp_ctrl_commit.' },
	{ name: 'sys_inp_bind', params: [], signature: 'sys_inp_bind', description: 'Input Controller binding register; write comma-separated button names as a string.' },
	{ name: 'sys_inp_ctrl', params: [], signature: 'sys_inp_ctrl', description: 'Input Controller command register; write inp_ctrl_commit, inp_ctrl_arm, or inp_ctrl_reset.' },
	{ name: 'sys_inp_query', params: [], signature: 'sys_inp_query', description: 'Input Controller query register; write an action expression such as left[p] or jump[jp].' },
	{ name: 'sys_inp_status', params: [], signature: 'sys_inp_status', description: 'Input Controller query result register; 1 when the last query was triggered, else 0.' },
	{ name: 'sys_inp_value', params: [], signature: 'sys_inp_value', description: 'Input Controller analog value register for simple single-action queries.' },
	{ name: 'sys_inp_consume', params: [], signature: 'sys_inp_consume', description: 'Input Controller consume register; write an action name or comma-separated action names string to consume them in order.' },
	{ name: 'sys_apu_source_addr', params: [], signature: 'sys_apu_source_addr', description: 'APU audio source address register.' },
	{ name: 'sys_apu_source_bytes', params: [], signature: 'sys_apu_source_bytes', description: 'APU audio source byte length register.' },
	{ name: 'sys_apu_source_sample_rate_hz', params: [], signature: 'sys_apu_source_sample_rate_hz', description: 'APU audio source sample rate register.' },
	{ name: 'sys_apu_source_channels', params: [], signature: 'sys_apu_source_channels', description: 'APU audio source channel count register.' },
	{ name: 'sys_apu_source_bits_per_sample', params: [], signature: 'sys_apu_source_bits_per_sample', description: 'APU audio source bit depth register.' },
	{ name: 'sys_apu_source_frame_count', params: [], signature: 'sys_apu_source_frame_count', description: 'APU audio source frame count register.' },
	{ name: 'sys_apu_source_data_offset', params: [], signature: 'sys_apu_source_data_offset', description: 'APU encoded audio data offset register.' },
	{ name: 'sys_apu_source_data_bytes', params: [], signature: 'sys_apu_source_data_bytes', description: 'APU encoded audio data byte length register.' },
	{ name: 'sys_apu_source_loop_start_sample', params: [], signature: 'sys_apu_source_loop_start_sample', description: 'APU loop start sample register.' },
	{ name: 'sys_apu_source_loop_end_sample', params: [], signature: 'sys_apu_source_loop_end_sample', description: 'APU loop end sample register.' },
	{ name: 'sys_apu_slot', params: [], signature: 'sys_apu_slot', description: 'APU hardware slot register.' },
	{ name: 'sys_apu_rate_step_q16', params: [], signature: 'sys_apu_rate_step_q16', description: 'APU playback step register in Q16.16; apu_rate_step_q16_one means normal speed.' },
	{ name: 'sys_apu_gain_q12', params: [], signature: 'sys_apu_gain_q12', description: 'APU gain register in Q12 fixed point; apu_gain_q12_one means unity gain.' },
	{ name: 'sys_apu_start_sample', params: [], signature: 'sys_apu_start_sample', description: 'APU start offset register in source samples.' },
	{ name: 'sys_apu_filter_kind', params: [], signature: 'sys_apu_filter_kind', description: 'APU filter type register.' },
	{ name: 'sys_apu_filter_freq_hz', params: [], signature: 'sys_apu_filter_freq_hz', description: 'APU filter frequency register in Hz.' },
	{ name: 'sys_apu_filter_q_milli', params: [], signature: 'sys_apu_filter_q_milli', description: 'APU filter Q register in milli-units.' },
	{ name: 'sys_apu_filter_gain_millidb', params: [], signature: 'sys_apu_filter_gain_millidb', description: 'APU filter gain register in milli-decibels.' },
	{ name: 'sys_apu_fade_samples', params: [], signature: 'sys_apu_fade_samples', description: 'APU STOP_SLOT fade duration register in samples at apu_sample_rate_hz.' },
	{ name: 'sys_apu_generator_kind', params: [], signature: 'sys_apu_generator_kind', description: 'APU internal generator kind register; apu_generator_none selects source-DMA playback.' },
	{ name: 'sys_apu_generator_duty_q12', params: [], signature: 'sys_apu_generator_duty_q12', description: 'APU square-generator duty cycle in Q12 fixed point.' },
	{ name: 'sys_apu_cmd', params: [], signature: 'sys_apu_cmd', description: 'APU command doorbell register.' },
	{ name: 'sys_apu_status', params: [], signature: 'sys_apu_status', description: 'APU status register.' },
	{ name: 'sys_apu_fault_code', params: [], signature: 'sys_apu_fault_code', description: 'APU sticky fault-code register.' },
	{ name: 'sys_apu_fault_detail', params: [], signature: 'sys_apu_fault_detail', description: 'APU sticky fault-detail register.' },
	{ name: 'sys_apu_fault_ack', params: [], signature: 'sys_apu_fault_ack', description: 'APU write-one-to-clear sticky fault register.' },
	{ name: 'sys_apu_event_kind', params: [], signature: 'sys_apu_event_kind', description: 'APU event kind register.' },
	{ name: 'sys_apu_event_slot', params: [], signature: 'sys_apu_event_slot', description: 'APU event slot register.' },
	{ name: 'sys_apu_event_source_addr', params: [], signature: 'sys_apu_event_source_addr', description: 'APU event source address register.' },
	{ name: 'sys_apu_event_seq', params: [], signature: 'sys_apu_event_seq', description: 'APU event sequence register.' },
	{ name: 'sys_apu_selected_source_addr', params: [], signature: 'sys_apu_selected_source_addr', description: 'APU active selected-slot source-address register.' },
	{ name: 'sys_apu_active_mask', params: [], signature: 'sys_apu_active_mask', description: 'APU active hardware slot mask register.' },
	{ name: 'sys_apu_selected_slot_regs', params: [], signature: 'sys_apu_selected_slot_regs', description: 'APU selected-slot raw parameter latch read/write window.' },
	{ name: 'sys_apu_selected_slot_reg_count', params: [], signature: 'sys_apu_selected_slot_reg_count', description: 'APU selected-slot raw parameter latch read/write word count.' },
	{ name: 'sys_apu_output_queued_frames', params: [], signature: 'sys_apu_output_queued_frames', description: 'APU AOUT output-ring queued-frame readback register.' },
	{ name: 'sys_apu_output_free_frames', params: [], signature: 'sys_apu_output_free_frames', description: 'APU AOUT output-ring free-frame readback register.' },
	{ name: 'sys_apu_output_capacity_frames', params: [], signature: 'sys_apu_output_capacity_frames', description: 'APU AOUT output-ring capacity readback register.' },
	{ name: 'sys_apu_cmd_queued', params: [], signature: 'sys_apu_cmd_queued', description: 'APU command FIFO queued-command readback register.' },
	{ name: 'sys_apu_cmd_free', params: [], signature: 'sys_apu_cmd_free', description: 'APU command FIFO free-entry readback register.' },
	{ name: 'sys_apu_cmd_capacity', params: [], signature: 'sys_apu_cmd_capacity', description: 'APU command FIFO capacity readback register.' },
	{ name: 'sys_rom_system_base', params: [], signature: 'sys_rom_system_base', description: 'System ROM base address.' },
	{ name: 'sys_rom_cart_base', params: [], signature: 'sys_rom_cart_base', description: 'Cart ROM base address.' },
	{ name: 'sys_rom_overlay_base', params: [], signature: 'sys_rom_overlay_base', description: 'Overlay ROM base address.' },
	{ name: 'sys_rom_overlay_size', params: [], signature: 'sys_rom_overlay_size', description: 'Overlay ROM size in bytes.' },
	{ name: 'sys_vram_system_slot_base', params: [], signature: 'sys_vram_system_slot_base', description: 'VRAM system slot base address.' },
	{ name: 'sys_vram_primary_slot_base', params: [], signature: 'sys_vram_primary_slot_base', description: 'VRAM primary slot slot base address.' },
	{ name: 'sys_vram_secondary_slot_base', params: [], signature: 'sys_vram_secondary_slot_base', description: 'VRAM secondary slot slot base address.' },
	{ name: 'sys_vram_framebuffer_base', params: [], signature: 'sys_vram_framebuffer_base', description: 'VRAM framebuffer base address.' },
	{ name: 'sys_vram_staging_base', params: [], signature: 'sys_vram_staging_base', description: 'VRAM staging buffer base address.' },
	{ name: 'sys_vram_system_slot_size', params: [], signature: 'sys_vram_system_slot_size', description: 'VRAM system slot size in bytes.' },
	{ name: 'sys_vram_primary_slot_size', params: [], signature: 'sys_vram_primary_slot_size', description: 'VRAM primary slot slot size in bytes.' },
	{ name: 'sys_vram_secondary_slot_size', params: [], signature: 'sys_vram_secondary_slot_size', description: 'VRAM secondary slot slot size in bytes.' },
	{ name: 'sys_vram_framebuffer_size', params: [], signature: 'sys_vram_framebuffer_size', description: 'VRAM framebuffer size in bytes.' },
	{ name: 'sys_vram_staging_size', params: [], signature: 'sys_vram_staging_size', description: 'VRAM staging buffer size in bytes.' },
	{ name: 'sys_vram_size', params: [], signature: 'sys_vram_size', description: 'Tracked total VRAM capacity in bytes.' },
	{ name: 'irq_dma_done', params: [], signature: 'irq_dma_done', description: 'IRQ flag for DMA completion.' },
	{ name: 'irq_dma_error', params: [], signature: 'irq_dma_error', description: 'IRQ flag for DMA error.' },
	{ name: 'irq_geo_done', params: [], signature: 'irq_geo_done', description: 'IRQ flag for GEO completion.' },
	{ name: 'irq_geo_error', params: [], signature: 'irq_geo_error', description: 'IRQ flag for GEO error.' },
	{ name: 'irq_img_done', params: [], signature: 'irq_img_done', description: 'IRQ flag for IMGDEC completion.' },
	{ name: 'irq_img_error', params: [], signature: 'irq_img_error', description: 'IRQ flag for IMGDEC error.' },
	{ name: 'irq_vblank', params: [], signature: 'irq_vblank', description: 'IRQ flag for VBLANK entry.' },
	{ name: 'irq_reinit', params: [], signature: 'irq_reinit', description: 'IRQ flag for cart reinitialization events.' },
	{ name: 'irq_newgame', params: [], signature: 'irq_newgame', description: 'IRQ flag for new-game start events.' },
	{ name: 'irq_apu', params: [], signature: 'irq_apu', description: 'IRQ flag for APU voice events.' },
	{ name: 'apu_cmd_play', params: [], signature: 'apu_cmd_play', description: 'APU command: play the handle in the selected slot.' },
	{ name: 'apu_cmd_stop_slot', params: [], signature: 'apu_cmd_stop_slot', description: 'APU command: stop the selected slot.' },
	{ name: 'apu_cmd_set_slot_gain', params: [], signature: 'apu_cmd_set_slot_gain', description: 'APU command: copy sys_apu_gain_q12 into the selected slot current-gain latch.' },
	{ name: 'apu_sample_rate_hz', params: [], signature: 'apu_sample_rate_hz', description: 'APU hardware sample clock in Hz.' },
	{ name: 'apu_rate_step_q16_one', params: [], signature: 'apu_rate_step_q16_one', description: 'APU Q16.16 rate-step value for normal speed.' },
	{ name: 'apu_gain_q12_one', params: [], signature: 'apu_gain_q12_one', description: 'APU Q12 gain value for unity gain.' },
	{ name: 'apu_generator_none', params: [], signature: 'apu_generator_none', description: 'APU generator kind: no internal generator; play source-DMA audio.' },
	{ name: 'apu_generator_square', params: [], signature: 'apu_generator_square', description: 'APU generator kind: square oscillator clocked by the source-rate register.' },
	{ name: 'apu_output_queue_capacity_frames', params: [], signature: 'apu_output_queue_capacity_frames', description: 'AOUT hardware output-ring capacity in PCM frames.' },
	{ name: 'apu_command_fifo_capacity', params: [], signature: 'apu_command_fifo_capacity', description: 'APU command FIFO capacity in queued commands.' },
	{ name: 'apu_status_fault', params: [], signature: 'apu_status_fault', description: 'APU status bit: sticky fault is latched.' },
	{ name: 'apu_status_selected_slot_active', params: [], signature: 'apu_status_selected_slot_active', description: 'APU status bit: selected hardware slot is active.' },
	{ name: 'apu_status_busy', params: [], signature: 'apu_status_busy', description: 'APU status bit: at least one hardware slot is pending or active.' },
	{ name: 'apu_status_output_empty', params: [], signature: 'apu_status_output_empty', description: 'APU status bit: AOUT output ring has no queued PCM frames.' },
	{ name: 'apu_status_output_full', params: [], signature: 'apu_status_output_full', description: 'APU status bit: AOUT output ring is full.' },
	{ name: 'apu_status_cmd_fifo_empty', params: [], signature: 'apu_status_cmd_fifo_empty', description: 'APU status bit: command FIFO has no queued commands.' },
	{ name: 'apu_status_cmd_fifo_full', params: [], signature: 'apu_status_cmd_fifo_full', description: 'APU status bit: command FIFO is full.' },
	{ name: 'apu_fault_none', params: [], signature: 'apu_fault_none', description: 'APU fault code: no fault latched.' },
	{ name: 'apu_fault_bad_cmd', params: [], signature: 'apu_fault_bad_cmd', description: 'APU fault code: unsupported command doorbell value.' },
	{ name: 'apu_fault_bad_slot', params: [], signature: 'apu_fault_bad_slot', description: 'APU fault code: selected slot is outside the hardware slot bank.' },
	{ name: 'apu_fault_cmd_fifo_full', params: [], signature: 'apu_fault_cmd_fifo_full', description: 'APU fault code: command FIFO is full.' },
	{ name: 'apu_fault_source_bytes', params: [], signature: 'apu_fault_source_bytes', description: 'APU fault code: source byte length is zero.' },
	{ name: 'apu_fault_source_range', params: [], signature: 'apu_fault_source_range', description: 'APU fault code: source range is outside readable RAM.' },
	{ name: 'apu_fault_source_sample_rate', params: [], signature: 'apu_fault_source_sample_rate', description: 'APU fault code: source sample-rate register is invalid.' },
	{ name: 'apu_fault_source_channels', params: [], signature: 'apu_fault_source_channels', description: 'APU fault code: source channel-count register is invalid.' },
	{ name: 'apu_fault_source_frame_count', params: [], signature: 'apu_fault_source_frame_count', description: 'APU fault code: source frame-count register is zero.' },
	{ name: 'apu_fault_source_data_range', params: [], signature: 'apu_fault_source_data_range', description: 'APU fault code: encoded source data range exceeds source bytes.' },
	{ name: 'apu_fault_source_bit_depth', params: [], signature: 'apu_fault_source_bit_depth', description: 'APU fault code: source bit-depth register is unsupported.' },
	{ name: 'apu_fault_unsupported_format', params: [], signature: 'apu_fault_unsupported_format', description: 'APU fault code: AOUT source header is not a supported encoded format.' },
	{ name: 'apu_fault_output_metadata', params: [], signature: 'apu_fault_output_metadata', description: 'APU fault code: AOUT encoded source metadata does not match the slot registerfile.' },
	{ name: 'apu_fault_output_data_range', params: [], signature: 'apu_fault_output_data_range', description: 'APU fault code: AOUT encoded source data range is invalid.' },
	{ name: 'apu_fault_output_playback_rate', params: [], signature: 'apu_fault_output_playback_rate', description: 'APU fault code: AOUT playback step is not positive.' },
	{ name: 'apu_fault_output_block', params: [], signature: 'apu_fault_output_block', description: 'APU fault code: AOUT encoded audio block is invalid.' },
	{ name: 'apu_filter_none', params: [], signature: 'apu_filter_none', description: 'APU filter constant: no filter.' },
	{ name: 'apu_filter_lowpass', params: [], signature: 'apu_filter_lowpass', description: 'APU filter constant: lowpass.' },
	{ name: 'apu_filter_highpass', params: [], signature: 'apu_filter_highpass', description: 'APU filter constant: highpass.' },
	{ name: 'apu_filter_bandpass', params: [], signature: 'apu_filter_bandpass', description: 'APU filter constant: bandpass.' },
	{ name: 'apu_filter_notch', params: [], signature: 'apu_filter_notch', description: 'APU filter constant: notch.' },
	{ name: 'apu_filter_allpass', params: [], signature: 'apu_filter_allpass', description: 'APU filter constant: allpass.' },
	{ name: 'apu_filter_peaking', params: [], signature: 'apu_filter_peaking', description: 'APU filter constant: peaking.' },
	{ name: 'apu_filter_lowshelf', params: [], signature: 'apu_filter_lowshelf', description: 'APU filter constant: lowshelf.' },
	{ name: 'apu_filter_highshelf', params: [], signature: 'apu_filter_highshelf', description: 'APU filter constant: highshelf.' },
	{ name: 'apu_event_none', params: [], signature: 'apu_event_none', description: 'APU event kind: no event.' },
	{ name: 'apu_event_slot_ended', params: [], signature: 'apu_event_slot_ended', description: 'APU event kind: slot playback ended.' },
	{ name: 'dma_ctrl_start', params: [], signature: 'dma_ctrl_start', description: 'DMA control bit: start transfer.' },
	{ name: 'dma_ctrl_strict', params: [], signature: 'dma_ctrl_strict', description: 'DMA control bit: strict overflow handling.' },
	{ name: 'dma_status_busy', params: [], signature: 'dma_status_busy', description: 'DMA status bit: busy.' },
	{ name: 'dma_status_done', params: [], signature: 'dma_status_done', description: 'DMA status bit: done.' },
	{ name: 'dma_status_error', params: [], signature: 'dma_status_error', description: 'DMA status bit: error.' },
	{ name: 'dma_status_clipped', params: [], signature: 'dma_status_clipped', description: 'DMA status bit: clipped.' },
	{ name: 'dma_status_rejected', params: [], signature: 'dma_status_rejected', description: 'DMA status bit: start request was rejected and no transfer began.' },
	{ name: 'sys_geo_ctrl_abort', params: [], signature: 'sys_geo_ctrl_abort', description: 'GEO control bit: abort active job.' },
	{ name: 'geo_status_busy', params: [], signature: 'geo_status_busy', description: 'GEO status bit: busy.' },
	{ name: 'geo_status_done', params: [], signature: 'geo_status_done', description: 'GEO status bit: done.' },
	{ name: 'geo_status_error', params: [], signature: 'geo_status_error', description: 'GEO status bit: error.' },
	{ name: 'geo_status_rejected', params: [], signature: 'geo_status_rejected', description: 'GEO status bit: submission was rejected.' },
	{ name: 'sys_geo_cmd_xform2_batch', params: [], signature: 'sys_geo_cmd_xform2_batch', description: 'GEO command opcode for batched 2D affine transforms.' },
	{ name: 'sys_geo_cmd_sat2_batch', params: [], signature: 'sys_geo_cmd_sat2_batch', description: 'GEO command opcode for batched convex polygon SAT tests.' },
	{ name: 'sys_geo_cmd_overlap2d_pass', params: [], signature: 'sys_geo_cmd_overlap2d_pass', description: 'GEO command opcode for the overlap2d coprocessor pass.' },
	{ name: 'sys_geo_index_none', params: [], signature: 'sys_geo_index_none', description: 'GEO sentinel index meaning no destination record.' },
	{ name: 'sys_geo_primitive_aabb', params: [], signature: 'sys_geo_primitive_aabb', description: 'GEO primitive kind for an AABB descriptor.' },
	{ name: 'sys_geo_primitive_convex_poly', params: [], signature: 'sys_geo_primitive_convex_poly', description: 'GEO primitive kind for a convex polygon descriptor.' },
	{ name: 'sys_geo_shape_convex_poly', params: [], signature: 'sys_geo_shape_convex_poly', description: 'GEO descriptor flag for convex polygon shapes.' },
	{ name: 'sys_geo_vertex2_bytes', params: [], signature: 'sys_geo_vertex2_bytes', description: 'GEO shared 2D vertex record size in bytes.' },
	{ name: 'sys_geo_vertex2_x_offset', params: [], signature: 'sys_geo_vertex2_x_offset', description: 'Byte offset of X in a GEO 2D vertex record.' },
	{ name: 'sys_geo_vertex2_y_offset', params: [], signature: 'sys_geo_vertex2_y_offset', description: 'Byte offset of Y in a GEO 2D vertex record.' },
	{ name: 'sys_geo_xform2_record_bytes', params: [], signature: 'sys_geo_xform2_record_bytes', description: 'GEO xform2 command record size in bytes.' },
	{ name: 'sys_geo_xform2_record_flags_offset', params: [], signature: 'sys_geo_xform2_record_flags_offset', description: 'Byte offset of flags in a GEO xform2 record.' },
	{ name: 'sys_geo_xform2_record_src_index_offset', params: [], signature: 'sys_geo_xform2_record_src_index_offset', description: 'Byte offset of source vertex index in a GEO xform2 record.' },
	{ name: 'sys_geo_xform2_record_dst_index_offset', params: [], signature: 'sys_geo_xform2_record_dst_index_offset', description: 'Byte offset of destination vertex index in a GEO xform2 record.' },
	{ name: 'sys_geo_xform2_record_aux_index_offset', params: [], signature: 'sys_geo_xform2_record_aux_index_offset', description: 'Byte offset of matrix index in a GEO xform2 record.' },
	{ name: 'sys_geo_xform2_record_vertex_count_offset', params: [], signature: 'sys_geo_xform2_record_vertex_count_offset', description: 'Byte offset of vertex count in a GEO xform2 record.' },
	{ name: 'sys_geo_xform2_record_dst1_index_offset', params: [], signature: 'sys_geo_xform2_record_dst1_index_offset', description: 'Byte offset of optional AABB index in a GEO xform2 record.' },
	{ name: 'sys_geo_xform2_matrix_bytes', params: [], signature: 'sys_geo_xform2_matrix_bytes', description: 'GEO xform2 matrix record size in bytes.' },
	{ name: 'sys_geo_xform2_matrix_m00_offset', params: [], signature: 'sys_geo_xform2_matrix_m00_offset', description: 'Byte offset of m00 in a GEO xform2 matrix record.' },
	{ name: 'sys_geo_xform2_matrix_m01_offset', params: [], signature: 'sys_geo_xform2_matrix_m01_offset', description: 'Byte offset of m01 in a GEO xform2 matrix record.' },
	{ name: 'sys_geo_xform2_matrix_tx_offset', params: [], signature: 'sys_geo_xform2_matrix_tx_offset', description: 'Byte offset of tx in a GEO xform2 matrix record.' },
	{ name: 'sys_geo_xform2_matrix_m10_offset', params: [], signature: 'sys_geo_xform2_matrix_m10_offset', description: 'Byte offset of m10 in a GEO xform2 matrix record.' },
	{ name: 'sys_geo_xform2_matrix_m11_offset', params: [], signature: 'sys_geo_xform2_matrix_m11_offset', description: 'Byte offset of m11 in a GEO xform2 matrix record.' },
	{ name: 'sys_geo_xform2_matrix_ty_offset', params: [], signature: 'sys_geo_xform2_matrix_ty_offset', description: 'Byte offset of ty in a GEO xform2 matrix record.' },
	{ name: 'sys_geo_xform2_aabb_bytes', params: [], signature: 'sys_geo_xform2_aabb_bytes', description: 'GEO xform2 output AABB record size in bytes.' },
	{ name: 'sys_geo_xform2_aabb_min_x_offset', params: [], signature: 'sys_geo_xform2_aabb_min_x_offset', description: 'Byte offset of min X in a GEO xform2 AABB record.' },
	{ name: 'sys_geo_xform2_aabb_min_y_offset', params: [], signature: 'sys_geo_xform2_aabb_min_y_offset', description: 'Byte offset of min Y in a GEO xform2 AABB record.' },
	{ name: 'sys_geo_xform2_aabb_max_x_offset', params: [], signature: 'sys_geo_xform2_aabb_max_x_offset', description: 'Byte offset of max X in a GEO xform2 AABB record.' },
	{ name: 'sys_geo_xform2_aabb_max_y_offset', params: [], signature: 'sys_geo_xform2_aabb_max_y_offset', description: 'Byte offset of max Y in a GEO xform2 AABB record.' },
	{ name: 'sys_geo_xform2_max_vertices', params: [], signature: 'sys_geo_xform2_max_vertices', description: 'GEO xform2 per-record vertex capacity.' },
	{ name: 'sys_geo_sat2_pair_bytes', params: [], signature: 'sys_geo_sat2_pair_bytes', description: 'GEO sat2 pair record size in bytes.' },
	{ name: 'sys_geo_sat2_pair_flags_offset', params: [], signature: 'sys_geo_sat2_pair_flags_offset', description: 'Byte offset of flags in a GEO sat2 pair record.' },
	{ name: 'sys_geo_sat2_pair_shape_a_index_offset', params: [], signature: 'sys_geo_sat2_pair_shape_a_index_offset', description: 'Byte offset of shape A index in a GEO sat2 pair record.' },
	{ name: 'sys_geo_sat2_pair_result_index_offset', params: [], signature: 'sys_geo_sat2_pair_result_index_offset', description: 'Byte offset of result index in a GEO sat2 pair record.' },
	{ name: 'sys_geo_sat2_pair_shape_b_index_offset', params: [], signature: 'sys_geo_sat2_pair_shape_b_index_offset', description: 'Byte offset of shape B index in a GEO sat2 pair record.' },
	{ name: 'sys_geo_sat2_pair_flags2_offset', params: [], signature: 'sys_geo_sat2_pair_flags2_offset', description: 'Byte offset of secondary flags in a GEO sat2 pair record.' },
	{ name: 'sys_geo_sat2_desc_bytes', params: [], signature: 'sys_geo_sat2_desc_bytes', description: 'GEO sat2 shape descriptor size in bytes.' },
	{ name: 'sys_geo_sat2_desc_flags_offset', params: [], signature: 'sys_geo_sat2_desc_flags_offset', description: 'Byte offset of flags in a GEO sat2 descriptor.' },
	{ name: 'sys_geo_sat2_desc_vertex_count_offset', params: [], signature: 'sys_geo_sat2_desc_vertex_count_offset', description: 'Byte offset of vertex count in a GEO sat2 descriptor.' },
	{ name: 'sys_geo_sat2_desc_vertex_offset_offset', params: [], signature: 'sys_geo_sat2_desc_vertex_offset_offset', description: 'Byte offset of vertex data offset in a GEO sat2 descriptor.' },
	{ name: 'sys_geo_sat2_desc_reserved_offset', params: [], signature: 'sys_geo_sat2_desc_reserved_offset', description: 'Byte offset of reserved word in a GEO sat2 descriptor.' },
	{ name: 'sys_geo_sat2_result_bytes', params: [], signature: 'sys_geo_sat2_result_bytes', description: 'GEO sat2 result record size in bytes.' },
	{ name: 'sys_geo_sat2_result_hit_offset', params: [], signature: 'sys_geo_sat2_result_hit_offset', description: 'Byte offset of hit flag in a GEO sat2 result record.' },
	{ name: 'sys_geo_sat2_result_nx_offset', params: [], signature: 'sys_geo_sat2_result_nx_offset', description: 'Byte offset of normal X in a GEO sat2 result record.' },
	{ name: 'sys_geo_sat2_result_ny_offset', params: [], signature: 'sys_geo_sat2_result_ny_offset', description: 'Byte offset of normal Y in a GEO sat2 result record.' },
	{ name: 'sys_geo_sat2_result_depth_offset', params: [], signature: 'sys_geo_sat2_result_depth_offset', description: 'Byte offset of penetration depth in a GEO sat2 result record.' },
	{ name: 'sys_geo_sat2_result_meta_offset', params: [], signature: 'sys_geo_sat2_result_meta_offset', description: 'Byte offset of metadata in a GEO sat2 result record.' },
	{ name: 'sys_geo_sat2_max_poly_vertices', params: [], signature: 'sys_geo_sat2_max_poly_vertices', description: 'GEO sat2 convex-polygon vertex scratch capacity.' },
	{ name: 'sys_geo_overlap_mode_candidate_pairs', params: [], signature: 'sys_geo_overlap_mode_candidate_pairs', description: 'GEO overlap2d mode for explicit candidate-pair input.' },
	{ name: 'sys_geo_overlap_mode_full_pass', params: [], signature: 'sys_geo_overlap_mode_full_pass', description: 'GEO overlap2d mode for full instance-pair traversal.' },
	{ name: 'sys_geo_overlap_broadphase_none', params: [], signature: 'sys_geo_overlap_broadphase_none', description: 'GEO overlap2d broadphase policy: no device broadphase.' },
	{ name: 'sys_geo_overlap_broadphase_local_bounds_aabb', params: [], signature: 'sys_geo_overlap_broadphase_local_bounds_aabb', description: 'GEO overlap2d broadphase policy: local-bounds AABB.' },
	{ name: 'sys_geo_overlap_contact_clipped_feature', params: [], signature: 'sys_geo_overlap_contact_clipped_feature', description: 'GEO overlap2d contact policy: clipped feature point.' },
	{ name: 'sys_geo_overlap_output_stop_on_overflow', params: [], signature: 'sys_geo_overlap_output_stop_on_overflow', description: 'GEO overlap2d output policy: stop and fault on result overflow.' },
	{ name: 'sys_geo_overlap_max_poly_vertices', params: [], signature: 'sys_geo_overlap_max_poly_vertices', description: 'GEO overlap2d per-piece polygon vertex scratch capacity.' },
	{ name: 'sys_geo_overlap_max_clip_vertices', params: [], signature: 'sys_geo_overlap_max_clip_vertices', description: 'GEO overlap2d clipped-contact vertex scratch capacity.' },
	{ name: 'sys_geo_overlap_instance_bytes', params: [], signature: 'sys_geo_overlap_instance_bytes', description: 'GEO overlap2d instance record size in bytes.' },
	{ name: 'sys_geo_overlap_instance_shape_offset', params: [], signature: 'sys_geo_overlap_instance_shape_offset', description: 'Byte offset of the shape address field in a GEO overlap2d instance record.' },
	{ name: 'sys_geo_overlap_instance_tx_offset', params: [], signature: 'sys_geo_overlap_instance_tx_offset', description: 'Byte offset of the world translation X field in a GEO overlap2d instance record.' },
	{ name: 'sys_geo_overlap_instance_ty_offset', params: [], signature: 'sys_geo_overlap_instance_ty_offset', description: 'Byte offset of the world translation Y field in a GEO overlap2d instance record.' },
	{ name: 'sys_geo_overlap_instance_layer_offset', params: [], signature: 'sys_geo_overlap_instance_layer_offset', description: 'Byte offset of the layer field in a GEO overlap2d instance record.' },
	{ name: 'sys_geo_overlap_instance_mask_offset', params: [], signature: 'sys_geo_overlap_instance_mask_offset', description: 'Byte offset of the mask field in a GEO overlap2d instance record.' },
	{ name: 'sys_geo_overlap_pair_bytes', params: [], signature: 'sys_geo_overlap_pair_bytes', description: 'GEO overlap2d candidate-pair record size in bytes.' },
	{ name: 'sys_geo_overlap_pair_instance_a_offset', params: [], signature: 'sys_geo_overlap_pair_instance_a_offset', description: 'Byte offset of instance A in a GEO overlap2d candidate-pair record.' },
	{ name: 'sys_geo_overlap_pair_instance_b_offset', params: [], signature: 'sys_geo_overlap_pair_instance_b_offset', description: 'Byte offset of instance B in a GEO overlap2d candidate-pair record.' },
	{ name: 'sys_geo_overlap_pair_meta_offset', params: [], signature: 'sys_geo_overlap_pair_meta_offset', description: 'Byte offset of pair metadata in a GEO overlap2d candidate-pair record.' },
	{ name: 'sys_geo_overlap_result_bytes', params: [], signature: 'sys_geo_overlap_result_bytes', description: 'GEO overlap2d result record size in bytes.' },
	{ name: 'sys_geo_overlap_result_nx_offset', params: [], signature: 'sys_geo_overlap_result_nx_offset', description: 'Byte offset of normal X in a GEO overlap2d result record.' },
	{ name: 'sys_geo_overlap_result_ny_offset', params: [], signature: 'sys_geo_overlap_result_ny_offset', description: 'Byte offset of normal Y in a GEO overlap2d result record.' },
	{ name: 'sys_geo_overlap_result_depth_offset', params: [], signature: 'sys_geo_overlap_result_depth_offset', description: 'Byte offset of penetration depth in a GEO overlap2d result record.' },
	{ name: 'sys_geo_overlap_result_px_offset', params: [], signature: 'sys_geo_overlap_result_px_offset', description: 'Byte offset of contact point X in a GEO overlap2d result record.' },
	{ name: 'sys_geo_overlap_result_py_offset', params: [], signature: 'sys_geo_overlap_result_py_offset', description: 'Byte offset of contact point Y in a GEO overlap2d result record.' },
	{ name: 'sys_geo_overlap_result_piece_a_offset', params: [], signature: 'sys_geo_overlap_result_piece_a_offset', description: 'Byte offset of winning piece A in a GEO overlap2d result record.' },
	{ name: 'sys_geo_overlap_result_piece_b_offset', params: [], signature: 'sys_geo_overlap_result_piece_b_offset', description: 'Byte offset of winning piece B in a GEO overlap2d result record.' },
	{ name: 'sys_geo_overlap_result_feature_meta_offset', params: [], signature: 'sys_geo_overlap_result_feature_meta_offset', description: 'Byte offset of feature metadata in a GEO overlap2d result record.' },
	{ name: 'sys_geo_overlap_result_pair_meta_offset', params: [], signature: 'sys_geo_overlap_result_pair_meta_offset', description: 'Byte offset of pair metadata in a GEO overlap2d result record.' },
	{ name: 'sys_geo_overlap_summary_bytes', params: [], signature: 'sys_geo_overlap_summary_bytes', description: 'GEO overlap2d summary record size in bytes.' },
	{ name: 'sys_geo_overlap_summary_result_count_offset', params: [], signature: 'sys_geo_overlap_summary_result_count_offset', description: 'Byte offset of result count in a GEO overlap2d summary record.' },
	{ name: 'sys_geo_overlap_summary_exact_pair_count_offset', params: [], signature: 'sys_geo_overlap_summary_exact_pair_count_offset', description: 'Byte offset of exact-pair count in a GEO overlap2d summary record.' },
	{ name: 'sys_geo_overlap_summary_broadphase_pair_count_offset', params: [], signature: 'sys_geo_overlap_summary_broadphase_pair_count_offset', description: 'Byte offset of broadphase-pair count in a GEO overlap2d summary record.' },
	{ name: 'sys_geo_overlap_summary_flags_offset', params: [], signature: 'sys_geo_overlap_summary_flags_offset', description: 'Byte offset of flags in a GEO overlap2d summary record.' },
	{ name: 'sys_geo_overlap_summary_flag_overflow', params: [], signature: 'sys_geo_overlap_summary_flag_overflow', description: 'Flag bit set when a GEO overlap2d pass overflowed result capacity.' },
	{ name: 'sys_geo_overlap_shape_desc_bytes', params: [], signature: 'sys_geo_overlap_shape_desc_bytes', description: 'GEO overlap2d shape descriptor size in bytes.' },
	{ name: 'sys_geo_overlap_shape_kind_offset', params: [], signature: 'sys_geo_overlap_shape_kind_offset', description: 'Byte offset of primitive kind in a GEO overlap2d shape descriptor.' },
	{ name: 'sys_geo_overlap_shape_kind_compound', params: [], signature: 'sys_geo_overlap_shape_kind_compound', description: 'GEO overlap2d shape kind for compound descriptors.' },
	{ name: 'sys_geo_overlap_shape_data_count_offset', params: [], signature: 'sys_geo_overlap_shape_data_count_offset', description: 'Byte offset of data count in a GEO overlap2d shape descriptor.' },
	{ name: 'sys_geo_overlap_shape_data_offset_offset', params: [], signature: 'sys_geo_overlap_shape_data_offset_offset', description: 'Byte offset of data offset in a GEO overlap2d shape descriptor.' },
	{ name: 'sys_geo_overlap_shape_bounds_offset_offset', params: [], signature: 'sys_geo_overlap_shape_bounds_offset_offset', description: 'Byte offset of bounds offset in a GEO overlap2d shape descriptor.' },
	{ name: 'sys_geo_overlap_shape_bounds_bytes', params: [], signature: 'sys_geo_overlap_shape_bounds_bytes', description: 'GEO overlap2d shape bounds payload size in bytes.' },
	{ name: 'sys_geo_overlap_shape_bounds_left_offset', params: [], signature: 'sys_geo_overlap_shape_bounds_left_offset', description: 'Byte offset of left in a GEO overlap2d shape bounds payload.' },
	{ name: 'sys_geo_overlap_shape_bounds_top_offset', params: [], signature: 'sys_geo_overlap_shape_bounds_top_offset', description: 'Byte offset of top in a GEO overlap2d shape bounds payload.' },
	{ name: 'sys_geo_overlap_shape_bounds_right_offset', params: [], signature: 'sys_geo_overlap_shape_bounds_right_offset', description: 'Byte offset of right in a GEO overlap2d shape bounds payload.' },
	{ name: 'sys_geo_overlap_shape_bounds_bottom_offset', params: [], signature: 'sys_geo_overlap_shape_bounds_bottom_offset', description: 'Byte offset of bottom in a GEO overlap2d shape bounds payload.' },
	{ name: 'sys_geo_overlap_aabb_data_count', params: [], signature: 'sys_geo_overlap_aabb_data_count', description: 'Data-count value for a GEO overlap2d AABB descriptor.' },
	{ name: 'sys_geo_overlap_aabb_shape_bytes', params: [], signature: 'sys_geo_overlap_aabb_shape_bytes', description: 'GEO overlap2d BIOS AABB shape footprint in bytes.' },
	{ name: 'sys_geo_overlap_pair_meta_instance_a_shift', params: [], signature: 'sys_geo_overlap_pair_meta_instance_a_shift', description: 'Bit shift for instance A in GEO overlap2d result pair metadata.' },
	{ name: 'sys_geo_overlap_pair_meta_instance_a_mask', params: [], signature: 'sys_geo_overlap_pair_meta_instance_a_mask', description: 'Mask for instance A in GEO overlap2d result pair metadata after shifting.' },
	{ name: 'sys_geo_overlap_pair_meta_instance_b_mask', params: [], signature: 'sys_geo_overlap_pair_meta_instance_b_mask', description: 'Mask for instance B in GEO overlap2d result pair metadata.' },
	{ name: 'sys_geo_sat_meta_axis_mask', params: [], signature: 'sys_geo_sat_meta_axis_mask', description: 'Mask for the SAT axis index bits in the GEO result meta word.' },
	{ name: 'sys_geo_sat_meta_shape_shift', params: [], signature: 'sys_geo_sat_meta_shape_shift', description: 'Bit shift for the SAT shape selector bits in the GEO result meta word.' },
	{ name: 'sys_geo_sat_meta_shape_src', params: [], signature: 'sys_geo_sat_meta_shape_src', description: 'SAT meta value meaning the winning axis came from shape A.' },
	{ name: 'sys_geo_sat_meta_shape_aux', params: [], signature: 'sys_geo_sat_meta_shape_aux', description: 'SAT meta value meaning the winning axis came from shape B.' },
	{ name: 'sys_geo_fault_aborted_by_host', params: [], signature: 'sys_geo_fault_aborted_by_host', description: 'GEO fault code: active job aborted by host.' },
	{ name: 'sys_geo_fault_bad_record_alignment', params: [], signature: 'sys_geo_fault_bad_record_alignment', description: 'GEO fault code: record or offset alignment was invalid.' },
	{ name: 'sys_geo_fault_bad_vertex_count', params: [], signature: 'sys_geo_fault_bad_vertex_count', description: 'GEO fault code: vertex count was invalid for the record.' },
	{ name: 'sys_geo_fault_src_range', params: [], signature: 'sys_geo_fault_src_range', description: 'GEO fault code: source read range was invalid.' },
	{ name: 'sys_geo_fault_dst_range', params: [], signature: 'sys_geo_fault_dst_range', description: 'GEO fault code: destination write range was invalid.' },
	{ name: 'sys_geo_fault_descriptor_kind', params: [], signature: 'sys_geo_fault_descriptor_kind', description: 'GEO fault code: descriptor kind or reserved bits were invalid.' },
	{ name: 'sys_geo_fault_numeric_overflow_internal', params: [], signature: 'sys_geo_fault_numeric_overflow_internal', description: 'GEO fault code: internal numeric overflow or NaN occurred.' },
	{ name: 'sys_geo_fault_bad_record_flags', params: [], signature: 'sys_geo_fault_bad_record_flags', description: 'GEO fault code: record flags were non-zero or unsupported.' },
	{ name: 'sys_geo_fault_result_capacity', params: [], signature: 'sys_geo_fault_result_capacity', description: 'GEO fault code: result table capacity was exhausted.' },
	{ name: 'sys_geo_fault_code_shift', params: [], signature: 'sys_geo_fault_code_shift', description: 'Bit shift for the fault code field in the GEO fault word.' },
	{ name: 'sys_geo_fault_code_mask', params: [], signature: 'sys_geo_fault_code_mask', description: 'Mask for the fault code field before packing or after shifting.' },
	{ name: 'sys_geo_fault_record_index_mask', params: [], signature: 'sys_geo_fault_record_index_mask', description: 'Mask for the record index field in the GEO fault word.' },
	{ name: 'sys_geo_fault_record_index_none', params: [], signature: 'sys_geo_fault_record_index_none', description: 'GEO fault record-index sentinel used for submit-time rejects.' },
	{ name: 'sys_geo_fault_reject_busy', params: [], signature: 'sys_geo_fault_reject_busy', description: 'GEO reject fault: host started a job while GEO was busy.' },
	{ name: 'sys_geo_fault_reject_bad_cmd', params: [], signature: 'sys_geo_fault_reject_bad_cmd', description: 'GEO reject fault: command was unsupported.' },
	{ name: 'sys_geo_fault_reject_bad_stride', params: [], signature: 'sys_geo_fault_reject_bad_stride', description: 'GEO reject fault: register stride values were invalid.' },
	{ name: 'sys_geo_fault_reject_dst_not_ram', params: [], signature: 'sys_geo_fault_reject_dst_not_ram', description: 'GEO reject fault: destination register pointed outside RAM.' },
	{ name: 'sys_geo_fault_reject_misaligned_regs', params: [], signature: 'sys_geo_fault_reject_misaligned_regs', description: 'GEO reject fault: register pointers were not word-aligned.' },
	{ name: 'sys_geo_fault_reject_bad_register_combo', params: [], signature: 'sys_geo_fault_reject_bad_register_combo', description: 'GEO reject fault: register combination was invalid for the command.' },
	{ name: 'img_ctrl_start', params: [], signature: 'img_ctrl_start', description: 'IMGDEC control bit: start decode.' },
	{ name: 'img_status_busy', params: [], signature: 'img_status_busy', description: 'IMGDEC status bit: busy.' },
	{ name: 'img_status_done', params: [], signature: 'img_status_done', description: 'IMGDEC status bit: done.' },
	{ name: 'img_status_error', params: [], signature: 'img_status_error', description: 'IMGDEC status bit: error.' },
	{ name: 'img_status_clipped', params: [], signature: 'img_status_clipped', description: 'IMGDEC status bit: clipped.' },
	{ name: 'img_status_rejected', params: [], signature: 'img_status_rejected', description: 'IMGDEC status bit: start request was rejected.' },
	{ name: 'inp_ctrl_commit', params: [], signature: 'inp_ctrl_commit', description: 'Input Controller command: commit sys_inp_action plus sys_inp_bind into the chip context.' },
	{ name: 'inp_ctrl_arm', params: [], signature: 'inp_ctrl_arm', description: 'Input Controller command: arm the next VBLANK input sample.' },
	{ name: 'inp_ctrl_reset', params: [], signature: 'inp_ctrl_reset', description: 'Input Controller command: pop the chip context for the current player and clear its actions.' },
];

const DEFAULT_LUA_BUILTIN_IDENTIFIER_EXTRAS = [
	'package',
	'math.pi',
];

export const DEFAULT_LUA_BUILTIN_NAMES: ReadonlyArray<string> = (() => {
	const names = new Set<string>();
	for (let index = 0; index < DEFAULT_LUA_BUILTIN_FUNCTIONS.length; index += 1) {
		const name = DEFAULT_LUA_BUILTIN_FUNCTIONS[index].name;
		names.add(name);
		const dot = name.indexOf('.');
		if (dot !== -1) {
			names.add(name.slice(0, dot));
		}
	}
	for (let index = 0; index < DEFAULT_LUA_BUILTIN_IDENTIFIER_EXTRAS.length; index += 1) {
		names.add(DEFAULT_LUA_BUILTIN_IDENTIFIER_EXTRAS[index]);
	}
	return Array.from(names);
})();
