export enum BitmapId {
	none = 'none',
	letter_0 = 'letter_0',
	letter_1 = 'letter_1',
	letter_2 = 'letter_2',
	letter_3 = 'letter_3',
	letter_4 = 'letter_4',
	letter_5 = 'letter_5',
	letter_6 = 'letter_6',
	letter_7 = 'letter_7',
	letter_8 = 'letter_8',
	letter_9 = 'letter_9',
	letter_a = 'letter_a',
	letter_apostroph = 'letter_apostroph',
	letter_b = 'letter_b',
	letter_c = 'letter_c',
	letter_colon = 'letter_colon',
	letter_comma = 'letter_comma',
	letter_continue = 'letter_continue',
	letter_d = 'letter_d',
	letter_dot = 'letter_dot',
	letter_e = 'letter_e',
	letter_exclamation = 'letter_exclamation',
	letter_f = 'letter_f',
	letter_g = 'letter_g',
	letter_h = 'letter_h',
	letter_i = 'letter_i',
	letter_ij = 'letter_ij',
	letter_j = 'letter_j',
	letter_k = 'letter_k',
	letter_l = 'letter_l',
	letter_line = 'letter_line',
	letter_m = 'letter_m',
	letter_n = 'letter_n',
	letter_o = 'letter_o',
	letter_p = 'letter_p',
	letter_percent = 'letter_percent',
	letter_q = 'letter_q',
	letter_question = 'letter_question',
	letter_r = 'letter_r',
	letter_s = 'letter_s',
	letter_slash = 'letter_slash',
	letter_space = 'letter_space',
	letter_speakend = 'letter_speakend',
	letter_speakstart = 'letter_speakstart',
	letter_streep = 'letter_streep',
	letter_t = 'letter_t',
	letter_u = 'letter_u',
	letter_v = 'letter_v',
	letter_w = 'letter_w',
	letter_x = 'letter_x',
	letter_y = 'letter_y',
	letter_z = 'letter_z',
	b2 = 'b2',
	b = 'b',
	skybox = 'skybox',
	joystick1 = 'joystick1',
	joystick2 = 'joystick2',
	joystick3 = 'joystick3',
	joystick4 = 'joystick4',
	joystick_none = 'joystick_none',
	whitepixel = 'whitepixel',
	_atlas = '_atlas',
}

export enum AudioId {
	none = 'none',
}

export enum DataId {
	none = 'none',
}

export enum ModelId {
	none = 'none',
	animatedmorphsphere = 'animatedmorphsphere',
	cube = 'cube',
	building = 'building',
}

export enum FsmId {
	none = 'none',
}
