import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const generatorPath = 'scripts/runtime/generate_cpu_executor_specializations.mjs';
const templatePath = resolve(
	process.cwd(),
	'machine/ts/machine/runtime/cpu_executor.ts.in',
);
const outputPath = resolve(
	process.cwd(),
	'machine/ts/machine/runtime/cpu_executor.ts',
);

const beginMarker = '\t/* CPU_EXECUTION_MODE_TEMPLATE_BEGIN */\n';
const endMarker = '\n\t/* CPU_EXECUTION_MODE_TEMPLATE_END */';
const template = readFileSync(templatePath, 'utf8');
const [sharedPrefix, modeAndSuffix] = template.split(beginMarker);
const [modeTemplate, sharedSuffix] = modeAndSuffix.split(endMarker);

function renderMode(suffix, cpuRunMethod) {
	return modeTemplate
		.replaceAll('__MODE_SUFFIX__', suffix)
		.replaceAll('__CPU_RUN_METHOD__', cpuRunMethod);
}

const source = `// Generated by ${generatorPath}. Do not edit.
// disable normalized_ast_duplicate_pattern repeated_statement_sequence_pattern repeated_expression_pattern -- generated normal and instrumented scheduler specializations are guarded by the generator check.
${sharedPrefix.trimStart()}${renderMode('Normal', 'runUntilDepth')}\n\n${renderMode('Instrumented', 'runUntilDepthInstrumented')}${sharedSuffix}`;

if (process.argv.includes('--check')) {
	if (readFileSync(outputPath, 'utf8') !== source) {
		console.error(`${outputPath} is stale`);
		process.exitCode = 1;
	}
} else {
	writeFileSync(outputPath, source);
}
