#pragma once

#include "common/primitives.h"

namespace bmsx {

constexpr u32 GX_GPU_GP0_DRAW_MODE = 0xe1u;
constexpr u32 GX_GPU_GP0_TEXTURE_WINDOW = 0xe2u;
constexpr u32 GX_GPU_GP0_DRAWING_AREA_TOP_LEFT = 0xe3u;
constexpr u32 GX_GPU_GP0_DRAWING_AREA_BOTTOM_RIGHT = 0xe4u;
constexpr u32 GX_GPU_GP0_DRAWING_OFFSET = 0xe5u;
constexpr u32 GX_GPU_GP0_MASK_BIT = 0xe6u;
constexpr u32 GX_GPU_GP0_IRQ_REQUEST = 0x1fu;
constexpr u32 GX_GPU_GP0_OPCODE_SHIFT = 24u;
constexpr u32 GX_GPU_GP0_PARAM_MASK = 0x00ffffffu;
constexpr u32 GX_GPU_GP0_FILL_RECTANGLE = 0x02u;
constexpr u32 GX_GPU_GP0_POLYGON_FIRST = 0x20u;
constexpr u32 GX_GPU_GP0_POLYGON_LAST = 0x3fu;
constexpr u32 GX_GPU_GP0_LINE_FIRST = 0x40u;
constexpr u32 GX_GPU_GP0_LINE_LAST = 0x5fu;
constexpr u32 GX_GPU_GP0_RECTANGLE_FIRST = 0x60u;
constexpr u32 GX_GPU_GP0_RECTANGLE_LAST = 0x7fu;
constexpr u32 GX_GPU_GP0_VRAM_TO_VRAM_FIRST = 0x80u;
constexpr u32 GX_GPU_GP0_VRAM_TO_VRAM_LAST = 0x9fu;
constexpr u32 GX_GPU_GP0_CPU_TO_VRAM_FIRST = 0xa0u;
constexpr u32 GX_GPU_GP0_CPU_TO_VRAM_LAST = 0xbfu;
constexpr u32 GX_GPU_GP0_VRAM_TO_CPU_FIRST = 0xc0u;
constexpr u32 GX_GPU_GP0_VRAM_TO_CPU_LAST = 0xdfu;
constexpr u32 GX_GPU_GP0_RENDER_TEXTURE_BIT = 0x04u;
constexpr u32 GX_GPU_GP0_RENDER_QUAD_OR_POLYLINE_BIT = 0x08u;
constexpr u32 GX_GPU_GP0_RENDER_GOURAUD_BIT = 0x10u;
constexpr u32 GX_GPU_GP0_RECTANGLE_SIZE_MASK = 0x18u;
constexpr u32 GX_GPU_GP0_COMMAND_BUFFER_WORDS = 16u;
constexpr size_t GX_GPU_COMMAND_FIFO_WORD_CAPACITY = 16u;
constexpr size_t GX_GPU_DMA_INGRESS_WORD_CAPACITY = 16u;
constexpr u32 GX_GPU_CLUT_4BIT_WORDS = 16u;
constexpr u32 GX_GPU_CLUT_8BIT_WORDS = 256u;
constexpr u32 GX_GPU_CLUT_4BIT_SIZE_WORD = GX_GPU_CLUT_4BIT_WORDS | (1u << 16u);

constexpr u32 GX_GPU_GP0_INGRESS_COMMAND = 0u;
constexpr u32 GX_GPU_GP0_INGRESS_FIXED = 1u;
constexpr u32 GX_GPU_GP0_INGRESS_IMAGE_HEADER = 2u;
constexpr u32 GX_GPU_GP0_INGRESS_IMAGE_PAYLOAD = 3u;
constexpr u32 GX_GPU_GP0_INGRESS_POLYLINE_HEADER = 4u;
constexpr u32 GX_GPU_GP0_INGRESS_POLYLINE_PAYLOAD = 5u;

constexpr u32 GX_GPU_DMA_DIRECTION_OFF = 0u;
constexpr u32 GX_GPU_DMA_DIRECTION_FIFO = 1u;
constexpr u32 GX_GPU_DMA_DIRECTION_CPU_TO_GP0 = 2u;
constexpr u32 GX_GPU_DMA_DIRECTION_GPUREAD_TO_CPU = 3u;

} // namespace bmsx
