import { registerLuaSourceRecord, type LuaSourceRecord, type LuaSourceRegistry } from '../runtime/source_registry';
import type { HostClock } from '../../hosts/common/clock';
import type { KeyValueStorage } from './key_value_storage';
import { toLuaModulePath } from '../../toolchain/ts/lua/module_path';
import { ROM_GENERATED_MODULE_PATHS } from '../../toolchain/ts/rompack/generated_modules';
import {
	CARTRIDGE_RESOURCE_DOMAINS,
	type LuaResourceCreationRequest,
	type ResourceIdentity,
	type RuntimeResource,
} from '../common/resource';
import {
	applyWorkspaceSourceOverrides,
	persistWorkspaceSourceFile,
} from './files';
import {
	deleteWorkspaceLuaSourceOverride,
	setWorkspaceLuaSourceOverride,
	workspaceCanonicalSourceCache,
} from './cache';
import type { WorkspaceRecord } from './records';
import { resolveWorkspacePath } from './path';
import { runtimeSemanticCache } from '../editor/contrib/intellisense/semantic/workspace/runtime';
import {
	developmentCartridgeSource,
	resolveRuntimeLuaSource,
	registerRuntimeLuaResource,
	runtimeLuaSourceDomain,
	type RuntimeSourceState,
} from '../runtime/sources';

export * from './files';
export { joinWorkspacePaths } from './path';

function resolveEditableCartLuaSources(sources: RuntimeSourceState): LuaSourceRegistry {
	const cartridge = developmentCartridgeSource(sources);
	return cartridge ? cartridge.luaSources : sources.activeLuaSources;
}

function markLuaSourceRegistryChanged(sources: RuntimeSourceState, registry: LuaSourceRegistry): void {
	if (registry === sources.systemLuaSources) {
		sources.systemBlua32MediaDirty = true;
	} else {
		for (const slot of CARTRIDGE_RESOURCE_DOMAINS) {
			if (sources.cartridgeSlots[slot]?.luaSources === registry) {
				sources.cartridgeBlua32MediaDirty[slot] = true;
				runtimeSemanticCache.delete(slot);
				return;
			}
		}
		throw new Error('Lua source registry is not installed.');
	}
	runtimeSemanticCache.clear();
}

function resolveEditableLuaSource(
	sources: RuntimeSourceState,
	identity: ResourceIdentity,
): { registry: LuaSourceRegistry; asset: LuaSourceRecord } {
	const source = resolveRuntimeLuaSource(sources, identity);
	if (!source) {
		throw new Error(`Missing Lua source registry for '${identity.path}'.`);
	}
	return { registry: source.registry, asset: source.record };
}

export function applyLuaCodeTabSources(
	sources: RuntimeSourceState,
	snapshots: ReadonlyArray<ResourceIdentity & { source: string }>,
): void {
	for (let index = 0; index < snapshots.length; index += 1) {
		const snapshot = snapshots[index];
		const target = resolveEditableLuaSource(sources, snapshot);
		setWorkspaceLuaSourceOverride(target.registry, target.asset.source_path, snapshot.source);
		markLuaSourceRegistryChanged(sources, target.registry);
	}
}

export async function saveLuaResourceSource(
	storage: KeyValueStorage,
	clock: HostClock,
	sources: RuntimeSourceState,
	identity: ResourceIdentity,
	source: string,
): Promise<void> {
	const target = resolveEditableLuaSource(sources, identity);
	const registry = target.registry;
	const asset = target.asset;
	if (asset.generated) {
		throw new Error(`Generated Lua source '${identity.path}' is read-only.`);
	}
	const sourcePath = asset.source_path;
	const record = await persistWorkspaceSourceFile(
		storage,
		clock,
		sourcePath,
		source,
		registry.projectRootPath,
	);
	asset.src = source;
	asset.base_src = source;
	asset.base_update_timestamp = record.updatedAt;
	asset.update_timestamp = record.updatedAt;
	registerLuaSourceRecord(registry, asset);
	markLuaSourceRegistryChanged(sources, registry);
	workspaceCanonicalSourceCache.set(resolveWorkspacePath(sourcePath, registry.projectRootPath), source);
	deleteWorkspaceLuaSourceOverride(registry, sourcePath);
}

export async function createLuaResource(
	storage: KeyValueStorage,
	clock: HostClock,
	sources: RuntimeSourceState,
	request: LuaResourceCreationRequest,
): Promise<RuntimeResource> {
	const contents = request.contents;
	const path = request.path;
	const slashIndex = path.lastIndexOf('/');
	const fileName = slashIndex === -1 ? path : path.slice(slashIndex + 1);
	const baseName = fileName.endsWith('.lua') ? fileName.slice(0, -4) : fileName;
	const modulePath = toLuaModulePath(path);
	if (ROM_GENERATED_MODULE_PATHS.includes(modulePath)) {
		throw new Error(`Lua module '${modulePath}' is generated by the ROM packer.`);
	}
	const systemSource = path.startsWith('bios/') || path.startsWith('system/');
	const registry = systemSource
		? sources.systemLuaSources
		: resolveEditableCartLuaSources(sources);
	const record = await persistWorkspaceSourceFile(
		storage,
		clock,
		path,
		contents,
		registry.projectRootPath,
	);
	const asset: LuaSourceRecord = {
		resid: baseName,
		type: 'lua',
		src: contents,
		base_src: contents,
		base_update_timestamp: record.updatedAt,
		source_path: path,
		module_path: modulePath,
		update_timestamp: record.updatedAt,
		generated: false,
	};
	const domain = runtimeLuaSourceDomain(sources, registry);
	registerLuaSourceRecord(registry, asset);
	const resource = registerRuntimeLuaResource(sources, domain, asset);
	registry.can_boot_from_source = true;
	markLuaSourceRegistryChanged(sources, registry);
	return resource;
}

export async function applyWorkspaceOverridesToRegistry(
	storage: KeyValueStorage,
	sources: RuntimeSourceState,
	params: {
		dirtyRecords: ReadonlyMap<string, WorkspaceRecord>;
		registry: LuaSourceRegistry;
		projectRootPath: string;
	},
): Promise<Set<string>> {
	const revision = params.registry.revision;
	const rejectedDirtyPaths = await applyWorkspaceSourceOverrides({
		dirtyRecords: params.dirtyRecords,
		domain: runtimeLuaSourceDomain(sources, params.registry),
		registry: params.registry,
		storage,
		projectRootPath: params.projectRootPath,
	});
	if (params.registry.revision !== revision) {
		markLuaSourceRegistryChanged(sources, params.registry);
	}
	return rejectedDirtyPaths;
}

export async function applyAllWorkspaceSourceOverrides(
	storage: KeyValueStorage,
	sources: RuntimeSourceState,
	dirtyRecords: ReadonlyMap<string, WorkspaceRecord>,
): Promise<Set<string>> {
	const rejectedDirtyPaths = new Set<string>();
	for (let slot = 0; slot < sources.cartridgeSlots.length; slot += 1) {
		const cartridge = sources.cartridgeSlots[slot];
		if (!cartridge || !cartridge.projectRootPath) {
			continue;
		}
		const rejected = await applyWorkspaceOverridesToRegistry(storage, sources, {
			dirtyRecords,
			registry: cartridge.luaSources,
			projectRootPath: cartridge.projectRootPath,
		});
		for (const path of rejected) {
			rejectedDirtyPaths.add(path);
		}
	}
	const rejectedSystemPaths = await applyWorkspaceOverridesToRegistry(storage, sources, {
		dirtyRecords,
		registry: sources.systemLuaSources,
		projectRootPath: sources.systemProjectRootPath,
	});
	for (const path of rejectedSystemPaths) {
		rejectedDirtyPaths.add(path);
	}
	return rejectedDirtyPaths;
}
