import {
	CLOSURE_ADDRESS_REGISTER_WIDE_C,
	EXT_A_BITS,
	EXT_B_BITS,
	EXT_BX_BITS,
	EXT_C_BITS,
	INSTRUCTION_BYTES,
	MAX_BX_BITS,
	MAX_EXT_REGISTER_A,
	MAX_EXT_REGISTER_BC,
	MAX_OP_BITS,
	MAX_OPERAND_BITS,
	MAX_SIGNED_BX,
	MIN_SIGNED_BX,
} from '../../../machine/ts/spec/blua32/instruction_format';
import {
	BLUA32_FUNCTION_ALIGNMENT,
	BLUA32_FUNCTION_CODE_ADDRESS_OFFSET,
	BLUA32_FUNCTION_CODE_BYTE_COUNT_OFFSET,
	BLUA32_FUNCTION_FLAGS_OFFSET,
	BLUA32_FUNCTION_MAX_STACK_OFFSET,
	BLUA32_FUNCTION_NUM_PARAMS_OFFSET,
	BLUA32_FUNCTION_RECORD_SIZE,
	BLUA32_FUNCTION_RESERVED_OFFSET,
	BLUA32_FUNCTION_UPVALUE_COUNT_OFFSET,
	BLUA32_FUNCTION_UPVALUE_TABLE_ADDRESS_OFFSET,
	BLUA32_UPVALUE_IN_STACK_MASK,
	BLUA32_UPVALUE_RECORD_SIZE,
} from '../../../machine/ts/spec/blua32/image_format';
import { OpCode } from '../../../machine/ts/spec/blua32/opcode';

export const BLUA32_FIRMWARE_MODULE_SOURCE = [
	'module<const>',
	'',
	'return {',
	`\tinstruction_bytes = ${INSTRUCTION_BYTES},`,
	`\tmax_op_bits = ${MAX_OP_BITS},`,
	`\tmax_operand_bits = ${MAX_OPERAND_BITS},`,
	`\tmax_bx_bits = ${MAX_BX_BITS},`,
	`\tmax_ext_register_a = ${MAX_EXT_REGISTER_A},`,
	`\tmax_ext_register_bc = ${MAX_EXT_REGISTER_BC},`,
	`\tmin_signed_bx = ${MIN_SIGNED_BX},`,
	`\tmax_signed_bx = ${MAX_SIGNED_BX},`,
	`\text_a_bits = ${EXT_A_BITS},`,
	`\text_b_bits = ${EXT_B_BITS},`,
	`\text_bx_bits = ${EXT_BX_BITS},`,
	`\text_c_bits = ${EXT_C_BITS},`,
	`\tclosure_address_register_wide_c = ${CLOSURE_ADDRESS_REGISTER_WIDE_C},`,
	`\tfunction_alignment = ${BLUA32_FUNCTION_ALIGNMENT},`,
	`\tfunction_record_size = ${BLUA32_FUNCTION_RECORD_SIZE},`,
	`\tfunction_code_address_offset = ${BLUA32_FUNCTION_CODE_ADDRESS_OFFSET},`,
	`\tfunction_code_byte_count_offset = ${BLUA32_FUNCTION_CODE_BYTE_COUNT_OFFSET},`,
	`\tfunction_num_params_offset = ${BLUA32_FUNCTION_NUM_PARAMS_OFFSET},`,
	`\tfunction_max_stack_offset = ${BLUA32_FUNCTION_MAX_STACK_OFFSET},`,
	`\tfunction_flags_offset = ${BLUA32_FUNCTION_FLAGS_OFFSET},`,
	`\tfunction_upvalue_table_address_offset = ${BLUA32_FUNCTION_UPVALUE_TABLE_ADDRESS_OFFSET},`,
	`\tfunction_upvalue_count_offset = ${BLUA32_FUNCTION_UPVALUE_COUNT_OFFSET},`,
	`\tfunction_reserved_offset = ${BLUA32_FUNCTION_RESERVED_OFFSET},`,
	`\tupvalue_record_size = ${BLUA32_UPVALUE_RECORD_SIZE},`,
	`\tupvalue_in_stack_mask = ${BLUA32_UPVALUE_IN_STACK_MASK},`,
	`\top_wide = ${OpCode.WIDE},`,
	`\top_mov = ${OpCode.MOV},`,
	`\top_knil = ${OpCode.KNIL},`,
	`\top_kfalse = ${OpCode.KFALSE},`,
	`\top_ktrue = ${OpCode.KTRUE},`,
	`\top_k0 = ${OpCode.K0},`,
	`\top_k1 = ${OpCode.K1},`,
	`\top_km1 = ${OpCode.KM1},`,
	`\top_ksmi = ${OpCode.KSMI},`,
	`\top_gett = ${OpCode.GETT},`,
	`\top_sett = ${OpCode.SETT},`,
	`\top_closure = ${OpCode.CLOSURE},`,
	`\top_getup = ${OpCode.GETUP},`,
	`\top_ret = ${OpCode.RET},`,
	`\top_geti = ${OpCode.GETI},`,
	`\top_seti = ${OpCode.SETI},`,
	'}',
	'',
].join('\n');
