export const ROM_ASSET_SYMBOL_MODULE_PATH = 'bmsx/assets';
export const ROM_ASSET_SYMBOL_SOURCE_PATH = `${ROM_ASSET_SYMBOL_MODULE_PATH}.lua`;
export const SYSTEM_ASSET_SYMBOL_MODULE_PATH = 'bmsx/system_assets';
export const SYSTEM_ASSET_SYMBOL_SOURCE_PATH = `${SYSTEM_ASSET_SYMBOL_MODULE_PATH}.lua`;
export const GX_VRAM_LAYOUT_MODULE_PATH = 'bmsx/gx_vram_layout';
export const GX_VRAM_LAYOUT_SOURCE_PATH = `${GX_VRAM_LAYOUT_MODULE_PATH}.lua`;
export const ROM_GENERATED_MODULE_PATHS: ReadonlyArray<string> = [
	ROM_ASSET_SYMBOL_MODULE_PATH,
	SYSTEM_ASSET_SYMBOL_MODULE_PATH,
	GX_VRAM_LAYOUT_MODULE_PATH,
];
