export const ROM_ASSET_SYMBOL_MODULE_PATH = 'bmsx/assets';
export const ROM_ASSET_SYMBOL_SOURCE_PATH = `${ROM_ASSET_SYMBOL_MODULE_PATH}.lua`;
export const SYSTEM_ASSET_SYMBOL_MODULE_PATH = 'bmsx/system_assets';
export const SYSTEM_ASSET_SYMBOL_SOURCE_PATH = `${SYSTEM_ASSET_SYMBOL_MODULE_PATH}.lua`;
export const TEXTURE_BINDINGS_MODULE_PATH = 'bmsx/texture_bindings';
export const TEXTURE_BINDINGS_SOURCE_PATH = `${TEXTURE_BINDINGS_MODULE_PATH}.lua`;
export const RENDERER_CONFIG_MODULE_PATH = 'bmsx/renderer_config';
export const RENDERER_CONFIG_SOURCE_PATH = `${RENDERER_CONFIG_MODULE_PATH}.lua`;
export const ROM_GENERATED_MODULE_PATHS: ReadonlyArray<string> = [
	ROM_ASSET_SYMBOL_MODULE_PATH,
	SYSTEM_ASSET_SYMBOL_MODULE_PATH,
	TEXTURE_BINDINGS_MODULE_PATH,
	RENDERER_CONFIG_MODULE_PATH,
];
