export const ROM_ASSET_SYMBOL_MODULE_PATH = 'bmsx/assets';
export const ROM_ASSET_SYMBOL_SOURCE_PATH = `${ROM_ASSET_SYMBOL_MODULE_PATH}.lua`;
export const SYSTEM_ASSET_SYMBOL_MODULE_PATH = 'bmsx/system_assets';
export const SYSTEM_ASSET_SYMBOL_SOURCE_PATH = `${SYSTEM_ASSET_SYMBOL_MODULE_PATH}.lua`;
export const BLUA32_FIRMWARE_MODULE_PATH = 'bmsx/blua32';
export const BLUA32_FIRMWARE_SOURCE_PATH = `${BLUA32_FIRMWARE_MODULE_PATH}.lua`;
export const TEXTURE_BINDINGS_MODULE_PATH = 'bmsx/texture_bindings';
export const TEXTURE_BINDINGS_SOURCE_PATH = `${TEXTURE_BINDINGS_MODULE_PATH}.lua`;
export const PRESENTATION_CONFIG_MODULE_PATH = 'bmsx/presentation_config';
export const PRESENTATION_CONFIG_SOURCE_PATH = `${PRESENTATION_CONFIG_MODULE_PATH}.lua`;
export const ROM_GENERATED_MODULE_PATHS: ReadonlyArray<string> = [
	ROM_ASSET_SYMBOL_MODULE_PATH,
	SYSTEM_ASSET_SYMBOL_MODULE_PATH,
	BLUA32_FIRMWARE_MODULE_PATH,
	TEXTURE_BINDINGS_MODULE_PATH,
	PRESENTATION_CONFIG_MODULE_PATH,
];
