import {
	GX_GPU_DISPLAY_DISPFB_GX16_1024_LAYOUT_WORD,
	GX_GPU_DISPLAY_HORIZONTAL_RANGE_WORD,
	GX_GPU_DISPLAY_PMODE_CIRCUIT1_OPAQUE_WORD,
	GX_GPU_DISPLAY_PRESET_256X192_PAL_WORDS,
	GX_GPU_DISPLAY_PRESET_256X212_PAL_WORDS,
	GX_GPU_DISPLAY_PRESET_256X240_PAL_WORDS,
	GX_GPU_DISPLAY_PRESET_320X240_PAL_WORDS,
	GX_GPU_DISPLAY_PRESET_368X240_PAL_WORDS,
	GX_GPU_DISPLAY_PRESET_512X240_PAL_WORDS,
	GX_GPU_DISPLAY_PRESET_640X240_PAL_WORDS,
	GX_GPU_DISPLAY_PRESET_640X448I_NTSC_WORDS,
	GX_GPU_DISPLAY_PRESET_640X480I_NTSC_WORDS,
	GX_GPU_DISPLAY_PRESET_640X512I_PAL_WORDS,
	GX_GPU_DISPLAY_PRESET_HEIGHT_WORD,
	GX_GPU_DISPLAY_PRESET_MODE_WORD,
	GX_GPU_DISPLAY_PRESET_PCRTC_DISPLAY_HIGH_WORD,
	GX_GPU_DISPLAY_PRESET_PCRTC_DISPLAY_LOW_WORD,
	GX_GPU_DISPLAY_PRESET_PCRTC_SMODE2_LOW_WORD,
	GX_GPU_DISPLAY_PRESET_PCRTC_SYNCV_LOW_WORD,
	GX_GPU_DISPLAY_PRESET_VERTICAL_RANGE_WORD,
	GX_GPU_DISPLAY_PRESET_WIDTH_WORD,
	GX_GPU_DISPLAY_TIMING_NTSC_WORDS,
	GX_GPU_DISPLAY_TIMING_PAL_WORDS,
	GX_GPU_DISPLAY_TIMING_SMODE1_HIGH_WORD,
	GX_GPU_DISPLAY_TIMING_SMODE1_RUN_LOW_WORD,
	GX_GPU_DISPLAY_TIMING_SMODE1_SETUP_LOW_WORD,
	GX_GPU_DISPLAY_TIMING_SYNCH1_HIGH_WORD,
	GX_GPU_DISPLAY_TIMING_SYNCH1_LOW_WORD,
	GX_GPU_DISPLAY_TIMING_SYNCH2_HIGH_WORD,
	GX_GPU_DISPLAY_TIMING_SYNCH2_LOW_WORD,
	GX_GPU_DISPLAY_TIMING_SYNCV_HIGH_WORD,
} from '../../../machine/ts/spec/gx/display_presets';
import {
	GX_GPU_GP1_DISPLAY_MODE,
	GX_GPU_GP1_HORIZONTAL_DISPLAY_RANGE,
	GX_GPU_GP1_VERTICAL_DISPLAY_RANGE,
	gxGpuGp1CommandWord,
} from '../../../machine/ts/spec/gx/gp1';
import { gxGpuPair16 } from '../../../machine/ts/spec/gx/gp0';

type GxDisplayPresetWords = readonly [number, number, number, number, number, number, number, number];

const GX_DISPLAY_PRESET_MODULE_MODES: ReadonlyArray<readonly [string, GxDisplayPresetWords]> = [
	['256x192', GX_GPU_DISPLAY_PRESET_256X192_PAL_WORDS],
	['256x212', GX_GPU_DISPLAY_PRESET_256X212_PAL_WORDS],
	['256x240', GX_GPU_DISPLAY_PRESET_256X240_PAL_WORDS],
	['320x240', GX_GPU_DISPLAY_PRESET_320X240_PAL_WORDS],
	['368x240', GX_GPU_DISPLAY_PRESET_368X240_PAL_WORDS],
	['512x240', GX_GPU_DISPLAY_PRESET_512X240_PAL_WORDS],
	['640x240', GX_GPU_DISPLAY_PRESET_640X240_PAL_WORDS],
	['640x480i', GX_GPU_DISPLAY_PRESET_640X480I_NTSC_WORDS],
	['640x448i', GX_GPU_DISPLAY_PRESET_640X448I_NTSC_WORDS],
	['640x512i', GX_GPU_DISPLAY_PRESET_640X512I_PAL_WORDS],
];

const lines = [
	'module<const>',
	'',
	'return {',
	`\tgp1_horizontal_display_range_command = ${gxGpuGp1CommandWord(GX_GPU_GP1_HORIZONTAL_DISPLAY_RANGE, GX_GPU_DISPLAY_HORIZONTAL_RANGE_WORD)},`,
	`\tpcrtc_dispfb_gx16_1024_layout_word = ${GX_GPU_DISPLAY_DISPFB_GX16_1024_LAYOUT_WORD},`,
	`\tpcrtc_pmode_circuit1_opaque_word = ${GX_GPU_DISPLAY_PMODE_CIRCUIT1_OPAQUE_WORD},`,
];

for (const [standard, words] of [
	['pal', GX_GPU_DISPLAY_TIMING_PAL_WORDS],
	['ntsc', GX_GPU_DISPLAY_TIMING_NTSC_WORDS],
] as const) {
	lines.push(
		`\t${standard}_smode1_setup_low_word = ${words[GX_GPU_DISPLAY_TIMING_SMODE1_SETUP_LOW_WORD]},`,
		`\t${standard}_smode1_run_low_word = ${words[GX_GPU_DISPLAY_TIMING_SMODE1_RUN_LOW_WORD]},`,
		`\t${standard}_smode1_high_word = ${words[GX_GPU_DISPLAY_TIMING_SMODE1_HIGH_WORD]},`,
		`\t${standard}_synch1_low_word = ${words[GX_GPU_DISPLAY_TIMING_SYNCH1_LOW_WORD]},`,
		`\t${standard}_synch1_high_word = ${words[GX_GPU_DISPLAY_TIMING_SYNCH1_HIGH_WORD]},`,
		`\t${standard}_synch2_low_word = ${words[GX_GPU_DISPLAY_TIMING_SYNCH2_LOW_WORD]},`,
		`\t${standard}_synch2_high_word = ${words[GX_GPU_DISPLAY_TIMING_SYNCH2_HIGH_WORD]},`,
		`\t${standard}_syncv_high_word = ${words[GX_GPU_DISPLAY_TIMING_SYNCV_HIGH_WORD]},`,
	);
}

for (const [name, words] of GX_DISPLAY_PRESET_MODULE_MODES) {
	const prefix = `mode_${name}`;
	lines.push(
		`\t${prefix}_size_word = ${gxGpuPair16(words[GX_GPU_DISPLAY_PRESET_WIDTH_WORD], words[GX_GPU_DISPLAY_PRESET_HEIGHT_WORD])},`,
		`\t${prefix}_gp1_display_mode_command = ${gxGpuGp1CommandWord(GX_GPU_GP1_DISPLAY_MODE, words[GX_GPU_DISPLAY_PRESET_MODE_WORD])},`,
		`\t${prefix}_gp1_vertical_range_command = ${gxGpuGp1CommandWord(GX_GPU_GP1_VERTICAL_DISPLAY_RANGE, words[GX_GPU_DISPLAY_PRESET_VERTICAL_RANGE_WORD])},`,
		`\t${prefix}_pcrtc_display_low_word = ${words[GX_GPU_DISPLAY_PRESET_PCRTC_DISPLAY_LOW_WORD]},`,
		`\t${prefix}_pcrtc_display_high_word = ${words[GX_GPU_DISPLAY_PRESET_PCRTC_DISPLAY_HIGH_WORD]},`,
		`\t${prefix}_pcrtc_syncv_low_word = ${words[GX_GPU_DISPLAY_PRESET_PCRTC_SYNCV_LOW_WORD]},`,
		`\t${prefix}_pcrtc_smode2_low_word = ${words[GX_GPU_DISPLAY_PRESET_PCRTC_SMODE2_LOW_WORD]},`,
	);
}

lines.push('}', '');

export const GX_DISPLAY_PRESET_MODULE_SOURCE = lines.join('\n');
