export const BMSX_ROM_BOOT_HEADER_SIZE = 60;
export const BMSX_ROM_HEADER_BLUA32_IMAGE_OFFSET = 32;
export const BMSX_ROM_HEADER_BLUA32_IMAGE_BYTE_COUNT_OFFSET = 36;
export const BMSX_ROM_HEADER_BLUA32_STARTUP_FUNCTION_ADDRESS_OFFSET = 40;
export const BMSX_ROM_HEADER_BLUA32_IRQ_FUNCTION_ADDRESS_OFFSET = 44;
export const BMSX_ROM_HEADER_BLUA32_EXCEPTION_FUNCTION_ADDRESS_OFFSET = 48;
export const BMSX_ROM_HEADER_BLUA32_STATIC_LAYOUT_TOKEN_LO_OFFSET = 52;
export const BMSX_ROM_HEADER_BLUA32_STATIC_LAYOUT_TOKEN_HI_OFFSET = 56;
