#pragma once

#include "common/primitives.h"

#include <cstddef>

namespace bmsx {

constexpr u32 IMGDEC_CONTROL_START = 1u << 0u;

constexpr u32 IMGDEC_STATUS_BUSY = 1u << 0u;
constexpr u32 IMGDEC_STATUS_DONE = 1u << 1u;
constexpr u32 IMGDEC_STATUS_INPUT_REQUEST = 1u << 2u;
constexpr u32 IMGDEC_STATUS_FORMAT_FAULT = 1u << 3u;
constexpr u32 IMGDEC_STATUS_OUTPUT_BLOCKED = 1u << 4u;
constexpr u32 IMGDEC_STATUS_OUTPUT_ABORTED = 1u << 5u;

constexpr size_t IMGDEC_INPUT_FIFO_WORD_CAPACITY = 32u;
constexpr size_t IMGDEC_OUTPUT_FIFO_WORD_CAPACITY = 64u;
constexpr u32 IMGDEC_DMA_BLOCK_WORDS = 16u;
constexpr u32 IMGDEC_DECODE_BATCH_WORDS = 16u;
constexpr size_t IMGDEC_HISTORY_WORD_CAPACITY = 4096u;
constexpr size_t IMGDEC_HISTORY_WORD_MASK = IMGDEC_HISTORY_WORD_CAPACITY - 1u;

constexpr u32 IMGDEC_STREAM_MAGIC = 0x31444d49u;
constexpr u32 IMGDEC_STREAM_HEADER_WORDS = 3u;

constexpr u32 IMGDEC_TOKEN_KIND_SHIFT = 30u;
constexpr u32 IMGDEC_TOKEN_KIND_LITERAL = 0u;
constexpr u32 IMGDEC_TOKEN_KIND_REPEAT = 1u;
constexpr u32 IMGDEC_TOKEN_KIND_BACK_REFERENCE = 2u;
constexpr u32 IMGDEC_TOKEN_KIND_ZERO = 3u;
constexpr u32 IMGDEC_TOKEN_RUN_LENGTH_MASK = 0x3fffffffu;
constexpr u32 IMGDEC_TOKEN_BACK_REFERENCE_DISTANCE_BITS = 12u;
constexpr u32 IMGDEC_TOKEN_BACK_REFERENCE_DISTANCE_MASK = (1u << IMGDEC_TOKEN_BACK_REFERENCE_DISTANCE_BITS) - 1u;
constexpr u32 IMGDEC_TOKEN_BACK_REFERENCE_LENGTH_SHIFT = IMGDEC_TOKEN_BACK_REFERENCE_DISTANCE_BITS;
constexpr u32 IMGDEC_TOKEN_BACK_REFERENCE_LENGTH_MASK = (1u << (30u - IMGDEC_TOKEN_BACK_REFERENCE_DISTANCE_BITS)) - 1u;
constexpr u32 IMGDEC_TOKEN_BACK_REFERENCE_MIN_LENGTH = 3u;

} // namespace bmsx
