export type Layer2D = 0 | 1 | 2;

export const LAYER_2D_WORLD: Layer2D = 0;
export const LAYER_2D_UI: Layer2D = 1;
export const LAYER_2D_IDE: Layer2D = 2;

export type VdpSlotSource = {
	slot: number;
	u: number;
	v: number;
	w: number;
	h: number;
};

export const SKYBOX_FACE_COUNT = 6;
export const SKYBOX_FACE_KEYS = ['posx', 'negx', 'posy', 'negy', 'posz', 'negz'] as const;
export const SKYBOX_FACE_WORD_STRIDE = 5;
export const SKYBOX_FACE_WORD_COUNT = SKYBOX_FACE_COUNT * SKYBOX_FACE_WORD_STRIDE;
export const SKYBOX_FACE_SLOT_WORD = 0;
export const SKYBOX_FACE_U_WORD = 1;
export const SKYBOX_FACE_V_WORD = 2;
export const SKYBOX_FACE_W_WORD = 3;
export const SKYBOX_FACE_H_WORD = 4;
export const VDP_SBX_CONTROL_ENABLE = 1;

export type VdpPmuBank = {
	xQ16: number;
	yQ16: number;
	scaleXQ16: number;
	scaleYQ16: number;
	control: number;
};

export const VDP_PMU_BANK_COUNT = 256;
export const VDP_PMU_BANK_WORD_STRIDE = 5;
export const VDP_PMU_BANK_WORD_COUNT = VDP_PMU_BANK_COUNT * VDP_PMU_BANK_WORD_STRIDE;
export const VDP_PMU_BANK_X_WORD = 0;
export const VDP_PMU_BANK_Y_WORD = 1;
export const VDP_PMU_BANK_SCALE_X_WORD = 2;
export const VDP_PMU_BANK_SCALE_Y_WORD = 3;
export const VDP_PMU_BANK_CONTROL_WORD = 4;
export const VDP_PMU_Q16_ONE = 0x00010000;

export const VDP_BBU_BILLBOARD_LIMIT = 1024;
export const VDP_MFU_WEIGHT_COUNT = 64;
export const VDP_JTU_MATRIX_WORDS = 16;
export const VDP_JTU_MATRIX_COUNT = 32;
export const VDP_JTU_REGISTER_WORDS = VDP_JTU_MATRIX_WORDS * VDP_JTU_MATRIX_COUNT;
export const VDP_MDU_MESH_LIMIT = 1024;
export const VDP_MDU_VERTEX_LIMIT = 65536;
export const VDP_MDU_MORPH_WEIGHT_LIMIT = 8;
export const VDP_MDU_MATERIAL_MESH_DEFAULT = 0xffffffff >>> 0;
export const VDP_MDU_CONTROL_TEXTURE_ENABLE = 1 << 0;
export const VDP_MDU_CONTROL_TEXTURE_SLOT_SHIFT = 1;
export const VDP_MDU_CONTROL_TEXTURE_SLOT_MASK = 0x3 << VDP_MDU_CONTROL_TEXTURE_SLOT_SHIFT;

export const VDP_RD_SURFACE_SYSTEM = 0;
export const VDP_RD_SURFACE_PRIMARY = 1;
export const VDP_RD_SURFACE_SECONDARY = 2;
export const VDP_RD_SURFACE_FRAMEBUFFER = 3;
export const VDP_RD_SURFACE_COUNT = 4;
export const VDP_SLOT_PRIMARY = 0;
export const VDP_SLOT_SECONDARY = 1;
export const VDP_SLOT_SYSTEM = 2;
export const VDP_SLOT_NONE = 0xffffffff >>> 0;
export const VDP_SLOT_ATLAS_NONE = 0xffffffff >>> 0;
export const VDP_SYSTEM_ATLAS_ID = 254;
export const VDP_RD_MODE_RGBA8888 = 0;
export const VDP_RD_STATUS_READY = 1 << 0;
export const VDP_RD_STATUS_OVERFLOW = 1 << 1;
export const VDP_FIFO_CTRL_SEAL = 1 << 0;
export const VDP_STATUS_VBLANK = 1 << 0;
export const VDP_STATUS_SUBMIT_BUSY = 1 << 1;
export const VDP_STATUS_SUBMIT_REJECTED = 1 << 2;
export const VDP_STATUS_FAULT = 1 << 3;
export const VDP_SBX_COMMIT_WRITE = 1;
export const VDP_FAULT_NONE = 0;
export const VDP_FAULT_RD_UNSUPPORTED_MODE = 0x0001;
export const VDP_FAULT_RD_SURFACE = 0x0002;
export const VDP_FAULT_RD_OOB = 0x0003;
export const VDP_FAULT_VRAM_WRITE_UNMAPPED = 0x0101;
export const VDP_FAULT_VRAM_WRITE_UNINITIALIZED = 0x0102;
export const VDP_FAULT_VRAM_WRITE_OOB = 0x0103;
export const VDP_FAULT_VRAM_WRITE_UNALIGNED = 0x0104;
export const VDP_FAULT_VRAM_SLOT_DIM = 0x0105;
export const VDP_FAULT_STREAM_BAD_PACKET = 0x0201;
export const VDP_FAULT_SUBMIT_STATE = 0x0202;
export const VDP_FAULT_CMD_BAD_DOORBELL = 0x0203;
export const VDP_FAULT_SUBMIT_BUSY = 0x0204;
export const VDP_FAULT_DEX_INVALID_SCALE = 0x0301;
export const VDP_FAULT_DEX_INVALID_LINE_WIDTH = 0x0302;
export const VDP_FAULT_DEX_SOURCE_SLOT = 0x0303;
export const VDP_FAULT_DEX_SOURCE_OOB = 0x0304;
export const VDP_FAULT_DEX_OVERFLOW = 0x0305;
export const VDP_FAULT_DEX_UNSUPPORTED_DRAW_CTRL = 0x0306;
export const VDP_FAULT_DEX_CMD_NO_BATCH = 0x0307;
export const VDP_FAULT_BLITTER_OOM_BATCH = 0x0308;
export const VDP_FAULT_SBX_SOURCE_OOB = 0x0401;
export const VDP_FAULT_BBU_ZERO_SIZE = 0x0501;
export const VDP_FAULT_BBU_OVERFLOW = 0x0502;
export const VDP_FAULT_BBU_SOURCE_OOB = 0x0503;
export const VDP_FAULT_MDU_OVERFLOW = 0x0601;
export const VDP_FAULT_MDU_BAD_MATRIX = 0x0602;
export const VDP_FAULT_MDU_BAD_MORPH_RANGE = 0x0603;
export const VDP_FAULT_MDU_BAD_JOINT_RANGE = 0x0604;
export const VDP_FAULT_MDU_BAD_TEXTURE_SLOT = 0x0605;
export const VDP_FRAMEBUFFER_PAGE_RENDER = 0;
export const VDP_FRAMEBUFFER_PAGE_DISPLAY = 1;
export type VdpFrameBufferPage = typeof VDP_FRAMEBUFFER_PAGE_RENDER | typeof VDP_FRAMEBUFFER_PAGE_DISPLAY;
