export const enum OpCode {
	WIDE,
	MOV,
	LOADK,
	LOADNIL,
	LOADBOOL,
	KNIL,
	KFALSE,
	KTRUE,
	K0,
	K1,
	KM1,
	KSMI,
	GETG,
	SETG,
	GETT,
	SETT,
	NEWT,
	ADD,
	SUB,
	MUL,
	DIV,
	MOD,
	FLOORDIV,
	POW,
	BAND,
	BOR,
	BXOR,
	SHL,
	SHR,
	CONCAT,
	CONCATN,
	UNM,
	NOT,
	LEN,
	BNOT,
	EQ,
	LT,
	LE,
	TEST,
	TESTSET,
	JMP,
	JMPIF,
	JMPIFNOT,
	CLOSURE,
	GETUP,
	SETUP,
	VARARG,
	CALL,
	RET,
	LOAD_MEM,
	STORE_MEM,
	STORE_MEM_WORDS,
	BR_TRUE,
	BR_FALSE,
	GETSYS,
	SETSYS,
	GETGL,
	SETGL,
	GETI,
	SETI,
	GETFIELD,
	SETFIELD,
	SELF,
	HALT,
}

export const OPCODE_COUNT = 64;

export const OPCODE = {
	WIDE: OpCode.WIDE,
	MOV: OpCode.MOV,
	LOADK: OpCode.LOADK,
	LOADNIL: OpCode.LOADNIL,
	LOADBOOL: OpCode.LOADBOOL,
	KNIL: OpCode.KNIL,
	KFALSE: OpCode.KFALSE,
	KTRUE: OpCode.KTRUE,
	K0: OpCode.K0,
	K1: OpCode.K1,
	KM1: OpCode.KM1,
	KSMI: OpCode.KSMI,
	GETG: OpCode.GETG,
	SETG: OpCode.SETG,
	GETT: OpCode.GETT,
	SETT: OpCode.SETT,
	NEWT: OpCode.NEWT,
	ADD: OpCode.ADD,
	SUB: OpCode.SUB,
	MUL: OpCode.MUL,
	DIV: OpCode.DIV,
	MOD: OpCode.MOD,
	FLOORDIV: OpCode.FLOORDIV,
	POW: OpCode.POW,
	BAND: OpCode.BAND,
	BOR: OpCode.BOR,
	BXOR: OpCode.BXOR,
	SHL: OpCode.SHL,
	SHR: OpCode.SHR,
	CONCAT: OpCode.CONCAT,
	CONCATN: OpCode.CONCATN,
	UNM: OpCode.UNM,
	NOT: OpCode.NOT,
	LEN: OpCode.LEN,
	BNOT: OpCode.BNOT,
	EQ: OpCode.EQ,
	LT: OpCode.LT,
	LE: OpCode.LE,
	TEST: OpCode.TEST,
	TESTSET: OpCode.TESTSET,
	JMP: OpCode.JMP,
	JMPIF: OpCode.JMPIF,
	JMPIFNOT: OpCode.JMPIFNOT,
	CLOSURE: OpCode.CLOSURE,
	GETUP: OpCode.GETUP,
	SETUP: OpCode.SETUP,
	VARARG: OpCode.VARARG,
	CALL: OpCode.CALL,
	RET: OpCode.RET,
	LOAD_MEM: OpCode.LOAD_MEM,
	STORE_MEM: OpCode.STORE_MEM,
	STORE_MEM_WORDS: OpCode.STORE_MEM_WORDS,
	BR_TRUE: OpCode.BR_TRUE,
	BR_FALSE: OpCode.BR_FALSE,
	GETSYS: OpCode.GETSYS,
	SETSYS: OpCode.SETSYS,
	GETGL: OpCode.GETGL,
	SETGL: OpCode.SETGL,
	GETI: OpCode.GETI,
	SETI: OpCode.SETI,
	GETFIELD: OpCode.GETFIELD,
	SETFIELD: OpCode.SETFIELD,
	SELF: OpCode.SELF,
	HALT: OpCode.HALT,
} as const;

export const OPCODE_NAMES: ReadonlyArray<string> = [
	'WIDE',
	'MOV',
	'LOADK',
	'LOADNIL',
	'LOADBOOL',
	'KNIL',
	'KFALSE',
	'KTRUE',
	'K0',
	'K1',
	'KM1',
	'KSMI',
	'GETG',
	'SETG',
	'GETT',
	'SETT',
	'NEWT',
	'ADD',
	'SUB',
	'MUL',
	'DIV',
	'MOD',
	'FLOORDIV',
	'POW',
	'BAND',
	'BOR',
	'BXOR',
	'SHL',
	'SHR',
	'CONCAT',
	'CONCATN',
	'UNM',
	'NOT',
	'LEN',
	'BNOT',
	'EQ',
	'LT',
	'LE',
	'TEST',
	'TESTSET',
	'JMP',
	'JMPIF',
	'JMPIFNOT',
	'CLOSURE',
	'GETUP',
	'SETUP',
	'VARARG',
	'CALL',
	'RET',
	'LOAD_MEM',
	'STORE_MEM',
	'STORE_MEM_WORDS',
	'BR_TRUE',
	'BR_FALSE',
	'GETSYS',
	'SETSYS',
	'GETGL',
	'SETGL',
	'GETI',
	'SETI',
	'GETFIELD',
	'SETFIELD',
	'SELF',
	'HALT',
];

export const BASE_CYCLES = new Uint8Array([
	0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 2, 1, 2,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 2,
	1, 1, 1, 1, 1, 2, 2, 2,
	2, 1, 2, 2, 1, 1, 1, 2,
	1, 2, 1, 2, 1, 2, 1, 1,
]);

export const OPCODE_USES_BX = new Uint8Array([
	0, 0, 1, 0, 0, 0, 0, 0,
	0, 0, 0, 1, 1, 1, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	1, 1, 1, 1, 0, 0, 0, 0,
	0, 0, 0, 0, 1, 1, 1, 1,
	1, 1, 0, 0, 0, 0, 0, 0,
]);

export const OPCODE_CATEGORY: ReadonlyArray<string> = [
	'wide prefix', 'load/move', 'load/move', 'load/move', 'load/move', 'load/move', 'load/move', 'load/move',
	'load/move', 'load/move', 'load/move', 'load/move', 'table get/set', 'table get/set', 'table get/set', 'table get/set',
	'table creation', 'arithmetic', 'arithmetic', 'arithmetic', 'arithmetic', 'arithmetic', 'arithmetic', 'arithmetic',
	'bitwise', 'bitwise', 'bitwise', 'bitwise', 'bitwise', 'string concat', 'string concat', 'arithmetic',
	'logical', 'length', 'bitwise', 'comparison', 'comparison', 'comparison', 'comparison', 'comparison',
	'branch/jump', 'branch/jump', 'branch/jump', 'closure creation', 'upvalue', 'upvalue', 'vararg', 'call/return',
	'call/return', 'memory I/O', 'memory I/O', 'memory I/O', 'branch/jump', 'branch/jump', 'global/sys access', 'global/sys access',
	'global/sys access', 'global/sys access', 'table get/set', 'table get/set', 'table get/set', 'table get/set', 'table get/set', 'sleep/halt',
];

export function getOpcodeName(opcode: OpCode): string {
	return OPCODE_NAMES[opcode];
}
