import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createInputControllerSnapshot, INPUT_CONTROLLER_SNAPSHOT_WORD_COUNT, InputControllerSampleContext, loadInputControllerSnapshotWords, storeInputControllerSnapshotWords } from '../../machine/ts/machine/devices/input/contracts';
import { InputJournal } from '../../machine/ts/machine/runtime/history/input_journal';

test('input journal retains raw words, sample contexts and unarmed supervisor edges across ring wrap', () => {
	const journal = new InputJournal();
	journal.reset(3);
	const snapshot = createInputControllerSnapshot();
	const expected = new Uint32Array(INPUT_CONTROLLER_SNAPSHOT_WORD_COUNT);
	for (let index = 0; index < expected.length; index += 1) expected[index] = (0xfedcba98 + index * 31) >>> 0;
	loadInputControllerSnapshotWords(snapshot, expected, 0);
	journal.recordSample(snapshot, InputControllerSampleContext.Normal);
	journal.recordLine(0x100000001, false);
	journal.recordLine(0x100000002, true);
	journal.recordSample(snapshot, InputControllerSampleContext.Supervisor);
	journal.recordLine(0x100000003, true);
	journal.recordLine(0x100000004, false);
	assert.equal(journal.firstSequence, 1);
	assert.equal(journal.endSequence, 4);
	assert.equal(journal.flagsAt(1), 4);
	assert.equal(journal.flagsAt(2), 7);
	assert.equal(journal.flagsAt(3), 0, 'overwritten unarmed record must not retain an old sample flag');
	assert.equal(journal.cycleAt(3), 0x100000004);
	assert.equal(journal.endAt(0x100000002), 2);
	assert.equal(journal.storageBytes, 3 * (8 + 4 * (1 + INPUT_CONTROLLER_SNAPSHOT_WORD_COUNT)));
	journal.replaySequence = 1;
	assert.equal(journal.replayLine(), true);
	const restored = createInputControllerSnapshot();
	journal.replaySample(restored);
	assert.equal(journal.replayLine(), true);
	const actual = new Uint32Array(expected.length);
	storeInputControllerSnapshotWords(restored, actual, 0);
	assert.deepEqual(actual, expected);
	journal.branch();
	assert.equal(journal.endSequence, 3);
	journal.recordLine(0x100000005, true);
	assert.equal(journal.replayLine(), true);
});
