import assert from 'node:assert/strict';
import test from 'node:test';
import { Input } from '../../hosts/common/input/manager';
import { HeadlessInputHub } from '../../hosts/node/headless/input';
import { VirtualHeadlessClock } from '../../hosts/node/headless/clock';
import type { PointerSnapshot } from '../../ide/common/models';
import { InputFocusService } from '../../ide/input/focus';
import { PointerButton } from '../../ide/input/pointer/buttons';
import { PointerCaptureService } from '../../ide/input/pointer/capture';
import { PointerHoverService } from '../../ide/input/pointer/hover';
import { WorkbenchSplitControl } from '../../ide/workbench/ui/split_control';
import { WorkbenchSplitView } from '../../ide/workbench/ui/split_view';

test('shared pane sash captures drag, releases on blur/replacement and consumes only its focused keyboard input', t => {
	const input = new Input(new VirtualHeadlessClock(), new HeadlessInputHub(), -1);
	const focus = new InputFocusService(), capture = new PointerCaptureService(), hover = new PointerHoverService();
	const parent = focus.createTarget(), control = new WorkbenchSplitControl(focus, capture, hover, parent);
	const view = new WorkbenchSplitView(0.4);
	t.after(() => { control.dispose(); input.dispose(); });
	view.layout(100, 20, 1100, 600);
	control.setInput(view);
	const pointer: PointerSnapshot = { valid: true, insideViewport: true, pressedButtons: PointerButton.Primary,
		justPressedButtons: PointerButton.Primary, justReleasedButtons: 0, viewportX: view.position + 2, viewportY: 40 };
	assert.equal(control.handlePointer({ ...pointer, viewportX: 200 }), false);
	assert.equal(control.handlePointer(pointer), true);
	assert.equal(focus.target, control.focusTarget);
	assert.equal(capture.active, true);
	capture.dispatch({ ...pointer, justPressedButtons: 0, viewportX: 802 }, false, 1);
	assert.equal(view.position, 800, 'drag retains its initial grip offset');
	parent.focus();
	assert.equal(capture.active, false);
	assert.equal(capture.dispatch({ ...pointer, viewportX: 1000 }, false, 2), false);
	assert.equal(view.position, 800, 'blur retires the gesture, rather than parking it');
	control.focusTarget.focus();
	input.inputButton('keyboard:0', 'ArrowLeft', true, 1, 1, 1);
	input.pollInput();
	focus.handleKeyboard(input.getPlayerInput(1));
	assert.ok(Math.abs(view.position - 750) <= 1);
	assert.equal(input.getPlayerInput(1).getRawButtonState('ArrowLeft', 'keyboard').consumed, true);
	control.handlePointer({ ...pointer, viewportX: view.position });
	control.setInput(new WorkbenchSplitView(0.5));
	assert.equal(capture.active, false);
	assert.equal(control.focusTarget.hasFocus, false);
	const revision = view.revision;
	view.layout(0, 20, 500, 600);
	assert.equal(view.revision, revision, 'viewport layout does not change the retained split preference');
	view.resize(2);
	assert.equal(view.ratio, 0.85);
	view.resize(view.defaultRatio);
	assert.equal(view.position, 200);
});
