// Generated by scripts/render/generate_gx_gpu_software_scanout_specializations.mjs. Do not edit.
// disable normalized_ast_duplicate_pattern repeated_statement_sequence_pattern repeated_expression_pattern -- generated storage and operation specialization is guarded by the generator check.
import {
	GX_GPU_PCRTC_SCANOUT_DRAW_RAW_RGB,
	GX_GPU_PCRTC_SCANOUT_DRAW_RAW_RGBA,
	GX_GPU_PCRTC_SCANOUT_DRAW_RAW_ALPHA,
	GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_SOURCE_RGB,
	GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_SOURCE_RGBA,
	GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_CONSTANT_RGB,
	GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_CONSTANT_RGBA,
	GX_GPU_PCRTC_SCANOUT_DRAW_NONE,
	GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT,
	GX_GPU_PCRTC_STORAGE_CT32,
	GX_GPU_PCRTC_STORAGE_CT24,
	GX_GPU_PCRTC_STORAGE_CT16,
	GX_GPU_PCRTC_STORAGE_CT16S,
	GX_GPU_PCRTC_STORAGE_GPU24,
	GX_GPU_PCRTC_STORAGE_GX16,
	GX_GPU_PCRTC_STORAGE_ZERO,
	type GxGpuPcrtcCircuit,
	type GxGpuPcrtcScanout,
} from '../../../machine/devices/gx/gpu_pcrtc';
import {
	gxGpuLocalMemoryAddress16,
	gxGpuLocalMemoryAddress16S,
	gxGpuLocalMemoryAddress32,
	gxGpuLocalMemoryAddressGpu24,
	gxGpuLocalMemoryAddressGx16,
} from '../../../machine/devices/gx/gpu_local_memory';
import type { GxGpuPipelineState } from '../backend';
import type { GxGpuSoftwareState } from './gx_gpu_state';
import { GX_GPU_SOFTWARE_RGB555_RGBA } from './gx_gpu_scanout_palette';

function rawWordAtAddress(software: GxGpuSoftwareState, address: number): number {
	return software.vram[address & software.vramWordMask];
}

function blendOutputRgba(destination: number, source: number, blendAlpha: number, outputAlpha: number): number {
	const inverseAlpha = 255 - blendAlpha;
	const red = (((source & 0xff) * blendAlpha + (destination & 0xff) * inverseAlpha + 127) / 255) | 0;
	const green = (((source >>> 8 & 0xff) * blendAlpha + (destination >>> 8 & 0xff) * inverseAlpha + 127) / 255) | 0;
	const blue = (((source >>> 16 & 0xff) * blendAlpha + (destination >>> 16 & 0xff) * inverseAlpha + 127) / 255) | 0;
	return (red | (green << 8) | (blue << 16) | outputAlpha) >>> 0;
}

function circuitPixelCt32(software: GxGpuSoftwareState, circuit: GxGpuPcrtcCircuit, sourceX: number, sourceY: number): number {
	const address = gxGpuLocalMemoryAddress32(
		circuit.framebufferBaseWord,
		circuit.framebufferPagesPerRow,
		sourceX,
		sourceY,
	);
	const low = rawWordAtAddress(software, address);
	const high = rawWordAtAddress(software, address + 1);
	return low | ((high & 0xff) << 16) | ((high >>> 8) << 24);
}

function circuitPixelCt24(software: GxGpuSoftwareState, circuit: GxGpuPcrtcCircuit, sourceX: number, sourceY: number): number {
	const address = gxGpuLocalMemoryAddress32(
		circuit.framebufferBaseWord,
		circuit.framebufferPagesPerRow,
		sourceX,
		sourceY,
	);
	const low = rawWordAtAddress(software, address);
	return low | ((rawWordAtAddress(software, address + 1) & 0xff) << 16) | 0x80000000;
}

function circuitPixelCt16(software: GxGpuSoftwareState, circuit: GxGpuPcrtcCircuit, sourceX: number, sourceY: number): number {
	const word = rawWordAtAddress(software, gxGpuLocalMemoryAddress16(
		circuit.framebufferBaseWord, circuit.framebufferPagesPerRow, sourceX, sourceY));
	return GX_GPU_SOFTWARE_RGB555_RGBA[word];
}

function circuitPixelCt16S(software: GxGpuSoftwareState, circuit: GxGpuPcrtcCircuit, sourceX: number, sourceY: number): number {
	const word = rawWordAtAddress(software, gxGpuLocalMemoryAddress16S(
		circuit.framebufferBaseWord, circuit.framebufferPagesPerRow, sourceX, sourceY));
	return GX_GPU_SOFTWARE_RGB555_RGBA[word];
}

function circuitPixelGpu24(software: GxGpuSoftwareState, circuit: GxGpuPcrtcCircuit, sourceX: number, sourceY: number): number {
	const first = rawWordAtAddress(software, gxGpuLocalMemoryAddressGpu24(
		circuit.framebufferBaseWord, circuit.framebufferPagesPerRow, sourceX, sourceY, 0));
	const second = rawWordAtAddress(software, gxGpuLocalMemoryAddressGpu24(
		circuit.framebufferBaseWord, circuit.framebufferPagesPerRow, sourceX, sourceY, 1));
	const rgb = (sourceX & 1) === 0
		? first | ((second & 0xff) << 16)
		: (first >>> 8) | (second << 8);
	return rgb | 0x80000000;
}

function circuitPixelGx16(software: GxGpuSoftwareState, circuit: GxGpuPcrtcCircuit, sourceX: number, sourceY: number): number {
	const word = rawWordAtAddress(software, gxGpuLocalMemoryAddressGx16(
		circuit.framebufferBaseWord, circuit.framebufferWidth, sourceX, sourceY));
	return GX_GPU_SOFTWARE_RGB555_RGBA[word];
}

function writeGx16RawRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	let sourceY = circuit.linearFieldSourceY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let address = circuit.framebufferBaseWord
			+ sourceY * circuit.framebufferWidth
			+ circuit.framebufferX + left - circuit.displayX;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const word = rawWordAtAddress(software, address);
			target[output] = (GX_GPU_SOFTWARE_RGB555_RGBA[word] & 0x00ffffff) | (target[output] & 0xff000000);
			address += 1;
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceY += circuit.linearFieldSourceRowStep;
	}
}

function writeGx16RawRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	let sourceY = circuit.linearFieldSourceY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let address = circuit.framebufferBaseWord
			+ sourceY * circuit.framebufferWidth
			+ circuit.framebufferX + left - circuit.displayX;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const word = rawWordAtAddress(software, address);
			target[output] = GX_GPU_SOFTWARE_RGB555_RGBA[word];
			address += 1;
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceY += circuit.linearFieldSourceRowStep;
	}
}

function writeGx16RawAlphaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	let sourceY = circuit.linearFieldSourceY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let address = circuit.framebufferBaseWord
			+ sourceY * circuit.framebufferWidth
			+ circuit.framebufferX + left - circuit.displayX;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			target[output] = (target[output] & 0x00ffffff) | ((rawWordAtAddress(software, address) & 0x8000) << 16);
			address += 1;
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceY += circuit.linearFieldSourceRowStep;
	}
}

function writeGx16BlendSourceRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	let sourceY = circuit.linearFieldSourceY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let address = circuit.framebufferBaseWord
			+ sourceY * circuit.framebufferWidth
			+ circuit.framebufferX + left - circuit.displayX;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const word = rawWordAtAddress(software, address);
			const sourceMask = -(word >>> 15);
			const destination = target[output];
			const rgb = (GX_GPU_SOFTWARE_RGB555_RGBA[word] & sourceMask & 0x00ffffff) | (destination & ~sourceMask & 0x00ffffff);
			target[output] = (rgb | (destination & 0xff000000)) >>> 0;
			address += 1;
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceY += circuit.linearFieldSourceRowStep;
	}
}

function writeGx16BlendSourceRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	let sourceY = circuit.linearFieldSourceY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let address = circuit.framebufferBaseWord
			+ sourceY * circuit.framebufferWidth
			+ circuit.framebufferX + left - circuit.displayX;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const word = rawWordAtAddress(software, address);
			const sourceMask = -(word >>> 15);
			const destination = target[output];
			const rgb = (GX_GPU_SOFTWARE_RGB555_RGBA[word] & sourceMask & 0x00ffffff) | (destination & ~sourceMask & 0x00ffffff);
			target[output] = (rgb | ((word & 0x8000) << 16)) >>> 0;
			address += 1;
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceY += circuit.linearFieldSourceRowStep;
	}
}

function writeGx16BlendConstantRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const blendAlpha = scanout.blendAlpha;
	let sourceY = circuit.linearFieldSourceY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let address = circuit.framebufferBaseWord
			+ sourceY * circuit.framebufferWidth
			+ circuit.framebufferX + left - circuit.displayX;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const word = rawWordAtAddress(software, address);
			const destination = target[output];
			target[output] = blendOutputRgba(destination, GX_GPU_SOFTWARE_RGB555_RGBA[word], blendAlpha, destination & 0xff000000);
			address += 1;
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceY += circuit.linearFieldSourceRowStep;
	}
}

function writeGx16BlendConstantRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const blendAlpha = scanout.blendAlpha;
	let sourceY = circuit.linearFieldSourceY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let address = circuit.framebufferBaseWord
			+ sourceY * circuit.framebufferWidth
			+ circuit.framebufferX + left - circuit.displayX;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const word = rawWordAtAddress(software, address);
			target[output] = blendOutputRgba(
			target[output],
			GX_GPU_SOFTWARE_RGB555_RGBA[word],
			blendAlpha,
			(word & 0x8000) << 16,
			);
			address += 1;
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceY += circuit.linearFieldSourceRowStep;
	}
}

function writeGenericCt32RawRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt32(software, circuit, sourceX, sourceY);
			target[output] = (source & 0x00ffffff) | (target[output] & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt24RawRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt24(software, circuit, sourceX, sourceY);
			target[output] = (source & 0x00ffffff) | (target[output] & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16RawRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16(software, circuit, sourceX, sourceY);
			target[output] = (source & 0x00ffffff) | (target[output] & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16SRawRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16S(software, circuit, sourceX, sourceY);
			target[output] = (source & 0x00ffffff) | (target[output] & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGpu24RawRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGpu24(software, circuit, sourceX, sourceY);
			target[output] = (source & 0x00ffffff) | (target[output] & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGx16RawRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGx16(software, circuit, sourceX, sourceY);
			target[output] = (source & 0x00ffffff) | (target[output] & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericZeroRawRgbRows(
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = 0;
			target[output] = (source & 0x00ffffff) | (target[output] & 0xff000000);
			output += 1;
		}
		outputY += scanout.outputRowStep;
	}
}

function writeGenericCt32RawRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			target[output] = circuitPixelCt32(software, circuit, sourceX, sourceY) >>> 0;
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt24RawRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			target[output] = circuitPixelCt24(software, circuit, sourceX, sourceY) >>> 0;
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16RawRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			target[output] = circuitPixelCt16(software, circuit, sourceX, sourceY) >>> 0;
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16SRawRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			target[output] = circuitPixelCt16S(software, circuit, sourceX, sourceY) >>> 0;
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGpu24RawRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			target[output] = circuitPixelGpu24(software, circuit, sourceX, sourceY) >>> 0;
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGx16RawRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			target[output] = circuitPixelGx16(software, circuit, sourceX, sourceY) >>> 0;
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericZeroRawRgbaRows(
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			target[output] = 0 >>> 0;
			output += 1;
		}
		outputY += scanout.outputRowStep;
	}
}

function writeGenericCt32RawAlphaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt32(software, circuit, sourceX, sourceY);
			target[output] = (target[output] & 0x00ffffff) | (source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt24RawAlphaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt24(software, circuit, sourceX, sourceY);
			target[output] = (target[output] & 0x00ffffff) | (source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16RawAlphaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16(software, circuit, sourceX, sourceY);
			target[output] = (target[output] & 0x00ffffff) | (source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16SRawAlphaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16S(software, circuit, sourceX, sourceY);
			target[output] = (target[output] & 0x00ffffff) | (source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGpu24RawAlphaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGpu24(software, circuit, sourceX, sourceY);
			target[output] = (target[output] & 0x00ffffff) | (source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGx16RawAlphaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGx16(software, circuit, sourceX, sourceY);
			target[output] = (target[output] & 0x00ffffff) | (source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericZeroRawAlphaRows(
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = 0;
			target[output] = (target[output] & 0x00ffffff) | (source & 0xff000000);
			output += 1;
		}
		outputY += scanout.outputRowStep;
	}
}

function writeGenericCt32BlendSourceRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt32(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt24BlendSourceRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt24(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16BlendSourceRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16SBlendSourceRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16S(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGpu24BlendSourceRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGpu24(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGx16BlendSourceRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGx16(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericZeroBlendSourceRgbRows(
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = 0;
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			output += 1;
		}
		outputY += scanout.outputRowStep;
	}
}

function writeGenericCt32BlendSourceRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt32(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt24BlendSourceRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt24(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16BlendSourceRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16SBlendSourceRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16S(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGpu24BlendSourceRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGpu24(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGx16BlendSourceRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGx16(software, circuit, sourceX, sourceY);
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericZeroBlendSourceRgbaRows(
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = 0;
			const doubledAlpha = source >>> 23 & 0x1fe;
			const blendAlpha = (doubledAlpha | -(doubledAlpha >>> 8)) & 0xff;
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			output += 1;
		}
		outputY += scanout.outputRowStep;
	}
}

function writeGenericCt32BlendConstantRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt32(software, circuit, sourceX, sourceY);
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt24BlendConstantRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt24(software, circuit, sourceX, sourceY);
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16BlendConstantRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16(software, circuit, sourceX, sourceY);
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16SBlendConstantRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16S(software, circuit, sourceX, sourceY);
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGpu24BlendConstantRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGpu24(software, circuit, sourceX, sourceY);
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGx16BlendConstantRgbRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGx16(software, circuit, sourceX, sourceY);
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericZeroBlendConstantRgbRows(
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const blendAlpha = scanout.blendAlpha;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = 0;
			const destination = target[output];
			target[output] = blendOutputRgba(destination, source, blendAlpha, destination & 0xff000000);
			output += 1;
		}
		outputY += scanout.outputRowStep;
	}
}

function writeGenericCt32BlendConstantRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt32(software, circuit, sourceX, sourceY);
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt24BlendConstantRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt24(software, circuit, sourceX, sourceY);
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16BlendConstantRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16(software, circuit, sourceX, sourceY);
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericCt16SBlendConstantRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelCt16S(software, circuit, sourceX, sourceY);
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGpu24BlendConstantRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGpu24(software, circuit, sourceX, sourceY);
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericGx16BlendConstantRgbaRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const sourceXStart = circuit.framebufferX
		+ (circuit.sourcePhaseX * circuit.sourceDivisionMultiplierX >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT);
	const sourceRemainderStart = circuit.sourcePhaseX % circuit.magnificationX;
	const blendAlpha = scanout.blendAlpha;
	let sourceYNumerator = circuit.fieldSourceNumeratorY;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		const sourceY = circuit.framebufferY
			+ (sourceYNumerator * circuit.fieldSourceDivisionMultiplierY >>> GX_GPU_PCRTC_SOURCE_DIVISION_SHIFT)
				* circuit.fieldSourceStride
			+ circuit.fieldSourcePhase;
		let sourceX = sourceXStart;
		let sourceRemainder = sourceRemainderStart;
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = circuitPixelGx16(software, circuit, sourceX, sourceY);
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			sourceX += circuit.sourceAdvanceX;
			sourceRemainder += circuit.sourceRemainderStepX;
			if (sourceRemainder >= circuit.magnificationX) {
				sourceRemainder -= circuit.magnificationX;
				sourceX += 1;
			}
			output += 1;
		}
		outputY += scanout.outputRowStep;
		sourceYNumerator += circuit.fieldSourceNumeratorStepY;
	}
}

function writeGenericZeroBlendConstantRgbaRows(
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
): void {
	const left = circuit.displayX;
	const right = circuit.displayRight;
	const blendAlpha = scanout.blendAlpha;
	let outputY = circuit.fieldDisplayY;
	for (let line = 0; line < circuit.fieldDisplayLineCount; line += 1) {
		let output = outputY * state.width + left;
		for (let outputX = left; outputX < right; outputX += 1) {
			const source = 0;
			target[output] = blendOutputRgba(target[output], source, blendAlpha, source & 0xff000000);
			output += 1;
		}
		outputY += scanout.outputRowStep;
	}
}

export function writeGx16CircuitRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
	drawPath: number,
): void {
	switch (drawPath) {
		case GX_GPU_PCRTC_SCANOUT_DRAW_NONE:
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_RAW_RGB:
			writeGx16RawRgbRows(software, state, target, scanout, circuit);
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_RAW_RGBA:
			writeGx16RawRgbaRows(software, state, target, scanout, circuit);
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_RAW_ALPHA:
			writeGx16RawAlphaRows(software, state, target, scanout, circuit);
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_SOURCE_RGB:
			writeGx16BlendSourceRgbRows(software, state, target, scanout, circuit);
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_SOURCE_RGBA:
			writeGx16BlendSourceRgbaRows(software, state, target, scanout, circuit);
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_CONSTANT_RGB:
			writeGx16BlendConstantRgbRows(software, state, target, scanout, circuit);
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_CONSTANT_RGBA:
			writeGx16BlendConstantRgbaRows(software, state, target, scanout, circuit);
			return;
	}
}

export function writeGenericCircuitRows(
	software: GxGpuSoftwareState,
	state: GxGpuPipelineState,
	target: Uint32Array,
	scanout: GxGpuPcrtcScanout,
	circuit: GxGpuPcrtcCircuit,
	drawPath: number,
): void {
	switch (drawPath) {
		case GX_GPU_PCRTC_SCANOUT_DRAW_NONE:
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_RAW_RGB:
			switch (circuit.framebufferStoragePath) {
				case GX_GPU_PCRTC_STORAGE_CT32:
					writeGenericCt32RawRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT24:
					writeGenericCt24RawRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16:
					writeGenericCt16RawRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16S:
					writeGenericCt16SRawRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GPU24:
					writeGenericGpu24RawRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GX16:
					writeGenericGx16RawRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_ZERO:
					writeGenericZeroRawRgbRows(state, target, scanout, circuit);
					return;
			}
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_RAW_RGBA:
			switch (circuit.framebufferStoragePath) {
				case GX_GPU_PCRTC_STORAGE_CT32:
					writeGenericCt32RawRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT24:
					writeGenericCt24RawRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16:
					writeGenericCt16RawRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16S:
					writeGenericCt16SRawRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GPU24:
					writeGenericGpu24RawRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GX16:
					writeGenericGx16RawRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_ZERO:
					writeGenericZeroRawRgbaRows(state, target, scanout, circuit);
					return;
			}
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_RAW_ALPHA:
			switch (circuit.framebufferStoragePath) {
				case GX_GPU_PCRTC_STORAGE_CT32:
					writeGenericCt32RawAlphaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT24:
					writeGenericCt24RawAlphaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16:
					writeGenericCt16RawAlphaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16S:
					writeGenericCt16SRawAlphaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GPU24:
					writeGenericGpu24RawAlphaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GX16:
					writeGenericGx16RawAlphaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_ZERO:
					writeGenericZeroRawAlphaRows(state, target, scanout, circuit);
					return;
			}
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_SOURCE_RGB:
			switch (circuit.framebufferStoragePath) {
				case GX_GPU_PCRTC_STORAGE_CT32:
					writeGenericCt32BlendSourceRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT24:
					writeGenericCt24BlendSourceRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16:
					writeGenericCt16BlendSourceRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16S:
					writeGenericCt16SBlendSourceRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GPU24:
					writeGenericGpu24BlendSourceRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GX16:
					writeGenericGx16BlendSourceRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_ZERO:
					writeGenericZeroBlendSourceRgbRows(state, target, scanout, circuit);
					return;
			}
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_SOURCE_RGBA:
			switch (circuit.framebufferStoragePath) {
				case GX_GPU_PCRTC_STORAGE_CT32:
					writeGenericCt32BlendSourceRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT24:
					writeGenericCt24BlendSourceRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16:
					writeGenericCt16BlendSourceRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16S:
					writeGenericCt16SBlendSourceRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GPU24:
					writeGenericGpu24BlendSourceRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GX16:
					writeGenericGx16BlendSourceRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_ZERO:
					writeGenericZeroBlendSourceRgbaRows(state, target, scanout, circuit);
					return;
			}
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_CONSTANT_RGB:
			switch (circuit.framebufferStoragePath) {
				case GX_GPU_PCRTC_STORAGE_CT32:
					writeGenericCt32BlendConstantRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT24:
					writeGenericCt24BlendConstantRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16:
					writeGenericCt16BlendConstantRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16S:
					writeGenericCt16SBlendConstantRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GPU24:
					writeGenericGpu24BlendConstantRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GX16:
					writeGenericGx16BlendConstantRgbRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_ZERO:
					writeGenericZeroBlendConstantRgbRows(state, target, scanout, circuit);
					return;
			}
			return;
		case GX_GPU_PCRTC_SCANOUT_DRAW_BLEND_CONSTANT_RGBA:
			switch (circuit.framebufferStoragePath) {
				case GX_GPU_PCRTC_STORAGE_CT32:
					writeGenericCt32BlendConstantRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT24:
					writeGenericCt24BlendConstantRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16:
					writeGenericCt16BlendConstantRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_CT16S:
					writeGenericCt16SBlendConstantRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GPU24:
					writeGenericGpu24BlendConstantRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_GX16:
					writeGenericGx16BlendConstantRgbaRows(software, state, target, scanout, circuit);
					return;
				case GX_GPU_PCRTC_STORAGE_ZERO:
					writeGenericZeroBlendConstantRgbaRows(state, target, scanout, circuit);
					return;
			}
			return;
	}
}
