import { editorTabGroup } from '../../../ide/workbench/ui/tab/group_model';
import { editorChromeState } from '../../../ide/workbench/ui/chrome_state';
import { resolveRuntimeLuaSource } from '../../../ide/runtime/sources';
import { captureRuntimeSaveState, applyRuntimeSaveState, type RuntimeSaveState } from '../../../machine/ts/machine/runtime/save_state';
import { HistoryMode } from '../../../machine/ts/machine/runtime/history/history';
import { IO_SYS_SUPERVISOR_FAULT_SEQUENCE } from '../../../machine/ts/spec/bmsx/io';
import type { TerminalInput } from '../../../ide/workbench/contrib/terminal/editor_input';
import { check, type StudioFixture } from './studio_fixture';
import { reachNemesisTitle } from './studio_nemesis_navigation';

/** Real input, BIOS compiler and ordinary scheduler, on all three renderers. */
export async function runStudioTerminal(test: StudioFixture) {
	const { ide, runtime, frame, until, press, cycles, clipboard } = test;
	await until(() => cycles() > runtime.timing.cpuHz * 13, 'terminal: boot real cartridge');
	await reachNemesisTitle(test);
	test.harness.openLuaSource('title_screen.lua');
	await frame();
	await test.runPaletteCommand('View: Lua Terminal');
	let input = editorTabGroup.activeTab as TerminalInput;
	check(input.kind === 'terminal', 'terminal opens through the registered View command');
	const session = ide.terminal;
	check(session.inputContext === 'cart', 'manual input starts with explicit cart globals');
	const position = cycles();
	for (let index = 0; index < 5; index++) await frame();
	check(cycles() === position, 'opening the terminal does not run the game');
	await test.runMenuCommand('pause');
	const paste = async (text: string) => {
		await test.click(input.composerBounds);
		clipboard.text = text;
		await press('ControlLeft', 'KeyA'); await press('ControlLeft', 'KeyV');
		check(input.draft.text === text, 'terminal paste reaches the real multiline control');
	};
	const evaluate = async (source: string) => {
		await paste(source); await press('Enter');
		check(input.draft.text === '', 'accepted input clears the composer');
		await until(() => session.active === undefined && test.tasks.ready, `terminal: ${source}`);
		check(runtime.machine.memory.readIoU32(IO_SYS_SUPERVISOR_FAULT_SEQUENCE) === 0, 'Lua errors are protected, not monitor faults');
		check(test.execution.userPaused && ide.editor.isActive, 'evaluation retains independent user pause and workbench');
		const stopped = cycles();
		for (let index = 0; index < 3; index++) await frame();
		check(cycles() === stopped && !ide.debugger.plans.mutationActive, 'only the explicit Lua call runs, then the machine is held');
		return session.transcript.entry(session.transcript.next - 1);
	};
	let result = await evaluate('terminal_counter = 20; return terminal_counter, type(new_game), type(cartlib__world__world)');
	check(result.text === '20\tfunction\ttable' && session.lastResult!.context === 'cart', 'implicit names reach real cart globals');
	check(ide.luaTooling.suspendedGuest.global('terminal_counter') === 20, 'cart assignment is immediate, not a writeback');
	result = await evaluate('load("return terminal_counter + 1")()');
	check(result.text === '21', 'default BIOS load resolves globals when called from a cart-context RAM function');
	await test.capture?.('lua-cart-context');
	await test.runPaletteCommand('Terminal: Select Lua Context');
	await press('ArrowDown'); await press('Enter');
	check(session.inputContext === 'session', 'ordinary context picker selects isolated session');
	result = await evaluate('terminal_counter');
	check(result.text === 'nil', 'isolated session does not implicitly see cart variables');
	result = await evaluate('1 + 2');
	check(result.kind === 'result' && result.text === '3', 'expression result comes from BIOS load and guest execution');
	result = await evaluate('counter = 40; print("hello from Lua"); return counter, nil, false');
	check(result.kind === 'result' && result.text === '40\tnil\tfalse', 'multiple return values retain nil and false');
	check(session.transcript.entry(result.id - 1).text === 'hello from Lua', 'ordinary debug TX arrives before the completion result');
	result = await evaluate('counter = counter + 2; return counter');
	check(result.text === '42', 'firmware session environment survives separate submissions');
	check(ide.luaTooling.suspendedGuest.global('counter') === null, 'session assignments do not masquerade as CPU global writes');
	result = await evaluate('local world = getglobal("cartlib__world__world"); world.terminal_probe = 70; setglobal("terminal_probe", 60); return world.terminal_probe, getglobal("terminal_probe"), type(getglobal("new_game"))');
	check(result.text === '70\t60\tfunction', 'manual input reads existing cart bindings and mutates the real world');
	const guest = ide.luaTooling.suspendedGuest;
	check(guest.global('terminal_probe') === 60 && guest.readStringMember(guest.global('cartlib__world__world'), 'terminal_probe') === 70,
		'no copied global table or writeback is involved');
	result = await evaluate('local captured = 7; fn = function(x) return captured + x end');
	result = await evaluate('fn(5)');
	check(result.text === '12', 'RAM closures and their captures remain rooted by guest state');
	result = await evaluate('local x = ;');
	check(result.kind === 'error' && result.text.includes('[load:'), 'syntax errors appear in the terminal');
	result = await evaluate('counter = 43; error("terminal error")');
	check(result.kind === 'error' && result.text === 'terminal error', 'protected runtime errors appear in the terminal');
	result = await evaluate('counter');
	check(result.text === '43', 'errors do not roll back earlier mutations');
	result = await evaluate('local transient = 9; return transient');
	check(result.text === '9', 'locals work within one submission');
	result = await evaluate('transient'); check(result.text === 'nil', 'locals are not promoted to session globals');
	result = await evaluate('load("return counter + 1")()');
	check(result.text === '44', 'session load inherits the firmware-owned environment');
	await evaluate('counter');
	await paste('return'); await press('ShiftLeft', 'Enter');
	check(input.draft.text === 'return\n', 'Shift+Enter inserts a newline without running input');
	await paste('draft kept');
	await press('ArrowUp'); check(input.draft.text === 'counter', 'Up recalls input history');
	await press('ArrowDown'); check(input.draft.text === 'draft kept', 'Down restores the unsubmitted draft');
	await test.capture?.('lua-results');

	await paste('local sum = 0; for i = 1, 2000000 do sum = sum + 1 end; return sum');
	await press('Enter');
	await until(() => session.active !== undefined && session.canToggleExecution, 'terminal: scheduled long-running Lua call');
	check(test.history.mode === HistoryMode.Disabled, 'tool-directed execution is not ordinary rewind history');
	await test.click(input.actions.items.find(item => item.command === 'terminal.pause')!.bounds);
	check(session.paused, `visible Pause stops the guest call: active=${session.active?.id} control=${ide.debugger.plans.controlActive} suspended=${ide.debugger.plans.controlSuspended}`);
	const held = cycles(), operation = session.active!;
	for (let index = 0; index < 5; index++) await frame();
	check(cycles() === held && operation.result === undefined, 'pause retains physical frames without pretending completion');
	await paste('counter = 999'); await press('Enter');
	check(input.draft.text === 'counter = 999' && session.active === operation, 'busy execution does not admit or drop another input');
	await test.capture?.('lua-paused');
	await test.click(input.actions.items.find(item => item.command === 'terminal.continue')!.bounds);
	await until(() => operation.result !== undefined, 'terminal: continue the same physical call');
	check(operation.result!.status === 'completed' && operation.result!.values[0] === '2e+06', `long-running call completes through ordinary scheduled slices: ${JSON.stringify(operation.result)}`);
	result = await evaluate('counter'); check(result.text === '43', 'busy draft was not queued or executed implicitly');
	const replResource = { domain: -1 as const, path: 'shell/repl.lua' };
	const replSource = resolveRuntimeLuaSource(ide.sources, replResource)!.record.src;
	const line = replSource.split('\n').findIndex(line => line.includes('return protect(chunk)')) + 1;
	check(line > 0, 'installed firmware has the protected invocation breakpoint');
	ide.debugger.breakpoints.toggle(replResource, line);
	await paste('counter + 10'); await press('Enter');
	await until(() => ide.debugger.source.stopped && ide.editor.isActive, 'terminal: normal BIOS source breakpoint');
	const breakpointCall = session.active!;
	await until(() => editorTabGroup.activeTab?.kind === 'code_editor', 'terminal: debugger opens the actual BIOS source');
	await test.runPaletteCommand('View: Lua Terminal');
	await test.click(input.actions.items.find(item => item.command === 'terminal.continue')!.bounds);
	await until(() => breakpointCall.result !== undefined, 'terminal: continue from a breakpoint without continuing gameplay');
	ide.debugger.breakpoints.toggle(replResource, line);
	check(breakpointCall.result!.values[0] === '53' && test.execution.userPaused && ide.editor.isActive,
		'terminal continuation retains user pause and Studio rather than using game Continue');
	await test.runPaletteCommand('View: Codex Assistant');
	await test.runPaletteCommand('View: Lua Terminal');
	check(editorTabGroup.activeTab === input, 'pane replacement retains the session and input');
	result = await evaluate('fn(8)'); check(result.text === '15', 'switching views does not discard firmware session state');
	await test.clickTab(input.id);
	test.movePointer(input.composerBounds); await frame();
	test.movePointer(editorChromeState.tabButtonBounds.get(input.id)!); await frame();
	check(editorChromeState.tabCloseButtonBounds.get(input.id)!.right > editorChromeState.tabCloseButtonBounds.get(input.id)!.left,
		'hover exposes the existing tab Close action');
	await test.click(editorChromeState.tabCloseButtonBounds.get(input.id)!);
	check(!editorTabGroup.tabs.includes(input), 'close releases the Terminal input, not the Lua session');
	await test.runPaletteCommand('View: Lua Terminal');
	input = editorTabGroup.activeTab as TerminalInput;
	result = await evaluate('fn(8)'); check(result.text === '15', 'closing and reopening retains the guest session');
	let saved!: RuntimeSaveState;
	await test.tasks.schedule(async () => {
		await test.presenter.backend.captureGxGpuVramSnapshot(runtime.machine.gxGpu);
		saved = captureRuntimeSaveState(runtime);
	}, error => { throw error; });
	await evaluate('counter = 99; fn = nil; setglobal("terminal_probe", 999)');
	await test.tasks.schedule(() => { applyRuntimeSaveState(runtime, saved); }, error => { throw error; });
	result = await evaluate('counter, fn(8)');
	check(result.text === '43\t15', 'restore uses the restored guest environment and RAM closures, not stale host references');
	result = await evaluate('local world = getglobal("cartlib__world__world"); return getglobal("terminal_probe"), world.terminal_probe');
	check(result.text === '60\t70', 'state restore retains dynamically registered globals and the real cart object');
	await press('ControlLeft', 'KeyL');
	check(session.transcript.start === session.transcript.next, 'Ctrl+L clears only scrollback');
	result = await evaluate('counter'); check(result.text === '43', 'clearing output does not reset the guest namespace');
	const lastRow = input.transcript.rows.findLastIndex(row => row.entry === result.id);
	const rowTop = input.viewport.offsetTop + lastRow * input.layout.rowHeight;
	await test.click({ left: 8, right: 9, top: rowTop + 1, bottom: rowTop + 2 });
	clipboard.text = ''; await press('ControlLeft', 'KeyC');
	check(clipboard.text === '43', 'transcript pointer selection and Copy use the retained entry text');
	await test.capture?.('lua-terminal');
	await paste('while true do end'); await press('Enter');
	await until(() => session.canToggleExecution, 'terminal: infinite input remains schedulable');
	await test.click(input.actions.items.find(item => item.command === 'terminal.pause')!.bounds);
	const interrupted = session.active!;
	await test.runMenuCommand('reboot');
	await until(() => interrupted.result !== undefined && test.tasks.ready, 'terminal: explicit reboot retires the call');
	check(interrupted.result!.status === 'interrupted' && !ide.debugger.plans.mutationActive, 'reset clears the real frames and retires the observer once');
	await until(() => cycles() > runtime.timing.cpuHz * 13, 'terminal: cartridge restarts through BIOS');
	await reachNemesisTitle(test);
	test.harness.openLuaSource('title_screen.lua'); await frame();
	await test.runMenuCommand('pause'); await test.runPaletteCommand('View: Lua Terminal');
	input = editorTabGroup.activeTab as TerminalInput;
	result = await evaluate('counter, fn');
	check(result.text === 'nil\tnil', 'reboot starts a fresh guest namespace while retaining historical scrollback');
	await test.capture?.('lua-reboot');
	return { renderer: 'shared', terminal: true, calls: session.history.length };
}
