import { AssistantHttpConnection } from '../../../ide/browser/assistant_connection';
import { StudioHttpSession } from '../../../ide/browser/http_session';
import { getActiveTab } from '../../../ide/workbench/ui/tabs';
import { TextStyle } from '../../../ide/common/markdown/model';
import { editorFeedbackState } from '../../../ide/common/feedback_state';
import { measureTextRange } from '../../../ide/editor/common/text/layout';
import { getCursorOffset } from '../../../ide/editor/ui/inline/text_field';
import { check, createStudioFixture } from './studio_fixture';
import { reachNemesisTitle } from './studio_nemesis_navigation';
import { createStudioRenderer, type StudioRendererKind } from './studio_renderer';
import { exerciseLongAssistantHistory } from './studio_assistant_history_stress';
import { submitAssistantText } from './studio_assistant_navigation';

/** Real browser/HTTP/process; an offline provider supplies the Markdown and waits for Stop. */
export async function runAssistantPresentation(kind: StudioRendererKind, canvas: HTMLCanvasElement, capture: (name: string) => Promise<void>, waitForModel: () => Promise<void>) {
	const renderer = await createStudioRenderer(kind, canvas, capture), http = new StudioHttpSession();
	const test = await createStudioFixture(canvas, renderer.backend, renderer.capture, (signal, emit) => AssistantHttpConnection.open(http, signal, emit));
	const { ide, runtime, cycles, until, harness, press, frame, presenter } = test;
	capture = renderer.capture!;
	await until(() => cycles() > runtime.timing.cpuHz * 13, 'presentation: boot the cart');
	await reachNemesisTitle(test);
	harness.openLuaSource('cart.lua'); await frame();
	await press('ControlLeft', 'Home'); test.clipboard.text = '-- REFERENCED WORKING COPY\n'; await press('ControlLeft', 'KeyV');
	await test.runPaletteCommand('View: Codex Assistant');
	const view = getActiveTab(); if (view.kind !== 'assistant') throw new Error('Assistant expected');
	const conversation = ide.editor.assistant, paused = cycles();
	const picker = ide.editor.quickInput;
	const emptyComposerHeight = view.composerBounds.bottom - view.composerBounds.top;
	await capture('empty-composer');
	await submitAssistantText(test, '/model');
	await until(() => picker.visible, 'presentation: native model catalog picker');
	await frame(); await capture('model-picker'); await press('Enter');
	await capture('effort-picker');
	const initialEffort = picker.model.list.rows[picker.model.list.selectionIndex].item.label;
	await press('Enter');
	await until(() => conversation.state === 'ready' && conversation.configuration?.effort === initialEffort, 'presentation: session defaults accepted without a thread');
	const selectedModel = conversation.configuration!.model!;
	check(conversation.thread === undefined && conversation.entries.length === 0, 'presentation: settings create neither transcript noise nor phantom history');
	await submitAssistantText(test, '/effort'); await until(() => picker.visible, 'presentation: effort picker');
	await press('ArrowDown');
	const selectedEffort = picker.model.list.rows[picker.model.list.selectionIndex].item.label;
	await press('Enter');
	await until(() => conversation.state === 'ready' && conversation.configuration?.effort === selectedEffort, 'presentation: effort changed through keyboard');
	await submitAssistantText(test, '/fast'); await until(() => picker.visible, 'presentation: speed picker');
	await press('ArrowDown'); await capture('speed-picker'); await press('Enter');
	await until(() => conversation.state === 'ready' && conversation.configuration?.serviceTier === 'priority', 'presentation: speed selection configures the session');
	await submitAssistantText(test, '/model'); await until(() => picker.visible, 'presentation: cancel picker'); await press('Escape');
	check(conversation.configuration!.model === selectedModel && conversation.thread === undefined, 'presentation: cancel keeps existing settings');
	await test.click(view.composerBounds);
	test.clipboard.text = 'One two three\n'.repeat(10); await press('ControlLeft', 'KeyV'); await frame();
	check(view.composerBounds.bottom - view.composerBounds.top > emptyComposerHeight, 'presentation: long draft grows the composer');
	check(view.composer.firstRow > 0, 'presentation: long draft scrolls to the caret');
	await capture('expanded-composer');
	await press('ControlLeft', 'Home'); check(view.composer.firstRow === 0, 'presentation: Home reveals the beginning');
	await press('ControlLeft', 'KeyA'); await press('Backspace'); await frame();
	check(view.composerBounds.bottom - view.composerBounds.top === emptyComposerHeight, 'presentation: deleting the draft returns transcript space');
	const draftMarkdown = '**Bold** *italic* `velocity_x_q8` ~~previous~~\n- [x] Keep markers\n```lua\n\treturn 7\n```\n[Guide](https://example.com)';
	test.clipboard.text = draftMarkdown; await press('ControlLeft', 'KeyV');
	ide.editor.setFontVariant('msx'); await frame(); await capture('composer-markdown-msx');
	await test.runPaletteCommand('Preferences: Toggle Theme'); await frame(); await capture('composer-markdown-dark-msx');
	await test.runPaletteCommand('Preferences: Toggle Theme'); await frame();
	const cursor = draftMarkdown.indexOf('italic') + 2;
	const cursorX = view.composerBounds.left + 3 + view.composer.rows[0].advances[cursor];
	await test.click({ left: cursorX - 1, right: cursorX + 1, top: view.composerBounds.top + 2, bottom: view.composerBounds.top + 2 + view.layout.rowHeight });
	check(getCursorOffset(view.draft) === cursor, 'presentation: styled source pointer positions the raw-text caret');
	for (let index = 0; index < 5; index++) await press('ShiftLeft', 'ArrowRight');
	await capture('composer-markdown-selection'); await press('ControlLeft', 'KeyC');
	check(await navigator.clipboard.readText() === draftMarkdown.slice(cursor, cursor + 5), 'presentation: selection Copy includes source Markdown delimiters');
	await press('ControlLeft', 'KeyX');
	const editedDraft = view.draft.text;
	check(editedDraft === draftMarkdown.slice(0, cursor) + draftMarkdown.slice(cursor + 5), 'presentation: Cut edits source, not the styled projection');
	await press('ControlLeft', 'KeyZ'); check(view.draft.text === draftMarkdown, 'presentation: styled draft Undo restores original source');
	await press('ControlLeft', 'KeyY'); check(view.draft.text === editedDraft, 'presentation: styled draft Redo restores the edit');
	await press('ControlLeft', 'KeyZ');
	await press('ControlLeft', 'KeyA'); await press('Backspace');
	ide.editor.setFontVariant('tiny'); await frame();
	await test.click(view.composerBounds);
	test.clipboard.text = 'Inspect the mijter enemy, then explain the change. @cart'; await press('ControlLeft', 'KeyV');
	await capture('reference-suggestions');
	await test.runPaletteCommand('Preferences: Toggle Theme'); await frame();
	// Returning to the composer restores suggestions without creating another prompt.
	await press('ArrowLeft'); await press('ArrowRight'); await capture('reference-suggestions-dark');
	await test.runPaletteCommand('Preferences: Toggle Theme'); await frame();
	await press('ArrowLeft'); await press('ArrowRight'); await press('Enter');
	check(view.draft.annotations.length === 1, 'presentation: Enter accepts a source reference without sending a turn');
	const references = view.draft.annotations.map(span => ({ from: span.from, to: span.to, source: span.data }));
	const referencePrompt = view.draft.text;
	await capture('reference-in-composer');
	await press('ControlLeft', 'KeyZ'); check(view.draft.annotations.length === 0, 'presentation: Undo removes the reference insertion');
	await press('ControlLeft', 'KeyY'); check(view.draft.annotations.length === 1, 'presentation: Redo restores its source identity');
	await press('ControlLeft', 'Enter');
	await until(() => conversation.entries.some(entry => entry.kind === 'assistant') && conversation.state === 'ready', 'presentation: actual Markdown reply');
	await until(() => conversation.thread?.title === Array.from(referencePrompt.trim()).slice(0, 80).join(''), 'presentation: persisted conversation title');
	await frame();
	const styles = view.transcript.rows.flatMap(row => row.runs.map(run => run.style));
	for (const style of [TextStyle.Bold, TextStyle.Italic, TextStyle.Code]) check(styles.some(value => (value & style) !== 0), 'presentation: parsed Markdown style ' + style);
	check(cycles() === paused, 'presentation: host UI does not run the game');
	const rows = view.transcript.rows.slice();
	for (let index = 0; index < 20; index++) await frame();
	check(rows.every((row, index) => row === view.transcript.rows[index]), 'presentation: idle frames retain layout');
	await capture('markdown-tiny');
	ide.editor.setFontVariant('msx'); await frame(); await capture('markdown-msx');
	await test.runPaletteCommand('Preferences: Toggle Theme'); await frame(); await capture('markdown-dark-msx');
	await test.runPaletteCommand('Preferences: Toggle Theme'); await frame();
	const reply = conversation.entries.find(entry => entry.kind === 'assistant')!;
	const codeRow = view.transcript.rows.findIndex((row, index) => row.entry === reply.index && row.code
		&& view.viewport.offsetTop + (index + view.transcript.firstRow) * view.layout.rowHeight >= view.viewport.bounds.top
		&& view.viewport.offsetTop + (index + view.transcript.firstRow + 1) * view.layout.rowHeight <= view.viewport.bounds.bottom);
	check(codeRow >= 0, 'presentation: a formatted code row is visible for pointer selection');
	const codeTop = view.viewport.offsetTop + (codeRow + view.transcript.firstRow) * view.layout.rowHeight;
	const codeBounds = { left: 12, right: 24, top: codeTop, bottom: codeTop + view.layout.rowHeight };
	await test.click(codeBounds);
	await press('ControlLeft', 'KeyC');
	check(view.selectedEntry === reply.index && test.clipboard.text === reply.text.getText(), 'presentation: click and Copy preserve the complete original Markdown');
	check(await navigator.clipboard.readText() === reply.text.getText(), 'presentation: formatted text Copy reaches the browser clipboard');
	await capture('selected-code-msx');
	await until(() => !editorFeedbackState.message.visible, 'presentation: shared clipboard confirmation expires without running the guest');
	await test.click({ ...codeBounds, left: view.viewport.bounds.right - 2, right: view.viewport.bounds.right - 1 });
	check(view.selectedEntry === -1, 'presentation: whitespace beside text clears the message selection');
	check(!ide.editor.commands.isEnabled('assistant.copy'), 'presentation: Copy is unavailable without a selected message');
	await capture('deselected-beside-text');
	await test.click(codeBounds);
	const gap = view.transcript.rows.findIndex(row => row.runs.length === 0);
	const gapTop = view.viewport.offsetTop + (gap + view.transcript.firstRow) * view.layout.rowHeight;
	await test.click({ left: 12, right: 24, top: gapTop, bottom: gapTop + view.layout.rowHeight });
	check(view.selectedEntry === -1, 'presentation: an empty separator does not select its neighbouring message');
	await test.click(codeBounds);
	await test.click({ left: 12, right: 24, top: view.viewport.bounds.bottom - 2, bottom: view.viewport.bounds.bottom - 1 });
	check(view.selectedEntry === -1, 'presentation: empty transcript space clears the message selection');
	await capture('deselected-below-messages');
	await test.click(codeBounds);
	await test.click(view.composerBounds);
	check(view.selectedEntry === -1 && view.draft.focusTarget.hasFocus, 'presentation: composer click clears message selection and retains field focus');
	await capture('deselected-composer');
	await test.click(codeBounds);
	await press('Escape');
	check(view.selectedEntry === -1, 'presentation: Escape clears transcript selection');
	await test.click(codeBounds);
	await press('ArrowUp'); await press('End');

	// Exercise a phone-width logical surface, not CSS scaling of a wide screenshot.
	presenter.setFixedRenderTargetSize(320, 384);
	ide.overlayRenderer.setRenderingViewportType(presenter, 'viewport'); ide.editor.updateViewport(ide.overlayRenderer.viewportSize);
	await frame();
	check(view.footerTop + (view.footer.lines.length - 1) * view.layout.rowHeight + 2 <= view.layout.bottom, 'presentation: footer text is above the global status clip');
	check(view.footer.lines.length > 1 && view.footer.lines.every(line => measureTextRange(line, 0, line.length) <= view.layout.right - 8), 'presentation: narrow footer keeps all settings in bounded rows');
	for (const row of view.transcript.rows) for (const run of row.runs) check(run.x + run.width <= view.layout.right - 16, 'presentation: styles wrap within the narrow transcript');
	await capture('narrow-msx');
	await test.runPaletteCommand('Preferences: Toggle Theme'); await frame(); await capture('narrow-dark-msx');
	await test.runPaletteCommand('Preferences: Toggle Theme'); await frame();
	await submitAssistantText(test, '/model'); await until(() => picker.visible, 'presentation: narrow model picker');
	await frame(); await capture('narrow-model-picker'); await press('Escape');
	ide.editor.setFontVariant('tiny'); await frame(); await capture('narrow-tiny');
	await test.click(view.composerBounds); test.clipboard.text = draftMarkdown; await press('ControlLeft', 'KeyV');
	await capture('composer-markdown-narrow'); await press('ControlLeft', 'Home'); await capture('composer-markdown-narrow-start');
	ide.editor.setFontVariant('msx'); await frame(); await capture('composer-markdown-narrow-msx-start');
	await press('ControlLeft', 'End'); await capture('composer-markdown-narrow-msx-end');
	await press('ControlLeft', 'KeyA'); await press('Backspace');
	ide.editor.setFontVariant('tiny'); await frame();
	await test.click(view.composerBounds);
	test.clipboard.text = 'Keep investigating while I review the result. @cart'; await press('ControlLeft', 'KeyV');
	await capture('reference-suggestions-narrow'); await press('Tab');
	check(view.draft.annotations.length === 1 && view.draft.focusTarget.hasFocus, 'presentation: Tab accepts a reference without moving focus');
	await press('ControlLeft', 'Enter');
	await waitForModel(); await frame();
	check(conversation.state === 'running' && view.busySince !== undefined && view.activityText.length > 0, 'presentation: work indicator is visible before any response text');
	await capture('working-a');
	await new Promise(resolve => setTimeout(resolve, 180)); await frame(); await capture('working-b');
	await new Promise(resolve => setTimeout(resolve, 1100)); await frame();
	check(view.activitySecond >= 1, 'presentation: elapsed clock runs while the game is paused');
	await test.click(view.turnActions.items.find(item => item.command === 'assistant.stop')!.bounds);
	await until(() => conversation.state === 'ready', 'presentation: Stop settles'); await frame();
	check(view.busySince === undefined && view.activityText === '', 'presentation: activity disappears after Stop');
	await capture('stopped');
	await submitAssistantText(test, '/history'); await until(() => picker.visible, 'presentation: browse native history'); await press('Enter');
	await until(() => conversation.state === 'ready' && conversation.entries.some(entry => entry.references?.length === 1), 'presentation: native history restores source references');
	check(conversation.entries.some(entry => entry.text.getText() === referencePrompt && JSON.stringify(entry.references) === JSON.stringify(references)),
		'presentation: history retains the original prompt and exact reference ranges');
	const historyStress = await exerciseLongAssistantHistory(test, view, capture);
	await renderer.finish();
	return { references, historyStress, presentation: 'pass', selectedModel, selectedEffort, footer: view.footer.lines, paused: cycles() === paused };
}
