import { AssistantHttpConnection } from '../../../ide/browser/assistant_connection';
import { StudioHttpSession } from '../../../ide/browser/http_session';
import { getActiveTab } from '../../../ide/workbench/ui/tabs';
import { check, createStudioFixture } from './studio_fixture';
import { reachNemesisTitle } from './studio_nemesis_navigation';
import { submitAssistantText } from './studio_assistant_navigation';
import { createStudioRenderer, type StudioRendererKind } from './studio_renderer';

type HistoryFixtureControl = {
	releaseFirst: () => Promise<void>;
	waitForStop: () => Promise<void>;
	metrics: () => Promise<{ requests: number; connects: number; commands: number }>;
};

/** Real persistent App Server history/queue, exercised through ordinary chat, pickers and keyboard. */
export async function runAssistantHistory(kind: StudioRendererKind, canvas: HTMLCanvasElement, capture: (name: string) => Promise<void>, control: HistoryFixtureControl) {
	const renderer = await createStudioRenderer(kind, canvas, capture), http = new StudioHttpSession();
	const test = await createStudioFixture(canvas, renderer.backend, renderer.capture, (signal, emit) => AssistantHttpConnection.open(http, signal, emit));
	const { ide, until, press, frame } = test;
	await until(() => test.cycles() > test.runtime.timing.cpuHz * 13, 'history: boot actual cart');
	await reachNemesisTitle(test);
	test.harness.openLuaSource('cart.lua'); await frame();
	const mainTab = getActiveTab(), main = test.harness.getActiveEditorDocument().model;
	await test.runPaletteCommand('View: Codex Assistant');
	let view = getActiveTab(); if (view.kind !== 'assistant') throw new Error('Assistant required');
	const model = ide.editor.assistant, picker = ide.editor.quickInput, position = test.cycles();
	check(view.turnActions.items.filter(item => item.visible).length === 1, 'idle chat shows only Send, no account/connect/disconnect toolbar');
	await submitAssistantText(test, '/');
	check(picker.visible && picker.title === 'Codex commands', 'slash discovery uses the shared picker without a process');
	await frame(); await renderer.capture!('commands'); await press('Escape');
	check((await control.metrics()).connects === 0, 'command discovery is local');
	await submitAssistantText(test, 'First history message');
	await until(() => model.state === 'running' && !model.submitting, 'history: implicit single connection starts first turn');
	await submitAssistantText(test, 'Queued original');
	await until(() => model.queued.length === 1 && !model.submitting, 'history: native queue admits text without a new turn');
	await submitAssistantText(test, 'Remove this queued message');
	await until(() => model.queued.length === 2 && !model.submitting, 'history: native queue has two messages');
	await submitAssistantText(test, '/queue');
	await until(() => picker.visible, 'history: queue picker ready');
	check(picker.visible && picker.title === 'Codex queue', 'slash queue opens the ordinary workbench picker');
	await renderer.capture!('queue');
	await press('Enter'); await press('Enter');
	check(view.editingQueuedId === model.queued[0].id && view.draft.text === 'Queued original', 'Edit transfers the selected native message into the composer');
	await submitAssistantText(test, 'Queued edited');
	await until(() => model.queued[0]?.text === 'Queued edited' && !model.submitting, 'history: queue update is acknowledged');
	await submitAssistantText(test, '/queue'); await until(() => picker.visible, 'history: remove picker ready');
	await press('ArrowDown'); await press('Enter'); await press('ArrowDown'); await press('Enter');
	await until(() => model.queued.length === 1 && !model.submitting, 'history: Remove deletes only the selected queued message');
	await submitAssistantText(test, 'Direct correction', true);
	await until(() => !model.submitting, 'history: direct steering acknowledged without creating a second turn');
	await test.clickTab(mainTab.id); await press('ControlLeft', 'Home');
	test.clipboard.text = '-- Edited while queued\n'; await press('ControlLeft', 'KeyV');
	const source = main.buffer.getText();
	await test.clickTab(view.id); await frame(); await renderer.capture!('working');
	const working = await control.metrics();
	for (let index = 0; index < 120; index++) await frame();
	check(JSON.stringify(await control.metrics()) === JSON.stringify(working), 'idle frames never poll, retry or resubmit queued text');
	await control.releaseFirst();
	await until(() => model.state === 'ready' && model.entries.some(entry => entry.kind === 'proposal'), 'history: native FIFO starts the edited message with fresh source context');
	check(model.queued.length === 0, 'native consumption empties the projected queue');
	check(JSON.stringify(model.entries.filter(entry => entry.kind === 'user').map(entry => entry.text.getText())) === JSON.stringify(['First history message', 'Direct correction', 'Queued edited']), 'only consumed user inputs enter the live transcript, in native order');
	const pending = model.entries.find(entry => entry.kind === 'proposal')!.proposal!, thread = model.thread!.id;
	check(pending.state === 'pending' && main.buffer.getText() === source, 'queued review cannot apply itself');
	await submitAssistantText(test, 'Wait for Stop'); await control.waitForStop(); await frame();
	await submitAssistantText(test, 'Resume this queued message');
	await until(() => model.queued.length === 1 && !model.submitting, 'history: queue before Stop');
	await test.click(view.turnActions.items.find(item => item.command === 'assistant.stop')!.bounds);
	await until(() => model.state === 'ready', 'history: Stop interrupts and retains waiting text');
	check(model.queuePaused && model.queued[0].text === 'Resume this queued message', 'Stop does not silently dispatch or discard waiting work');
	const stopped = await control.metrics();
	for (let index = 0; index < 120; index++) await frame();
	check(JSON.stringify(await control.metrics()) === JSON.stringify(stopped), 'stopped queue never loops or retries');
	await press('ControlLeft', 'KeyW');
	check(pending.state === 'stale' && model.state === 'disconnected', 'closing retires source rights, not persisted text');
	await test.runPaletteCommand('View: Codex Assistant');
	view = getActiveTab(); if (view.kind !== 'assistant') throw new Error('Assistant required');
	await submitAssistantText(test, '/queue');
	await until(() => picker.visible && picker.title === 'Codex queue', 'history: queue inspection reconnects without executing');
	check(picker.model.list.rows.length === 1, 'cold queue snapshot retains the pending message'); await press('Escape');
	await submitAssistantText(test, '/history');
	await until(() => picker.visible && picker.title === 'Codex history', 'history: cold private profile lists its persisted conversation');
	check(picker.model.list.rows.length === 1, 'one real thread, not copies for queued or direct inputs');
	await frame(); await renderer.capture!('history');
	const browsing = await control.metrics();
	test.clipboard.text = 'First history'; await press('ControlLeft', 'KeyV');
	for (let index = 0; index < 120; index++) await frame();
	check(JSON.stringify(await control.metrics()) === JSON.stringify(browsing), 'history filtering uses retained data, not per-keystroke provider calls');
	await press('Enter');
	await until(() => model.state === 'ready' && !view.commandPending, 'history: read-only transcript selected');
	check(model.thread!.id === thread && model.queued.length === 1 && model.queuePaused, 'selection restores identity and waiting text without starting work');
	check(model.entries.every(entry => entry.kind !== 'proposal') && !view.turnActions.items.find(item => item.command === 'assistant.review')!.visible, 'historical tool records are not current edit rights');
	check(model.entries.some(entry => entry.kind === 'user' && entry.text.getText() === 'Direct correction'), 'persisted history includes the consumed direct message');
	check((await control.metrics()).requests === stopped.requests, 'listing and selecting history add no inference');
	await frame(); await renderer.capture!('resumed-transcript');
	await submitAssistantText(test, '/queue'); await until(() => picker.visible, 'history: cold edit picker ready');
	await press('Enter'); await press('Enter'); await submitAssistantText(test, 'Resume this edited queued message');
	await until(() => model.queued[0]?.text === 'Resume this edited queued message' && !model.submitting, 'history: unloaded queue edit publishes its snapshot');
	await submitAssistantText(test, 'Remove this cold queued message');
	await until(() => model.queued.length === 2 && !model.submitting, 'history: unloaded queue accepts waiting text without resuming');
	await submitAssistantText(test, '/queue'); await until(() => picker.visible, 'history: cold remove picker ready');
	await press('ArrowDown'); await press('Enter'); await press('ArrowDown'); await press('Enter');
	await until(() => model.queued.length === 1 && !model.submitting, 'history: unloaded queue delete publishes its snapshot');
	check((await control.metrics()).requests === stopped.requests, 'editing the unloaded queue cannot start inference');
	await submitAssistantText(test, '/continue');
	await until(() => model.state === 'ready' && model.queued.length === 0, 'history: explicit Continue starts the stopped native queue');
	check(model.thread!.id === thread && model.entries.at(-1)!.text.getText() === 'Turn completed.', 'continued work stays in the saved conversation');
	await submitAssistantText(test, '/new');
	await until(() => model.state === 'ready' && model.thread === undefined && model.entries.length === 0, 'history: New clears local source and transcript authority');
	await submitAssistantText(test, 'Second saved conversation');
	await until(() => model.state === 'ready' && model.thread !== undefined, 'history: only the new explicit message creates a second thread');
	check(model.thread!.id !== thread, 'New changes actual native thread identity');
	await submitAssistantText(test, '/history');
	await until(() => picker.visible && picker.title === 'Codex history', 'history: both saved conversations remain available');
	check(picker.model.list.rows.length === 2, 'New never deletes previous history');
	await frame(); await renderer.capture!('two-conversations'); await press('Escape');
	check(test.cycles() === position && test.observations.suspended, 'conversation IO never releases ordinary Studio pause');
	await renderer.finish(); await ide.editor.shutdown();
	return { history: 'pass', source, frames: test.observations.hostFrames };
}
