export { runAssistantTestDebugger } from './studio_assistant_test_debugger';
export { runAssistantTestInspection } from './studio_assistant_test_inspection';
export { runAssistantDebugger } from './studio_assistant_debugger';
import { AssistantHttpConnection } from '../../../ide/browser/assistant_connection';
import { StudioHttpSession } from '../../../ide/browser/http_session';
import { getActiveTab } from '../../../ide/workbench/ui/tabs';
import { editorTabGroup } from '../../../ide/workbench/ui/tab/group_model';
import { problemsPanel } from '../../../ide/workbench/contrib/problems/panel/controller';
import { check, createStudioFixture } from './studio_fixture';
import { reachNemesisTitle } from './studio_nemesis_navigation';
import { createStudioRenderer, type StudioRendererKind } from './studio_renderer';

export { runAssistantAccount } from './studio_assistant_account';
export { runAssistantLogin } from './studio_assistant_login';
export { runAssistantTestEvidence } from './studio_assistant_test_evidence';
export { runAssistantTestExecution } from './studio_assistant_test_execution';
export { runAssistantHistory } from './studio_assistant_history';
export { runAssistantRuntime } from './studio_assistant_runtime';
export { runAssistantNavigation } from './studio_assistant_frame_navigation';
export { runAssistantTerminal } from './studio_assistant_terminal';
export { runAssistantStack } from './studio_assistant_stack';

/** Automated fixture setup; prompt, review and Undo use the production keyboard/pointer route. */
export async function runAssistant(kind: StudioRendererKind, canvas: HTMLCanvasElement, capture: (name: string) => Promise<void>, waitForModel: () => Promise<void>) {
	const renderer = await createStudioRenderer(kind, canvas, capture);
	const http = new StudioHttpSession();
	const test = await createStudioFixture(canvas, renderer.backend, renderer.capture, (signal, emit) => AssistantHttpConnection.open(http, signal, emit));
	capture = renderer.capture!;
	const { ide, runtime, frame, press, until, cycles, harness } = test;
	await until(() => cycles() > runtime.timing.cpuHz * 13, 'assistant: boot actual cart');
	await reachNemesisTitle(test);
	harness.openLuaSource('cart.lua'); await frame();
	const main = harness.getActiveEditorDocument().model, mainTab = getActiveTab();
	await press('ControlLeft', 'Home'); test.clipboard.text = '-- UNSAVED ASSISTANT FIXTURE\n'; await press('ControlLeft', 'KeyV');
	await press('ArrowDown'); // Keep module<entry> before the first executable statement.
	test.clipboard.text = 'local studio_diagnostic_probe = missing_from_assistant_context\n'; await press('ControlLeft', 'KeyV');
	const before = main.buffer.getText(), saved = main.lastSavedSource, media = ide.sources.currentBlua32Media;
	await test.runPaletteCommand('View: Codex Assistant');
	const view = getActiveTab();
	if (view.kind !== 'assistant') throw new Error('Assistant pane expected');
	const conversation = ide.editor.assistant;
	check(conversation.state === 'disconnected', 'opening a pane never starts the process or account');
	const position = cycles();
	for (let index = 0; index < 12; index++) await frame();
	check(cycles() === position && test.execution.paused && !test.execution.userPaused && test.observations.suspended,
		'assistant: ordinary workbench pause holds the guest and audio without a requested pause');
	await capture('disconnected');
	await test.click(view.composerBounds);
	test.clipboard.text = 'Read the unsaved Lua and authored YAML.'; await press('ControlLeft', 'KeyV');
	await press('Enter'); test.clipboard.text = 'Propose comments for review; do not save.'; await press('ControlLeft', 'KeyV');
	check(view.draft.lines.length === 2 && conversation.entries.length === 0, 'Enter is a newline, not submission');
	await press('ControlLeft', 'KeyZ'); check(view.draft.text.endsWith('\n'), 'composer Undo uses field history');
	await press('ControlLeft', 'KeyY');
	await frame(); await capture('composer');
	ide.editor.setFontVariant('msx'); await frame();
	check(view.turnActions.items.filter(item => item.visible).every(item => item.bounds.left >= 0), 'MSX font keeps message controls on screen');
	await capture('composer-msx');
	ide.editor.setFontVariant('tiny'); await frame();
	await press('ControlLeft', 'Enter');
	await until(() => conversation.entries.some(entry => entry.kind === 'proposal') && conversation.state === 'ready', 'assistant: real source tools return a review');
	check(cycles() === position && test.observations.suspended, 'assistant: model/tool progress continues while the game and audio stay paused');
	const proposal = conversation.entries.find(entry => entry.kind === 'proposal')!.proposal!;
	check(proposal.state === 'pending' && proposal.files.length === 2 && main.buffer.getText() === before, 'assistant cannot apply its own edits');
	const diagnostic = ide.diagnostics.diagnostics.find(marker => marker.model === main && marker.message.includes('missing_from_assistant_context'))!;
	check(diagnostic !== undefined && diagnostic.version === main.version, 'assistant diagnostics use the actual unsaved model result: ' + JSON.stringify({
		status: ide.diagnostics.get(main.identity)!.status, version: main.version,
		markers: ide.diagnostics.diagnostics.filter(marker => marker.model === main).map(marker => marker.message),
	}));
	await test.runPaletteCommand('View: Problems Panel');
	check(problemsPanel.isVisible && problemsPanel.getDiagnostics().includes(diagnostic), 'ordinary Problems shares the exact diagnostic owner');
	await frame(); await capture('shared-diagnostics');
	await test.runPaletteCommand('View: Problems Panel');
	await test.click(view.composerBounds);
	check(conversation.entries.some(entry => entry.kind === 'assistant' && entry.text.getText() === 'Contract fixture finished.'), 'real message reaches transcript');
	await frame(); const rows = view.transcript.rows.slice(); await frame();
	check(view.transcript.rows.every((row, index) => row === rows[index]), 'unchanged frames retain text layout');
	await capture('response');
	await press('Tab'); await press('Tab'); await press('ArrowDown'); await press('ControlLeft', 'KeyC');
	check(test.clipboard.text === 'Contract fixture finished.', 'transcript keyboard selects and copies an ordinary message');
	check(await navigator.clipboard.readText() === 'Contract fixture finished.', 'transcript Copy reaches the authorized browser clipboard');
	await press('ArrowUp');
	await test.clickTab(mainTab.id); await test.clickTab(view.id);
	check(conversation.state === 'ready' && proposal.state === 'pending', 'switching panes does not retire conversation/review');
	await test.click(view.turnActions.items.find(item => item.command === 'assistant.review')!.bounds);
	const review = getActiveTab(); if (review.kind !== 'workspace_edit_review') throw new Error('Shared review expected');
	await frame(); await capture('review');
	check(cycles() === position && !test.execution.userPaused, 'assistant: opening edit review never releases the workbench hold');
	await test.click(review.actionBar.items.find(item => item.command === 'workspaceEditReview.apply')!.bounds);
	check(proposal.state === 'applied' && main.buffer.getText().startsWith('-- Codex reviewed\n'), 'visible Apply edits ordinary model');
	check(main.lastSavedSource === saved && ide.sources.currentBlua32Media === media, 'Apply does not Save or install');
	await test.clickTab(mainTab.id); await press('ControlLeft', 'KeyZ');
	check(main.buffer.getText() === before && proposal.files[1].model.dirty === false, 'Lua Undo restores both Lua and YAML');
	await test.clickTab(view.id);
	check(view.transcript.rows.some(row => row.text === 'REVIEW: APPLIED'), 'Apply settles the transcript heading even while its pane was detached');
	await capture('applied');
	await test.click(view.composerBounds);
	test.clipboard.text = 'Wait so I can stop the response.'; await press('ControlLeft', 'KeyV');
	await press('ControlLeft', 'Enter'); await waitForModel(); await frame();
	check(conversation.state === 'running', 'second real model stream is still waiting');
	await test.click(view.turnActions.items.find(item => item.command === 'assistant.stop')!.bounds);
	await until(() => conversation.state === 'ready', 'assistant: Stop retires the actual provider wait');
	check(conversation.entries.at(-1)!.text.getText() === 'Turn interrupted.', 'Stop is not reported as successful completion');
	check(cycles() === position && test.observations.suspended, 'assistant: stopping Codex does not resume the game');
	await test.click(view.composerBounds);
	test.clipboard.text = 'Offer a new review so I can discard it.'; await press('ControlLeft', 'KeyV'); await press('ControlLeft', 'Enter');
	await until(() => conversation.state === 'ready' && conversation.entries.filter(entry => entry.kind === 'proposal').length === 2, 'assistant: new prompt has fresh source rights');
	const discarded = conversation.entries.filter(entry => entry.kind === 'proposal')[1].proposal!;
	await test.click(view.turnActions.items.find(item => item.command === 'assistant.review')!.bounds);
	const discardReview = getActiveTab(); if (discardReview.kind !== 'workspace_edit_review') throw new Error('Shared review expected');
	await test.click(discardReview.actionBar.items.find(item => item.command === 'workspaceEditReview.discard')!.bounds);
	await test.clickTab(view.id);
	check(discarded.state === 'discarded' && main.buffer.getText() === before, 'Discard settles without source changes');
	check(view.transcript.rows.some(row => row.text === 'REVIEW: DISCARDED'), 'Discard is visible in the retained conversation');
	await capture('discarded');
	await test.click(view.composerBounds);
	test.clipboard.text = 'Offer a review before I edit the source myself.'; await press('ControlLeft', 'KeyV'); await press('ControlLeft', 'Enter');
	await until(() => conversation.state === 'ready' && conversation.entries.filter(entry => entry.kind === 'proposal').length === 3, 'assistant: user source edit will invalidate a pending review');
	const stale = conversation.entries.filter(entry => entry.kind === 'proposal')[2].proposal!;
	await test.clickTab(mainTab.id); await press('ControlLeft', 'Home');
	test.clipboard.text = '-- Author correction\n'; await press('ControlLeft', 'KeyV');
	const corrected = main.buffer.getText();
	await test.clickTab(view.id);
	check(stale.state === 'stale' && view.transcript.rows.some(row => row.text === 'REVIEW: STALE'), 'source invalidation settles the transcript without a network event');
	await capture('stale');
	await test.click(view.turnActions.items.find(item => item.command === 'assistant.review')!.bounds);
	const staleReview = getActiveTab(); if (staleReview.kind !== 'workspace_edit_review') throw new Error('Shared review expected');
	await test.click(staleReview.actionBar.items.find(item => item.command === 'workspaceEditReview.apply')!.bounds);
	check(main.buffer.getText() === corrected, 'stale Apply is disabled rather than rebasing or replacing user edits');
	await test.clickTab(mainTab.id); await press('ControlLeft', 'KeyZ');
	check(main.buffer.getText() === before && stale.state === 'stale', 'source Undo cannot rearm retired edit rights');
	await test.clickTab(view.id); await test.click(view.composerBounds);
	test.clipboard.text = 'Offer one last review so I can close it.'; await press('ControlLeft', 'KeyV'); await press('ControlLeft', 'Enter');
	await until(() => conversation.state === 'ready' && conversation.entries.filter(entry => entry.kind === 'proposal').length === 4, 'assistant: final pending review before disconnect');
	const pending = conversation.entries.filter(entry => entry.kind === 'proposal')[3].proposal!;
	check(pending.state === 'pending', 'new review stays pending until user action');
	const serialized = editorTabGroup.serialize(ide.editor.editorInputSerializers);
	check(serialized.inputs.every(input => input.kind !== ('assistant' as string) && input.kind !== ('workspace_edit_review' as string)), 'session does not persist conversations or edit rights');
	await press('ControlLeft', 'KeyW'); check(conversation.state === 'disconnected' && pending.state === 'stale', 'closing the tab retires process and pending review');
	await test.runPaletteCommand('View: Codex Assistant');
	check(conversation.state === 'disconnected', 'reopening does not replay a prompt');
	await frame(); await capture('closed-reopened');
	check(cycles() === position && !test.execution.userPaused, 'assistant: pane switches and disconnect preserve the workbench pause');
	await press('ControlRight', 'ShiftRight');
	check(!ide.editor.isActive && !test.execution.paused, 'assistant: hiding Studio releases only its own pause reason');
	await until(() => cycles() > position, 'assistant: game resumes after hiding Studio');
	await press('ControlRight', 'ShiftRight');
	const returnedPosition = cycles();
	for (let index = 0; index < 12; index++) await frame();
	check(cycles() === returnedPosition && test.observations.suspended, 'assistant: reopening the retained assistant pane pauses again');
	await test.runMenuCommand('pause');
	check(test.execution.userPaused, 'assistant: independent user pause can be requested while Studio is open');
	await press('ControlRight', 'ShiftRight');
	for (let index = 0; index < 12; index++) await frame();
	check(cycles() === returnedPosition && test.execution.userPaused && test.observations.suspended,
		'assistant: hiding Studio must not clear the independent user pause');
	await renderer.finish();
	await ide.editor.shutdown();
	return { assistant: 'pass', sourceFiles: proposal.files.length, frames: test.observations.hostFrames };
}
