#pragma once

#include "machine/memory/map.h"

#include <array>

namespace bmsx {

/**
 * Runtime I/O memory layout constants.
 *
 * The runtime exposes a memory-mapped register bank.
 */

constexpr int IO_SYS_BASE_INDEX = 0;

constexpr int IO_SYS_HOST_FAULT_FLAGS_INDEX = IO_SYS_BASE_INDEX;
constexpr int IO_SYS_HOST_FAULT_STAGE_INDEX = IO_SYS_BASE_INDEX + 1;

constexpr int IO_SYS_SIZE = 2;
constexpr int IO_IRQ_BASE_INDEX = IO_SYS_BASE_INDEX + IO_SYS_SIZE;
constexpr int IO_IRQ_FLAGS_INDEX = IO_IRQ_BASE_INDEX;
constexpr int IO_IRQ_ACK_INDEX = IO_IRQ_BASE_INDEX + 1;
constexpr int IO_IRQ_MASK_INDEX = IO_IRQ_BASE_INDEX + 2;
constexpr int IO_IRQ_SIZE = 3;

constexpr int IO_DMA_BASE_INDEX = IO_IRQ_BASE_INDEX + IO_IRQ_SIZE;
constexpr int IO_DMA_READ_ADDR_INDEX = IO_DMA_BASE_INDEX;
constexpr int IO_DMA_WRITE_ADDR_INDEX = IO_DMA_BASE_INDEX + 1;
constexpr int IO_DMA_TRANSFER_COUNT_INDEX = IO_DMA_BASE_INDEX + 2;
constexpr int IO_DMA_CONTROL_INDEX = IO_DMA_BASE_INDEX + 3;
constexpr int IO_DMA_STATUS_INDEX = IO_DMA_BASE_INDEX + 4;
constexpr int IO_DMA_TRIGGER_INDEX = IO_DMA_BASE_INDEX + 5;
constexpr int IO_DMA_SIZE = 6;

constexpr int IO_GEO_BASE_INDEX = IO_DMA_BASE_INDEX + IO_DMA_SIZE;
constexpr int IO_GEO_SRC0_INDEX = IO_GEO_BASE_INDEX;
constexpr int IO_GEO_SRC1_INDEX = IO_GEO_BASE_INDEX + 1;
constexpr int IO_GEO_SRC2_INDEX = IO_GEO_BASE_INDEX + 2;
constexpr int IO_GEO_DST0_INDEX = IO_GEO_BASE_INDEX + 3;
constexpr int IO_GEO_DST1_INDEX = IO_GEO_BASE_INDEX + 4;
constexpr int IO_GEO_COUNT_INDEX = IO_GEO_BASE_INDEX + 5;
constexpr int IO_GEO_CMD_INDEX = IO_GEO_BASE_INDEX + 6;
constexpr int IO_GEO_CTRL_INDEX = IO_GEO_BASE_INDEX + 7;
constexpr int IO_GEO_STATUS_INDEX = IO_GEO_BASE_INDEX + 8;
constexpr int IO_GEO_PARAM0_INDEX = IO_GEO_BASE_INDEX + 9;
constexpr int IO_GEO_PARAM1_INDEX = IO_GEO_BASE_INDEX + 10;
constexpr int IO_GEO_STRIDE0_INDEX = IO_GEO_BASE_INDEX + 11;
constexpr int IO_GEO_STRIDE1_INDEX = IO_GEO_BASE_INDEX + 12;
constexpr int IO_GEO_STRIDE2_INDEX = IO_GEO_BASE_INDEX + 13;
constexpr int IO_GEO_PROCESSED_INDEX = IO_GEO_BASE_INDEX + 14;
constexpr int IO_GEO_FAULT_INDEX = IO_GEO_BASE_INDEX + 15;
constexpr int IO_GEO_SIZE = 16;

constexpr int IO_INP_BASE_INDEX = IO_GEO_BASE_INDEX + IO_GEO_SIZE;
constexpr int IO_INP_CTRL_INDEX = IO_INP_BASE_INDEX;
constexpr int IO_INP_STATUS_INDEX = IO_INP_BASE_INDEX + 1;
constexpr int IO_INP_KEYS_INDEX = IO_INP_BASE_INDEX + 2;
constexpr int IO_INP_KEY_WORD_COUNT = 8;
constexpr int IO_INP_POINTER_BUTTONS_INDEX = IO_INP_KEYS_INDEX + IO_INP_KEY_WORD_COUNT;
constexpr int IO_INP_POINTER_X_INDEX = IO_INP_POINTER_BUTTONS_INDEX + 1;
constexpr int IO_INP_POINTER_Y_INDEX = IO_INP_POINTER_BUTTONS_INDEX + 2;
constexpr int IO_INP_POINTER_WHEEL_INDEX = IO_INP_POINTER_BUTTONS_INDEX + 3;
constexpr int IO_INP_PADS_INDEX = IO_INP_POINTER_BUTTONS_INDEX + 4;
constexpr int IO_INP_PAD_COUNT = 4;
constexpr int IO_INP_PAD_WORD_COUNT = 7; // buttons, lx, ly, rx, ry, lt, rt
constexpr int IO_INP_OUTPUT_PORT_INDEX = IO_INP_PADS_INDEX + IO_INP_PAD_COUNT * IO_INP_PAD_WORD_COUNT;
constexpr int IO_INP_OUTPUT_INTENSITY_Q16_INDEX = IO_INP_OUTPUT_PORT_INDEX + 1;
constexpr int IO_INP_OUTPUT_DURATION_MS_INDEX = IO_INP_OUTPUT_PORT_INDEX + 2;
constexpr int IO_INP_OUTPUT_STATUS_INDEX = IO_INP_OUTPUT_PORT_INDEX + 3;
constexpr int IO_INP_OUTPUT_CTRL_INDEX = IO_INP_OUTPUT_PORT_INDEX + 4;
constexpr int IO_INP_SIZE = IO_INP_OUTPUT_CTRL_INDEX - IO_INP_BASE_INDEX + 1;

constexpr int IO_APU_BASE_INDEX = IO_INP_BASE_INDEX + IO_INP_SIZE;
constexpr int IO_APU_SOURCE_ADDR_INDEX = IO_APU_BASE_INDEX;
constexpr int IO_APU_SOURCE_BYTES_INDEX = IO_APU_BASE_INDEX + 1;
constexpr int IO_APU_SOURCE_SAMPLE_RATE_HZ_INDEX = IO_APU_BASE_INDEX + 2;
constexpr int IO_APU_SOURCE_CHANNELS_INDEX = IO_APU_BASE_INDEX + 3;
constexpr int IO_APU_SOURCE_BITS_PER_SAMPLE_INDEX = IO_APU_BASE_INDEX + 4;
constexpr int IO_APU_SOURCE_FRAME_COUNT_INDEX = IO_APU_BASE_INDEX + 5;
constexpr int IO_APU_SOURCE_DATA_OFFSET_INDEX = IO_APU_BASE_INDEX + 6;
constexpr int IO_APU_SOURCE_DATA_BYTES_INDEX = IO_APU_BASE_INDEX + 7;
constexpr int IO_APU_SOURCE_LOOP_START_SAMPLE_INDEX = IO_APU_BASE_INDEX + 8;
constexpr int IO_APU_SOURCE_LOOP_END_SAMPLE_INDEX = IO_APU_BASE_INDEX + 9;
constexpr int IO_APU_SLOT_INDEX = IO_APU_BASE_INDEX + 10;
constexpr int IO_APU_RATE_STEP_Q16_INDEX = IO_APU_BASE_INDEX + 11;
constexpr int IO_APU_GAIN_Q12_INDEX = IO_APU_BASE_INDEX + 12;
constexpr int IO_APU_START_SAMPLE_INDEX = IO_APU_BASE_INDEX + 13;
constexpr int IO_APU_FILTER_KIND_INDEX = IO_APU_BASE_INDEX + 14;
constexpr int IO_APU_FILTER_FREQ_HZ_INDEX = IO_APU_BASE_INDEX + 15;
constexpr int IO_APU_FILTER_Q_MILLI_INDEX = IO_APU_BASE_INDEX + 16;
constexpr int IO_APU_FILTER_GAIN_MILLIDB_INDEX = IO_APU_BASE_INDEX + 17;
constexpr int IO_APU_FADE_SAMPLES_INDEX = IO_APU_BASE_INDEX + 18;
constexpr int IO_APU_GENERATOR_KIND_INDEX = IO_APU_BASE_INDEX + 19;
constexpr int IO_APU_GENERATOR_DUTY_Q12_INDEX = IO_APU_BASE_INDEX + 20;
constexpr int IO_APU_CMD_INDEX = IO_APU_BASE_INDEX + 21;
constexpr int IO_APU_STATUS_INDEX = IO_APU_BASE_INDEX + 22;
constexpr int IO_APU_EVENT_KIND_INDEX = IO_APU_BASE_INDEX + 23;
constexpr int IO_APU_EVENT_SLOT_INDEX = IO_APU_BASE_INDEX + 24;
constexpr int IO_APU_EVENT_SOURCE_ADDR_INDEX = IO_APU_BASE_INDEX + 25;
constexpr int IO_APU_EVENT_SEQ_INDEX = IO_APU_BASE_INDEX + 26;
constexpr int IO_APU_SELECTED_SOURCE_ADDR_INDEX = IO_APU_BASE_INDEX + 27;
constexpr int IO_APU_ACTIVE_MASK_INDEX = IO_APU_BASE_INDEX + 28;
constexpr int IO_APU_SELECTED_SLOT_REG0_INDEX = IO_APU_BASE_INDEX + 29;
constexpr int IO_APU_SELECTED_SLOT_REG_COUNT = 21;
constexpr int IO_APU_OUTPUT_QUEUED_FRAMES_INDEX = IO_APU_SELECTED_SLOT_REG0_INDEX + IO_APU_SELECTED_SLOT_REG_COUNT;
constexpr int IO_APU_OUTPUT_FREE_FRAMES_INDEX = IO_APU_OUTPUT_QUEUED_FRAMES_INDEX + 1;
constexpr int IO_APU_OUTPUT_CAPACITY_FRAMES_INDEX = IO_APU_OUTPUT_FREE_FRAMES_INDEX + 1;
constexpr int IO_APU_CMD_QUEUED_INDEX = IO_APU_OUTPUT_CAPACITY_FRAMES_INDEX + 1;
constexpr int IO_APU_CMD_FREE_INDEX = IO_APU_CMD_QUEUED_INDEX + 1;
constexpr int IO_APU_CMD_CAPACITY_INDEX = IO_APU_CMD_FREE_INDEX + 1;
constexpr int IO_APU_SIZE = IO_APU_CMD_CAPACITY_INDEX - IO_APU_BASE_INDEX + 1;

constexpr int IO_PAYLOAD_WRITE_PTR_INDEX = IO_APU_BASE_INDEX + IO_APU_SIZE;
constexpr int IO_PAYLOAD_BUFFER_BASE_INDEX = IO_PAYLOAD_WRITE_PTR_INDEX + 1;
constexpr int IO_PAYLOAD_CAPACITY = 16384;

constexpr int IO_SYS_BUS_FAULT_CODE_INDEX = IO_PAYLOAD_BUFFER_BASE_INDEX + IO_PAYLOAD_CAPACITY;
constexpr int IO_SYS_BUS_FAULT_ADDR_INDEX = IO_SYS_BUS_FAULT_CODE_INDEX + 1;
constexpr int IO_SYS_BUS_FAULT_ACCESS_INDEX = IO_SYS_BUS_FAULT_CODE_INDEX + 2;
constexpr int IO_SYS_BUS_FAULT_ACK_INDEX = IO_SYS_BUS_FAULT_CODE_INDEX + 3;
constexpr int IO_APU_FAULT_CODE_INDEX = IO_SYS_BUS_FAULT_ACK_INDEX + 1;
constexpr int IO_APU_FAULT_DETAIL_INDEX = IO_APU_FAULT_CODE_INDEX + 1;
constexpr int IO_APU_FAULT_ACK_INDEX = IO_APU_FAULT_CODE_INDEX + 2;
constexpr int IO_GEO_FAULT_ACK_INDEX = IO_APU_FAULT_ACK_INDEX + 1;
constexpr int IO_SYS_TIME_MS_INDEX = IO_GEO_FAULT_ACK_INDEX + 1;
constexpr int IO_SYS_FRAME_MS_INDEX = IO_SYS_TIME_MS_INDEX + 1;
constexpr int IO_SYS_PRINT_CHAR_INDEX = IO_SYS_FRAME_MS_INDEX + 1;
constexpr int IO_SYS_PRINT_FLUSH_INDEX = IO_SYS_PRINT_CHAR_INDEX + 1;
constexpr int IO_SYS_CYCLES_PER_FRAME_INDEX = IO_SYS_PRINT_FLUSH_INDEX + 1;
constexpr int IO_GX_GPU_GP0_INDEX = IO_SYS_CYCLES_PER_FRAME_INDEX + 1;
constexpr int IO_GX_GPU_GP1_INDEX = IO_GX_GPU_GP0_INDEX + 1;
constexpr int IO_GX_GTE_DATA0_INDEX = IO_GX_GPU_GP1_INDEX + 1;
constexpr int IO_GX_GTE_DATA_REGISTER_COUNT = 32;
constexpr int IO_GX_GTE_CONTROL0_INDEX = IO_GX_GTE_DATA0_INDEX + IO_GX_GTE_DATA_REGISTER_COUNT;
constexpr int IO_GX_GTE_CONTROL_REGISTER_COUNT = 32;
constexpr int IO_GX_GTE_COMMAND_INDEX = IO_GX_GTE_CONTROL0_INDEX + IO_GX_GTE_CONTROL_REGISTER_COUNT;
constexpr int IO_GX_GTE_CYCLES_INDEX = IO_GX_GTE_COMMAND_INDEX + 1;
constexpr int IO_SYS_CONTROL_INDEX = IO_GX_GTE_CYCLES_INDEX + 1;
constexpr int IO_SLOT_COUNT = IO_SYS_CONTROL_INDEX + 1;

constexpr uint32_t IO_ARG_STRIDE = IO_WORD_SIZE;
constexpr uint32_t IO_PAYLOAD_WRITE_PTR_ADDR = IO_BASE + IO_PAYLOAD_WRITE_PTR_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_PAYLOAD_BUFFER_BASE = IO_BASE + IO_PAYLOAD_BUFFER_BASE_INDEX * IO_WORD_SIZE;

constexpr uint32_t IO_SYS_BASE = IO_BASE + IO_SYS_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_HOST_FAULT_FLAGS = IO_BASE + IO_SYS_HOST_FAULT_FLAGS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_HOST_FAULT_STAGE = IO_BASE + IO_SYS_HOST_FAULT_STAGE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_TIME_MS = IO_BASE + IO_SYS_TIME_MS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_FRAME_MS = IO_BASE + IO_SYS_FRAME_MS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_PRINT_CHAR = IO_BASE + IO_SYS_PRINT_CHAR_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_PRINT_FLUSH = IO_BASE + IO_SYS_PRINT_FLUSH_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_CYCLES_PER_FRAME = IO_BASE + IO_SYS_CYCLES_PER_FRAME_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GX_GPU_GP0 = IO_BASE + IO_GX_GPU_GP0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GX_GPU_GP1 = IO_BASE + IO_GX_GPU_GP1_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GX_GTE_DATA0 = IO_BASE + IO_GX_GTE_DATA0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GX_GTE_CONTROL0 = IO_BASE + IO_GX_GTE_CONTROL0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GX_GTE_COMMAND = IO_BASE + IO_GX_GTE_COMMAND_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GX_GTE_CYCLES = IO_BASE + IO_GX_GTE_CYCLES_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_CONTROL = IO_BASE + IO_SYS_CONTROL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_BUS_FAULT_CODE = IO_BASE + IO_SYS_BUS_FAULT_CODE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_BUS_FAULT_ADDR = IO_BASE + IO_SYS_BUS_FAULT_ADDR_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_BUS_FAULT_ACCESS = IO_BASE + IO_SYS_BUS_FAULT_ACCESS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_BUS_FAULT_ACK = IO_BASE + IO_SYS_BUS_FAULT_ACK_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IRQ_BASE = IO_BASE + IO_IRQ_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IRQ_FLAGS = IO_BASE + IO_IRQ_FLAGS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IRQ_ACK = IO_BASE + IO_IRQ_ACK_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IRQ_MASK = IO_BASE + IO_IRQ_MASK_INDEX * IO_WORD_SIZE;

constexpr uint32_t IO_DMA_BASE = IO_BASE + IO_DMA_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_READ_ADDR = IO_BASE + IO_DMA_READ_ADDR_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_WRITE_ADDR = IO_BASE + IO_DMA_WRITE_ADDR_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_TRANSFER_COUNT = IO_BASE + IO_DMA_TRANSFER_COUNT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_CONTROL = IO_BASE + IO_DMA_CONTROL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_STATUS = IO_BASE + IO_DMA_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_TRIGGER = IO_BASE + IO_DMA_TRIGGER_INDEX * IO_WORD_SIZE;

constexpr uint32_t IO_GEO_BASE = IO_BASE + IO_GEO_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_SRC0 = IO_BASE + IO_GEO_SRC0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_SRC1 = IO_BASE + IO_GEO_SRC1_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_SRC2 = IO_BASE + IO_GEO_SRC2_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_DST0 = IO_BASE + IO_GEO_DST0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_DST1 = IO_BASE + IO_GEO_DST1_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_COUNT = IO_BASE + IO_GEO_COUNT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_CMD = IO_BASE + IO_GEO_CMD_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_CTRL = IO_BASE + IO_GEO_CTRL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_STATUS = IO_BASE + IO_GEO_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_PARAM0 = IO_BASE + IO_GEO_PARAM0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_PARAM1 = IO_BASE + IO_GEO_PARAM1_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_STRIDE0 = IO_BASE + IO_GEO_STRIDE0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_STRIDE1 = IO_BASE + IO_GEO_STRIDE1_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_STRIDE2 = IO_BASE + IO_GEO_STRIDE2_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_PROCESSED = IO_BASE + IO_GEO_PROCESSED_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_FAULT = IO_BASE + IO_GEO_FAULT_INDEX * IO_WORD_SIZE;
constexpr std::array<uint32_t, IO_GEO_SIZE> IO_GEO_REGISTER_ADDRS = {
	IO_GEO_SRC0,
	IO_GEO_SRC1,
	IO_GEO_SRC2,
	IO_GEO_DST0,
	IO_GEO_DST1,
	IO_GEO_COUNT,
	IO_GEO_CMD,
	IO_GEO_CTRL,
	IO_GEO_STATUS,
	IO_GEO_PARAM0,
	IO_GEO_PARAM1,
	IO_GEO_STRIDE0,
	IO_GEO_STRIDE1,
	IO_GEO_STRIDE2,
	IO_GEO_PROCESSED,
	IO_GEO_FAULT,
};
constexpr uint32_t IO_GEO_FAULT_ACK = IO_BASE + IO_GEO_FAULT_ACK_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_BASE = IO_BASE + IO_INP_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_CTRL = IO_BASE + IO_INP_CTRL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_STATUS = IO_BASE + IO_INP_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_KEYS = IO_BASE + IO_INP_KEYS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_POINTER_BUTTONS = IO_BASE + IO_INP_POINTER_BUTTONS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_POINTER_X = IO_BASE + IO_INP_POINTER_X_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_POINTER_Y = IO_BASE + IO_INP_POINTER_Y_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_POINTER_WHEEL = IO_BASE + IO_INP_POINTER_WHEEL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_PADS = IO_BASE + IO_INP_PADS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_PAD_STRIDE = IO_INP_PAD_WORD_COUNT * IO_WORD_SIZE;
constexpr uint32_t IO_INP_PAD_BUTTONS_OFFSET = 0 * IO_WORD_SIZE;
constexpr uint32_t IO_INP_PAD_LX_OFFSET = 1 * IO_WORD_SIZE;
constexpr uint32_t IO_INP_PAD_LY_OFFSET = 2 * IO_WORD_SIZE;
constexpr uint32_t IO_INP_PAD_RX_OFFSET = 3 * IO_WORD_SIZE;
constexpr uint32_t IO_INP_PAD_RY_OFFSET = 4 * IO_WORD_SIZE;
constexpr uint32_t IO_INP_PAD_LT_OFFSET = 5 * IO_WORD_SIZE;
constexpr uint32_t IO_INP_PAD_RT_OFFSET = 6 * IO_WORD_SIZE;
constexpr uint32_t IO_INP_OUTPUT_PORT = IO_BASE + IO_INP_OUTPUT_PORT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_OUTPUT_INTENSITY_Q16 = IO_BASE + IO_INP_OUTPUT_INTENSITY_Q16_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_OUTPUT_DURATION_MS = IO_BASE + IO_INP_OUTPUT_DURATION_MS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_OUTPUT_STATUS = IO_BASE + IO_INP_OUTPUT_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_OUTPUT_CTRL = IO_BASE + IO_INP_OUTPUT_CTRL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_BASE = IO_BASE + IO_APU_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_ADDR = IO_BASE + IO_APU_SOURCE_ADDR_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_BYTES = IO_BASE + IO_APU_SOURCE_BYTES_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_SAMPLE_RATE_HZ = IO_BASE + IO_APU_SOURCE_SAMPLE_RATE_HZ_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_CHANNELS = IO_BASE + IO_APU_SOURCE_CHANNELS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_BITS_PER_SAMPLE = IO_BASE + IO_APU_SOURCE_BITS_PER_SAMPLE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_FRAME_COUNT = IO_BASE + IO_APU_SOURCE_FRAME_COUNT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_DATA_OFFSET = IO_BASE + IO_APU_SOURCE_DATA_OFFSET_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_DATA_BYTES = IO_BASE + IO_APU_SOURCE_DATA_BYTES_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_LOOP_START_SAMPLE = IO_BASE + IO_APU_SOURCE_LOOP_START_SAMPLE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_LOOP_END_SAMPLE = IO_BASE + IO_APU_SOURCE_LOOP_END_SAMPLE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SLOT = IO_BASE + IO_APU_SLOT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_RATE_STEP_Q16 = IO_BASE + IO_APU_RATE_STEP_Q16_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_GAIN_Q12 = IO_BASE + IO_APU_GAIN_Q12_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_START_SAMPLE = IO_BASE + IO_APU_START_SAMPLE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FILTER_KIND = IO_BASE + IO_APU_FILTER_KIND_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FILTER_FREQ_HZ = IO_BASE + IO_APU_FILTER_FREQ_HZ_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FILTER_Q_MILLI = IO_BASE + IO_APU_FILTER_Q_MILLI_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FILTER_GAIN_MILLIDB = IO_BASE + IO_APU_FILTER_GAIN_MILLIDB_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FADE_SAMPLES = IO_BASE + IO_APU_FADE_SAMPLES_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_GENERATOR_KIND = IO_BASE + IO_APU_GENERATOR_KIND_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_GENERATOR_DUTY_Q12 = IO_BASE + IO_APU_GENERATOR_DUTY_Q12_INDEX * IO_WORD_SIZE;
constexpr std::array<uint32_t, IO_APU_SELECTED_SLOT_REG_COUNT> IO_APU_PARAMETER_REGISTER_ADDRS = {
	IO_APU_SOURCE_ADDR,
	IO_APU_SOURCE_BYTES,
	IO_APU_SOURCE_SAMPLE_RATE_HZ,
	IO_APU_SOURCE_CHANNELS,
	IO_APU_SOURCE_BITS_PER_SAMPLE,
	IO_APU_SOURCE_FRAME_COUNT,
	IO_APU_SOURCE_DATA_OFFSET,
	IO_APU_SOURCE_DATA_BYTES,
	IO_APU_SOURCE_LOOP_START_SAMPLE,
	IO_APU_SOURCE_LOOP_END_SAMPLE,
	IO_APU_SLOT,
	IO_APU_RATE_STEP_Q16,
	IO_APU_GAIN_Q12,
	IO_APU_START_SAMPLE,
	IO_APU_FILTER_KIND,
	IO_APU_FILTER_FREQ_HZ,
	IO_APU_FILTER_Q_MILLI,
	IO_APU_FILTER_GAIN_MILLIDB,
	IO_APU_FADE_SAMPLES,
	IO_APU_GENERATOR_KIND,
	IO_APU_GENERATOR_DUTY_Q12,
};
constexpr uint32_t IO_APU_CMD = IO_BASE + IO_APU_CMD_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_STATUS = IO_BASE + IO_APU_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FAULT_CODE = IO_BASE + IO_APU_FAULT_CODE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FAULT_DETAIL = IO_BASE + IO_APU_FAULT_DETAIL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FAULT_ACK = IO_BASE + IO_APU_FAULT_ACK_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_EVENT_KIND = IO_BASE + IO_APU_EVENT_KIND_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_EVENT_SLOT = IO_BASE + IO_APU_EVENT_SLOT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_EVENT_SOURCE_ADDR = IO_BASE + IO_APU_EVENT_SOURCE_ADDR_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_EVENT_SEQ = IO_BASE + IO_APU_EVENT_SEQ_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SELECTED_SOURCE_ADDR = IO_BASE + IO_APU_SELECTED_SOURCE_ADDR_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_ACTIVE_MASK = IO_BASE + IO_APU_ACTIVE_MASK_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SELECTED_SLOT_REG0 = IO_BASE + IO_APU_SELECTED_SLOT_REG0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_OUTPUT_QUEUED_FRAMES = IO_BASE + IO_APU_OUTPUT_QUEUED_FRAMES_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_OUTPUT_FREE_FRAMES = IO_BASE + IO_APU_OUTPUT_FREE_FRAMES_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_OUTPUT_CAPACITY_FRAMES = IO_BASE + IO_APU_OUTPUT_CAPACITY_FRAMES_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_CMD_QUEUED = IO_BASE + IO_APU_CMD_QUEUED_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_CMD_FREE = IO_BASE + IO_APU_CMD_FREE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_CMD_CAPACITY = IO_BASE + IO_APU_CMD_CAPACITY_INDEX * IO_WORD_SIZE;

constexpr uint32_t IRQ_DMA_DONE = 1 << 0;
constexpr uint32_t IRQ_RESERVED_1 = 1 << 1;
constexpr uint32_t IRQ_VBLANK = 1 << 2;
constexpr uint32_t IRQ_GEO_DONE = 1 << 3;
constexpr uint32_t IRQ_GEO_ERROR = 1 << 4;
constexpr uint32_t IRQ_APU = 1 << 5;
constexpr uint32_t IRQ_GPU = 1 << 6;


constexpr uint32_t DMA_CONTROL_READ_INCREMENT = 1u << 0u;
constexpr uint32_t DMA_CONTROL_WRITE_INCREMENT = 1u << 1u;
constexpr uint32_t DMA_CONTROL_REQUEST_SHIFT = 2u;
constexpr uint32_t DMA_CONTROL_REQUEST_MASK = 0x3u << DMA_CONTROL_REQUEST_SHIFT;
constexpr uint32_t DMA_CONTROL_REQUEST_FORCE = 0u << DMA_CONTROL_REQUEST_SHIFT;
constexpr uint32_t DMA_CONTROL_REQUEST_GX_WRITE = 1u << DMA_CONTROL_REQUEST_SHIFT;
constexpr uint32_t DMA_CONTROL_REQUEST_GX_READ = 2u << DMA_CONTROL_REQUEST_SHIFT;
constexpr uint32_t DMA_CONTROL_REQUEST_DISABLED = 3u << DMA_CONTROL_REQUEST_SHIFT;
constexpr uint32_t DMA_STATUS_BUSY = 1 << 0;
constexpr uint32_t DMA_STATUS_DONE = 1 << 1;
constexpr uint32_t DMA_TRIGGER_START = 1u << 0u;

constexpr uint32_t HOST_FAULT_FLAG_ACTIVE = 1u << 0u;
constexpr uint32_t HOST_FAULT_FLAG_STARTUP_BLOCKING = 1u << 1u;
constexpr uint32_t HOST_FAULT_STAGE_NONE = 0u;
constexpr uint32_t HOST_FAULT_STAGE_STARTUP_AUDIO_REFRESH = 1u;

constexpr uint32_t BUS_FAULT_NONE = 0u;
constexpr uint32_t BUS_FAULT_UNMAPPED = 1u;
constexpr uint32_t BUS_FAULT_UNALIGNED_IO = 2u;
constexpr uint32_t BUS_FAULT_READ_ONLY = 3u;
constexpr uint32_t BUS_FAULT_ACCESS_READ = 1u << 0u;
constexpr uint32_t BUS_FAULT_ACCESS_WRITE = 1u << 1u;
constexpr uint32_t BUS_FAULT_ACCESS_U8 = 1u << 8u;
constexpr uint32_t BUS_FAULT_ACCESS_U16 = 1u << 9u;
constexpr uint32_t BUS_FAULT_ACCESS_U32 = 1u << 10u;
constexpr uint32_t BUS_FAULT_ACCESS_WORD = 1u << 11u;
constexpr uint32_t BUS_FAULT_ACCESS_F32 = 1u << 12u;
constexpr uint32_t BUS_FAULT_ACCESS_F64 = 1u << 13u;

constexpr uint32_t INP_CTRL_ARM = 1u;
constexpr uint32_t INP_CTRL_RESET = 2u;
constexpr uint32_t SYS_CONTROL_RESET = 1u;

} // namespace bmsx
