set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7-a)

get_filename_component(BMSX_REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../../../.." ABSOLUTE)
set(BMSX_SNESMINI_SDK_SYSROOT "${BMSX_REPO_ROOT}/.snesmini/sdk-sysroot")
set(BMSX_SNESMINI_TARGET_TRIPLE "arm-linux-gnueabihf")

execute_process(
	COMMAND python3 "${BMSX_REPO_ROOT}/scripts/snesmini/sdk_recipe_id.py" "${BMSX_REPO_ROOT}"
	OUTPUT_VARIABLE BMSX_SNESMINI_EXPECTED_SDK_ID
	OUTPUT_STRIP_TRAILING_WHITESPACE
	RESULT_VARIABLE BMSX_SNESMINI_RECIPE_RESULT
)
if(NOT BMSX_SNESMINI_RECIPE_RESULT EQUAL 0)
	message(FATAL_ERROR "Could not calculate the SNES Mini SDK recipe identity.")
endif()
file(READ "${BMSX_SNESMINI_SDK_SYSROOT}/.bmsx-snesmini-sdk" BMSX_SNESMINI_SDK_ID)
string(STRIP "${BMSX_SNESMINI_SDK_ID}" BMSX_SNESMINI_SDK_ID)
set(BMSX_SNESMINI_EXPECTED_SDK_MARKER
	"${BMSX_SNESMINI_EXPECTED_SDK_ID} $ENV{BMSX_SNESMINI_BUILDER_IMAGE_ID}")
if(NOT BMSX_SNESMINI_SDK_ID STREQUAL BMSX_SNESMINI_EXPECTED_SDK_MARKER)
	message(FATAL_ERROR "SNES Mini SDK sysroot is not prepared. Run npm run setup:snesmini.")
endif()

set(CMAKE_SYSROOT "${BMSX_SNESMINI_SDK_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${BMSX_SNESMINI_SDK_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY FALSE)
set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY FALSE)

set(CMAKE_C_COMPILER "${BMSX_SNESMINI_TARGET_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${BMSX_SNESMINI_TARGET_TRIPLE}-g++")
set(CMAKE_AR "${BMSX_SNESMINI_TARGET_TRIPLE}-ar")
set(CMAKE_RANLIB "${BMSX_SNESMINI_TARGET_TRIPLE}-ranlib")
set(CMAKE_STRIP "${BMSX_SNESMINI_TARGET_TRIPLE}-strip")

execute_process(
	COMMAND "${BMSX_SNESMINI_TARGET_TRIPLE}-gcc" -print-libgcc-file-name
	OUTPUT_VARIABLE BMSX_SNESMINI_LIBGCC
	OUTPUT_STRIP_TRAILING_WHITESPACE
	RESULT_VARIABLE BMSX_SNESMINI_COMPILER_RESULT
)
if(NOT BMSX_SNESMINI_COMPILER_RESULT EQUAL 0)
	message(FATAL_ERROR "The SNES Mini ARM compiler is not available.")
endif()
get_filename_component(BMSX_SNESMINI_GCC_DIR "${BMSX_SNESMINI_LIBGCC}" DIRECTORY)
set(BMSX_SNESMINI_CXX_ROOT "${BMSX_SNESMINI_SDK_SYSROOT}/opt/bmsx-snesmini-cxx")
set(BMSX_SNESMINI_CXX_INCLUDE "${BMSX_SNESMINI_CXX_ROOT}/include/c++/10.2.0")
set(BMSX_SNESMINI_CXX_LIB "${BMSX_SNESMINI_CXX_ROOT}/lib")
set(BMSX_SNESMINI_GCC_INCLUDE "${BMSX_SNESMINI_GCC_DIR}/include")
set(BMSX_SNESMINI_SDK_INCLUDE
	"${BMSX_SNESMINI_SDK_SYSROOT}/usr/include/${BMSX_SNESMINI_TARGET_TRIPLE}")
set(BMSX_SNESMINI_SDK_USR_INCLUDE "${BMSX_SNESMINI_SDK_SYSROOT}/usr/include")
set(BMSX_SNESMINI_SDK_LIB
	"${BMSX_SNESMINI_SDK_SYSROOT}/lib/${BMSX_SNESMINI_TARGET_TRIPLE}")
set(BMSX_SNESMINI_SDK_USR_LIB
	"${BMSX_SNESMINI_SDK_SYSROOT}/usr/lib/${BMSX_SNESMINI_TARGET_TRIPLE}")

string(CONCAT BMSX_SNESMINI_C_FLAGS
	"-nostdinc "
	"-isystem ${BMSX_SNESMINI_GCC_INCLUDE} "
	"-isystem ${BMSX_SNESMINI_SDK_INCLUDE} "
	"-isystem ${BMSX_SNESMINI_SDK_USR_INCLUDE}")
string(CONCAT BMSX_SNESMINI_CXX_FLAGS
	"-nostdinc -nostdinc++ "
	"-isystem ${BMSX_SNESMINI_CXX_INCLUDE} "
	"-isystem ${BMSX_SNESMINI_CXX_INCLUDE}/${BMSX_SNESMINI_TARGET_TRIPLE} "
	"-isystem ${BMSX_SNESMINI_CXX_INCLUDE}/backward "
	"-isystem ${BMSX_SNESMINI_GCC_INCLUDE} "
	"-isystem ${BMSX_SNESMINI_SDK_INCLUDE} "
	"-isystem ${BMSX_SNESMINI_SDK_USR_INCLUDE}")
string(CONCAT BMSX_SNESMINI_LINK_FLAGS
	"-B${BMSX_SNESMINI_CXX_LIB}/ "
	"-L${BMSX_SNESMINI_CXX_LIB} "
	"-B${BMSX_SNESMINI_SDK_USR_LIB}/ "
	"-B${BMSX_SNESMINI_SDK_LIB}/ "
	"-L${BMSX_SNESMINI_SDK_USR_LIB} "
	"-L${BMSX_SNESMINI_SDK_LIB} "
	"-Wl,-rpath-link,${BMSX_SNESMINI_SDK_USR_LIB} "
	"-Wl,-rpath-link,${BMSX_SNESMINI_SDK_LIB}")

set(CMAKE_C_FLAGS "${BMSX_SNESMINI_C_FLAGS}" CACHE STRING "SNES Mini C flags" FORCE)
set(CMAKE_CXX_FLAGS "${BMSX_SNESMINI_CXX_FLAGS}" CACHE STRING "SNES Mini C++ flags" FORCE)
set(CMAKE_EXE_LINKER_FLAGS "${BMSX_SNESMINI_LINK_FLAGS}" CACHE STRING "SNES Mini executable linker flags" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "${BMSX_SNESMINI_LINK_FLAGS}" CACHE STRING "SNES Mini shared-library linker flags" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS "${BMSX_SNESMINI_LINK_FLAGS}" CACHE STRING "SNES Mini module linker flags" FORCE)

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${BMSX_SNESMINI_SDK_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR}
	"${BMSX_SNESMINI_SDK_USR_LIB}/pkgconfig:${BMSX_SNESMINI_SDK_SYSROOT}/usr/share/pkgconfig")

set(BMSX_SNESMINI_TARGET ON CACHE BOOL "Build for the SNES Mini runtime" FORCE)
