export const GX_GPU_GP1_RESET = 0x00;
export const GX_GPU_GP1_CLEAR_FIFO = 0x01;
export const GX_GPU_GP1_ACK_INTERRUPT = 0x02;
export const GX_GPU_GP1_DISPLAY_DISABLE = 0x03;
export const GX_GPU_GP1_DMA_DIRECTION = 0x04;
export const GX_GPU_GP1_DISPLAY_START = 0x05;
export const GX_GPU_GP1_HORIZONTAL_DISPLAY_RANGE = 0x06;
export const GX_GPU_GP1_VERTICAL_DISPLAY_RANGE = 0x07;
export const GX_GPU_GP1_DISPLAY_MODE = 0x08;
export const GX_GPU_GP1_VRAM_Y_ADDRESS_EXTENSION = 0x09;
export const GX_GPU_GP1_GET_GPU_INFO = 0x10;
export const GX_GPU_GP1_GET_GPU_INFO_LAST = 0x1f;
export const GX_GPU_GP1_OPCODE_SHIFT = 24;
export const GX_GPU_GP1_PARAM_MASK = 0x00ffffff;
export const GX_GPU_GP1_GET_GPU_INFO_INDEX_MASK = 0x0f;
export const GX_GPU_GP1_DISPLAY_ENABLED = 0;
export const GX_GPU_GP1_DISPLAY_DISABLED = 1;
export const GX_GPU_GP1_VRAM_Y_ADDRESS_EXTENSION_ENABLED = 0x00000001;

export const GX_GPU_DISPLAY_START_MASK = 0x000ffffe;
export const GX_GPU_DISPLAY_MODE_MASK = 0x000000ff;
export const GX_GPU_HORIZONTAL_DISPLAY_RANGE_MASK = 0x00ffffff;
export const GX_GPU_VERTICAL_DISPLAY_RANGE_MASK = 0x000fffff;
export const GX_GPU_VERTICAL_DISPLAY_RANGE_START_MASK = 0x000003ff;
export const GX_GPU_VERTICAL_DISPLAY_RANGE_END_SHIFT = 10;
export const GX_GPU_VERTICAL_DISPLAY_RANGE_END_MASK = 0x000003ff;

export const GX_GPU_DISPLAY_MODE_VERTICAL_RESOLUTION_BIT = 0x04;
export const GX_GPU_DISPLAY_MODE_50HZ_BIT = 0x08;
export const GX_GPU_DISPLAY_MODE_RGB24_BIT = 0x10;
export const GX_GPU_DISPLAY_MODE_VERTICAL_INTERLACE_BIT = 0x20;

export const GX_GPU_INFO_GPU_TYPE_V2 = 0x00000002;

export const GX_GPU_RESET_DISPLAY_MODE_WORD = 0x00000009;
export const GX_GPU_RESET_HORIZONTAL_DISPLAY_RANGE_WORD = 0x00c60260;
export const GX_GPU_RESET_VERTICAL_DISPLAY_RANGE_WORD = 0x00044c23;

export function gxGpuGp1CommandWord(opcode: number, payload: number): number {
	return ((opcode << GX_GPU_GP1_OPCODE_SHIFT) | (payload & GX_GPU_GP1_PARAM_MASK)) >>> 0;
}
