export const BLUA32_DIAGNOSTIC_DIRECTORY_HEADER_SIZE = 32;

export const BLUA32_DIAGNOSTIC_DIRECTORY_RANGE_COUNT_OFFSET = 0;
export const BLUA32_DIAGNOSTIC_DIRECTORY_RANGE_TABLE_OFFSET = 4;
export const BLUA32_DIAGNOSTIC_DIRECTORY_FILE_COUNT_OFFSET = 8;
export const BLUA32_DIAGNOSTIC_DIRECTORY_FILE_TABLE_OFFSET = 12;
export const BLUA32_DIAGNOSTIC_DIRECTORY_LINE_OFFSET_COUNT_OFFSET = 16;
export const BLUA32_DIAGNOSTIC_DIRECTORY_LINE_OFFSET_TABLE_OFFSET = 20;
export const BLUA32_DIAGNOSTIC_DIRECTORY_PATH_TABLE_OFFSET = 24;
export const BLUA32_DIAGNOSTIC_DIRECTORY_PATH_BYTES_COUNT_OFFSET = 28;

export const BLUA32_DIAGNOSTIC_RANGE_RECORD_SIZE = 12;
export const BLUA32_DIAGNOSTIC_RANGE_PC_START_OFFSET = 0;
export const BLUA32_DIAGNOSTIC_RANGE_LINE_FILE_OFFSET = 4;
export const BLUA32_DIAGNOSTIC_RANGE_COLUMN_OFFSET = 8;
export const BLUA32_DIAGNOSTIC_NO_SOURCE = 0xffffffff;

export const BLUA32_DIAGNOSTIC_FILE_RECORD_SIZE = 20;
export const BLUA32_DIAGNOSTIC_FILE_PATH_OFFSET = 0;
export const BLUA32_DIAGNOSTIC_FILE_PATH_BYTE_COUNT_OFFSET = 4;
export const BLUA32_DIAGNOSTIC_FILE_SOURCE_OFFSET = 8;
export const BLUA32_DIAGNOSTIC_FILE_SOURCE_BYTE_COUNT_OFFSET = 12;
export const BLUA32_DIAGNOSTIC_FILE_LINE_OFFSET_START_INDEX_OFFSET = 16;
