export const BLUA32_DIAGNOSTIC_DIRECTORY_HEADER_SIZE = 76;

export const BLUA32_DIAGNOSTIC_DIRECTORY_RANGE_COUNT_OFFSET = 0;
export const BLUA32_DIAGNOSTIC_DIRECTORY_RANGE_TABLE_OFFSET = 4;
export const BLUA32_DIAGNOSTIC_DIRECTORY_FILE_COUNT_OFFSET = 8;
export const BLUA32_DIAGNOSTIC_DIRECTORY_FILE_TABLE_OFFSET = 12;
export const BLUA32_DIAGNOSTIC_DIRECTORY_LINE_OFFSET_COUNT_OFFSET = 16;
export const BLUA32_DIAGNOSTIC_DIRECTORY_LINE_OFFSET_TABLE_OFFSET = 20;
export const BLUA32_DIAGNOSTIC_DIRECTORY_PATH_TABLE_OFFSET = 24;
export const BLUA32_DIAGNOSTIC_DIRECTORY_PATH_BYTES_COUNT_OFFSET = 28;

export const BLUA32_DIAGNOSTIC_RANGE_RECORD_SIZE = 12;
export const BLUA32_DIAGNOSTIC_RANGE_PC_START_OFFSET = 0;
export const BLUA32_DIAGNOSTIC_RANGE_LINE_FILE_OFFSET = 4;
export const BLUA32_DIAGNOSTIC_RANGE_COLUMN_OFFSET = 8;
export const BLUA32_DIAGNOSTIC_NO_SOURCE = 0xffffffff;

export const BLUA32_DIAGNOSTIC_FILE_RECORD_SIZE = 20;
export const BLUA32_DIAGNOSTIC_FILE_PATH_OFFSET = 0;
export const BLUA32_DIAGNOSTIC_FILE_PATH_BYTE_COUNT_OFFSET = 4;
export const BLUA32_DIAGNOSTIC_FILE_SOURCE_OFFSET = 8;
export const BLUA32_DIAGNOSTIC_FILE_SOURCE_BYTE_COUNT_OFFSET = 12;
export const BLUA32_DIAGNOSTIC_FILE_LINE_OFFSET_START_INDEX_OFFSET = 16;

export const BLUA32_DIAGNOSTIC_DIRECTORY_FUNCTION_COUNT_OFFSET = 32;
export const BLUA32_DIAGNOSTIC_DIRECTORY_FUNCTION_TABLE_OFFSET = 36;
export const BLUA32_DIAGNOSTIC_DIRECTORY_FRAME_COUNT_OFFSET = 40;
export const BLUA32_DIAGNOSTIC_DIRECTORY_FRAME_TABLE_OFFSET = 44;
export const BLUA32_DIAGNOSTIC_DIRECTORY_BINDING_COUNT_OFFSET = 48;
export const BLUA32_DIAGNOSTIC_DIRECTORY_BINDING_TABLE_OFFSET = 52;
export const BLUA32_DIAGNOSTIC_DIRECTORY_INTERVAL_COUNT_OFFSET = 56;
export const BLUA32_DIAGNOSTIC_DIRECTORY_INTERVAL_TABLE_OFFSET = 60;
export const BLUA32_DIAGNOSTIC_DIRECTORY_NAME_BYTES_COUNT_OFFSET = 64;
export const BLUA32_DIAGNOSTIC_DIRECTORY_NAME_TABLE_OFFSET = 68;
export const BLUA32_DIAGNOSTIC_DIRECTORY_STATIC_GLOBAL_COUNT_OFFSET = 72;

export const BLUA32_DIAGNOSTIC_FUNCTION_RECORD_SIZE = 16;
export const BLUA32_DIAGNOSTIC_FUNCTION_ADDRESS_OFFSET = 0;
export const BLUA32_DIAGNOSTIC_FUNCTION_CODE_ADDRESS_OFFSET = 4;
export const BLUA32_DIAGNOSTIC_FUNCTION_FRAME_START_OFFSET = 8;
export const BLUA32_DIAGNOSTIC_FUNCTION_FRAME_COUNT_OFFSET = 12;

export const BLUA32_DIAGNOSTIC_FRAME_RECORD_SIZE = 28;
export const BLUA32_DIAGNOSTIC_FRAME_DEPTH_OFFSET = 0;
export const BLUA32_DIAGNOSTIC_FRAME_NAME_OFFSET = 4;
export const BLUA32_DIAGNOSTIC_FRAME_NAME_BYTES_OFFSET = 8;
export const BLUA32_DIAGNOSTIC_FRAME_ACTIVE_START_OFFSET = 12;
export const BLUA32_DIAGNOSTIC_FRAME_ACTIVE_COUNT_OFFSET = 16;
export const BLUA32_DIAGNOSTIC_FRAME_BINDING_START_OFFSET = 20;
export const BLUA32_DIAGNOSTIC_FRAME_BINDING_COUNT_OFFSET = 24;

export const BLUA32_DIAGNOSTIC_BINDING_RECORD_SIZE = 32;
export const BLUA32_DIAGNOSTIC_BINDING_NAME_OFFSET = 0;
export const BLUA32_DIAGNOSTIC_BINDING_NAME_BYTES_OFFSET = 4;
export const BLUA32_DIAGNOSTIC_BINDING_FLAGS_OFFSET = 8;
export const BLUA32_DIAGNOSTIC_BINDING_INDEX_OFFSET = 12;
export const BLUA32_DIAGNOSTIC_BINDING_VISIBLE_START_OFFSET = 16;
export const BLUA32_DIAGNOSTIC_BINDING_VISIBLE_COUNT_OFFSET = 20;
export const BLUA32_DIAGNOSTIC_BINDING_LIVE_START_OFFSET = 24;
export const BLUA32_DIAGNOSTIC_BINDING_LIVE_COUNT_OFFSET = 28;

export const BLUA32_DIAGNOSTIC_INTERVAL_RECORD_SIZE = 8;
export const BLUA32_DIAGNOSTIC_INTERVAL_START_OFFSET = 0;
export const BLUA32_DIAGNOSTIC_INTERVAL_END_OFFSET = 4;

export const BLUA32_DIAGNOSTIC_BINDING_UPVALUE = 1;
export const BLUA32_DIAGNOSTIC_BINDING_CONST = 2;
export const BLUA32_DIAGNOSTIC_BINDING_ADDRESS = 4;
export const BLUA32_DIAGNOSTIC_BINDING_TYPE = 8;
export const BLUA32_DIAGNOSTIC_NO_LOCATION = 0xffffffff;
