export const BLUA32_IMAGE_MAGIC = 0x32334c42;
export const BLUA32_IMAGE_VERSION = 1;
export const BLUA32_IMAGE_HEADER_SIZE = 96;

export const BLUA32_IMAGE_MAGIC_OFFSET = 0;
export const BLUA32_IMAGE_VERSION_OFFSET = 4;
export const BLUA32_IMAGE_BYTE_COUNT_OFFSET = 8;
export const BLUA32_IMAGE_FLAGS_OFFSET = 12;
export const BLUA32_IMAGE_FUNCTION_TABLE_ADDRESS_OFFSET = 16;
export const BLUA32_IMAGE_FUNCTION_COUNT_OFFSET = 20;
export const BLUA32_IMAGE_CONSTANT_TABLE_ADDRESS_OFFSET = 24;
export const BLUA32_IMAGE_CONSTANT_COUNT_OFFSET = 28;
export const BLUA32_IMAGE_GLOBAL_NAME_TABLE_ADDRESS_OFFSET = 32;
export const BLUA32_IMAGE_GLOBAL_NAME_COUNT_OFFSET = 36;
export const BLUA32_IMAGE_SYSTEM_GLOBAL_NAME_TABLE_ADDRESS_OFFSET = 40;
export const BLUA32_IMAGE_SYSTEM_GLOBAL_NAME_COUNT_OFFSET = 44;
export const BLUA32_IMAGE_STRING_ADDRESS_OFFSET = 48;
export const BLUA32_IMAGE_STRING_BYTE_COUNT_OFFSET = 52;
export const BLUA32_IMAGE_RODATA_ADDRESS_OFFSET = 56;
export const BLUA32_IMAGE_RODATA_BYTE_COUNT_OFFSET = 60;
export const BLUA32_IMAGE_DATA_LOAD_ADDRESS_OFFSET = 64;
export const BLUA32_IMAGE_DATA_BYTE_COUNT_OFFSET = 68;
export const BLUA32_IMAGE_DATA_ADDRESS_OFFSET = 72;
export const BLUA32_IMAGE_BSS_ADDRESS_OFFSET = 76;
export const BLUA32_IMAGE_BSS_BYTE_COUNT_OFFSET = 80;
export const BLUA32_IMAGE_TEXT_ADDRESS_OFFSET = 84;
export const BLUA32_IMAGE_TEXT_BYTE_COUNT_OFFSET = 88;
export const BLUA32_IMAGE_RESERVED_OFFSET = 92;

export const BLUA32_FUNCTION_RECORD_SIZE = 32;
export const BLUA32_FUNCTION_ALIGNMENT = 16;
export const BLUA32_FUNCTION_CODE_ADDRESS_OFFSET = 0;
export const BLUA32_FUNCTION_CODE_BYTE_COUNT_OFFSET = 4;
export const BLUA32_FUNCTION_NUM_PARAMS_OFFSET = 8;
export const BLUA32_FUNCTION_MAX_STACK_OFFSET = 12;
export const BLUA32_FUNCTION_FLAGS_OFFSET = 16;
export const BLUA32_FUNCTION_UPVALUE_TABLE_ADDRESS_OFFSET = 20;
export const BLUA32_FUNCTION_UPVALUE_COUNT_OFFSET = 24;
export const BLUA32_FUNCTION_RESERVED_OFFSET = 28;

export const BLUA32_FUNCTION_VARARG = 1 << 0;
export const BLUA32_FUNCTION_STATIC = 1 << 1;

export const BLUA32_UPVALUE_RECORD_SIZE = 4;
export const BLUA32_UPVALUE_IN_STACK_MASK = 0x80000000;
export const BLUA32_UPVALUE_INDEX_MASK = 0x7fffffff;

export const BLUA32_CONSTANT_RECORD_SIZE = 16;
export const BLUA32_CONSTANT_TAG_OFFSET = 0;
export const BLUA32_CONSTANT_PAYLOAD_OFFSET = 4;
export const BLUA32_CONSTANT_STRING_BYTE_COUNT_OFFSET = 8;

export const BLUA32_GLOBAL_NAME_RECORD_SIZE = 8;
export const BLUA32_GLOBAL_NAME_ADDRESS_OFFSET = 0;
export const BLUA32_GLOBAL_NAME_BYTE_COUNT_OFFSET = 4;

export const enum Blua32ConstantTag {
	Nil = 0,
	False = 1,
	True = 2,
	Number = 3,
	String = 4,
}
