#pragma once

#include "common/primitives.h"

namespace bmsx {

constexpr u32 CARTRIDGE_SLOT_COUNT = 2u;

constexpr u32 CARTRIDGE_STATUS_SLOT0_PRESENT = 1u << 0u;
constexpr u32 CARTRIDGE_STATUS_SLOT1_PRESENT = 1u << 1u;
constexpr u32 CARTRIDGE_STATUS_SELECTED_SLOT1 = 1u << 16u;

constexpr u32 CARTRIDGE_MAILBOX_DATA_OFFSET = 0x00u;
constexpr u32 CARTRIDGE_MAILBOX_CONTROL_OFFSET = 0x04u;
constexpr u32 CARTRIDGE_MAILBOX_STATUS_OFFSET = 0x08u;
constexpr u32 CARTRIDGE_MAILBOX_IRQ_ACK_OFFSET = 0x0cu;
constexpr u32 CARTRIDGE_MAILBOX_CONTROL_IRQ_TRIGGER = 1u << 0u;
constexpr u32 CARTRIDGE_MAILBOX_CONTROL_DREQ_READ = 1u << 1u;
constexpr u32 CARTRIDGE_MAILBOX_CONTROL_DREQ_WRITE = 1u << 2u;
constexpr u32 CARTRIDGE_MAILBOX_STATUS_IRQ_PENDING = 1u << 0u;

} // namespace bmsx
