#pragma once

#include <cstdint>

namespace bmsx {

constexpr uint32_t BMSX_ROM_BOOT_HEADER_SIZE = 60u;
constexpr uint32_t BMSX_ROM_HEADER_BLUA32_IMAGE_OFFSET = 32u;
constexpr uint32_t BMSX_ROM_HEADER_BLUA32_IMAGE_BYTE_COUNT_OFFSET = 36u;
constexpr uint32_t BMSX_ROM_HEADER_BLUA32_STARTUP_FUNCTION_ADDRESS_OFFSET = 40u;
constexpr uint32_t BMSX_ROM_HEADER_BLUA32_IRQ_FUNCTION_ADDRESS_OFFSET = 44u;
constexpr uint32_t BMSX_ROM_HEADER_BLUA32_EXCEPTION_FUNCTION_ADDRESS_OFFSET = 48u;
constexpr uint32_t BMSX_ROM_HEADER_BLUA32_STATIC_LAYOUT_TOKEN_LO_OFFSET = 52u;
constexpr uint32_t BMSX_ROM_HEADER_BLUA32_STATIC_LAYOUT_TOKEN_HI_OFFSET = 56u;

} // namespace bmsx
