import type { EditorCommandId } from '../common/commands';

export type EditorCommandPresentation = {
	readonly title: string;
	readonly category: string;
	readonly shortTitle?: string;
	readonly activeTitle?: string;
};

/** Human-facing command metadata. Execution and enablement stay in the controller. */
export const EDITOR_COMMAND_PRESENTATION: Readonly<
	Record<EditorCommandId, EditorCommandPresentation>
> = {
	'graph.zoomIn': { category: 'Graph', title: 'Zoom In', shortTitle: '+' },
	'graph.zoomOut': { category: 'Graph', title: 'Zoom Out', shortTitle: '-' },
	'graph.resetZoom': { category: 'Graph', title: 'Reset Zoom (100%)', shortTitle: '1:1' },
	'propertyInspector.source': { category: 'Inspect', title: 'Open Property Source', shortTitle: 'Source' },
	'propertyInspector.close': { category: 'Inspect', title: 'Close Property Details', shortTitle: 'Back' },
	'sourceEditReview.apply': { category: 'Review', title: 'Apply Source Edit', shortTitle: 'Apply' },
	'sourceEditReview.discard': { category: 'Review', title: 'Discard Source Edit', shortTitle: 'Discard' },
	'sourceEditReview.source': { category: 'Review', title: 'Open Impact Source', shortTitle: 'Source' },
	navigateBack: { category: 'Go', title: 'Back' },
	navigateForward: { category: 'Go', title: 'Forward' },
	contextMenu: { category: 'View', title: 'Show Context Menu' },
	commandPalette: { category: 'View', title: 'Command Palette' },
	undo: { category: 'Edit', title: 'Undo' },
	redo: { category: 'Edit', title: 'Redo' },
	symbolSearch: { category: 'Go', title: 'Go to Symbol' },
	symbolSearchGlobal: { category: 'Go', title: 'Go to Symbol in Workspace' },
	resourceSearch: { category: 'Go', title: 'Go to File' },
	runtimeErrorFocus: { category: 'Go', title: 'Go to Runtime Error' },
	createResource: { category: 'File', title: 'New Lua File' },
	findGlobal: { category: 'Search', title: 'Find in Workspace' },
	findLocal: { category: 'Search', title: 'Find' },
	lineJump: { category: 'Go', title: 'Go to Line' },
	referenceSearch: { category: 'Go', title: 'Go to References' },
	rename: { category: 'Edit', title: 'Rename Symbol' },
	renamePreview: { category: 'Edit', title: 'Rename Symbol with Preview' },
	assistant: { category: 'View', title: 'Codex Assistant' },
	terminal: { category: 'View', title: 'Lua Terminal' },
	'terminal.evaluate': { category: 'Terminal', title: 'Execute Lua', shortTitle: 'Run' },
	'terminal.context': { category: 'Terminal', title: 'Select Lua Context', shortTitle: 'Context' },
	'terminal.pause': { category: 'Terminal', title: 'Pause Lua Call', shortTitle: 'Pause' },
	'terminal.continue': { category: 'Terminal', title: 'Continue Lua Call', shortTitle: 'Continue' },
	'terminal.clear': { category: 'Terminal', title: 'Clear Output' },
	'terminal.copy': { category: 'Terminal', title: 'Copy Selected Entry' },
	'assistant.signIn': { category: 'Codex', title: 'Sign In to Studio Account', shortTitle: 'Sign in' },
	'assistant.cancelLogin': { category: 'Codex', title: 'Cancel Sign In', shortTitle: 'Cancel' },
	'assistant.signOut': { category: 'Codex', title: 'Sign Out of Studio Account', shortTitle: 'Sign out' },
	'assistant.openLogin': { category: 'Codex', title: 'Open Official Device Sign In', shortTitle: 'Open login' },
	'assistant.copyCode': { category: 'Codex', title: 'Copy Sign-In Code', shortTitle: 'Copy code' },
	'assistant.send': { category: 'Codex', title: 'Send Prompt', shortTitle: 'Send' },
	'assistant.queue': { category: 'Codex', title: 'Queue Message', shortTitle: 'Queue' },
	'assistant.direct': { category: 'Codex', title: 'Send Direct Message', shortTitle: 'Direct' },
	'assistant.history': { category: 'Codex', title: 'Conversation History', shortTitle: 'History' },
	'assistant.new': { category: 'Codex', title: 'New Conversation', shortTitle: 'New' },
	'assistant.commands': { category: 'Codex', title: 'Chat Commands', shortTitle: 'Commands' },
	'assistant.stop': { category: 'Codex', title: 'Stop Response', shortTitle: 'Stop' },
	'assistant.review': { category: 'Codex', title: 'Review Selected Proposal', shortTitle: 'Review' },
	'assistant.copy': { category: 'Codex', title: 'Copy Selected Message', shortTitle: 'Copy' },
	'workspaceEditReview.apply': { category: 'Review', title: 'Apply Workspace Edit', shortTitle: 'Apply' },
	'workspaceEditReview.discard': { category: 'Review', title: 'Discard Workspace Edit', shortTitle: 'Discard' },
	goToDefinition: { category: 'Go', title: 'Go to Definition' },
	callHierarchy: { category: 'Go', title: 'Show Call Hierarchy' },
	resources: { category: 'View', title: 'Show Files', activeTitle: 'Hide Files' },
	problems: { category: 'View', title: 'Problems Panel' },
	behaviorLens: { category: 'Behavior Lens', title: 'Open', shortTitle: 'Behavior Lens' },
	'behaviorLens.preview': { category: 'Behavior Lens', title: 'Preview Definition' },
	keepEditor: { category: 'Editor', title: 'Keep Open' },
	'behaviorLens.actionEffects': { category: 'Behavior Lens', title: 'Open ActionEffect' },
	'behaviorLens.stateMachines': { category: 'Behavior Lens', title: 'Open State Machine (FSM)' },
	'behaviorLens.behaviorTrees': { category: 'Behavior Lens', title: 'Open Behavior Tree (BT)' },
	scenarioLab: { category: 'Scenario Lab', title: 'Open', shortTitle: 'Scenario Lab' },
	sceneEditor: { category: 'Scene Editor', title: 'Open', shortTitle: 'Scene Editor' },
	actorLab: { category: 'Actor Lab', title: 'Open', shortTitle: 'Actor Lab' },
	gameView: { category: 'View', title: 'Game' },
	'gameView.playback': { category: 'Game', title: 'Play / Pause', shortTitle: 'Play/Pause' },
	'actorLab.playback': { category: 'Actor Lab', title: 'Play / Pause', shortTitle: 'Play/Pause' },
	'actorLab.select': { category: 'Actor Lab', title: 'Select Running Actor', shortTitle: 'Actor' },
	'actorLab.spawn': { category: 'Actor Lab', title: 'Spawn Registered Prefab', shortTitle: 'Spawn' },
	'actorLab.emit': { category: 'Actor Lab', title: 'Emit Event', shortTitle: 'Event' },
	'actorLab.actions': { category: 'Actor Lab', title: 'Instance Actions', shortTitle: 'Actions' },
	'actorLab.call': { category: 'Actor Lab', title: 'Call Lua Method', shortTitle: 'Call' },
	'actorLab.details': { category: 'Actor Lab', title: 'Inspect Instance', shortTitle: 'Details' },
	'sceneEditor.source': { category: 'Scene Editor', title: 'Open Source', shortTitle: 'Source' },
	'behaviorLens.details': { category: 'Behavior Lens', title: 'Open Source Details', shortTitle: 'Details' },
	'behaviorLens.inspectRuntimeEffect': { category: 'Behavior Lens', title: 'Inspect Granted ActionEffect', shortTitle: 'Live' },
	'behaviorLens.inspectRuntimeStateMachine': { category: 'State Machine', title: 'Inspect Runtime Instance', shortTitle: 'Live' },
	'behaviorLens.inspectRuntimeTree': { category: 'Behavior Tree', title: 'Inspect Runtime Instance', shortTitle: 'Live' },
	'behaviorLens.inspectRegisteredDefinitions': { category: 'Behavior Lens', title: 'Inspect Registered Definitions', shortTitle: 'Registered Definitions' },
	'behaviorLens.editProperty': { category: 'Behavior Lens', title: 'Edit Authored Property', shortTitle: 'Edit' },
	'behaviorLens.moveChildEarlier': { category: 'Behavior Lens', title: 'Move BT Child Earlier', shortTitle: 'Earlier' },
	'behaviorLens.moveChildLater': { category: 'Behavior Lens', title: 'Move BT Child Later', shortTitle: 'Later' },
	'behaviorLens.removeChild': { category: 'Behavior Lens', title: 'Remove BT Child', shortTitle: 'Remove' },
	'behaviorLens.duplicateChild': { category: 'Behavior Lens', title: 'Duplicate BT Child', shortTitle: 'Duplicate' },
	'behaviorLens.setInitialState': { category: 'State Machine', title: 'Set Selected State as Initial', shortTitle: 'Set Initial' },
	'behaviorLens.source': { category: 'Behavior Lens', title: 'Open Source', shortTitle: 'Source' },
	'sceneEditor.removeMember': { category: 'Scene Editor', title: 'Remove Member', shortTitle: 'Remove' },
	'sceneEditor.moveMemberUp': { category: 'Scene Editor', title: 'Move Member Up', shortTitle: 'Up' },
	'sceneEditor.moveMemberDown': { category: 'Scene Editor', title: 'Move Member Down', shortTitle: 'Down' },
	filter: { category: 'File', title: 'All Resources', activeTitle: 'Lua Files Only' },
	wrap: { category: 'View', title: 'Word Wrap' },
	'hot-resume': { category: 'Run', title: 'Hot Resume' },
	runCurrentFile: { category: 'Run', title: 'Run Current Lua File' },
	runProject: { category: 'Run', title: 'Run Project' },
	reboot: { category: 'Run', title: 'Reboot' },
	save: { category: 'File', title: 'Save' },
	'theme-toggle': { category: 'Preferences', title: 'Toggle Theme' },
	debugContinue: { category: 'Debug', title: 'Continue' },
	debugEvaluation: { category: 'Debug', title: 'Pause Lua Call', activeTitle: 'Continue Lua Call' },
	pause: { category: 'Run', title: 'Pause', activeTitle: 'Resume' },
	stepFrame: { category: 'Run', title: 'Next Frame' },
	stepFrameBack: { category: 'Run', title: 'Previous Frame' },
	debugStepInto: { category: 'Debug', title: 'Step Into' },
	debugStepOut: { category: 'Debug', title: 'Step Out' },
	debugStepOver: { category: 'Debug', title: 'Step Over' },
	'scenarioLab.inspectTarget': { category: 'Scenario Lab', title: 'Inspect Retained Test Target', shortTitle: 'Target' },
	'scenarioLab.closeTarget': { category: 'Scenario Lab', title: 'Close Target Inspection', shortTitle: 'Close' },
	'scenarioLab.details': { category: 'Scenario Lab', title: 'Inspect Test Result', shortTitle: 'Details' },
	'scenarioLab.debug': { category: 'Scenario Lab', title: 'Debug Selected Test Case', shortTitle: 'Debug' },
	'scenarioLab.continue': { category: 'Scenario Lab', title: 'Continue Test', shortTitle: 'Continue' },
	'scenarioLab.stepInto': { category: 'Scenario Lab', title: 'Step Into Test', shortTitle: 'Into' },
	'scenarioLab.stepOver': { category: 'Scenario Lab', title: 'Step Over Test', shortTitle: 'Over' },
	'scenarioLab.stepOut': { category: 'Scenario Lab', title: 'Step Out of Test', shortTitle: 'Out' },
	'scenarioLab.pause': { category: 'Scenario Lab', title: 'Pause Test', shortTitle: 'Pause' },
	'scenarioLab.breakpoints': { category: 'Scenario Lab', title: 'Compiled Test Sources and Breakpoints', shortTitle: 'Breakpoints' },
	'scenarioLab.inspectStop': { category: 'Scenario Lab', title: 'Inspect Stopped Test', shortTitle: 'Inspect' },
	'scenarioLab.run': { category: 'Scenario Lab', title: 'Run Scenarios', shortTitle: 'Run' },
	'scenarioLab.rerun': { category: 'Scenario Lab', title: 'Rerun Scenarios', shortTitle: 'Rerun' },
	'scenarioLab.cancel': { category: 'Scenario Lab', title: 'Stop Scenarios', shortTitle: 'Stop' },
};

export const EDITOR_COMMAND_IDS = Object.keys(EDITOR_COMMAND_PRESENTATION) as EditorCommandId[];

export function editorCommandTitle(command: EditorCommandId, active: boolean, renderShortTitle = false): string {
	const presentation = EDITOR_COMMAND_PRESENTATION[command];
	if (active && presentation.activeTitle !== undefined) return presentation.activeTitle;
	return renderShortTitle && presentation.shortTitle !== undefined ? presentation.shortTitle : presentation.title;
}
