export const IMGDEC_HISTORY_WORD_CAPACITY = 4096;
export const IMGDEC_HISTORY_WORD_MASK = IMGDEC_HISTORY_WORD_CAPACITY - 1;

export const IMGDEC_STREAM_MAGIC = 0x31444d49;
export const IMGDEC_STREAM_HEADER_WORDS = 3;

export const IMGDEC_TOKEN_KIND_SHIFT = 30;
export const IMGDEC_TOKEN_KIND_LITERAL = 0;
export const IMGDEC_TOKEN_KIND_REPEAT = 1;
export const IMGDEC_TOKEN_KIND_BACK_REFERENCE = 2;
export const IMGDEC_TOKEN_KIND_ZERO = 3;
export const IMGDEC_TOKEN_RUN_LENGTH_MASK = 0x3fffffff;
export const IMGDEC_TOKEN_BACK_REFERENCE_DISTANCE_BITS = 12;
export const IMGDEC_TOKEN_BACK_REFERENCE_DISTANCE_MASK = (1 << IMGDEC_TOKEN_BACK_REFERENCE_DISTANCE_BITS) - 1;
export const IMGDEC_TOKEN_BACK_REFERENCE_LENGTH_SHIFT = IMGDEC_TOKEN_BACK_REFERENCE_DISTANCE_BITS;
export const IMGDEC_TOKEN_BACK_REFERENCE_LENGTH_MASK = (1 << (30 - IMGDEC_TOKEN_BACK_REFERENCE_DISTANCE_BITS)) - 1;
export const IMGDEC_TOKEN_BACK_REFERENCE_MIN_LENGTH = 3;
