import { CHARACTER_CODES } from '../../../common/character_map';
import { EDITOR_TOGGLE_KEY, ESCAPE_KEY, TERMINAL_TOGGLE_KEY } from '../../../common/constants';

export const captureKeys: string[] = [...new Set([
	EDITOR_TOGGLE_KEY,
	TERMINAL_TOGGLE_KEY,
	ESCAPE_KEY,
	'ArrowUp',
	'ArrowDown',
	'ArrowLeft',
	'ArrowRight',
	'Backspace',
	'Delete',
	'Enter',
	'NumpadEnter',
	'End',
	'Home',
	'PageDown',
	'PageUp',
	'Space',
	'Tab',
	'F3',
	'F5',
	'F9',
	'F10',
	'F11',
	'F12',
	'NumpadDivide',
	...CHARACTER_CODES,
])];
