import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const tsOutputPath = resolve(process.cwd(), 'machine/ts/render/post/device_quantize/lut.ts');
const cppOutputPath = resolve(process.cwd(), 'machine/cpp/render/post/device_quantize/lut.cpp');

const transferTableSize = 4096;
const transferTableScale = 4095.0;
const lutWidth = 256;
const lutHeight = 16;

function buildLinearToSignalTable() {
	const table = new Float32Array(transferTableSize);
	for (let index = 0; index < transferTableSize; index += 1) {
		const channel = index / transferTableScale;
		table[index] = channel <= 0.0031308
			? channel * 12.92
			: 1.055 * Math.pow(channel, 1.0 / 2.4) - 0.055;
	}
	return table;
}

function buildSignalToLinearTable() {
	const table = new Float32Array(transferTableSize);
	for (let index = 0; index < transferTableSize; index += 1) {
		const channel = index / transferTableScale;
		table[index] = channel <= 0.04045
			? channel / 12.92
			: Math.pow((channel + 0.055) / 1.055, 2.4);
	}
	return table;
}

const linearToSignalTable = buildLinearToSignalTable();
const signalToLinearTable = buildSignalToLinearTable();

function transferTableLookup(table, value) {
	return table[(value * transferTableScale + 0.5) | 0];
}

function buildChannelLut(levels) {
	const lut = new Uint8Array(lutWidth * lutHeight);
	for (let thresholdIndex = 0; thresholdIndex < lutHeight; thresholdIndex += 1) {
		const threshold = (thresholdIndex + 0.5) * (1.0 / 16.0);
		for (let signalByte = 0; signalByte < lutWidth; signalByte += 1) {
			const signal = transferTableLookup(linearToSignalTable, signalByte * (1.0 / 255.0));
			const value = signal * levels;
			const bucket = value | 0;
			const quantized = (bucket + (value - bucket >= threshold ? 1.0 : 0.0)) / levels;
			lut[(thresholdIndex << 8) | signalByte] = (transferTableLookup(signalToLinearTable, quantized) * 255.0) | 0;
		}
	}
	return lut;
}

function buildTextureLut(redBlue, green) {
	const lut = new Uint8Array(lutWidth * lutHeight * 4);
	for (let thresholdIndex = 0; thresholdIndex < lutHeight; thresholdIndex += 1) {
		const channelOffset = thresholdIndex << 8;
		for (let signalByte = 0; signalByte < lutWidth; signalByte += 1) {
			const source = channelOffset | signalByte;
			const target = source << 2;
			lut[target + 0] = redBlue[source];
			lut[target + 1] = green[source];
			lut[target + 2] = redBlue[source];
			lut[target + 3] = 255;
		}
	}
	return lut;
}

const rgb565RedBlue = buildChannelLut(31.0);
const rgb565Green = buildChannelLut(63.0);
const rgb343RedBlue = buildChannelLut(7.0);
const rgb343Green = buildChannelLut(15.0);
const rgb565Texture = buildTextureLut(rgb565RedBlue, rgb565Green);
const rgb343Texture = buildTextureLut(rgb343RedBlue, rgb343Green);

function byteLines(bytes, prefix, suffix) {
	const lines = [];
	for (let offset = 0; offset < bytes.length; offset += 32) {
		lines.push(`${prefix}${Array.from(bytes.subarray(offset, offset + 32), value => `0x${value.toString(16).padStart(2, '0')}`).join(', ')}${suffix}`);
	}
	return lines.join('\n');
}

function tsArray(name, bytes) {
	return `const ${name} = new Uint8Array([\n${byteLines(bytes, '\t', ',')}\n]);`;
}

const tsSource = `// Generated by scripts/render/generate_device_quantize_luts.mjs. Do not edit.

export const DEVICE_QUANTIZE_LUT_WIDTH = ${lutWidth};
export const DEVICE_QUANTIZE_LUT_HEIGHT = ${lutHeight};
export const DEVICE_QUANTIZE_LUT_MODE_COUNT = 2;

export const DEVICE_QUANTIZE_BAYER_4X4 = new Uint8Array([
\t0, 8, 2, 10,
\t12, 4, 14, 6,
\t3, 11, 1, 9,
\t15, 7, 13, 5,
]);

export interface DeviceQuantizeLuts {
\treadonly redBlue: Uint8Array;
\treadonly green: Uint8Array;
\treadonly texture: Uint8Array;
}

${tsArray('RGB565_RED_BLUE_LUT', rgb565RedBlue)}

${tsArray('RGB565_GREEN_LUT', rgb565Green)}

${tsArray('RGB343_RED_BLUE_LUT', rgb343RedBlue)}

${tsArray('RGB343_GREEN_LUT', rgb343Green)}

${tsArray('RGB565_TEXTURE_LUT', rgb565Texture)}

${tsArray('RGB343_TEXTURE_LUT', rgb343Texture)}

export const DEVICE_QUANTIZE_LUTS: readonly DeviceQuantizeLuts[] = [
\t{ redBlue: RGB565_RED_BLUE_LUT, green: RGB565_GREEN_LUT, texture: RGB565_TEXTURE_LUT },
\t{ redBlue: RGB343_RED_BLUE_LUT, green: RGB343_GREEN_LUT, texture: RGB343_TEXTURE_LUT },
];
`;

function cppArray(bytes, indentation) {
	return `{\n${byteLines(bytes, indentation, ',')}\n${indentation.slice(0, -1)}}`;
}

const cppSource = `// Generated by scripts/render/generate_device_quantize_luts.mjs. Do not edit.

#include "lut.h"

namespace bmsx {

const std::array<DeviceQuantizeLuts, DEVICE_QUANTIZE_LUT_MODE_COUNT> DEVICE_QUANTIZE_LUTS{{
\t{
\t\t${cppArray(rgb565RedBlue, '\t\t\t')},
\t\t${cppArray(rgb565Green, '\t\t\t')},
\t\t${cppArray(rgb565Texture, '\t\t\t')},
\t},
\t{
\t\t${cppArray(rgb343RedBlue, '\t\t\t')},
\t\t${cppArray(rgb343Green, '\t\t\t')},
\t\t${cppArray(rgb343Texture, '\t\t\t')},
\t},
}};

} // namespace bmsx
`;

if (process.argv.includes('--check')) {
	if (readFileSync(tsOutputPath, 'utf8') !== tsSource) {
		console.error(`${tsOutputPath} is stale`);
		process.exitCode = 1;
	}
	if (readFileSync(cppOutputPath, 'utf8') !== cppSource) {
		console.error(`${cppOutputPath} is stale`);
		process.exitCode = 1;
	}
} else {
	writeFileSync(tsOutputPath, tsSource);
	writeFileSync(cppOutputPath, cppSource);
}
