import { biosResPath, prepareRomInputs } from '../rompacker/build_inputs';
import {
	getResMetaList,
	getResourcesList,
} from '../rompacker/rombuilder';
import type { ImageResource, Resource } from '../rompacker/rompacker.rompack';
import { GX_SYSTEM_TEXTURE_ATLAS_NAME } from '../rompacker/texture_atlas_contract';

import { createCanvas } from 'canvas';
import potpack from 'potpack';

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { addHostFontStyles } from './host_font_styles';

type HostAtlasImage = {
	id: string;
	width: number;
	height: number;
	u: number;
	v: number;
	w: number;
	h: number;
};

type HostAtlasBuild = {
	width: number;
	height: number;
	pixels: Uint8ClampedArray;
	images: HostAtlasImage[];
};

const HOST_SYSTEM_ATLAS_TS_PATH = join(process.cwd(), 'machine', 'ts', 'render', 'host_overlay', 'atlas.generated.ts');
const HOST_SYSTEM_ATLAS_CPP_SOURCE_PATH = join(process.cwd(), 'machine', 'cpp', 'render', 'host_overlay', 'atlas.generated.cpp');
const HOST_RESOURCE_PATH = './hosts/res';

const GENERATED_FILE_HEADER = [
	'// Generated by scripts/render/generate_host_system_atlas.ts.',
	'// Do not edit by hand.',
	'',
].join('\n');

function buildHostAtlasFromResources(resources: readonly Resource[]): HostAtlasBuild {
	// Host overlay pixels have no GX page/VRAM representation. Pack them directly;
	// do not send fonts through the guest ROM texture encoder or its 256x64 limit.
	const boxes = resources.filter((resource): resource is ImageResource => (
		resource.type === 'image' && resource.targetAtlasName === GX_SYSTEM_TEXTURE_ATLAS_NAME
	)).map(resource => ({ resource, w: resource.img!.width, h: resource.img!.height, x: 0, y: 0 }));
	const { w, h } = potpack(boxes);
	const atlas = createCanvas(w, h), context = atlas.getContext('2d');
	const images: HostAtlasImage[] = [];
	for (const box of boxes) {
		context.drawImage(box.resource.img!, box.x, box.y);
		images.push({ id: box.resource.name, width: box.w, height: box.h, u: box.x, v: box.y, w: box.w, h: box.h });
	}
	images.sort((a, b) => a.id < b.id ? -1 : a.id > b.id ? 1 : 0);
	if (images.length === 0) {
		throw new Error('[HostSystemAtlas] No system-atlas images were generated.');
	}
	return {
		width: w,
		height: h,
		pixels: context.getImageData(0, 0, w, h).data,
		images,
	};
}

function renderByteRows(bytes: Uint8ClampedArray, indent: string): string[] {
	const rows: string[] = [];
	for (let start = 0; start < bytes.length; start += 32) {
		const values: string[] = [];
		const end = start + 32 < bytes.length ? start + 32 : bytes.length;
		for (let index = start; index < end; index += 1) {
			values.push(String(bytes[index]));
		}
		rows.push(`${indent}${values.join(', ')},`);
	}
	return rows;
}

function renderTypeScriptArtifact(build: HostAtlasBuild): string {
	const imageEntries = build.images.map(image => (
		`\t\t{ id: ${JSON.stringify(image.id)}, width: ${image.width}, height: ${image.height}, u: ${image.u}, v: ${image.v}, w: ${image.w}, h: ${image.h} },`
	));
	return GENERATED_FILE_HEADER + [
		"import type { HostSystemAtlas } from './atlas';",
		'',
		'export const HOST_SYSTEM_ATLAS: HostSystemAtlas = {',
		`\twidth: ${build.width},`,
		`\theight: ${build.height},`,
		'\tpixels: new Uint8Array([',
		...renderByteRows(build.pixels, '\t\t'),
		'\t]),',
		'\timages: [',
		...imageEntries,
		'\t],',
		'};',
		'',
	].join('\n');
}

function renderCppSource(build: HostAtlasBuild): string {
	const imageEntries = build.images.map(image => (
		`\tHostSystemAtlasImage{std::string_view(${JSON.stringify(image.id)}), ${image.width}, ${image.height}, ${image.u}u, ${image.v}u, ${image.w}u, ${image.h}u},`
	));
	return GENERATED_FILE_HEADER + [
		'#include "render/host_overlay/atlas.h"',
		'',
		'namespace bmsx {',
		'namespace {',
		'',
		'constexpr u8 HOST_SYSTEM_ATLAS_PIXELS[] = {',
		...renderByteRows(build.pixels, '\t'),
		'};',
		'constexpr HostSystemAtlasImage HOST_SYSTEM_ATLAS_IMAGES[] = {',
		...imageEntries,
		'};',
		'',
		'} // namespace',
		'',
		'const HostSystemAtlas HOST_SYSTEM_ATLAS{',
		`\t${build.width}u,`,
		`\t${build.height}u,`,
		'\tHOST_SYSTEM_ATLAS_PIXELS,',
		'\tHOST_SYSTEM_ATLAS_IMAGES,',
		'};',
		'',
		'} // namespace bmsx',
		'',
	].join('\n');
}

async function writeIfChanged(path: string, contents: string): Promise<boolean> {
	let current = '';
	try {
		current = await readFile(path, 'utf8');
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
			throw error;
		}
	}
	if (current === contents) {
		return false;
	}
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, contents, 'utf8');
	return true;
}

async function writeHostSystemAtlasArtifacts(build: HostAtlasBuild): Promise<boolean> {
	const writes = await Promise.all([
		writeIfChanged(HOST_SYSTEM_ATLAS_TS_PATH, renderTypeScriptArtifact(build)),
		writeIfChanged(HOST_SYSTEM_ATLAS_CPP_SOURCE_PATH, renderCppSource(build)),
	]);
	return writes.some(Boolean);
}

async function generateHostSystemAtlasArtifacts(): Promise<boolean> {
	const biosProjectRoot = join(biosResPath, '..');
	const biosVirtualRoot = biosProjectRoot.replace(/^\.\//, '');
	const resourceRoots = [biosResPath, HOST_RESOURCE_PATH];
	const inputs = await prepareRomInputs(resourceRoots, []);
	const resMeta = await getResMetaList(inputs, {
		domain: 'system',
		sourceOnlyLuaRootFiles: [],
		sourceOnlyLuaModuleRoots: [],
		virtualRoot: biosVirtualRoot,
	});
	const resources = await getResourcesList(resMeta);
	await addHostFontStyles(resources);
	return writeHostSystemAtlasArtifacts(buildHostAtlasFromResources(resources));
}

if (require.main === module) {
	generateHostSystemAtlasArtifacts()
		.then(updated => {
			console.log(
				`Host system atlas -> machine/{ts,cpp}/render/host_overlay/atlas.generated`
				+ `${updated ? '' : ' (up-to-date)'}`,
			);
		})
		.catch(error => {
			console.error(error);
			process.exitCode = 1;
		});
}
