import { SYSTEM_ROM_NAME } from '../../toolchain/ts/rompack/system';
import {
	biosResPath,
	createTextureAtlases,
	getResMetaList,
	getResourcesList,
} from '../rompacker/rombuilder';
import type { Resource, TextureAtlasResource } from '../rompacker/rompacker.rompack';
import { GX_SYSTEM_TEXTURE_GROUP_ID } from '../rompacker/texture_atlas_contract';

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

type HostAtlasImage = {
	id: string;
	width: number;
	height: number;
	u: number;
	v: number;
	w: number;
	h: number;
};

type HostAtlasBuild = {
	width: number;
	height: number;
	pixels: Uint8ClampedArray;
	images: HostAtlasImage[];
};

const HOST_SYSTEM_ATLAS_TS_PATH = join(process.cwd(), 'machine', 'ts', 'render', 'host_overlay', 'atlas.generated.ts');
const HOST_SYSTEM_ATLAS_CPP_SOURCE_PATH = join(process.cwd(), 'machine', 'cpp', 'render', 'host_overlay', 'atlas.generated.cpp');
const HOST_RESOURCE_PATH = './hosts/res';

const GENERATED_FILE_HEADER = [
	'// Generated by scripts/render/generate_host_system_atlas.ts.',
	'// Do not edit by hand.',
	'',
].join('\n');

function buildHostAtlasFromResources(resources: readonly Resource[]): HostAtlasBuild {
	const atlas = resources.find((resource): resource is TextureAtlasResource => (
		resource.type === 'atlas' && resource.atlasId === GX_SYSTEM_TEXTURE_GROUP_ID
	))!;
	const rgba = atlas.img!.getContext('2d').getImageData(0, 0, atlas.img!.width, atlas.img!.height).data;
	const images: HostAtlasImage[] = [];
	for (let index = 0; index < resources.length; index += 1) {
		const resource = resources[index];
		if (resource.type === 'image' && resource.targetAtlasId === GX_SYSTEM_TEXTURE_GROUP_ID) {
			images.push({
				id: resource.name,
				width: resource.img!.width,
				height: resource.img!.height,
				u: resource.textureU!,
				v: resource.textureV!,
				w: resource.img!.width,
				h: resource.img!.height,
			});
		}
	}
	images.sort((a, b) => a.id < b.id ? -1 : a.id > b.id ? 1 : 0);
	if (images.length === 0) {
		throw new Error('[HostSystemAtlas] No system-atlas images were generated.');
	}
	return {
		width: atlas.img!.width,
		height: atlas.img!.height,
		pixels: rgba,
		images,
	};
}

function renderByteRows(bytes: Uint8ClampedArray, indent: string): string[] {
	const rows: string[] = [];
	for (let start = 0; start < bytes.length; start += 32) {
		const values: string[] = [];
		const end = start + 32 < bytes.length ? start + 32 : bytes.length;
		for (let index = start; index < end; index += 1) {
			values.push(String(bytes[index]));
		}
		rows.push(`${indent}${values.join(', ')},`);
	}
	return rows;
}

function renderTypeScriptArtifact(build: HostAtlasBuild): string {
	const imageEntries = build.images.map(image => (
		`\t\t{ id: ${JSON.stringify(image.id)}, width: ${image.width}, height: ${image.height}, u: ${image.u}, v: ${image.v}, w: ${image.w}, h: ${image.h} },`
	));
	return GENERATED_FILE_HEADER + [
		"import type { HostSystemAtlas } from './atlas';",
		'',
		'export const HOST_SYSTEM_ATLAS: HostSystemAtlas = {',
		`\twidth: ${build.width},`,
		`\theight: ${build.height},`,
		'\tpixels: new Uint8Array([',
		...renderByteRows(build.pixels, '\t\t'),
		'\t]),',
		'\timages: [',
		...imageEntries,
		'\t],',
		'};',
		'',
	].join('\n');
}

function renderCppSource(build: HostAtlasBuild): string {
	const imageEntries = build.images.map(image => (
		`\tHostSystemAtlasImage{std::string_view(${JSON.stringify(image.id)}), ${image.width}, ${image.height}, ${image.u}u, ${image.v}u, ${image.w}u, ${image.h}u},`
	));
	return GENERATED_FILE_HEADER + [
		'#include "render/host_overlay/atlas.h"',
		'',
		'namespace bmsx {',
		'namespace {',
		'',
		'constexpr u8 HOST_SYSTEM_ATLAS_PIXELS[] = {',
		...renderByteRows(build.pixels, '\t'),
		'};',
		'constexpr HostSystemAtlasImage HOST_SYSTEM_ATLAS_IMAGES[] = {',
		...imageEntries,
		'};',
		'',
		'} // namespace',
		'',
		'const HostSystemAtlas HOST_SYSTEM_ATLAS{',
		`\t${build.width}u,`,
		`\t${build.height}u,`,
		'\tHOST_SYSTEM_ATLAS_PIXELS,',
		'\tHOST_SYSTEM_ATLAS_IMAGES,',
		'};',
		'',
		'} // namespace bmsx',
		'',
	].join('\n');
}

async function writeIfChanged(path: string, contents: string): Promise<boolean> {
	let current = '';
	try {
		current = await readFile(path, 'utf8');
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
			throw error;
		}
	}
	if (current === contents) {
		return false;
	}
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, contents, 'utf8');
	return true;
}

async function writeHostSystemAtlasArtifacts(build: HostAtlasBuild): Promise<boolean> {
	const writes = await Promise.all([
		writeIfChanged(HOST_SYSTEM_ATLAS_TS_PATH, renderTypeScriptArtifact(build)),
		writeIfChanged(HOST_SYSTEM_ATLAS_CPP_SOURCE_PATH, renderCppSource(build)),
	]);
	return writes.some(Boolean);
}

async function generateHostSystemAtlasArtifacts(): Promise<boolean> {
	const biosProjectRoot = join(biosResPath, '..');
	const biosVirtualRoot = biosProjectRoot.replace(/^\.\//, '');
	const resourceRoots = [biosResPath, HOST_RESOURCE_PATH];
	const resMeta = await getResMetaList(resourceRoots, SYSTEM_ROM_NAME, {
		extraLuaPaths: [],
		virtualRoot: biosVirtualRoot,
		systemResourceRoots: resourceRoots,
	});
	const resources = await getResourcesList(resMeta);
	await createTextureAtlases(resources);
	return writeHostSystemAtlasArtifacts(buildHostAtlasFromResources(resources));
}

if (require.main === module) {
	generateHostSystemAtlasArtifacts()
		.then(updated => {
			console.log(
				`Host system atlas -> machine/{ts,cpp}/render/host_overlay/atlas.generated`
				+ `${updated ? '' : ' (up-to-date)'}`,
			);
		})
		.catch(error => {
			console.error(error);
			process.exitCode = 1;
		});
}
