import { machineManager } from '../../core/machine_manager';
import { registerLuaSourceRecord, resolveLuaSourceRecord, type LuaSourceRecord, type LuaSourceRegistry } from '../../lua/source_registry';
import { toLuaModulePath } from '../../machine/program/loader';
import type { StorageService } from '../../platform';
import { ROM_GENERATED_CONST_MODULE_PATHS } from '../../rompack/format';
import * as luaPipeline from '../runtime/lua_pipeline';
import type { LuaResourceCreationRequest, ResourceDescriptor } from '../../rompack/tooling/resource';
import { joinWorkspacePaths, resolveWorkspacePath } from './path';
import {
	applyWorkspaceSourceOverrides,
	collectScratchWorkspaceDirtyPaths,
	deleteWorkspaceServerFile,
	persistWorkspaceSourceFile,
	buildWorkspaceDirtyEntryPath,
	buildWorkspaceStorageKey,
	persistWorkspaceOverridesToLocalStorage,
	WORKSPACE_METADATA_DIR,
	WORKSPACE_STATE_FILE,
} from './files';
import { workspaceSourceCache } from './cache';
import { clearWorkspaceDirtyBuffers } from '../workbench/workspace/autosave';

export * from './files';
export { joinWorkspacePaths } from './path';

function resolveEditableCartLuaSources(): LuaSourceRegistry {
	const sources = machineManager.sourceState;
	return sources.cartLuaSources ?? sources.activeLuaSources;
}


export async function saveLuaResourceSource(path: string, source: string): Promise<void> {
	const sources = machineManager.sourceState;
	let registry = sources.systemLuaSources;
	let asset: LuaSourceRecord | null = null;
	const cartRegistry = sources.cartLuaSources;
	if (cartRegistry) {
		asset = resolveLuaSourceRecord(cartRegistry, path);
		if (asset) {
			registry = cartRegistry;
		}
	}
	if (!asset) {
		asset = resolveLuaSourceRecord(registry, path);
	}
	if (!asset) {
		throw new Error(`Missing Lua source registry for '${path}'.`);
	}
	if (asset.generated) {
		throw new Error(`Generated Lua source '${path}' is read-only.`);
	}
	const sourcePath = asset.source_path;
	const projectRootPath = registry.projectRootPath;
	await persistWorkspaceSourceFile(sourcePath, source, projectRootPath);
	const updatedAt = machineManager.platform.clock.dateNow();
	asset.src = source;
	asset.base_update_timestamp = updatedAt;
	asset.update_timestamp = updatedAt;
	registerLuaSourceRecord(registry, asset);
	persistWorkspaceOverridesToLocalStorage(machineManager.platform.storage, projectRootPath, new Map([[
		sourcePath,
		{ source, path: sourcePath, cartPath: sourcePath, updatedAt },
	]]), updatedAt);
	const dirtyPath = buildWorkspaceDirtyEntryPath(projectRootPath, sourcePath);
	machineManager.platform.storage.removeItem(buildWorkspaceStorageKey(projectRootPath, dirtyPath));
	await deleteWorkspaceServerFile(dirtyPath);
	workspaceSourceCache.delete(dirtyPath);
	workspaceSourceCache.set(sourcePath, source);
	luaPipeline.markSourceChunkAsDirty(sourcePath);
}

export async function createLuaResource(request: LuaResourceCreationRequest): Promise<ResourceDescriptor> {
	const contents = typeof request.contents === 'string' ? request.contents : '';
	const path = request.path;
	const slashIndex = path.lastIndexOf('/');
	const fileName = slashIndex === -1 ? path : path.slice(slashIndex + 1);
	const baseName = fileName.endsWith('.lua') ? fileName.slice(0, -4) : fileName;
	const modulePath = toLuaModulePath(path);
	if (ROM_GENERATED_CONST_MODULE_PATHS.includes(modulePath)) {
		throw new Error(`Lua module '${modulePath}' is generated by the ROM packer.`);
	}
	const updatedAt = machineManager.platform.clock.dateNow();
	const asset: LuaSourceRecord = {
		resid: baseName,
		type: 'lua',
		src: contents,
		base_src: contents,
		base_update_timestamp: updatedAt,
		source_path: path,
		module_path: modulePath,
		update_timestamp: updatedAt,
		generated: false,
	};
	const systemSource = asset.source_path.startsWith('bios/') || asset.source_path.startsWith('system/');
	const sources = machineManager.sourceState;
	const registry = systemSource
		? sources.systemLuaSources
		: resolveEditableCartLuaSources();
	registerLuaSourceRecord(registry, asset);
	registry.can_boot_from_source = true;
	luaPipeline.invalidateModuleLookups();
	const filesystemPath = asset.source_path;
	await persistWorkspaceSourceFile(filesystemPath, contents, systemSource ? sources.systemProjectRootPath : sources.cartProjectRootPath);
	machineManager.sourceState.luaGenericChunksExecuted.delete(asset.source_path);
	const descriptor: ResourceDescriptor = { path: asset.source_path, type: 'lua' };
	return descriptor;
}

export async function applyWorkspaceOverridesToRegistry(params: { registry: LuaSourceRegistry; storage: StorageService; includeServer?: boolean; projectRootPath?: string }): Promise<Set<string>> {
	return await applyWorkspaceSourceOverrides({
		registry: params.registry,
		storage: params.storage,
		includeServer: params.includeServer,
		projectRootPath: params.projectRootPath ?? machineManager.sourceState.cartProjectRootPath,
		timestampNow: machineManager.platform.clock.dateNow(),
	});
}

export async function applyWorkspaceOverridesToCart(params: { cart: LuaSourceRegistry; storage: StorageService; includeServer?: boolean; projectRootPath: string }): Promise<Set<string>> {
	return await applyWorkspaceOverridesToRegistry({
		registry: params.cart,
		storage: params.storage,
		includeServer: params.includeServer,
		projectRootPath: params.projectRootPath,
	});
}

async function discardWorkspaceDirtyPath(storage: StorageService, root: string, cartPath: string): Promise<void> {
	const dirtyPath = buildWorkspaceDirtyEntryPath(root, cartPath);
	const storageKey = buildWorkspaceStorageKey(root, dirtyPath);
	storage.removeItem(storageKey);
	await deleteWorkspaceServerFile(dirtyPath);
}

async function discardWorkspaceCanonicalPath(storage: StorageService, root: string, cartPath: string): Promise<void> {
	const storageKey = buildWorkspaceStorageKey(root, cartPath);
	storage.removeItem(storageKey);
	await deleteWorkspaceServerFile(resolveWorkspacePath(cartPath, root));
}

export async function clearWorkspaceArtifacts(cart: LuaSourceRegistry, storage: StorageService): Promise<void> {
	const root = machineManager.sourceState.cartProjectRootPath;
	for (const asset of cart.records) {
		if (asset.generated) {
			continue;
		}
		await discardWorkspaceDirtyPath(storage, root, asset.source_path);
		await discardWorkspaceCanonicalPath(storage, root, asset.source_path);
	}
	const statePath = joinWorkspacePaths(root, WORKSPACE_METADATA_DIR, WORKSPACE_STATE_FILE);
	const stateKey = buildWorkspaceStorageKey(root, statePath);
	storage.removeItem(stateKey);
	await deleteWorkspaceServerFile(statePath);
}

async function clearWorkspaceDirtyFiles(cart: LuaSourceRegistry, storage: StorageService): Promise<void> {
	const root = machineManager.sourceState.cartProjectRootPath;
	const scratchPaths = await collectScratchWorkspaceDirtyPaths(root);
	for (const asset of cart.records) {
		if (asset.generated) {
			continue;
		}
		await discardWorkspaceDirtyPath(storage, root, asset.source_path);
	}
	for (const dirtyPath of scratchPaths) {
		const storageKey = buildWorkspaceStorageKey(root, dirtyPath);
		storage.removeItem(storageKey);
		await deleteWorkspaceServerFile(dirtyPath);
	}
}

// Re-applies the saved (canonical) sources and clears dirty buffers, returning the
// workspace to its on-disk baseline. Shared tail of the reset/nuke flows.
async function reapplyWorkspaceBaseline(registry: LuaSourceRegistry): Promise<void> {
	await applyWorkspaceSourceOverrides({
		registry,
		storage: machineManager.platform.storage,
		includeServer: false,
		projectRootPath: machineManager.sourceState.cartProjectRootPath,
		timestampNow: machineManager.platform.clock.dateNow(),
	});
	clearWorkspaceDirtyBuffers();
}

export async function resetWorkspaceDirtyBuffersAndStorage(): Promise<void> {
	const registry = resolveEditableCartLuaSources();
	await clearWorkspaceDirtyFiles(registry, machineManager.platform.storage);
	await reapplyWorkspaceBaseline(registry);
}

export async function nukeWorkspaceState(): Promise<void> {
	const registry = resolveEditableCartLuaSources();
	await clearWorkspaceArtifacts(registry, machineManager.platform.storage);
	await reapplyWorkspaceBaseline(registry);
}

export function listResources(): ResourceDescriptor[] {
	const descriptorsByPath = new Map<string, ResourceDescriptor>();
	for (const registry of machineManager.sourceState.luaSourceRegistries) {
		for (const asset of registry.records) {
			const path = asset.source_path;
			if (descriptorsByPath.has(path)) {
				continue;
			}
			descriptorsByPath.set(path, { path, type: asset.type, asset_id: asset.resid, readOnly: asset.generated });
		}
	}
	const descriptors = Array.from(descriptorsByPath.values());
	descriptors.sort((left, right) => left.path.localeCompare(right.path));
	return descriptors;
}
