#pragma once

#include "machine/devices/gx/character_plane.h"

#include <array>

namespace bmsx {

constexpr size_t GX_CHARACTER_PLANE_CELL_TEXTURE_WIDTH = 256u;
constexpr size_t GX_CHARACTER_PLANE_CELL_TEXTURE_HEIGHT = GX_CHARACTER_PLANE_ROWS;
constexpr size_t GX_CHARACTER_PLANE_CELL_TEXTURE_BYTES = GX_CHARACTER_PLANE_CELL_TEXTURE_WIDTH * GX_CHARACTER_PLANE_CELL_TEXTURE_HEIGHT * 4u;
constexpr size_t GX_CHARACTER_PLANE_GLYPH_TEXTURE_COLUMNS = 16u;
constexpr size_t GX_CHARACTER_PLANE_GLYPH_TEXTURE_WIDTH = GX_CHARACTER_PLANE_GLYPH_TEXTURE_COLUMNS * GX_CHARACTER_PLANE_GLYPH_WIDTH;
constexpr size_t GX_CHARACTER_PLANE_GLYPH_TEXTURE_HEIGHT = (GX_CHARACTER_PLANE_GLYPH_WORDS / GX_CHARACTER_PLANE_GLYPH_TEXTURE_COLUMNS) * GX_CHARACTER_PLANE_GLYPH_HEIGHT;
constexpr size_t GX_CHARACTER_PLANE_GLYPH_TEXTURE_BYTES = GX_CHARACTER_PLANE_GLYPH_TEXTURE_WIDTH * GX_CHARACTER_PLANE_GLYPH_TEXTURE_HEIGHT * 4u;
constexpr size_t GX_CHARACTER_PLANE_PALETTE_TEXTURE_WIDTH = 64u;
constexpr size_t GX_CHARACTER_PLANE_PALETTE_TEXTURE_HEIGHT = 1u;
constexpr size_t GX_CHARACTER_PLANE_PALETTE_TEXTURE_BYTES = GX_CHARACTER_PLANE_PALETTE_TEXTURE_WIDTH * 4u;

void writeGxCharacterPlanePaletteTexture(
	const std::array<u8, GX_CHARACTER_PLANE_PALETTE_BYTES>& source,
	std::array<u8, GX_CHARACTER_PLANE_PALETTE_TEXTURE_BYTES>& target);
void writeGxCharacterPlaneGlyphTexture(
	const std::array<u8, GX_CHARACTER_PLANE_GLYPH_BYTES>& source,
	std::array<u8, GX_CHARACTER_PLANE_GLYPH_TEXTURE_BYTES>& target);
void writeGxCharacterPlaneCellTexture(
	const std::array<u8, GX_CHARACTER_PLANE_CELL_BYTES>& source,
	std::array<u8, GX_CHARACTER_PLANE_CELL_TEXTURE_BYTES>& target);

} // namespace bmsx
