module<const>

return {
	board_id = 0x53545544,
	board_ram_bytes = 0x00100000,
	descriptor_magic = 0x53584d42,
	descriptor_version = 1,

	header_magic = 0,
	header_version = 1,
	header_revision = 2,
	header_flags = 3,
	header_object_count = 4,
	header_component_count = 5,
	header_selected_object_handle = 6,
	header_selected_component_handle = 7,
	header_hover_object_handle = 8,
	header_active_space_token_lo = 9,
	header_active_space_token_hi = 10,
	header_view_origin_x = 11,
	header_view_origin_y = 12,
	header_view_width = 13,
	header_view_height = 14,
	header_pointer_x = 15,
	header_pointer_y = 16,
	header_applied_command_sequence = 17,
	header_object_table_word_offset = 18,
	header_object_stride_words = 19,
	header_component_table_word_offset = 20,
	header_component_stride_words = 21,
	header_command_word_offset = 22,
	header_command_word_count = 23,
	header_game_slot = 24,
	header_board_slot = 25,
	header_overlay_origin = 26,
	header_game_origin = 27,
	header_word_count = 32,

	flag_gameplay_running = 0x00000001,
	flag_pointer_primary = 0x00000002,
	flag_translating = 0x00000004,

	object_handle = 0,
	object_definition_token_lo = 1,
	object_definition_token_hi = 2,
	object_space_token_lo = 3,
	object_space_token_hi = 4,
	object_parent_handle = 5,
	object_x = 6,
	object_y = 7,
	object_z = 8,
	object_sx = 9,
	object_sy = 10,
	object_pick_left = 11,
	object_pick_top = 12,
	object_pick_right = 13,
	object_pick_bottom = 14,
	object_flags = 15,
	object_first_component = 16,
	object_component_count = 17,
	object_visual_order = 18,
	object_stride_words = 20,

	object_flag_active = 0x00000001,
	object_flag_visible = 0x00000002,
	object_flag_selected = 0x00000004,
	object_flag_hover = 0x00000008,
	object_flag_has_pick_bounds = 0x00000010,

	component_handle = 0,
	component_owner_handle = 1,
	component_class_word = 2,
	component_local_id_kind = 3,
	component_local_id_lo = 4,
	component_local_id_hi = 5,
	component_flags = 6,
	component_pick_left = 7,
	component_pick_top = 8,
	component_pick_right = 9,
	component_pick_bottom = 10,
	component_visual_order = 11,
	component_stride_words = 12,

	component_local_id_none = 0,
	component_local_id_f32 = 1,
	component_local_id_token = 2,
	component_flag_enabled = 0x00000001,
	component_flag_has_pick_bounds = 0x00000002,
	component_flag_visual = 0x00000004,
	component_flag_selected = 0x00000008,

	command_word_offset = 0x0003ffc0,
	command_word_count = 16,
	command_sequence = 0,
	command_opcode = 1,
	command_object_handle = 2,
	command_component_handle = 3,
	command_arg0 = 4,
	command_arg1 = 5,
	command_arg2 = 6,
	command_arg3 = 7,
	command_token_lo = 8,
	command_token_hi = 9,

	command_select = 1,
	command_set_pos = 2,
	command_set_visible = 3,
	command_set_component_enabled = 4,
	command_set_gameplay_running = 5,
	command_spawn = 6,
	command_dispose = 7,
}
