import { IO_BASE, IO_WORD_SIZE, VDP_CMD_ARG_COUNT } from './memory_map';

export const IO_CMD_VDP_CLEAR = 0x10;
export const IO_CMD_VDP_FILL_RECT = 0x11;
export const IO_CMD_VDP_BLIT = 0x12;
export const IO_CMD_VDP_DRAW_LINE = 0x13;
export const IO_CMD_VDP_GLYPH_RUN = 0x14;
export const IO_CMD_VDP_TILE_RUN = 0x15;

export const IO_VDP_TILE_HANDLE_NONE = 0xffffffff >>> 0;

export const IO_SYS_BASE_INDEX = 0;
export const IO_SYS_BOOT_CART_INDEX = IO_SYS_BASE_INDEX;
export const IO_SYS_CART_BOOTREADY_INDEX = IO_SYS_BASE_INDEX + 1;
export const IO_SYS_SIZE = 2;
export const IO_VDP_BASE_INDEX = IO_SYS_BASE_INDEX + IO_SYS_SIZE;
export const IO_VDP_DITHER_INDEX = IO_VDP_BASE_INDEX;
export const IO_VDP_PRIMARY_ATLAS_ID_INDEX = IO_VDP_BASE_INDEX + 1;
export const IO_VDP_SECONDARY_ATLAS_ID_INDEX = IO_VDP_BASE_INDEX + 2;
export const IO_VDP_RD_SURFACE_INDEX = IO_VDP_BASE_INDEX + 3;
export const IO_VDP_RD_X_INDEX = IO_VDP_BASE_INDEX + 4;
export const IO_VDP_RD_Y_INDEX = IO_VDP_BASE_INDEX + 5;
export const IO_VDP_RD_MODE_INDEX = IO_VDP_BASE_INDEX + 6;
export const IO_VDP_RD_STATUS_INDEX = IO_VDP_BASE_INDEX + 7;
export const IO_VDP_RD_DATA_INDEX = IO_VDP_BASE_INDEX + 8;
export const IO_VDP_CMD_INDEX = IO_VDP_BASE_INDEX + 9;
export const IO_VDP_CMD_ARG0_INDEX = IO_VDP_BASE_INDEX + 10;
export const IO_VDP_CMD_ARG_COUNT = VDP_CMD_ARG_COUNT;
export const IO_VDP_FIFO_INDEX = IO_VDP_CMD_ARG0_INDEX + IO_VDP_CMD_ARG_COUNT;
export const IO_VDP_FIFO_CTRL_INDEX = IO_VDP_FIFO_INDEX + 1;
export const IO_VDP_SIZE = 12 + IO_VDP_CMD_ARG_COUNT;

export const IO_IRQ_BASE_INDEX = IO_VDP_BASE_INDEX + IO_VDP_SIZE;
export const IO_IRQ_FLAGS_INDEX = IO_IRQ_BASE_INDEX;
export const IO_IRQ_ACK_INDEX = IO_IRQ_BASE_INDEX + 1;
export const IO_IRQ_SIZE = 2;

export const IO_DMA_BASE_INDEX = IO_IRQ_BASE_INDEX + IO_IRQ_SIZE;
export const IO_DMA_SRC_INDEX = IO_DMA_BASE_INDEX;
export const IO_DMA_DST_INDEX = IO_DMA_BASE_INDEX + 1;
export const IO_DMA_LEN_INDEX = IO_DMA_BASE_INDEX + 2;
export const IO_DMA_CTRL_INDEX = IO_DMA_BASE_INDEX + 3;
export const IO_DMA_STATUS_INDEX = IO_DMA_BASE_INDEX + 4;
export const IO_DMA_WRITTEN_INDEX = IO_DMA_BASE_INDEX + 5;
export const IO_DMA_SIZE = 6;

export const IO_IMG_BASE_INDEX = IO_DMA_BASE_INDEX + IO_DMA_SIZE;
export const IO_IMG_SRC_INDEX = IO_IMG_BASE_INDEX;
export const IO_IMG_LEN_INDEX = IO_IMG_BASE_INDEX + 1;
export const IO_IMG_DST_INDEX = IO_IMG_BASE_INDEX + 2;
export const IO_IMG_CAP_INDEX = IO_IMG_BASE_INDEX + 3;
export const IO_IMG_CTRL_INDEX = IO_IMG_BASE_INDEX + 4;
export const IO_IMG_STATUS_INDEX = IO_IMG_BASE_INDEX + 5;
export const IO_IMG_WRITTEN_INDEX = IO_IMG_BASE_INDEX + 6;
export const IO_IMG_SIZE = 7;

export const IO_VDP_STATUS_INDEX = IO_IMG_BASE_INDEX + IO_IMG_SIZE;
export const IO_VDP_STATUS_SIZE = 1;

export const IO_PAYLOAD_WRITE_PTR_INDEX = IO_VDP_STATUS_INDEX + IO_VDP_STATUS_SIZE;
export const IO_PAYLOAD_ALLOC_INDEX = IO_PAYLOAD_WRITE_PTR_INDEX + 1;
export const IO_PAYLOAD_DATA_INDEX = IO_PAYLOAD_ALLOC_INDEX + 1;
export const IO_PAYLOAD_BUFFER_BASE_INDEX = IO_PAYLOAD_DATA_INDEX + 1;
export const IO_PAYLOAD_CAPACITY = 16384;
export const IO_SLOT_COUNT = IO_PAYLOAD_BUFFER_BASE_INDEX + IO_PAYLOAD_CAPACITY;

export const IO_ARG_STRIDE = IO_WORD_SIZE;
export const IO_PAYLOAD_WRITE_PTR_ADDR = IO_BASE + IO_PAYLOAD_WRITE_PTR_INDEX * IO_WORD_SIZE;
export const IO_PAYLOAD_ALLOC_ADDR = IO_BASE + IO_PAYLOAD_ALLOC_INDEX * IO_WORD_SIZE;
export const IO_PAYLOAD_DATA_ADDR = IO_BASE + IO_PAYLOAD_DATA_INDEX * IO_WORD_SIZE;
export const IO_PAYLOAD_BUFFER_BASE = IO_BASE + IO_PAYLOAD_BUFFER_BASE_INDEX * IO_WORD_SIZE;

export const IO_SYS_BASE = IO_BASE + IO_SYS_BASE_INDEX * IO_WORD_SIZE;
export const IO_SYS_BOOT_CART = IO_BASE + IO_SYS_BOOT_CART_INDEX * IO_WORD_SIZE;
export const IO_SYS_CART_BOOTREADY = IO_BASE + IO_SYS_CART_BOOTREADY_INDEX * IO_WORD_SIZE;
export const IO_VDP_BASE = IO_BASE + IO_VDP_BASE_INDEX * IO_WORD_SIZE;
export const IO_VDP_DITHER = IO_BASE + IO_VDP_DITHER_INDEX * IO_WORD_SIZE;
export const IO_VDP_PRIMARY_ATLAS_ID = IO_BASE + IO_VDP_PRIMARY_ATLAS_ID_INDEX * IO_WORD_SIZE;
export const IO_VDP_SECONDARY_ATLAS_ID = IO_BASE + IO_VDP_SECONDARY_ATLAS_ID_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_SURFACE = IO_BASE + IO_VDP_RD_SURFACE_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_X = IO_BASE + IO_VDP_RD_X_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_Y = IO_BASE + IO_VDP_RD_Y_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_MODE = IO_BASE + IO_VDP_RD_MODE_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_STATUS = IO_BASE + IO_VDP_RD_STATUS_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_DATA = IO_BASE + IO_VDP_RD_DATA_INDEX * IO_WORD_SIZE;
export const IO_VDP_CMD = IO_BASE + IO_VDP_CMD_INDEX * IO_WORD_SIZE;
export const IO_VDP_CMD_ARG0 = IO_BASE + IO_VDP_CMD_ARG0_INDEX * IO_WORD_SIZE;
export const IO_VDP_FIFO = IO_BASE + IO_VDP_FIFO_INDEX * IO_WORD_SIZE;
export const IO_VDP_FIFO_CTRL = IO_BASE + IO_VDP_FIFO_CTRL_INDEX * IO_WORD_SIZE;

export const IO_IRQ_BASE = IO_BASE + IO_IRQ_BASE_INDEX * IO_WORD_SIZE;
export const IO_IRQ_FLAGS = IO_BASE + IO_IRQ_FLAGS_INDEX * IO_WORD_SIZE;
export const IO_IRQ_ACK = IO_BASE + IO_IRQ_ACK_INDEX * IO_WORD_SIZE;

export const IO_DMA_BASE = IO_BASE + IO_DMA_BASE_INDEX * IO_WORD_SIZE;
export const IO_DMA_SRC = IO_BASE + IO_DMA_SRC_INDEX * IO_WORD_SIZE;
export const IO_DMA_DST = IO_BASE + IO_DMA_DST_INDEX * IO_WORD_SIZE;
export const IO_DMA_LEN = IO_BASE + IO_DMA_LEN_INDEX * IO_WORD_SIZE;
export const IO_DMA_CTRL = IO_BASE + IO_DMA_CTRL_INDEX * IO_WORD_SIZE;
export const IO_DMA_STATUS = IO_BASE + IO_DMA_STATUS_INDEX * IO_WORD_SIZE;
export const IO_DMA_WRITTEN = IO_BASE + IO_DMA_WRITTEN_INDEX * IO_WORD_SIZE;

export const IO_IMG_BASE = IO_BASE + IO_IMG_BASE_INDEX * IO_WORD_SIZE;
export const IO_IMG_SRC = IO_BASE + IO_IMG_SRC_INDEX * IO_WORD_SIZE;
export const IO_IMG_LEN = IO_BASE + IO_IMG_LEN_INDEX * IO_WORD_SIZE;
export const IO_IMG_DST = IO_BASE + IO_IMG_DST_INDEX * IO_WORD_SIZE;
export const IO_IMG_CAP = IO_BASE + IO_IMG_CAP_INDEX * IO_WORD_SIZE;
export const IO_IMG_CTRL = IO_BASE + IO_IMG_CTRL_INDEX * IO_WORD_SIZE;
export const IO_IMG_STATUS = IO_BASE + IO_IMG_STATUS_INDEX * IO_WORD_SIZE;
export const IO_IMG_WRITTEN = IO_BASE + IO_IMG_WRITTEN_INDEX * IO_WORD_SIZE;
export const IO_VDP_STATUS = IO_BASE + IO_VDP_STATUS_INDEX * IO_WORD_SIZE;

export const IRQ_DMA_DONE = 1 << 0;
export const IRQ_DMA_ERROR = 1 << 1;
export const IRQ_IMG_DONE = 1 << 2;
export const IRQ_IMG_ERROR = 1 << 3;
export const IRQ_VBLANK = 1 << 4;
export const IRQ_REINIT = 1 << 5;
export const IRQ_NEWGAME = 1 << 6;

export const DMA_CTRL_START = 1 << 0;
export const DMA_CTRL_STRICT = 1 << 1;
export const DMA_STATUS_BUSY = 1 << 0;
export const DMA_STATUS_DONE = 1 << 1;
export const DMA_STATUS_ERROR = 1 << 2;
export const DMA_STATUS_CLIPPED = 1 << 3;
export const DMA_STATUS_REJECTED = 1 << 4;

export const IMG_CTRL_START = 1 << 0;
export const IMG_STATUS_BUSY = 1 << 0;
export const IMG_STATUS_DONE = 1 << 1;
export const IMG_STATUS_ERROR = 1 << 2;
export const IMG_STATUS_CLIPPED = 1 << 3;
export const IMG_STATUS_REJECTED = 1 << 4;

export const VDP_ATLAS_ID_NONE = 0xffffffff >>> 0;
export const VDP_RD_MODE_RGBA8888 = 0;
export const VDP_RD_STATUS_READY = 1 << 0;
export const VDP_RD_STATUS_OVERFLOW = 1 << 1;
export const VDP_FIFO_CTRL_SEAL = 1 << 0;
export const VDP_STATUS_VBLANK = 1 << 0;
export const VDP_STATUS_SUBMIT_BUSY = 1 << 1;
// Sticky latch: set when a VDP submit attempt is rejected because the submit path is busy,
// and cleared only when a later VDP submit attempt is accepted.
export const VDP_STATUS_SUBMIT_REJECTED = 1 << 2;
