import { IO_BASE, IO_WORD_SIZE, VDP_CMD_ARG_COUNT } from './memory_map';

export const IO_CMD_VDP_CLEAR = 0x10;
export const IO_CMD_VDP_FILL_RECT = 0x11;
export const IO_CMD_VDP_BLIT = 0x12;
export const IO_CMD_VDP_DRAW_LINE = 0x13;
export const IO_CMD_VDP_GLYPH_RUN = 0x14;
export const IO_CMD_VDP_TILE_RUN = 0x15;

export const IO_VDP_TILE_HANDLE_NONE = 0xffffffff >>> 0;

export const IO_SYS_BASE_INDEX = 0;
export const IO_SYS_BOOT_CART_INDEX = IO_SYS_BASE_INDEX;
export const IO_SYS_CART_BOOTREADY_INDEX = IO_SYS_BASE_INDEX + 1;
export const IO_SYS_SIZE = 2;
export const IO_VDP_BASE_INDEX = IO_SYS_BASE_INDEX + IO_SYS_SIZE;
export const IO_VDP_DITHER_INDEX = IO_VDP_BASE_INDEX;
export const IO_VDP_PRIMARY_ATLAS_ID_INDEX = IO_VDP_BASE_INDEX + 1;
export const IO_VDP_SECONDARY_ATLAS_ID_INDEX = IO_VDP_BASE_INDEX + 2;
export const IO_VDP_RD_SURFACE_INDEX = IO_VDP_BASE_INDEX + 3;
export const IO_VDP_RD_X_INDEX = IO_VDP_BASE_INDEX + 4;
export const IO_VDP_RD_Y_INDEX = IO_VDP_BASE_INDEX + 5;
export const IO_VDP_RD_MODE_INDEX = IO_VDP_BASE_INDEX + 6;
export const IO_VDP_RD_STATUS_INDEX = IO_VDP_BASE_INDEX + 7;
export const IO_VDP_RD_DATA_INDEX = IO_VDP_BASE_INDEX + 8;
export const IO_VDP_CMD_INDEX = IO_VDP_BASE_INDEX + 9;
export const IO_VDP_CMD_ARG0_INDEX = IO_VDP_BASE_INDEX + 10;
export const IO_VDP_CMD_ARG_COUNT = VDP_CMD_ARG_COUNT;
export const IO_VDP_FIFO_INDEX = IO_VDP_CMD_ARG0_INDEX + IO_VDP_CMD_ARG_COUNT;
export const IO_VDP_FIFO_CTRL_INDEX = IO_VDP_FIFO_INDEX + 1;
export const IO_VDP_SIZE = 12 + IO_VDP_CMD_ARG_COUNT;

export const IO_IRQ_BASE_INDEX = IO_VDP_BASE_INDEX + IO_VDP_SIZE;
export const IO_IRQ_FLAGS_INDEX = IO_IRQ_BASE_INDEX;
export const IO_IRQ_ACK_INDEX = IO_IRQ_BASE_INDEX + 1;
export const IO_IRQ_SIZE = 2;

export const IO_DMA_BASE_INDEX = IO_IRQ_BASE_INDEX + IO_IRQ_SIZE;
export const IO_DMA_SRC_INDEX = IO_DMA_BASE_INDEX;
export const IO_DMA_DST_INDEX = IO_DMA_BASE_INDEX + 1;
export const IO_DMA_LEN_INDEX = IO_DMA_BASE_INDEX + 2;
export const IO_DMA_CTRL_INDEX = IO_DMA_BASE_INDEX + 3;
export const IO_DMA_STATUS_INDEX = IO_DMA_BASE_INDEX + 4;
export const IO_DMA_WRITTEN_INDEX = IO_DMA_BASE_INDEX + 5;
export const IO_DMA_SIZE = 6;

export const IO_IMG_BASE_INDEX = IO_DMA_BASE_INDEX + IO_DMA_SIZE;
export const IO_IMG_SRC_INDEX = IO_IMG_BASE_INDEX;
export const IO_IMG_LEN_INDEX = IO_IMG_BASE_INDEX + 1;
export const IO_IMG_DST_INDEX = IO_IMG_BASE_INDEX + 2;
export const IO_IMG_CAP_INDEX = IO_IMG_BASE_INDEX + 3;
export const IO_IMG_CTRL_INDEX = IO_IMG_BASE_INDEX + 4;
export const IO_IMG_STATUS_INDEX = IO_IMG_BASE_INDEX + 5;
export const IO_IMG_WRITTEN_INDEX = IO_IMG_BASE_INDEX + 6;
export const IO_IMG_SIZE = 7;

export const IO_VDP_STATUS_INDEX = IO_IMG_BASE_INDEX + IO_IMG_SIZE;
export const IO_VDP_STATUS_SIZE = 1;

export const IO_GEO_BASE_INDEX = IO_VDP_STATUS_INDEX + IO_VDP_STATUS_SIZE;
export const IO_GEO_SRC0_INDEX = IO_GEO_BASE_INDEX;
export const IO_GEO_SRC1_INDEX = IO_GEO_BASE_INDEX + 1;
export const IO_GEO_SRC2_INDEX = IO_GEO_BASE_INDEX + 2;
export const IO_GEO_DST0_INDEX = IO_GEO_BASE_INDEX + 3;
export const IO_GEO_DST1_INDEX = IO_GEO_BASE_INDEX + 4;
export const IO_GEO_COUNT_INDEX = IO_GEO_BASE_INDEX + 5;
export const IO_GEO_CMD_INDEX = IO_GEO_BASE_INDEX + 6;
export const IO_GEO_CTRL_INDEX = IO_GEO_BASE_INDEX + 7;
export const IO_GEO_STATUS_INDEX = IO_GEO_BASE_INDEX + 8;
export const IO_GEO_PARAM0_INDEX = IO_GEO_BASE_INDEX + 9;
export const IO_GEO_PARAM1_INDEX = IO_GEO_BASE_INDEX + 10;
export const IO_GEO_STRIDE0_INDEX = IO_GEO_BASE_INDEX + 11;
export const IO_GEO_STRIDE1_INDEX = IO_GEO_BASE_INDEX + 12;
export const IO_GEO_STRIDE2_INDEX = IO_GEO_BASE_INDEX + 13;
export const IO_GEO_PROCESSED_INDEX = IO_GEO_BASE_INDEX + 14;
export const IO_GEO_FAULT_INDEX = IO_GEO_BASE_INDEX + 15;
export const IO_GEO_SIZE = 16;

export const IO_PAYLOAD_WRITE_PTR_INDEX = IO_GEO_BASE_INDEX + IO_GEO_SIZE;
export const IO_PAYLOAD_ALLOC_INDEX = IO_PAYLOAD_WRITE_PTR_INDEX + 1;
export const IO_PAYLOAD_DATA_INDEX = IO_PAYLOAD_ALLOC_INDEX + 1;
export const IO_PAYLOAD_BUFFER_BASE_INDEX = IO_PAYLOAD_DATA_INDEX + 1;
export const IO_PAYLOAD_CAPACITY = 16384;
export const IO_SLOT_COUNT = IO_PAYLOAD_BUFFER_BASE_INDEX + IO_PAYLOAD_CAPACITY;

export const IO_ARG_STRIDE = IO_WORD_SIZE;
export const IO_PAYLOAD_WRITE_PTR_ADDR = IO_BASE + IO_PAYLOAD_WRITE_PTR_INDEX * IO_WORD_SIZE;
export const IO_PAYLOAD_ALLOC_ADDR = IO_BASE + IO_PAYLOAD_ALLOC_INDEX * IO_WORD_SIZE;
export const IO_PAYLOAD_DATA_ADDR = IO_BASE + IO_PAYLOAD_DATA_INDEX * IO_WORD_SIZE;
export const IO_PAYLOAD_BUFFER_BASE = IO_BASE + IO_PAYLOAD_BUFFER_BASE_INDEX * IO_WORD_SIZE;

export const IO_SYS_BASE = IO_BASE + IO_SYS_BASE_INDEX * IO_WORD_SIZE;
export const IO_SYS_BOOT_CART = IO_BASE + IO_SYS_BOOT_CART_INDEX * IO_WORD_SIZE;
export const IO_SYS_CART_BOOTREADY = IO_BASE + IO_SYS_CART_BOOTREADY_INDEX * IO_WORD_SIZE;
export const IO_VDP_BASE = IO_BASE + IO_VDP_BASE_INDEX * IO_WORD_SIZE;
export const IO_VDP_DITHER = IO_BASE + IO_VDP_DITHER_INDEX * IO_WORD_SIZE;
export const IO_VDP_PRIMARY_ATLAS_ID = IO_BASE + IO_VDP_PRIMARY_ATLAS_ID_INDEX * IO_WORD_SIZE;
export const IO_VDP_SECONDARY_ATLAS_ID = IO_BASE + IO_VDP_SECONDARY_ATLAS_ID_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_SURFACE = IO_BASE + IO_VDP_RD_SURFACE_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_X = IO_BASE + IO_VDP_RD_X_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_Y = IO_BASE + IO_VDP_RD_Y_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_MODE = IO_BASE + IO_VDP_RD_MODE_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_STATUS = IO_BASE + IO_VDP_RD_STATUS_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_DATA = IO_BASE + IO_VDP_RD_DATA_INDEX * IO_WORD_SIZE;
export const IO_VDP_CMD = IO_BASE + IO_VDP_CMD_INDEX * IO_WORD_SIZE;
export const IO_VDP_CMD_ARG0 = IO_BASE + IO_VDP_CMD_ARG0_INDEX * IO_WORD_SIZE;
export const IO_VDP_FIFO = IO_BASE + IO_VDP_FIFO_INDEX * IO_WORD_SIZE;
export const IO_VDP_FIFO_CTRL = IO_BASE + IO_VDP_FIFO_CTRL_INDEX * IO_WORD_SIZE;

export const IO_IRQ_BASE = IO_BASE + IO_IRQ_BASE_INDEX * IO_WORD_SIZE;
export const IO_IRQ_FLAGS = IO_BASE + IO_IRQ_FLAGS_INDEX * IO_WORD_SIZE;
export const IO_IRQ_ACK = IO_BASE + IO_IRQ_ACK_INDEX * IO_WORD_SIZE;

export const IO_DMA_BASE = IO_BASE + IO_DMA_BASE_INDEX * IO_WORD_SIZE;
export const IO_DMA_SRC = IO_BASE + IO_DMA_SRC_INDEX * IO_WORD_SIZE;
export const IO_DMA_DST = IO_BASE + IO_DMA_DST_INDEX * IO_WORD_SIZE;
export const IO_DMA_LEN = IO_BASE + IO_DMA_LEN_INDEX * IO_WORD_SIZE;
export const IO_DMA_CTRL = IO_BASE + IO_DMA_CTRL_INDEX * IO_WORD_SIZE;
export const IO_DMA_STATUS = IO_BASE + IO_DMA_STATUS_INDEX * IO_WORD_SIZE;
export const IO_DMA_WRITTEN = IO_BASE + IO_DMA_WRITTEN_INDEX * IO_WORD_SIZE;

export const IO_IMG_BASE = IO_BASE + IO_IMG_BASE_INDEX * IO_WORD_SIZE;
export const IO_IMG_SRC = IO_BASE + IO_IMG_SRC_INDEX * IO_WORD_SIZE;
export const IO_IMG_LEN = IO_BASE + IO_IMG_LEN_INDEX * IO_WORD_SIZE;
export const IO_IMG_DST = IO_BASE + IO_IMG_DST_INDEX * IO_WORD_SIZE;
export const IO_IMG_CAP = IO_BASE + IO_IMG_CAP_INDEX * IO_WORD_SIZE;
export const IO_IMG_CTRL = IO_BASE + IO_IMG_CTRL_INDEX * IO_WORD_SIZE;
export const IO_IMG_STATUS = IO_BASE + IO_IMG_STATUS_INDEX * IO_WORD_SIZE;
export const IO_IMG_WRITTEN = IO_BASE + IO_IMG_WRITTEN_INDEX * IO_WORD_SIZE;
export const IO_VDP_STATUS = IO_BASE + IO_VDP_STATUS_INDEX * IO_WORD_SIZE;
export const IO_GEO_BASE = IO_BASE + IO_GEO_BASE_INDEX * IO_WORD_SIZE;
export const IO_GEO_SRC0 = IO_BASE + IO_GEO_SRC0_INDEX * IO_WORD_SIZE;
export const IO_GEO_SRC1 = IO_BASE + IO_GEO_SRC1_INDEX * IO_WORD_SIZE;
export const IO_GEO_SRC2 = IO_BASE + IO_GEO_SRC2_INDEX * IO_WORD_SIZE;
export const IO_GEO_DST0 = IO_BASE + IO_GEO_DST0_INDEX * IO_WORD_SIZE;
export const IO_GEO_DST1 = IO_BASE + IO_GEO_DST1_INDEX * IO_WORD_SIZE;
export const IO_GEO_COUNT = IO_BASE + IO_GEO_COUNT_INDEX * IO_WORD_SIZE;
export const IO_GEO_CMD = IO_BASE + IO_GEO_CMD_INDEX * IO_WORD_SIZE;
export const IO_GEO_CTRL = IO_BASE + IO_GEO_CTRL_INDEX * IO_WORD_SIZE;
export const IO_GEO_STATUS = IO_BASE + IO_GEO_STATUS_INDEX * IO_WORD_SIZE;
export const IO_GEO_PARAM0 = IO_BASE + IO_GEO_PARAM0_INDEX * IO_WORD_SIZE;
export const IO_GEO_PARAM1 = IO_BASE + IO_GEO_PARAM1_INDEX * IO_WORD_SIZE;
export const IO_GEO_STRIDE0 = IO_BASE + IO_GEO_STRIDE0_INDEX * IO_WORD_SIZE;
export const IO_GEO_STRIDE1 = IO_BASE + IO_GEO_STRIDE1_INDEX * IO_WORD_SIZE;
export const IO_GEO_STRIDE2 = IO_BASE + IO_GEO_STRIDE2_INDEX * IO_WORD_SIZE;
export const IO_GEO_PROCESSED = IO_BASE + IO_GEO_PROCESSED_INDEX * IO_WORD_SIZE;
export const IO_GEO_FAULT = IO_BASE + IO_GEO_FAULT_INDEX * IO_WORD_SIZE;

export const IRQ_DMA_DONE = 1 << 0;
export const IRQ_DMA_ERROR = 1 << 1;
export const IRQ_IMG_DONE = 1 << 2;
export const IRQ_IMG_ERROR = 1 << 3;
export const IRQ_VBLANK = 1 << 4;
export const IRQ_REINIT = 1 << 5;
export const IRQ_NEWGAME = 1 << 6;
export const IRQ_GEO_DONE = 1 << 7;
export const IRQ_GEO_ERROR = 1 << 8;

export const DMA_CTRL_START = 1 << 0;
export const DMA_CTRL_STRICT = 1 << 1;
export const DMA_STATUS_BUSY = 1 << 0;
export const DMA_STATUS_DONE = 1 << 1;
export const DMA_STATUS_ERROR = 1 << 2;
export const DMA_STATUS_CLIPPED = 1 << 3;
export const DMA_STATUS_REJECTED = 1 << 4;

export const IMG_CTRL_START = 1 << 0;
export const IMG_STATUS_BUSY = 1 << 0;
export const IMG_STATUS_DONE = 1 << 1;
export const IMG_STATUS_ERROR = 1 << 2;
export const IMG_STATUS_CLIPPED = 1 << 3;
export const IMG_STATUS_REJECTED = 1 << 4;

export const GEO_CTRL_START = 1 << 0;
export const GEO_CTRL_ABORT = 1 << 1;
export const GEO_STATUS_BUSY = 1 << 0;
export const GEO_STATUS_DONE = 1 << 1;
export const GEO_STATUS_ERROR = 1 << 2;
export const GEO_STATUS_REJECTED = 1 << 3;

export const IO_CMD_GEO_XFORM2_BATCH = 0x20;
export const IO_CMD_GEO_SAT2_BATCH = 0x21;
export const IO_CMD_GEO_XFORM3_BATCH = 0x30;
export const IO_CMD_GEO_PROJECT3_BATCH = 0x31;

export const GEO_INDEX_NONE = 0xffffffff >>> 0;
export const GEO_SHAPE_CONVEX_POLY = 1 << 0;
export const GEO_SAT_META_AXIS_MASK = 0xffff;
export const GEO_SAT_META_SHAPE_SHIFT = 16;
export const GEO_SAT_META_SHAPE_SRC = 0;
export const GEO_SAT_META_SHAPE_AUX = 1;

export const GEO_FAULT_ABORTED_BY_HOST = 0x0001;
export const GEO_FAULT_BAD_RECORD_ALIGNMENT = 0x0002;
export const GEO_FAULT_BAD_VERTEX_COUNT = 0x0003;
export const GEO_FAULT_SRC_RANGE = 0x0004;
export const GEO_FAULT_DST_RANGE = 0x0005;
export const GEO_FAULT_DESCRIPTOR_KIND = 0x0006;
export const GEO_FAULT_NUMERIC_OVERFLOW_INTERNAL = 0x0007;
export const GEO_FAULT_BAD_RECORD_FLAGS = 0x0008;

export const GEO_FAULT_REJECT_BUSY = 0x8001;
export const GEO_FAULT_REJECT_BAD_CMD = 0x8002;
export const GEO_FAULT_REJECT_BAD_STRIDE = 0x8003;
export const GEO_FAULT_REJECT_DST_NOT_RAM = 0x8004;
export const GEO_FAULT_REJECT_MISALIGNED_REGS = 0x8005;
export const GEO_FAULT_REJECT_BAD_REGISTER_COMBO = 0x8006;

export const VDP_ATLAS_ID_NONE = 0xffffffff >>> 0;
export const VDP_RD_MODE_RGBA8888 = 0;
export const VDP_RD_STATUS_READY = 1 << 0;
export const VDP_RD_STATUS_OVERFLOW = 1 << 1;
export const VDP_FIFO_CTRL_SEAL = 1 << 0;
export const VDP_STATUS_VBLANK = 1 << 0;
export const VDP_STATUS_SUBMIT_BUSY = 1 << 1;
// Sticky latch: set when a VDP submit attempt is rejected because the submit path is busy,
// and cleared only when a later VDP submit attempt is accepted.
export const VDP_STATUS_SUBMIT_REJECTED = 1 << 2;
