import { IO_BASE, IO_WORD_SIZE } from './memory_map';

export const IO_WRITE_PTR_INDEX = 0;
export const IO_BUFFER_BASE_INDEX = 1;
export const IO_COMMAND_STRIDE_WORDS = 4;
export const IO_ARG0_OFFSET_WORDS = 1;

export const IO_CMD_PRINT = 1;

export const IO_COMMAND_CAPACITY = 256;
export const IO_SYS_BASE_INDEX = IO_BUFFER_BASE_INDEX + IO_COMMAND_STRIDE_WORDS * IO_COMMAND_CAPACITY;
export const IO_SYS_BOOT_CART_INDEX = IO_SYS_BASE_INDEX;
export const IO_SYS_CART_BOOTREADY_INDEX = IO_SYS_BASE_INDEX + 1;
export const IO_SYS_SIZE = 2;
export const IO_VDP_BASE_INDEX = IO_SYS_BASE_INDEX + IO_SYS_SIZE;
export const IO_VDP_DITHER_INDEX = IO_VDP_BASE_INDEX;
export const IO_VDP_PRIMARY_ATLAS_ID_INDEX = IO_VDP_BASE_INDEX + 1;
export const IO_VDP_SECONDARY_ATLAS_ID_INDEX = IO_VDP_BASE_INDEX + 2;
export const IO_VDP_RD_SURFACE_INDEX = IO_VDP_BASE_INDEX + 3;
export const IO_VDP_RD_X_INDEX = IO_VDP_BASE_INDEX + 4;
export const IO_VDP_RD_Y_INDEX = IO_VDP_BASE_INDEX + 5;
export const IO_VDP_RD_MODE_INDEX = IO_VDP_BASE_INDEX + 6;
export const IO_VDP_RD_STATUS_INDEX = IO_VDP_BASE_INDEX + 7;
export const IO_VDP_RD_DATA_INDEX = IO_VDP_BASE_INDEX + 8;
export const IO_VDP_OAM_FRONT_BASE_INDEX = IO_VDP_BASE_INDEX + 9;
export const IO_VDP_OAM_BACK_BASE_INDEX = IO_VDP_BASE_INDEX + 10;
export const IO_VDP_OAM_FRONT_COUNT_INDEX = IO_VDP_BASE_INDEX + 11;
export const IO_VDP_OAM_BACK_COUNT_INDEX = IO_VDP_BASE_INDEX + 12;
export const IO_VDP_OAM_CAPACITY_INDEX = IO_VDP_BASE_INDEX + 13;
export const IO_VDP_OAM_ENTRY_WORDS_INDEX = IO_VDP_BASE_INDEX + 14;
export const IO_VDP_OAM_READ_SOURCE_INDEX = IO_VDP_BASE_INDEX + 15;
export const IO_VDP_OAM_COMMIT_SEQ_INDEX = IO_VDP_BASE_INDEX + 16;
export const IO_VDP_OAM_CMD_INDEX = IO_VDP_BASE_INDEX + 17;
export const IO_VDP_SIZE = 18;

export const IO_IRQ_BASE_INDEX = IO_VDP_BASE_INDEX + IO_VDP_SIZE;
export const IO_IRQ_FLAGS_INDEX = IO_IRQ_BASE_INDEX;
export const IO_IRQ_ACK_INDEX = IO_IRQ_BASE_INDEX + 1;
export const IO_IRQ_SIZE = 2;

export const IO_DMA_BASE_INDEX = IO_IRQ_BASE_INDEX + IO_IRQ_SIZE;
export const IO_DMA_SRC_INDEX = IO_DMA_BASE_INDEX;
export const IO_DMA_DST_INDEX = IO_DMA_BASE_INDEX + 1;
export const IO_DMA_LEN_INDEX = IO_DMA_BASE_INDEX + 2;
export const IO_DMA_CTRL_INDEX = IO_DMA_BASE_INDEX + 3;
export const IO_DMA_STATUS_INDEX = IO_DMA_BASE_INDEX + 4;
export const IO_DMA_WRITTEN_INDEX = IO_DMA_BASE_INDEX + 5;
export const IO_DMA_SIZE = 6;

export const IO_IMG_BASE_INDEX = IO_DMA_BASE_INDEX + IO_DMA_SIZE;
export const IO_IMG_SRC_INDEX = IO_IMG_BASE_INDEX;
export const IO_IMG_LEN_INDEX = IO_IMG_BASE_INDEX + 1;
export const IO_IMG_DST_INDEX = IO_IMG_BASE_INDEX + 2;
export const IO_IMG_CAP_INDEX = IO_IMG_BASE_INDEX + 3;
export const IO_IMG_CTRL_INDEX = IO_IMG_BASE_INDEX + 4;
export const IO_IMG_STATUS_INDEX = IO_IMG_BASE_INDEX + 5;
export const IO_IMG_WRITTEN_INDEX = IO_IMG_BASE_INDEX + 6;
export const IO_IMG_SIZE = 7;

export const IO_VDP_STATUS_INDEX = IO_IMG_BASE_INDEX + IO_IMG_SIZE;
export const IO_VDP_STATUS_SIZE = 1;

export const IO_SLOT_COUNT = IO_VDP_STATUS_INDEX + IO_VDP_STATUS_SIZE;

export const IO_WRITE_PTR_ADDR = IO_BASE + IO_WRITE_PTR_INDEX * IO_WORD_SIZE;
export const IO_BUFFER_BASE = IO_BASE + IO_BUFFER_BASE_INDEX * IO_WORD_SIZE;
export const IO_COMMAND_STRIDE = IO_COMMAND_STRIDE_WORDS * IO_WORD_SIZE;
export const IO_ARG0_OFFSET = IO_ARG0_OFFSET_WORDS * IO_WORD_SIZE;
export const IO_ARG_STRIDE = IO_WORD_SIZE;

export const IO_SYS_BASE = IO_BASE + IO_SYS_BASE_INDEX * IO_WORD_SIZE;
export const IO_SYS_BOOT_CART = IO_BASE + IO_SYS_BOOT_CART_INDEX * IO_WORD_SIZE;
export const IO_SYS_CART_BOOTREADY = IO_BASE + IO_SYS_CART_BOOTREADY_INDEX * IO_WORD_SIZE;
export const IO_VDP_BASE = IO_BASE + IO_VDP_BASE_INDEX * IO_WORD_SIZE;
export const IO_VDP_DITHER = IO_BASE + IO_VDP_DITHER_INDEX * IO_WORD_SIZE;
export const IO_VDP_PRIMARY_ATLAS_ID = IO_BASE + IO_VDP_PRIMARY_ATLAS_ID_INDEX * IO_WORD_SIZE;
export const IO_VDP_SECONDARY_ATLAS_ID = IO_BASE + IO_VDP_SECONDARY_ATLAS_ID_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_SURFACE = IO_BASE + IO_VDP_RD_SURFACE_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_X = IO_BASE + IO_VDP_RD_X_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_Y = IO_BASE + IO_VDP_RD_Y_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_MODE = IO_BASE + IO_VDP_RD_MODE_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_STATUS = IO_BASE + IO_VDP_RD_STATUS_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_DATA = IO_BASE + IO_VDP_RD_DATA_INDEX * IO_WORD_SIZE;
export const IO_VDP_OAM_FRONT_BASE = IO_BASE + IO_VDP_OAM_FRONT_BASE_INDEX * IO_WORD_SIZE;
export const IO_VDP_OAM_BACK_BASE = IO_BASE + IO_VDP_OAM_BACK_BASE_INDEX * IO_WORD_SIZE;
export const IO_VDP_OAM_FRONT_COUNT = IO_BASE + IO_VDP_OAM_FRONT_COUNT_INDEX * IO_WORD_SIZE;
export const IO_VDP_OAM_BACK_COUNT = IO_BASE + IO_VDP_OAM_BACK_COUNT_INDEX * IO_WORD_SIZE;
export const IO_VDP_OAM_CAPACITY = IO_BASE + IO_VDP_OAM_CAPACITY_INDEX * IO_WORD_SIZE;
export const IO_VDP_OAM_ENTRY_WORDS = IO_BASE + IO_VDP_OAM_ENTRY_WORDS_INDEX * IO_WORD_SIZE;
export const IO_VDP_OAM_READ_SOURCE = IO_BASE + IO_VDP_OAM_READ_SOURCE_INDEX * IO_WORD_SIZE;
export const IO_VDP_OAM_COMMIT_SEQ = IO_BASE + IO_VDP_OAM_COMMIT_SEQ_INDEX * IO_WORD_SIZE;
export const IO_VDP_OAM_CMD = IO_BASE + IO_VDP_OAM_CMD_INDEX * IO_WORD_SIZE;

export const IO_IRQ_BASE = IO_BASE + IO_IRQ_BASE_INDEX * IO_WORD_SIZE;
export const IO_IRQ_FLAGS = IO_BASE + IO_IRQ_FLAGS_INDEX * IO_WORD_SIZE;
export const IO_IRQ_ACK = IO_BASE + IO_IRQ_ACK_INDEX * IO_WORD_SIZE;

export const IO_DMA_BASE = IO_BASE + IO_DMA_BASE_INDEX * IO_WORD_SIZE;
export const IO_DMA_SRC = IO_BASE + IO_DMA_SRC_INDEX * IO_WORD_SIZE;
export const IO_DMA_DST = IO_BASE + IO_DMA_DST_INDEX * IO_WORD_SIZE;
export const IO_DMA_LEN = IO_BASE + IO_DMA_LEN_INDEX * IO_WORD_SIZE;
export const IO_DMA_CTRL = IO_BASE + IO_DMA_CTRL_INDEX * IO_WORD_SIZE;
export const IO_DMA_STATUS = IO_BASE + IO_DMA_STATUS_INDEX * IO_WORD_SIZE;
export const IO_DMA_WRITTEN = IO_BASE + IO_DMA_WRITTEN_INDEX * IO_WORD_SIZE;

export const IO_IMG_BASE = IO_BASE + IO_IMG_BASE_INDEX * IO_WORD_SIZE;
export const IO_IMG_SRC = IO_BASE + IO_IMG_SRC_INDEX * IO_WORD_SIZE;
export const IO_IMG_LEN = IO_BASE + IO_IMG_LEN_INDEX * IO_WORD_SIZE;
export const IO_IMG_DST = IO_BASE + IO_IMG_DST_INDEX * IO_WORD_SIZE;
export const IO_IMG_CAP = IO_BASE + IO_IMG_CAP_INDEX * IO_WORD_SIZE;
export const IO_IMG_CTRL = IO_BASE + IO_IMG_CTRL_INDEX * IO_WORD_SIZE;
export const IO_IMG_STATUS = IO_BASE + IO_IMG_STATUS_INDEX * IO_WORD_SIZE;
export const IO_IMG_WRITTEN = IO_BASE + IO_IMG_WRITTEN_INDEX * IO_WORD_SIZE;
export const IO_VDP_STATUS = IO_BASE + IO_VDP_STATUS_INDEX * IO_WORD_SIZE;

export const IRQ_DMA_DONE = 1 << 0;
export const IRQ_DMA_ERROR = 1 << 1;
export const IRQ_IMG_DONE = 1 << 2;
export const IRQ_IMG_ERROR = 1 << 3;
export const IRQ_VBLANK = 1 << 4;
export const IRQ_REINIT = 1 << 5;
export const IRQ_NEWGAME = 1 << 6;

export const DMA_CTRL_START = 1 << 0;
export const DMA_CTRL_STRICT = 1 << 1;
export const DMA_STATUS_BUSY = 1 << 0;
export const DMA_STATUS_DONE = 1 << 1;
export const DMA_STATUS_ERROR = 1 << 2;
export const DMA_STATUS_CLIPPED = 1 << 3;

export const IMG_CTRL_START = 1 << 0;
export const IMG_STATUS_BUSY = 1 << 0;
export const IMG_STATUS_DONE = 1 << 1;
export const IMG_STATUS_ERROR = 1 << 2;
export const IMG_STATUS_CLIPPED = 1 << 3;

export const VDP_ATLAS_ID_NONE = 0xffffffff >>> 0;
export const VDP_RD_MODE_RGBA8888 = 0;
export const VDP_RD_STATUS_READY = 1 << 0;
export const VDP_RD_STATUS_OVERFLOW = 1 << 1;
export const VDP_STATUS_VBLANK = 1 << 0;
export const VDP_OAM_READ_SOURCE_FRONT = 0;
export const VDP_OAM_READ_SOURCE_BACK = 1;
export const OAM_CMD_SWAP = 1;
export const OAM_CMD_CLEAR_BACK = 2;
