const ENGINE_LUA_BUILTIN_FUNCTION_NAMES = [
	'define_fsm',
	'define_prefab',
	'define_subsystem',
	'define_component',
	'define_effect',
	'inst',
	'inst_subsystem',
	'oget',
	'rget',
	'subsystem',
	'add_space',
	'set_space',
	'get_space',
	'attach_component',
	'update',
	'reset',
	'configure_ecs',
	'apply_default_pipeline',
	'enlist',
	'delist',
	'grant_effect',
	'trigger_effect',
	'vdp_map_slot',
	'vdp_load_slot',
	'vdp_load_sys_atlas',
	'irq',
	'on_irq',
	'on_vdp_load',
	'bool01',
	'clear_map',
	'deep_clone',
	'consume_axis_accum',
	'set_velocity',
	'move_with_velocity',
	'rect_overlaps',
	'clamp_int',
	'div_toward_zero',
	'round_to_nearest',
	'rol8',
	'swap_remove',
	'objects_by_type',
	'objects_by_tag',
	'find_by_type',
	'find_by_tag',
] as const;

const ENGINE_LUA_BUILTIN_GLOBAL_NAMES = [
	'timeline',
	'eventemitter',
	'scratchbatch',
	'sorted_scratchbatch',
] as const;

export const ENGINE_SYSTEM_HELPER_NAMES = [
	'game',
	'$',
	'assets',
	'cart_manifest',
	'machine_manifest',
	'cart_project_root_path',
	'resolve_cart_rom_asset_range',
	'resolve_sys_rom_asset_range',
	'resolve_rom_asset_range',
	'wait_vblank',
	'clock_now',
] as const;

export const ENGINE_SYSTEM_GLOBAL_NAMES: ReadonlyArray<string> = [
	...ENGINE_SYSTEM_HELPER_NAMES,
	...ENGINE_LUA_BUILTIN_FUNCTION_NAMES,
	...ENGINE_LUA_BUILTIN_GLOBAL_NAMES,
];

export const ENGINE_SYSTEM_GLOBAL_NAME_SET: ReadonlySet<string> = new Set(ENGINE_SYSTEM_GLOBAL_NAMES);
