const ENGINE_LUA_BUILTIN_FUNCTION_NAMES = [
	'define_fsm',
	'define_prefab',
	'define_subsystem',
	'define_component',
	'define_effect',
	'inst',
	'inst_subsystem',
	'oget',
	'rget',
	'subsystem',
	'add_space',
	'set_space',
	'get_space',
	'attach_component',
	'update',
	'reset',
	'configure_ecs',
	'apply_default_pipeline',
	'enlist',
	'delist',
	'grant_effect',
	'trigger_effect',
	'vdp_map_slot',
	'vdp_load_slot',
	'vdp_load_sys_atlas',
	'irq',
	'on_irq',
	'on_vdp_load',
	'bool01',
	'clear_map',
	'deep_clone',
	'consume_axis_accum',
	'set_velocity',
	'move_with_velocity',
	'rect_overlaps',
	'clamp_int',
	'div_toward_zero',
	'round_to_nearest',
	'rol8',
	'swap_remove',
	'objects_by_type',
	'objects_by_tag',
	'find_by_type',
	'find_by_tag',
] as const;

const ENGINE_LUA_BUILTIN_GLOBAL_NAMES = [
	'timeline',
	'eventemitter',
	'scratchbatch',
	'sorted_scratchbatch',
] as const;

export const ENGINE_SYSTEM_HELPER_NAMES = [
	'game',
	'$',
	'assets',
	'cart_manifest',
	'machine_manifest',
	'cart_project_root_path',
	'resolve_cart_rom_asset_range',
	'resolve_sys_rom_asset_range',
	'resolve_rom_asset_range',
	'wait_vblank',
	'clock_now',
] as const;

const ENGINE_SYSTEM_GEO_GLOBAL_NAMES = [
	'sys_geo_scratch_base',
	'sys_geo_scratch_size',
	'sys_geo_src0',
	'sys_geo_src1',
	'sys_geo_src2',
	'sys_geo_dst0',
	'sys_geo_dst1',
	'sys_geo_count',
	'sys_geo_cmd',
	'sys_geo_ctrl',
	'sys_geo_status',
	'sys_geo_param0',
	'sys_geo_param1',
	'sys_geo_stride0',
	'sys_geo_stride1',
	'sys_geo_stride2',
	'sys_geo_processed',
	'sys_geo_fault',
	'irq_geo_done',
	'irq_geo_error',
	'sys_geo_ctrl_start',
	'sys_geo_ctrl_abort',
	'sys_geo_status_busy',
	'sys_geo_status_done',
	'sys_geo_status_error',
	'sys_geo_status_rejected',
	'sys_geo_cmd_xform2_batch',
	'sys_geo_cmd_sat2_batch',
	'sys_geo_cmd_xform3_batch',
	'sys_geo_cmd_project3_batch',
	'sys_geo_index_none',
	'sys_geo_shape_convex_poly',
	'sys_geo_sat_meta_axis_mask',
	'sys_geo_sat_meta_shape_shift',
	'sys_geo_sat_meta_shape_src',
	'sys_geo_sat_meta_shape_aux',
	'sys_geo_fault_aborted_by_host',
	'sys_geo_fault_bad_record_alignment',
	'sys_geo_fault_bad_vertex_count',
	'sys_geo_fault_src_range',
	'sys_geo_fault_dst_range',
	'sys_geo_fault_descriptor_kind',
	'sys_geo_fault_numeric_overflow_internal',
	'sys_geo_fault_bad_record_flags',
	'sys_geo_fault_reject_busy',
	'sys_geo_fault_reject_bad_cmd',
	'sys_geo_fault_reject_bad_stride',
	'sys_geo_fault_reject_dst_not_ram',
	'sys_geo_fault_reject_misaligned_regs',
	'sys_geo_fault_reject_bad_register_combo',
] as const;

export const ENGINE_SYSTEM_GLOBAL_NAMES: ReadonlyArray<string> = [
	...ENGINE_SYSTEM_HELPER_NAMES,
	...ENGINE_LUA_BUILTIN_FUNCTION_NAMES,
	...ENGINE_LUA_BUILTIN_GLOBAL_NAMES,
	...ENGINE_SYSTEM_GEO_GLOBAL_NAMES,
];

export const ENGINE_SYSTEM_GLOBAL_NAME_SET: ReadonlySet<string> = new Set(ENGINE_SYSTEM_GLOBAL_NAMES);
