#pragma once

#include <cstddef>
#include <cstdint>

namespace bmsx {

constexpr uint32_t GEO_CTRL_START = 1u << 0u;
constexpr uint32_t GEO_CTRL_ABORT = 1u << 1u;
constexpr uint32_t GEO_STATUS_BUSY = 1u << 0u;
constexpr uint32_t GEO_STATUS_DONE = 1u << 1u;
constexpr uint32_t GEO_STATUS_ERROR = 1u << 2u;
constexpr uint32_t GEO_STATUS_REJECTED = 1u << 3u;

constexpr std::size_t GEOMETRY_CONTROLLER_REGISTER_COUNT = 16u;
constexpr uint32_t GEOMETRY_CONTROLLER_PHASE_IDLE = 0u;
constexpr uint32_t GEOMETRY_CONTROLLER_PHASE_BUSY = 1u;
constexpr uint32_t GEOMETRY_CONTROLLER_PHASE_DONE = 2u;
constexpr uint32_t GEOMETRY_CONTROLLER_PHASE_ERROR = 3u;
constexpr uint32_t GEOMETRY_CONTROLLER_PHASE_REJECTED = 4u;

enum class GeometryControllerPhase : uint32_t {
	Idle = GEOMETRY_CONTROLLER_PHASE_IDLE,
	Busy = GEOMETRY_CONTROLLER_PHASE_BUSY,
	Done = GEOMETRY_CONTROLLER_PHASE_DONE,
	Error = GEOMETRY_CONTROLLER_PHASE_ERROR,
	Rejected = GEOMETRY_CONTROLLER_PHASE_REJECTED,
};

constexpr uint32_t IO_CMD_GEO_XFORM2_BATCH = 0x20u;
constexpr uint32_t IO_CMD_GEO_SAT2_BATCH = 0x21u;
constexpr uint32_t IO_CMD_GEO_OVERLAP2D_PASS = 0x22u;
constexpr uint32_t IO_CMD_GEO_XFORM3_BATCH = 0x30u;
constexpr uint32_t IO_CMD_GEO_PROJECT3_BATCH = 0x31u;

constexpr uint32_t GEO_INDEX_NONE = 0xffffffffu;
constexpr uint32_t GEO_SHAPE_CONVEX_POLY = 1u << 0u;
constexpr uint32_t GEO_PRIMITIVE_AABB = 1u;
constexpr uint32_t GEO_PRIMITIVE_CIRCLE = 2u;
constexpr uint32_t GEO_PRIMITIVE_CONVEX_POLY = 3u;
constexpr uint32_t GEO_SAT_META_AXIS_MASK = 0xffffu;
constexpr uint32_t GEO_SAT_META_SHAPE_SHIFT = 16u;
constexpr uint32_t GEO_SAT_META_SHAPE_SRC = 0u;
constexpr uint32_t GEO_SAT_META_SHAPE_AUX = 1u;
constexpr uint32_t GEO_VERTEX2_BYTES = 8u;
constexpr uint32_t GEO_VERTEX2_X_OFFSET = 0u;
constexpr uint32_t GEO_VERTEX2_Y_OFFSET = 4u;
constexpr uint32_t GEO_XFORM2_RECORD_WORDS = 6u;
constexpr uint32_t GEO_XFORM2_RECORD_BYTES = GEO_XFORM2_RECORD_WORDS * 4u;
constexpr uint32_t GEO_XFORM2_RECORD_FLAGS_OFFSET = 0u;
constexpr uint32_t GEO_XFORM2_RECORD_SRC_INDEX_OFFSET = 4u;
constexpr uint32_t GEO_XFORM2_RECORD_DST_INDEX_OFFSET = 8u;
constexpr uint32_t GEO_XFORM2_RECORD_AUX_INDEX_OFFSET = 12u;
constexpr uint32_t GEO_XFORM2_RECORD_VERTEX_COUNT_OFFSET = 16u;
constexpr uint32_t GEO_XFORM2_RECORD_DST1_INDEX_OFFSET = 20u;
constexpr uint32_t GEO_XFORM2_MATRIX_WORDS = 6u;
constexpr uint32_t GEO_XFORM2_MATRIX_BYTES = GEO_XFORM2_MATRIX_WORDS * 4u;
constexpr uint32_t GEO_XFORM2_MATRIX_M00_OFFSET = 0u;
constexpr uint32_t GEO_XFORM2_MATRIX_M01_OFFSET = 4u;
constexpr uint32_t GEO_XFORM2_MATRIX_TX_OFFSET = 8u;
constexpr uint32_t GEO_XFORM2_MATRIX_M10_OFFSET = 12u;
constexpr uint32_t GEO_XFORM2_MATRIX_M11_OFFSET = 16u;
constexpr uint32_t GEO_XFORM2_MATRIX_TY_OFFSET = 20u;
constexpr uint32_t GEO_XFORM2_AABB_BYTES = 16u;
constexpr uint32_t GEO_XFORM2_AABB_MIN_X_OFFSET = 0u;
constexpr uint32_t GEO_XFORM2_AABB_MIN_Y_OFFSET = 4u;
constexpr uint32_t GEO_XFORM2_AABB_MAX_X_OFFSET = 8u;
constexpr uint32_t GEO_XFORM2_AABB_MAX_Y_OFFSET = 12u;
constexpr uint32_t GEO_SAT2_PAIR_WORDS = 5u;
constexpr uint32_t GEO_SAT2_PAIR_BYTES = GEO_SAT2_PAIR_WORDS * 4u;
constexpr uint32_t GEO_SAT2_PAIR_FLAGS_OFFSET = 0u;
constexpr uint32_t GEO_SAT2_PAIR_SHAPE_A_INDEX_OFFSET = 4u;
constexpr uint32_t GEO_SAT2_PAIR_RESULT_INDEX_OFFSET = 8u;
constexpr uint32_t GEO_SAT2_PAIR_SHAPE_B_INDEX_OFFSET = 12u;
constexpr uint32_t GEO_SAT2_PAIR_FLAGS2_OFFSET = 16u;
constexpr uint32_t GEO_SAT2_DESC_WORDS = 4u;
constexpr uint32_t GEO_SAT2_DESC_BYTES = GEO_SAT2_DESC_WORDS * 4u;
constexpr uint32_t GEO_SAT2_DESC_FLAGS_OFFSET = 0u;
constexpr uint32_t GEO_SAT2_DESC_VERTEX_COUNT_OFFSET = 4u;
constexpr uint32_t GEO_SAT2_DESC_VERTEX_OFFSET_OFFSET = 8u;
constexpr uint32_t GEO_SAT2_DESC_RESERVED_OFFSET = 12u;
constexpr uint32_t GEO_SAT2_RESULT_WORDS = 5u;
constexpr uint32_t GEO_SAT2_RESULT_BYTES = GEO_SAT2_RESULT_WORDS * 4u;
constexpr uint32_t GEO_SAT2_RESULT_HIT_OFFSET = 0u;
constexpr uint32_t GEO_SAT2_RESULT_NX_OFFSET = 4u;
constexpr uint32_t GEO_SAT2_RESULT_NY_OFFSET = 8u;
constexpr uint32_t GEO_SAT2_RESULT_DEPTH_OFFSET = 12u;
constexpr uint32_t GEO_SAT2_RESULT_META_OFFSET = 16u;
constexpr uint32_t GEO_OVERLAP2D_MODE_MASK = 0x3u;
constexpr uint32_t GEO_OVERLAP2D_MODE_CANDIDATE_PAIRS = 0x1u;
constexpr uint32_t GEO_OVERLAP2D_MODE_FULL_PASS = 0x2u;
constexpr uint32_t GEO_OVERLAP2D_BROADPHASE_SHIFT = 2u;
constexpr uint32_t GEO_OVERLAP2D_BROADPHASE_MASK = 0x3u << GEO_OVERLAP2D_BROADPHASE_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_BROADPHASE_NONE = 0u << GEO_OVERLAP2D_BROADPHASE_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_BROADPHASE_LOCAL_BOUNDS_AABB = 0x1u << GEO_OVERLAP2D_BROADPHASE_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_CONTACT_POLICY_SHIFT = 4u;
constexpr uint32_t GEO_OVERLAP2D_CONTACT_POLICY_MASK = 0x3u << GEO_OVERLAP2D_CONTACT_POLICY_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_CONTACT_POLICY_CLIPPED_FEATURE = 0u << GEO_OVERLAP2D_CONTACT_POLICY_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_OUTPUT_POLICY_SHIFT = 6u;
constexpr uint32_t GEO_OVERLAP2D_OUTPUT_POLICY_MASK = 0x3u << GEO_OVERLAP2D_OUTPUT_POLICY_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_OUTPUT_POLICY_STOP_ON_OVERFLOW = 0u << GEO_OVERLAP2D_OUTPUT_POLICY_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_SUMMARY_FLAG_OVERFLOW = 1u << 0u;
constexpr uint32_t GEO_OVERLAP2D_PARAM0_RESERVED_MASK = 0xffff0000u;
constexpr uint32_t GEO_OVERLAP2D_INSTANCE_WORDS = 5u;
constexpr uint32_t GEO_OVERLAP2D_INSTANCE_BYTES = GEO_OVERLAP2D_INSTANCE_WORDS * 4u;
constexpr uint32_t GEO_OVERLAP2D_INSTANCE_SHAPE_OFFSET = 0u;
constexpr uint32_t GEO_OVERLAP2D_INSTANCE_TX_OFFSET = 4u;
constexpr uint32_t GEO_OVERLAP2D_INSTANCE_TY_OFFSET = 8u;
constexpr uint32_t GEO_OVERLAP2D_INSTANCE_LAYER_OFFSET = 12u;
constexpr uint32_t GEO_OVERLAP2D_INSTANCE_MASK_OFFSET = 16u;
constexpr uint32_t GEO_OVERLAP2D_PAIR_WORDS = 3u;
constexpr uint32_t GEO_OVERLAP2D_PAIR_BYTES = GEO_OVERLAP2D_PAIR_WORDS * 4u;
constexpr uint32_t GEO_OVERLAP2D_PAIR_INSTANCE_A_OFFSET = 0u;
constexpr uint32_t GEO_OVERLAP2D_PAIR_INSTANCE_B_OFFSET = 4u;
constexpr uint32_t GEO_OVERLAP2D_PAIR_META_OFFSET = 8u;
constexpr uint32_t GEO_OVERLAP2D_RESULT_WORDS = 9u;
constexpr uint32_t GEO_OVERLAP2D_RESULT_BYTES = GEO_OVERLAP2D_RESULT_WORDS * 4u;
constexpr uint32_t GEO_OVERLAP2D_RESULT_NX_OFFSET = 0u;
constexpr uint32_t GEO_OVERLAP2D_RESULT_NY_OFFSET = 4u;
constexpr uint32_t GEO_OVERLAP2D_RESULT_DEPTH_OFFSET = 8u;
constexpr uint32_t GEO_OVERLAP2D_RESULT_PX_OFFSET = 12u;
constexpr uint32_t GEO_OVERLAP2D_RESULT_PY_OFFSET = 16u;
constexpr uint32_t GEO_OVERLAP2D_RESULT_PIECE_A_OFFSET = 20u;
constexpr uint32_t GEO_OVERLAP2D_RESULT_PIECE_B_OFFSET = 24u;
constexpr uint32_t GEO_OVERLAP2D_RESULT_FEATURE_META_OFFSET = 28u;
constexpr uint32_t GEO_OVERLAP2D_RESULT_PAIR_META_OFFSET = 32u;
constexpr uint32_t GEO_OVERLAP2D_SUMMARY_RESULT_COUNT_OFFSET = 0u;
constexpr uint32_t GEO_OVERLAP2D_SUMMARY_EXACT_PAIR_COUNT_OFFSET = 4u;
constexpr uint32_t GEO_OVERLAP2D_SUMMARY_BROADPHASE_PAIR_COUNT_OFFSET = 8u;
constexpr uint32_t GEO_OVERLAP2D_SUMMARY_FLAGS_OFFSET = 12u;
constexpr uint32_t GEO_OVERLAP2D_SUMMARY_BYTES = 16u;
constexpr uint32_t GEO_OVERLAP2D_SHAPE_KIND_OFFSET = 0u;
constexpr uint32_t GEO_OVERLAP2D_SHAPE_DATA_COUNT_OFFSET = 4u;
constexpr uint32_t GEO_OVERLAP2D_SHAPE_DATA_OFFSET_OFFSET = 8u;
constexpr uint32_t GEO_OVERLAP2D_SHAPE_BOUNDS_OFFSET_OFFSET = 12u;
constexpr uint32_t GEO_OVERLAP2D_SHAPE_DESC_BYTES = 16u;
constexpr uint32_t GEO_OVERLAP2D_SHAPE_BOUNDS_BYTES = 16u;
constexpr uint32_t GEO_OVERLAP2D_SHAPE_BOUNDS_LEFT_OFFSET = 0u;
constexpr uint32_t GEO_OVERLAP2D_SHAPE_BOUNDS_TOP_OFFSET = 4u;
constexpr uint32_t GEO_OVERLAP2D_SHAPE_BOUNDS_RIGHT_OFFSET = 8u;
constexpr uint32_t GEO_OVERLAP2D_SHAPE_BOUNDS_BOTTOM_OFFSET = 12u;
constexpr uint32_t GEO_OVERLAP2D_SHAPE_KIND_COMPOUND = 4u;
constexpr uint32_t GEO_OVERLAP2D_AABB_DATA_COUNT = 4u;
constexpr uint32_t GEO_OVERLAP2D_AABB_SHAPE_BYTES = GEO_OVERLAP2D_SHAPE_DESC_BYTES + GEO_OVERLAP2D_SHAPE_BOUNDS_BYTES;
constexpr uint32_t GEO_OVERLAP2D_PAIR_META_INSTANCE_A_SHIFT = 16u;
constexpr uint32_t GEO_OVERLAP2D_PAIR_META_INSTANCE_A_MASK = 0xffffu;
constexpr uint32_t GEO_OVERLAP2D_PAIR_META_INSTANCE_B_MASK = 0xffffu;

constexpr uint32_t GEO_FAULT_ABORTED_BY_HOST = 0x0001u;
constexpr uint32_t GEO_FAULT_BAD_RECORD_ALIGNMENT = 0x0002u;
constexpr uint32_t GEO_FAULT_BAD_VERTEX_COUNT = 0x0003u;
constexpr uint32_t GEO_FAULT_SRC_RANGE = 0x0004u;
constexpr uint32_t GEO_FAULT_DST_RANGE = 0x0005u;
constexpr uint32_t GEO_FAULT_DESCRIPTOR_KIND = 0x0006u;
constexpr uint32_t GEO_FAULT_NUMERIC_OVERFLOW_INTERNAL = 0x0007u;
constexpr uint32_t GEO_FAULT_BAD_RECORD_FLAGS = 0x0008u;
constexpr uint32_t GEO_FAULT_RESULT_CAPACITY = 0x0009u;
constexpr uint32_t GEO_FAULT_CODE_SHIFT = 16u;
constexpr uint32_t GEO_FAULT_CODE_MASK = 0xffffu;
constexpr uint32_t GEO_FAULT_RECORD_INDEX_MASK = 0xffffu;
constexpr uint32_t GEO_FAULT_RECORD_INDEX_NONE = 0xffffu;

constexpr uint32_t GEO_FAULT_REJECT_BUSY = 0x8001u;
constexpr uint32_t GEO_FAULT_REJECT_BAD_CMD = 0x8002u;
constexpr uint32_t GEO_FAULT_REJECT_BAD_STRIDE = 0x8003u;
constexpr uint32_t GEO_FAULT_REJECT_DST_NOT_RAM = 0x8004u;
constexpr uint32_t GEO_FAULT_REJECT_MISALIGNED_REGS = 0x8005u;
constexpr uint32_t GEO_FAULT_REJECT_BAD_REGISTER_COMBO = 0x8006u;

} // namespace bmsx
