export const COP0_BAD_ADDRESS = 8;
export const COP0_STATUS = 12;
export const COP0_CAUSE = 13;
export const COP0_EPC = 14;

export const CPU_STATUS_INTERRUPT_ENABLE_CURRENT = 1 << 0;
export const CPU_STATUS_USER_MODE_CURRENT = 1 << 1;
export const CPU_STATUS_MODE_STACK_MASK = 0x3f;
export const CPU_STATUS_RFE_RESTORE_MASK = 0x0f;

export const CPU_STATUS_SYSTEM_ENTRY = CPU_STATUS_INTERRUPT_ENABLE_CURRENT;
export const CPU_STATUS_CART_ENTRY = CPU_STATUS_INTERRUPT_ENABLE_CURRENT | CPU_STATUS_USER_MODE_CURRENT;

export const CPU_CAUSE_IRQ = 1 << 10;
export const CPU_CAUSE_NMI = 1 << 16;
export const CPU_CAUSE_CODE_COPROCESSOR_UNUSABLE = 11 << 2;
