export const enum OpCode {
	WIDE,
	MOV,
	LOADK,
	LOADNIL,
	LOAD_MEM_D,
	KNIL,
	KFALSE,
	KTRUE,
	K0,
	K1,
	KM1,
	KSMI,
	STORE_MEM_D,
	STORE_MEM_WORDS_D,
	GETT,
	SETT,
	NEWT,
	ADD,
	SUB,
	MUL,
	DIV,
	MOD,
	FLOORDIV,
	POW,
	BAND,
	BOR,
	BXOR,
	SHL,
	SHR,
	CONCAT,
	CONCATN,
	UNM,
	NOT,
	LEN,
	BNOT,
	EQ,
	LT,
	LE,
	RESERVED0,
	RESERVED1,
	JMP,
	JMPIF,
	JMPIFNOT,
	CLOSURE,
	GETUP,
	SETUP,
	VARARG,
	CALL,
	RET,
	LOAD_MEM,
	STORE_MEM,
	STORE_MEM_WORDS,
	RESERVED2,
	RESERVED3,
	GETSYS,
	SETSYS,
	GETGL,
	SETGL,
	GETI,
	SETI,
	GETFIELD,
	SETFIELD,
	SELF,
	HALT,
}

export const OPCODE_COUNT = 64;

export const encodeFixedCallArgCount = (argCount: number): number => argCount + 1;

export const decodeCallArgCount = (operand: number, openArgCount: number): number =>
	operand === 0 ? openArgCount : operand - 1;

export const OPCODE_NAMES: ReadonlyArray<string> = [
	'WIDE',
	'MOV',
	'LOADK',
	'LOADNIL',
	'LOAD_MEM_D',
	'KNIL',
	'KFALSE',
	'KTRUE',
	'K0',
	'K1',
	'KM1',
	'KSMI',
	'STORE_MEM_D',
	'STORE_MEM_WORDS_D',
	'GETT',
	'SETT',
	'NEWT',
	'ADD',
	'SUB',
	'MUL',
	'DIV',
	'MOD',
	'FLOORDIV',
	'POW',
	'BAND',
	'BOR',
	'BXOR',
	'SHL',
	'SHR',
	'CONCAT',
	'CONCATN',
	'UNM',
	'NOT',
	'LEN',
	'BNOT',
	'EQ',
	'LT',
	'LE',
	'RESERVED0',
	'RESERVED1',
	'JMP',
	'JMPIF',
	'JMPIFNOT',
	'CLOSURE',
	'GETUP',
	'SETUP',
	'VARARG',
	'CALL',
	'RET',
	'LOAD_MEM',
	'STORE_MEM',
	'STORE_MEM_WORDS',
	'RESERVED2',
	'RESERVED3',
	'GETSYS',
	'SETSYS',
	'GETGL',
	'SETGL',
	'GETI',
	'SETI',
	'GETFIELD',
	'SETFIELD',
	'SELF',
	'HALT',
];

export const BASE_CYCLES = new Uint8Array([
	0, 1, 1, 1, 2, 1, 1, 1,
	1, 1, 1, 1, 2, 2, 1, 2,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 2, 2, 2,
	2, 2, 2, 2, 1, 1, 1, 2,
	1, 2, 1, 2, 1, 2, 1, 1,
]);

export const OPCODE_USES_BX = new Uint8Array([
	0, 0, 1, 0, 0, 0, 0, 0,
	0, 0, 0, 1, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	1, 1, 1, 1, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 1, 1,
	1, 1, 0, 0, 0, 0, 0, 0,
]);

export const OPCODE_USES_DISP = new Uint8Array([
	0, 0, 0, 0, 1, 0, 0, 0,
	0, 0, 0, 0, 1, 1, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
]);

export const OPCODE_CATEGORY: ReadonlyArray<string> = [
	'wide prefix', 'load/move', 'load/move', 'load/move', 'memory I/O', 'load/move', 'load/move', 'load/move',
	'load/move', 'load/move', 'load/move', 'load/move', 'memory I/O', 'memory I/O', 'table get/set', 'table get/set',
	'table creation', 'arithmetic', 'arithmetic', 'arithmetic', 'arithmetic', 'arithmetic', 'arithmetic', 'arithmetic',
	'bitwise', 'bitwise', 'bitwise', 'bitwise', 'bitwise', 'string concat', 'string concat', 'arithmetic',
	'logical', 'length', 'bitwise', 'comparison', 'comparison', 'comparison', 'reserved', 'reserved',
	'branch/jump', 'branch/jump', 'branch/jump', 'closure creation', 'upvalue', 'upvalue', 'vararg', 'call/return',
	'call/return', 'memory I/O', 'memory I/O', 'memory I/O', 'reserved', 'reserved', 'global/sys access', 'global/sys access',
	'global/sys access', 'global/sys access', 'table get/set', 'table get/set', 'table get/set', 'table get/set', 'table get/set', 'sleep/halt',
];

export function getOpcodeName(opcode: OpCode): string {
	return OPCODE_NAMES[opcode];
}
