set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armv7)

set(BMSX_SYSROOT "$ENV{BMSX_SYSROOT}")
if(NOT BMSX_SYSROOT)
	message(FATAL_ERROR "BMSX_SYSROOT is required for the SNES Mini toolchain.")
endif()

set(BMSX_TOOLCHAIN_PREFIX "$ENV{BMSX_TOOLCHAIN_PREFIX}")
if(NOT BMSX_TOOLCHAIN_PREFIX)
	set(BMSX_TOOLCHAIN_PREFIX "arm-linux-gnueabihf")
endif()

set(CMAKE_SYSROOT "${BMSX_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${BMSX_SYSROOT}")

if(IS_ABSOLUTE "${BMSX_TOOLCHAIN_PREFIX}")
	set(BMSX_C_COMPILER "${BMSX_TOOLCHAIN_PREFIX}-gcc")
	set(BMSX_CXX_COMPILER "${BMSX_TOOLCHAIN_PREFIX}-g++")
else()
	set(BMSX_GCC_CANDIDATES
		"${BMSX_TOOLCHAIN_PREFIX}-gcc-11"
		"${BMSX_TOOLCHAIN_PREFIX}-gcc-10"
		"${BMSX_TOOLCHAIN_PREFIX}-gcc"
	)
	set(BMSX_GXX_CANDIDATES
		"${BMSX_TOOLCHAIN_PREFIX}-g++-11"
		"${BMSX_TOOLCHAIN_PREFIX}-g++-10"
		"${BMSX_TOOLCHAIN_PREFIX}-g++"
	)

	find_program(BMSX_C_COMPILER NAMES ${BMSX_GCC_CANDIDATES})
	find_program(BMSX_CXX_COMPILER NAMES ${BMSX_GXX_CANDIDATES})

	if(NOT BMSX_C_COMPILER)
		set(BMSX_C_COMPILER "${BMSX_TOOLCHAIN_PREFIX}-gcc")
	endif()
	if(NOT BMSX_CXX_COMPILER)
		set(BMSX_CXX_COMPILER "${BMSX_TOOLCHAIN_PREFIX}-g++")
	endif()
endif()

set(CMAKE_C_COMPILER "${BMSX_C_COMPILER}")
set(CMAKE_CXX_COMPILER "${BMSX_CXX_COMPILER}")
set(CMAKE_AR "${BMSX_TOOLCHAIN_PREFIX}-ar")
set(CMAKE_RANLIB "${BMSX_TOOLCHAIN_PREFIX}-ranlib")
set(CMAKE_STRIP "${BMSX_TOOLCHAIN_PREFIX}-strip")

get_filename_component(BMSX_TARGET_TRIPLET "${BMSX_TOOLCHAIN_PREFIX}" NAME)
execute_process(
	COMMAND "${CMAKE_CXX_COMPILER}" -dumpversion
	OUTPUT_VARIABLE BMSX_GXX_VERSION
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
if(NOT BMSX_GXX_VERSION)
	message(FATAL_ERROR "Failed to detect cross compiler version via '${CMAKE_CXX_COMPILER} -dumpversion'.")
endif()

set(BMSX_CXX_INCLUDE_ROOT "/usr/${BMSX_TARGET_TRIPLET}/include/c++/${BMSX_GXX_VERSION}")
set(BMSX_CXX_INCLUDE_TARGET_DIR "${BMSX_CXX_INCLUDE_ROOT}/${BMSX_TARGET_TRIPLET}")
if(NOT EXISTS "${BMSX_CXX_INCLUDE_TARGET_DIR}/bits/c++config.h")
	message(FATAL_ERROR "Cross libstdc++ headers not found at: ${BMSX_CXX_INCLUDE_TARGET_DIR}")
endif()

execute_process(
	COMMAND "${CMAKE_CXX_COMPILER}" -print-file-name=include
	OUTPUT_VARIABLE BMSX_GCC_INCLUDE_DIR
	OUTPUT_STRIP_TRAILING_WHITESPACE
)
if(NOT BMSX_GCC_INCLUDE_DIR)
	message(FATAL_ERROR "Failed to detect GCC internal include dir via '${CMAKE_CXX_COMPILER} -print-file-name=include'.")
endif()

set(BMSX_ARCH_FLAGS "-march=armv7-a -mfpu=neon-vfpv4 -mfloat-abi=hard")
set(BMSX_SNESMINI_COMPAT_DIR "${CMAKE_CURRENT_LIST_DIR}/snesmini-compat/include")
set(BMSX_COMPAT_INCLUDE "-I${BMSX_SNESMINI_COMPAT_DIR}")
set(BMSX_SNESMINI_GLIBC_FLAGS "-U_TIME_BITS -D_TIME_BITS=32")
set(BMSX_SYSROOT_INCLUDE_FLAGS "-isystem${BMSX_SYSROOT}/usr/include/arm-linux-gnueabihf -isystem${BMSX_SYSROOT}/usr/include")
set(BMSX_CXX_STD_INCLUDE_FLAGS "-nostdinc -isystem${BMSX_CXX_INCLUDE_ROOT} -isystem${BMSX_CXX_INCLUDE_TARGET_DIR}/. -isystem${BMSX_CXX_INCLUDE_ROOT}/backward ${BMSX_SYSROOT_INCLUDE_FLAGS} -isystem${BMSX_GCC_INCLUDE_DIR}")
set(CMAKE_C_FLAGS_INIT "-O3 -fPIC ${BMSX_ARCH_FLAGS} ${BMSX_COMPAT_INCLUDE} ${BMSX_SYSROOT_INCLUDE_FLAGS} ${BMSX_SNESMINI_GLIBC_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "-O3 -fPIC ${BMSX_ARCH_FLAGS} ${BMSX_COMPAT_INCLUDE} ${BMSX_CXX_STD_INCLUDE_FLAGS} ${BMSX_SNESMINI_GLIBC_FLAGS} -D_GLIBCXX_USE_CXX11_ABI=0 -DBMSX_SNESMINI_LEGACY=1 -fno-sized-deallocation")

set(BMSX_SYSROOT_LIB_DIR "${BMSX_SYSROOT}/lib/arm-linux-gnueabihf")
set(BMSX_SYSROOT_USR_LIB_DIR "${BMSX_SYSROOT}/usr/lib/arm-linux-gnueabihf")
set(BMSX_SYSROOT_LINK_FLAGS "-L${BMSX_SYSROOT_USR_LIB_DIR} -L${BMSX_SYSROOT_LIB_DIR} -Wl,-rpath-link,${BMSX_SYSROOT_USR_LIB_DIR}:${BMSX_SYSROOT_LIB_DIR}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${BMSX_SYSROOT_LINK_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${BMSX_SYSROOT_LINK_FLAGS}")

set(ZLIB_USE_STATIC_LIBS OFF CACHE BOOL "" FORCE)
set(BMSX_ZLIB_INCLUDE "${BMSX_SYSROOT}/usr/include")
set(BMSX_ZLIB_LIB_SHARED "${BMSX_SYSROOT}/lib/arm-linux-gnueabihf/libz.so.1")
set(BMSX_ZLIB_LIB_SHARED_ALT "${BMSX_SYSROOT}/usr/lib/arm-linux-gnueabihf/libz.so.1")
if(EXISTS "${BMSX_ZLIB_LIB_SHARED}")
	set(ZLIB_LIBRARY "${BMSX_ZLIB_LIB_SHARED}" CACHE FILEPATH "" FORCE)
elseif(EXISTS "${BMSX_ZLIB_LIB_SHARED_ALT}")
	set(ZLIB_LIBRARY "${BMSX_ZLIB_LIB_SHARED_ALT}" CACHE FILEPATH "" FORCE)
endif()
if(EXISTS "${BMSX_ZLIB_INCLUDE}")
	set(ZLIB_INCLUDE_DIR "${BMSX_ZLIB_INCLUDE}" CACHE PATH "" FORCE)
	set(ZLIB_INCLUDE_DIRS "${BMSX_ZLIB_INCLUDE}" CACHE PATH "" FORCE)
endif()
if(DEFINED ZLIB_LIBRARY)
	set(ZLIB_LIBRARIES "${ZLIB_LIBRARY}" CACHE FILEPATH "" FORCE)
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
