#pragma once

#include <cstdint>

namespace bmsx {

constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_HEADER_SIZE = 76u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_RANGE_COUNT_OFFSET = 0u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_RANGE_TABLE_OFFSET = 4u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_FILE_COUNT_OFFSET = 8u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_FILE_TABLE_OFFSET = 12u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_LINE_OFFSET_COUNT_OFFSET = 16u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_LINE_OFFSET_TABLE_OFFSET = 20u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_PATH_TABLE_OFFSET = 24u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_PATH_BYTES_COUNT_OFFSET = 28u;

constexpr uint32_t BLUA32_DIAGNOSTIC_RANGE_RECORD_SIZE = 12u;
constexpr uint32_t BLUA32_DIAGNOSTIC_RANGE_PC_START_OFFSET = 0u;
constexpr uint32_t BLUA32_DIAGNOSTIC_RANGE_LINE_FILE_OFFSET = 4u;
constexpr uint32_t BLUA32_DIAGNOSTIC_RANGE_COLUMN_OFFSET = 8u;
constexpr uint32_t BLUA32_DIAGNOSTIC_NO_SOURCE = 0xffffffffu;

constexpr uint32_t BLUA32_DIAGNOSTIC_FILE_RECORD_SIZE = 20u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FILE_PATH_OFFSET = 0u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FILE_PATH_BYTE_COUNT_OFFSET = 4u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FILE_SOURCE_OFFSET = 8u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FILE_SOURCE_BYTE_COUNT_OFFSET = 12u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FILE_LINE_OFFSET_START_INDEX_OFFSET = 16u;

constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_FUNCTION_COUNT_OFFSET = 32u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_FUNCTION_TABLE_OFFSET = 36u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_FRAME_COUNT_OFFSET = 40u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_FRAME_TABLE_OFFSET = 44u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_BINDING_COUNT_OFFSET = 48u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_BINDING_TABLE_OFFSET = 52u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_INTERVAL_COUNT_OFFSET = 56u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_INTERVAL_TABLE_OFFSET = 60u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_NAME_BYTES_COUNT_OFFSET = 64u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_NAME_TABLE_OFFSET = 68u;
constexpr uint32_t BLUA32_DIAGNOSTIC_DIRECTORY_STATIC_GLOBAL_COUNT_OFFSET = 72u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FUNCTION_RECORD_SIZE = 16u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FUNCTION_ADDRESS_OFFSET = 0u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FUNCTION_CODE_ADDRESS_OFFSET = 4u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FUNCTION_FRAME_START_OFFSET = 8u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FUNCTION_FRAME_COUNT_OFFSET = 12u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FRAME_RECORD_SIZE = 28u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FRAME_DEPTH_OFFSET = 0u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FRAME_NAME_OFFSET = 4u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FRAME_NAME_BYTES_OFFSET = 8u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FRAME_ACTIVE_START_OFFSET = 12u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FRAME_ACTIVE_COUNT_OFFSET = 16u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FRAME_BINDING_START_OFFSET = 20u;
constexpr uint32_t BLUA32_DIAGNOSTIC_FRAME_BINDING_COUNT_OFFSET = 24u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_RECORD_SIZE = 32u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_NAME_OFFSET = 0u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_NAME_BYTES_OFFSET = 4u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_FLAGS_OFFSET = 8u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_INDEX_OFFSET = 12u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_VISIBLE_START_OFFSET = 16u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_VISIBLE_COUNT_OFFSET = 20u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_LIVE_START_OFFSET = 24u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_LIVE_COUNT_OFFSET = 28u;
constexpr uint32_t BLUA32_DIAGNOSTIC_INTERVAL_RECORD_SIZE = 8u;
constexpr uint32_t BLUA32_DIAGNOSTIC_INTERVAL_START_OFFSET = 0u;
constexpr uint32_t BLUA32_DIAGNOSTIC_INTERVAL_END_OFFSET = 4u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_UPVALUE = 1u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_CONST = 2u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_ADDRESS = 4u;
constexpr uint32_t BLUA32_DIAGNOSTIC_BINDING_TYPE = 8u;
constexpr uint32_t BLUA32_DIAGNOSTIC_NO_LOCATION = 0xffffffffu;

} // namespace bmsx
