#pragma once

#include <cstdint>

namespace bmsx {

constexpr uint32_t BLUA32_IMAGE_MAGIC = 0x32334c42u;
constexpr uint32_t BLUA32_IMAGE_VERSION = 1u;
constexpr uint32_t BLUA32_IMAGE_HEADER_SIZE = 96u;

constexpr uint32_t BLUA32_IMAGE_MAGIC_OFFSET = 0u;
constexpr uint32_t BLUA32_IMAGE_VERSION_OFFSET = 4u;
constexpr uint32_t BLUA32_IMAGE_BYTE_COUNT_OFFSET = 8u;
constexpr uint32_t BLUA32_IMAGE_FLAGS_OFFSET = 12u;
constexpr uint32_t BLUA32_IMAGE_FUNCTION_TABLE_ADDRESS_OFFSET = 16u;
constexpr uint32_t BLUA32_IMAGE_FUNCTION_COUNT_OFFSET = 20u;
constexpr uint32_t BLUA32_IMAGE_CONSTANT_TABLE_ADDRESS_OFFSET = 24u;
constexpr uint32_t BLUA32_IMAGE_CONSTANT_COUNT_OFFSET = 28u;
constexpr uint32_t BLUA32_IMAGE_GLOBAL_NAME_TABLE_ADDRESS_OFFSET = 32u;
constexpr uint32_t BLUA32_IMAGE_GLOBAL_NAME_COUNT_OFFSET = 36u;
constexpr uint32_t BLUA32_IMAGE_SYSTEM_GLOBAL_NAME_TABLE_ADDRESS_OFFSET = 40u;
constexpr uint32_t BLUA32_IMAGE_SYSTEM_GLOBAL_NAME_COUNT_OFFSET = 44u;
constexpr uint32_t BLUA32_IMAGE_STRING_ADDRESS_OFFSET = 48u;
constexpr uint32_t BLUA32_IMAGE_STRING_BYTE_COUNT_OFFSET = 52u;
constexpr uint32_t BLUA32_IMAGE_RODATA_ADDRESS_OFFSET = 56u;
constexpr uint32_t BLUA32_IMAGE_RODATA_BYTE_COUNT_OFFSET = 60u;
constexpr uint32_t BLUA32_IMAGE_DATA_LOAD_ADDRESS_OFFSET = 64u;
constexpr uint32_t BLUA32_IMAGE_DATA_BYTE_COUNT_OFFSET = 68u;
constexpr uint32_t BLUA32_IMAGE_DATA_ADDRESS_OFFSET = 72u;
constexpr uint32_t BLUA32_IMAGE_BSS_ADDRESS_OFFSET = 76u;
constexpr uint32_t BLUA32_IMAGE_BSS_BYTE_COUNT_OFFSET = 80u;
constexpr uint32_t BLUA32_IMAGE_TEXT_ADDRESS_OFFSET = 84u;
constexpr uint32_t BLUA32_IMAGE_TEXT_BYTE_COUNT_OFFSET = 88u;
constexpr uint32_t BLUA32_IMAGE_RESERVED_OFFSET = 92u;

constexpr uint32_t BLUA32_FUNCTION_RECORD_SIZE = 32u;
constexpr uint32_t BLUA32_FUNCTION_ALIGNMENT = 16u;
constexpr uint32_t BLUA32_FUNCTION_CODE_ADDRESS_OFFSET = 0u;
constexpr uint32_t BLUA32_FUNCTION_CODE_BYTE_COUNT_OFFSET = 4u;
constexpr uint32_t BLUA32_FUNCTION_NUM_PARAMS_OFFSET = 8u;
constexpr uint32_t BLUA32_FUNCTION_MAX_STACK_OFFSET = 12u;
constexpr uint32_t BLUA32_FUNCTION_FLAGS_OFFSET = 16u;
constexpr uint32_t BLUA32_FUNCTION_UPVALUE_TABLE_ADDRESS_OFFSET = 20u;
constexpr uint32_t BLUA32_FUNCTION_UPVALUE_COUNT_OFFSET = 24u;
constexpr uint32_t BLUA32_FUNCTION_RESERVED_OFFSET = 28u;

constexpr uint32_t BLUA32_FUNCTION_VARARG = 1u << 0u;
constexpr uint32_t BLUA32_FUNCTION_STATIC = 1u << 1u;

constexpr uint32_t BLUA32_UPVALUE_RECORD_SIZE = 4u;
constexpr uint32_t BLUA32_UPVALUE_IN_STACK_MASK = 0x80000000u;
constexpr uint32_t BLUA32_UPVALUE_INDEX_MASK = 0x7fffffffu;

constexpr uint32_t BLUA32_CONSTANT_RECORD_SIZE = 16u;
constexpr uint32_t BLUA32_CONSTANT_TAG_OFFSET = 0u;
constexpr uint32_t BLUA32_CONSTANT_PAYLOAD_OFFSET = 4u;
constexpr uint32_t BLUA32_CONSTANT_STRING_BYTE_COUNT_OFFSET = 8u;

constexpr uint32_t BLUA32_GLOBAL_NAME_RECORD_SIZE = 8u;
constexpr uint32_t BLUA32_GLOBAL_NAME_ADDRESS_OFFSET = 0u;
constexpr uint32_t BLUA32_GLOBAL_NAME_BYTE_COUNT_OFFSET = 4u;

enum class Blua32ConstantTag : uint32_t {
	Nil = 0u,
	False = 1u,
	True = 2u,
	Number = 3u,
	String = 4u,
};

} // namespace bmsx
