#include "spec/blua32/opcode.h"

namespace bmsx {

const std::array<uint8_t, OPCODE_COUNT> BASE_CYCLES{
	0u, // WIDE
	1u, // MOV
	1u, // LOADK
	1u, // LOADNIL
	2u, // LOAD_MEM_D
	1u, // KNIL
	1u, // KFALSE
	1u, // KTRUE
	1u, // K0
	1u, // K1
	1u, // KM1
	1u, // KSMI
	2u, // STORE_MEM_D
	2u, // STORE_MEM_WORDS_D
	1u, // GETT
	2u, // SETT
	1u, // NEWT
	1u, // ADD
	1u, // SUB
	1u, // MUL
	1u, // DIV
	1u, // MOD
	1u, // FLOORDIV
	1u, // POW
	1u, // BAND
	1u, // BOR
	1u, // BXOR
	1u, // SHL
	1u, // SHR
	1u, // CONCAT
	2u, // CONCATN
	1u, // UNM
	1u, // NOT
	1u, // LEN
	1u, // BNOT
	1u, // EQ
	1u, // LT
	1u, // LE
	1u, // MFC0
	1u, // MTC0
	1u, // JMP
	1u, // JMPIF
	1u, // JMPIFNOT
	1u, // CLOSURE
	1u, // GETUP
	2u, // SETUP
	2u, // VARARG
	2u, // CALL
	2u, // RET
	2u, // LOAD_MEM
	2u, // STORE_MEM
	2u, // STORE_MEM_WORDS
	1u, // RFE
	1u, // LOADKR
	1u, // GETSYS
	2u, // SETSYS
	1u, // GETGL
	2u, // SETGL
	1u, // GETI
	2u, // SETI
	1u, // GETFIELD
	2u, // SETFIELD
	1u, // SELF
	1u, // HALT
};

const std::array<uint8_t, OPCODE_COUNT> OPCODE_USES_BX{
	0u, // WIDE
	0u, // MOV
	1u, // LOADK
	0u, // LOADNIL
	0u, // LOAD_MEM_D
	0u, // KNIL
	0u, // KFALSE
	0u, // KTRUE
	0u, // K0
	0u, // K1
	0u, // KM1
	1u, // KSMI
	0u, // STORE_MEM_D
	0u, // STORE_MEM_WORDS_D
	0u, // GETT
	0u, // SETT
	0u, // NEWT
	0u, // ADD
	0u, // SUB
	0u, // MUL
	0u, // DIV
	0u, // MOD
	0u, // FLOORDIV
	0u, // POW
	0u, // BAND
	0u, // BOR
	0u, // BXOR
	0u, // SHL
	0u, // SHR
	0u, // CONCAT
	0u, // CONCATN
	0u, // UNM
	0u, // NOT
	0u, // LEN
	0u, // BNOT
	0u, // EQ
	0u, // LT
	0u, // LE
	0u, // MFC0
	0u, // MTC0
	1u, // JMP
	1u, // JMPIF
	1u, // JMPIFNOT
	1u, // CLOSURE
	0u, // GETUP
	0u, // SETUP
	0u, // VARARG
	0u, // CALL
	0u, // RET
	0u, // LOAD_MEM
	0u, // STORE_MEM
	0u, // STORE_MEM_WORDS
	0u, // RFE
	0u, // LOADKR
	1u, // GETSYS
	1u, // SETSYS
	1u, // GETGL
	1u, // SETGL
	0u, // GETI
	0u, // SETI
	0u, // GETFIELD
	0u, // SETFIELD
	0u, // SELF
	0u, // HALT
};

const std::array<uint8_t, OPCODE_COUNT> OPCODE_USES_DISP{
	0u, // WIDE
	0u, // MOV
	0u, // LOADK
	0u, // LOADNIL
	1u, // LOAD_MEM_D
	0u, // KNIL
	0u, // KFALSE
	0u, // KTRUE
	0u, // K0
	0u, // K1
	0u, // KM1
	0u, // KSMI
	1u, // STORE_MEM_D
	1u, // STORE_MEM_WORDS_D
	0u, // GETT
	0u, // SETT
	0u, // NEWT
	0u, // ADD
	0u, // SUB
	0u, // MUL
	0u, // DIV
	0u, // MOD
	0u, // FLOORDIV
	0u, // POW
	0u, // BAND
	0u, // BOR
	0u, // BXOR
	0u, // SHL
	0u, // SHR
	0u, // CONCAT
	0u, // CONCATN
	0u, // UNM
	0u, // NOT
	0u, // LEN
	0u, // BNOT
	0u, // EQ
	0u, // LT
	0u, // LE
	0u, // MFC0
	0u, // MTC0
	0u, // JMP
	0u, // JMPIF
	0u, // JMPIFNOT
	0u, // CLOSURE
	0u, // GETUP
	0u, // SETUP
	0u, // VARARG
	0u, // CALL
	0u, // RET
	0u, // LOAD_MEM
	0u, // STORE_MEM
	0u, // STORE_MEM_WORDS
	0u, // RFE
	0u, // LOADKR
	0u, // GETSYS
	0u, // SETSYS
	0u, // GETGL
	0u, // SETGL
	0u, // GETI
	0u, // SETI
	0u, // GETFIELD
	0u, // SETFIELD
	0u, // SELF
	0u, // HALT
};

} // namespace bmsx
