export const COMMON_LANGUAGE_LINT_RULES = [
	'local_const_pattern',
	'single_use_local_pattern',
	'empty_string_condition_pattern',
	'empty_string_fallback_pattern',
	'or_nil_fallback_pattern',
	'explicit_truthy_comparison_pattern',
	'string_or_chain_comparison_pattern',
	'single_line_method_pattern',
	'useless_terminal_return_pattern',
] as const;

export const CODE_QUALITY_ONLY_LINT_RULES = [
	'hot_path_object_literal_pattern',
	'hot_path_closure_argument_pattern',
	'nullish_null_normalization_pattern',
	'nullish_return_guard_pattern',
	'ensure_lazy_init_pattern',
	'ensure_pattern',
	'lookup_alias_return_pattern',
	'defensive_optional_chain_pattern',
	'numeric_defensive_sanitization_pattern',
	'repeated_expression_pattern',
	'facade_module_density_pattern',
	'normalized_ast_duplicate_pattern',
	'cross_layer_import_pattern',
	'duplicate_exported_type_name_pattern',
] as const;

export const CODE_QUALITY_LINT_RULES = [
	...COMMON_LANGUAGE_LINT_RULES,
	...CODE_QUALITY_ONLY_LINT_RULES,
] as const;

export const LUA_CART_ONLY_LINT_RULES = [
	'syntax_error_pattern',
	'uppercase_code_pattern',
	'comparison_wrapper_getter_pattern',
	'visual_update_pattern',
	'bool01_duplicate_pattern',
	'pure_copy_function_pattern',
	'useless_assert_pattern',
	'cross_file_local_global_constant_pattern',
	'shadowed_require_alias_pattern',
	'unused_init_value_pattern',
	'getter_setter_pattern',
	'builtin_recreation_pattern',
	'forbidden_math_floor_pattern',
	'forbidden_random_helper_pattern',
	'local_function_const_pattern',
	'multi_has_tag_pattern',
	'single_use_has_tag_pattern',
	'self_property_local_alias_pattern',
	'imgid_assignment_pattern',
	'self_imgid_assignment_pattern',
	'imgid_fallback_pattern',
	'forbidden_transition_to_pattern',
	'forbidden_matches_state_path_pattern',
	'forbidden_dispatch_pattern',
	'event_handler_dispatch_pattern',
	'event_handler_state_dispatch_pattern',
	'event_handler_flag_proxy_pattern',
	'contiguous_multi_emit_pattern',
	'dispatch_fanout_loop_pattern',
	'tick_flag_polling_pattern',
	'tick_input_check_pattern',
	'action_triggered_bool_chain_pattern',
	'set_space_roundtrip_pattern',
	'cross_object_state_event_relay_pattern',
	'foreign_object_internal_mutation_pattern',
	'runtime_tag_table_access_pattern',
	'fsm_state_name_mirror_assignment_pattern',
	'constant_copy_pattern',
	'split_local_table_init_pattern',
	'duplicate_initializer_pattern',
	'handler_identity_dispatch_pattern',
	'ensure_local_alias_pattern',
	'service_definition_suffix_pattern',
	'define_factory_tick_enabled_pattern',
	'define_factory_space_id_pattern',
	'create_service_id_addon_pattern',
	'define_service_id_pattern',
	'fsm_entering_state_visual_setup_pattern',
	'fsm_direct_state_handler_shorthand_pattern',
	'fsm_event_reemit_handler_pattern',
	'fsm_forbidden_legacy_fields_pattern',
	'fsm_process_input_polling_transition_pattern',
	'fsm_run_checks_input_transition_pattern',
	'fsm_lifecycle_wrapper_pattern',
	'fsm_tick_counter_transition_pattern',
	'fsm_id_label_pattern',
	'bt_id_label_pattern',
	'injected_service_id_property_pattern',
	'inline_static_lookup_table_pattern',
	'staged_export_local_call_pattern',
	'staged_export_local_table_pattern',
	'require_lua_extension_pattern',
	'branch_uninitialized_local_pattern',
	'ensure_pattern',
	'forbidden_render_wrapper_call_pattern',
	'forbidden_render_module_require_pattern',
	'forbidden_render_layer_string_pattern',
] as const;

export const LUA_CART_LINT_RULES = [
	...COMMON_LANGUAGE_LINT_RULES,
	...LUA_CART_ONLY_LINT_RULES,
] as const;

export type CommonLanguageLintRule = typeof COMMON_LANGUAGE_LINT_RULES[number];
export type CodeQualityOnlyLintRule = typeof CODE_QUALITY_ONLY_LINT_RULES[number];
export type CodeQualityLintRule = typeof CODE_QUALITY_LINT_RULES[number];
export type LuaCartOnlyLintRule = typeof LUA_CART_ONLY_LINT_RULES[number];
export type LuaCartLintRule = typeof LUA_CART_LINT_RULES[number];
