local constants<const> = {}

constants.ids = {
	stage_def = 'nemesis_s.stage',
	stage_instance = 'nemesis_s.stage',
	stage_fsm = 'nemesis_s.stage.fsm',
	stage_star_blink_timeline = 'nemesis_s.stage.timeline.star_blink',
	player_def = 'nemesis_s.player',
	player_instance = 'nemesis_s.player',
	player_fsm = 'nemesis_s.player.fsm',
	director_def = 'nemesis_s.director',
	director_instance = 'nemesis_s.director',
	director_fsm = 'nemesis_s.director.fsm',
}

constants.machine = {
	screen_width = 256,
	screen_height = 192,
	game_width = 256,
	game_height = 176,
}

constants.player = {
	width = 16,
	height = 10,
	start_x = 80,
	start_y = 60,
	base_movement_speed = 1,
	movement_speed_increase = 1,
	speed_powerups = 0,
	option_follow_delay = 10,
	max_projectiles = 2,
	fire_spawn_offset_x = 16,
	fire_spawn_offset_y = 5,
	hitcheck_x = { 4, 8, 14, 4, 8, 8 },
	hitcheck_y = { 4, 4, 5, 7, 5, 7 },
}

constants.loadout = {
	speed_powerups = 1,
	option_count = 4,
	laser_level = 2,
	missile_level = 2,
	uplaser_level = 2,
}

constants.projectile = {
	width = 6,
	height = 2,
	movement_speed = 6,
}

constants.weapons = {
	laser = {
		tile_width = 8,
		tile_height = 2,
		movement_speed = 18,
		max_length_px = 240,
		max_active = 1,
		spawn_offset_x = 16,
		spawn_offset_y = 5,
	},
	missile = {
		width = 8,
		height_fall = 8,
		height_floor = 4,
		movement_speed = 4,
		max_active = 1,
		spawn_offset_x = 4,
		spawn_offset_y = 0,
	},
	uplaser = {
		tile_width = 8,
		tile_height = 2,
		length_unit_px = 8,
		movement_speed = 4,
		max_active = 1,
		level1_length_units = 2,
		level2_initial_length_units = 2,
		level2_gate_frames = 4,
		level2_growth_units_per_gate = 2,
		level2_growth_units_at_top = 1,
		level2_extra_rise_px = 8,
		spawn_offset_x = 0,
		spawn_offset_y = 8,
	},
}

constants.stage = {
	asset_id = 'nemesis_s_stage',
	star_blink_gate_frames = 15,
	star_particle_z = 8,
}

constants.assets = {
	player_n = 'metallion_n',
	player_u = 'metallion_u',
	player_d = 'metallion_d',
	option1 = 'option1',
	option2 = 'option2',
	option3 = 'option3',
	option4 = 'option4',
	projectile = 'kogeltje',
	laser = 'laser',
	missile1 = 'missile1',
	missile2 = 'missile2',
	star_blue = 'star_blue',
	star_yellow = 'star_yellow',
	house_tile_1 = 'house_tile_1',
	house_tile_2 = 'house_tile_2',
	house_tile_3 = 'house_tile_3',
	house_tile_4 = 'house_tile_4',
	house_tile_5 = 'house_tile_5',
	house_tile_6 = 'house_tile_6',
	house_tile_7 = 'house_tile_7',
	house_tile_8 = 'house_tile_8',
	house_tile_9 = 'house_tile_9',
	house_tile_10 = 'house_tile_10',
	house_tile_11 = 'house_tile_11',
	house_tile_12 = 'house_tile_12',
	house_tile_13 = 'house_tile_13',
	house_tile_door = 'house_tile_door',
	house_tile_window = 'house_tile_window',
	house_tile_window2 = 'house_tile_window2',
	lantaarn_tile_1 = 'lantaarn_tile_1',
	lantaarn_tile_2 = 'lantaarn_tile_2',
	lantaarn_tile_3 = 'lantaarn_tile_3',
	ground = 'ground',
	ground2 = 'ground2',
	ground_v = 'ground_v',
	ground2_v = 'ground2_v',
	ground3 = 'ground3',
	ground4 = 'ground4',
	ground_start = 'ground_start',
	ground_end = 'ground_end',
	ground_start_v = 'ground_start_v',
	ground_end_v = 'ground_end_v',
	snow = 'snow',
	schoorsteen1 = 'schoorsteen1',
	schoorsteen2 = 'schoorsteen2',
	schoorsteen3 = 'schoorsteen3',
	snowtree1 = 'snowtree1',
	snowtree2 = 'snowtree2',
	snowtree3 = 'snowtree3',
	snowtree4 = 'snowtree4',
	snowtree5 = 'snowtree5',
	snowtree6 = 'snowtree6',
	snowtree7 = 'snowtree7',
	snowtree8 = 'snowtree8',
	snowtree9 = 'snowtree9',
	snowtree10 = 'snowtree10',
	snowtree11 = 'snowtree11',
	snowtree12 = 'snowtree12',
	snowtree13 = 'snowtree13',
	snowtree14 = 'snowtree14',
	snowtree15 = 'snowtree15',
	snowtree16 = 'snowtree16',
	snowtree17 = 'snowtree17',
	snowtree18 = 'snowtree18',
	snowtree19 = 'snowtree19',
	snowtree20 = 'snowtree20',
	snowtree21 = 'snowtree21',
}

constants.stars = {
	yellow = {
		{ x = 4, y = 10 },
		{ x = 92, y = 10 },
		{ x = 184, y = 10 },
		{ x = 196, y = 10 },
		{ x = 60, y = 43 },
		{ x = 236, y = 43 },
		{ x = 76, y = 58 },
		{ x = 220, y = 74 },
		{ x = 36, y = 75 },
		{ x = 140, y = 91 },
		{ x = 4, y = 10 },
		{ x = 172, y = 107 },
		{ x = 4, y = 10 },
		{ x = 99, y = 122 },
		{ x = 131, y = 138 },
		{ x = 155, y = 138 },
		{ x = 179, y = 154 },
	},
	blue = {
		{ x = 44, y = 3 },
		{ x = 20, y = 35 },
		{ x = 124, y = 35 },
		{ x = 204, y = 35 },
		{ x = 108, y = 51 },
		{ x = 134, y = 67 },
		{ x = 252, y = 67 },
		{ x = 52, y = 99 },
		{ x = 116, y = 99 },
		{ x = 212, y = 99 },
		{ x = 243, y = 115 },
		{ x = 67, y = 132 },
		{ x = 187, y = 132 },
		{ x = 99, y = 122 },
		{ x = 27, y = 127 },
		{ x = 227, y = 127 },
	},
}

constants.telemetry = {
	enabled = false,
	metric_prefix = 'NEMESIS_S_METRIC',
	event_prefix = 'NEMESIS_S_EVENT',
}

return constants
