#!/usr/bin/env bash
# History of non-dry-run apply commands used to migrate exported functions
# Generated by the assistant on 2025-11-24. This file records the exact apply
# commands (no --dry-run) that were run during the refactor session.

set -euo pipefail

# NOTE: these commands were executed from the repository root (/home/boaz/BMSX)
# to move named exported functions from the monolithic file into smaller modules.
# Run them again if you want to re-apply the same moves on another checkout.

# diagnostics -> diagnostics.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/diagnostics.ts \
	-n enqueueDiagnosticsJob -n executeDiagnosticsComputation -n findContextByChunk \
	-n getActiveSemanticDefinitions -n getConsoleRuntime -n getDiagnosticsForRow \
	-n getLuaModuleAliases -n handleRuntimeTaskError -n buildRuntimeErrorLines \
	-n clearAllRuntimeErrorOverlays -n clearExecutionStopHighlights -n clearRuntimeErrorOverlay \
	-n collectDiagnosticsBatch -n copyRuntimeErrorOverlayToClipboard -n createDiagnosticProviders \
	-n hasPendingRuntimeReload -n markDiagnosticsDirty \
	-n navigateToRuntimeErrorFrameTarget -n prepareRuntimeSnapshotForResume -n processRuntimeErrorOverlayPointer \
	-n scheduleRuntimeTask -n setActiveRuntimeErrorOverlay -n setExecutionStopHighlight \
	-n showRuntimeError -n showRuntimeErrorInChunk -n simplifyRuntimeErrorMessage -n tryShowLuaErrorOverlay \
	-n findFunctionDefinitionRowInActiveFile -n getActiveBreakpointChunkName -n toggleBreakpointAtCursor -n toggleBreakpointForEditorRow

# search_ui -> search_ui.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/search_ui.ts \
	-n searchVisibleResultCount -n searchResultEntryHeight \
	-n renderSearchResults -n openSearch -n closeSearch -n toggleSearch -n focusSearchField \
	-n applySearchFilter -n computeSearchMatches -n collectSymbolSearchResults -n symbolCatalogDedupKey

# window_listeners -> window_listeners.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/window_listeners.ts \
	-n installPlatformVisibilityListener -n installWindowEventListeners \
	-n resetInputFocusState -n requestWindowFocusState -n flushWindowFocusState

# runtime_overlay -> runtime_overlay.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/runtime_overlay.ts \
	-n syncRuntimeErrorOverlayFromContext -n updateRuntimeErrorOverlay \
	-n showRuntimeOverlay -n hideRuntimeOverlay -n computeOverlayBounds -n renderRuntimeOverlay \
	-n handleRuntimeHover -n clearRuntimeOverlay -n enqueueRuntimeOverlayUpdate -n processRuntimeOverlayQueue

# draw -> draw.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/draw.ts \
	-n drawCodeArea -n drawRuntimeErrorOverlay -n drawTopBar -n drawStatusArea

# ui_layout -> ui_layout.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/ui_layout.ts \
	-n computeEditorBounds -n getSymbolSearchBarHeight -n computeInlineBarBounds \
	-n topBarHeight -n computeTabBarHeight -n visibleRowCount -n statusAreaHeight -n computeProblemsPanelHeight

# topbar -> topbar.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/topbar.ts \
	-n renderTopBar -n handleTopBarButtonClick -n updateTopBarState -n openActionPrompt \
	-n closeActionPrompt -n computeTopBarButtonBounds -n topBarPointerHandler -n drawTopBarButtons -n updateTopBarTooltip

# pointer -> pointer.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/pointer.ts \
	-n registerPointerClick -n resetPointerClickTracking -n handlePointerMove -n handlePointerDown \
	-n handlePointerUp -n handlePointerLeave -n updateHoverState -n pointerHoverTooltip -n processPointerWheel -n computePointerPosition -n handlePointerDoubleClick

# navigation -> navigation.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/navigation.ts \
	-n beginNavigationCapture -n completeNavigation -n setActiveTab -n closeTab -n navigateToSymbol \
	-n navigateBackward -n navigateForward -n computeNavigationCheckpoint -n saveNavigationState -n restoreNavigationState

# editor_core -> editor_core.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/editor_core.ts \
	-n invalidateLineRange -n findWordLeft -n findWordRight -n getLineRangeForMovement \
	-n getTabBarTotalHeight -n topMargin -n statusAreaHeight -n bottomMargin -n getVisibleProblemsPanelHeight \
	-n getStatusMessageLines -n tryShowLuaErrorOverlay -n safeInspectLuaExpression -n update -n processDiagnosticsQueue \
	-n scheduleDiagnosticsComputation -n runDiagnosticsForContexts -n updateDiagnosticsAggregates -n refreshActiveDiagnostics -n markDiagnosticsDirtyForChunk -n isActive

# lifecycle -> lifecycle.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/lifecycle.ts \
	-n serializeState -n restoreState -n shutdown -n getKeyboard -n handleEscapeShortcut \
	-n toggleEditorFromShortcut -n handleEscapeKey -n activate -n applyEditorCrtDimming -n restoreCrtOptions -n deactivate \
	-n applyCaseNormalizationIfNeeded -n applyDocumentFormatting -n applySourceToDocument -n bumpTextVersion \
	-n capturePreMutationSource -n computeDocumentOffset -n computeEditContextFromSources -n createConsoleCartEditor \
	-n ensureVisualLines -n flushWindowFocusState -n getBuiltinIdentifierSet -n handlePostEditMutation \
	-n initializeConsoleCartEditor -n installPlatformVisibilityListener -n installWindowEventListeners -n markTextMutated \
	-n recordEditContext -n requestSemanticRefresh -n requestWindowFocusState -n resetActionPromptState \
	-n resetBlink -n resetEditorContent -n resetInputFocusState -n scheduleNextFrame -n serializeCurrentSource \
	-n splitLines -n update -n updateBlink

# input_and_prompt -> input_and_prompt.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/input_and_prompt.ts \
	-n splitLines -n handleActionPromptInput -n handleEditorInput -n handleCustomKeybinding \
	-n handleCreateResourceInput -n openCreateResourcePrompt -n closeCreateResourcePrompt -n cancelCreateResourcePrompt

# symbols_focus -> symbols_focus.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/symbols_focus.ts \
	-n symbolPriority -n symbolKindLabel -n symbolSourceLabel -n focusEditorFromProblemsPanel -n focusEditorFromResourcePanel

# topbar_pointer_actions -> topbar_pointer_actions.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/topbar_pointer_actions.ts \
	-n handleActionPromptPointer -n handleTopBarPointer -n handleTabBarPointer -n handleTabBarMiddleClick \
	-n handlePointerWheel -n handleTopBarButtonPress -n openActionPrompt -n executePendingAction -n performAction -n performResume -n performReboot \
	-n attemptPromptSave -n executePendingAction -n handleActionPromptSelection -n openActionPrompt \
	-n performAction -n performReboot -n performResume -n handleActionPromptPointer

# pointer_inline -> pointer_inline.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/pointer_inline.ts \
	-n applySymbolSearchFieldText -n inlineFieldMetrics -n createInlineFieldEditingHandlers \
	-n processInlineFieldEditing -n processInlineFieldPointer -n updateRuntimeErrorOverlay -n pasteFromClipboard -n registerPointerClick -n resetPointerClickTracking

# resource_panel -> resource_panel.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/resource_panel.ts \
	-n findFunctionDefinitionRowInActiveFile -n notifyReadOnlyEdit -n toggleResourcePanel -n toggleProblemsPanel \
	-n showProblemsPanel -n hideProblemsPanel -n toggleResourcePanelFilterMode -n updateViewport -n toggleResolutionMode -n toggleWordWrap \
	-n hideResourcePanel -n openLuaCodeTab -n openResourceViewerTab -n closeActiveTab -n resetEditorContent -n resetResourcePanelState \
	-n refreshResourcePanelContents -n enterResourceViewer -n applyPendingResourceSelection -n appendResourceViewerLines \
	-n clampResourcePanelRatio -n collectEventEmitterLines -n collectRegistryLines -n collectWorldObjectLines \
	-n computePanelPixelWidth -n computePanelRatioBounds -n defaultResourcePanelRatio -n describeListenerSet \
	-n describeMetadataValue -n drawResourceViewer -n ensureResourceViewerSprite -n enterResourceViewerTab \
	-n hideResourcePanel -n hideResourceViewerSprite -n isDebugPanelActive -n isPointerOverResourcePanelDivider \
	-n resourceBrowserEnsureSelectionVisible -n resourceViewerClampScroll -n resourceViewerImageLayout \
	-n resourceViewerTextCapacity -n resetResourcePanelState -n safeJsonStringify -n scrollResourceBrowser \
	-n scrollResourceBrowserHorizontal -n scrollResourceViewer -n toggleProblemsPanel -n toggleResolutionMode \
	-n toggleResourcePanel -n toggleResourcePanelFilterMode -n toggleWordWrap -n trimResourceViewerLines

# text_editing -> text_editing.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/text_editing.ts \
	-n addLineComments -n countLeadingIndent -n currentLine -n deleteActiveLines \
	-n deleteCharLeft -n deleteCharRight -n deleteSelection -n deleteWordBackward \
	-n deleteWordForward -n firstNonWhitespaceIndex -n indentSelectionOrLine -n insertNewline \
	-n moveSelectionLines -n removeLineComments -n shiftPositionsForInsertion \
	-n shiftPositionsForRemoval -n toggleLineComments -n unindentSelectionOrLine \
	-n copySelectionToClipboard -n cutLineToClipboard -n cutSelectionToClipboard -n pasteFromClipboard -n save -n writeClipboard

# undo_snapshot -> undo_snapshot.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/undo_snapshot.ts \
	-n breakUndoSequence -n captureSnapshot -n prepareUndo -n recordSnapshotPre \
	-n recordSnapshotPost -n redo -n restoreSnapshot -n undo

# viewport -> viewport.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/viewport.ts \
	-n applyScrollbarScroll -n clampScrollColumn -n clampScrollRow -n codeViewportTop \
	-n computeMaximumScrollColumn -n computeWrapWidth -n ensureCursorVisible -n getCodeAreaBounds \
	-n getVisualLineCount -n mapScreenPointToViewport -n maximumLineLength -n resolvePointerColumn \
	-n resolvePointerRow -n scrollRows -n visualIndexToSegment -n visibleColumnCount -n visibleRowCount

# cursor -> cursor.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/cursor.ts \
	-n centerCursorVertically -n clampCursorColumn -n clampCursorRow -n clampSelectionPosition \
	-n moveCursorDown -n moveCursorEnd -n moveCursorHome -n moveCursorHorizontal -n moveCursorLeft \
	-n moveCursorRight -n moveCursorUp -n moveCursorVertical -n moveWordLeft -n moveWordRight \
	-n onCursorMoved -n pageDown -n pageUp -n positionToVisualIndex -n revealCursor \
	-n setCursorFromVisualIndex -n setCursorPosition -n updateDesiredColumn

# search_navigation -> search_navigation.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/search_navigation.ts \
	-n applyDefinitionSelection -n applyLineJump -n applySearchFieldText -n applySymbolSearchSelection \
	-n buildReferenceCatalogForExpression -n cancelSearchJob -n clearGotoHoverHighlight -n clearReferenceHighlights \
	-n closeLineJump -n closeResourceSearch -n closeSymbolSearch -n commitRename -n ensureResourceSearchSelectionVisible \
	-n ensureSymbolSearchSelectionVisible -n extractHoverExpression -n extractIdentifierAt -n findDefinitionAtPosition \
	-n focusEditorFromLineJump -n focusEditorFromRename -n focusEditorFromResourceSearch -n focusEditorFromSymbolSearch \
	-n getActiveSymbolSearchMatch -n getCrossFileRenameDependencies -n gotoDiagnostic -n handleCompletionKeybindings \
	-n handleLineJumpInput -n handleResourceSearchInput -n handleSearchInput -n handleSymbolSearchInput \
	-n moveResourceSearchSelection -n moveSymbolSearchSelection -n navigateToLuaDefinition -n openGlobalSymbolSearch \
	-n openLineJump -n openReferenceSearchPopup -n openRenamePrompt -n openResourceSearch -n openSymbolSearch \
	-n refreshGotoHoverHighlight -n refreshSymbolCatalog -n resolveSemanticDefinitionLocation -n showReferenceStatusMessage \
	-n tryGotoDefinitionAt -n updateReferenceSearchMatches -n updateSymbolSearchMatches -n applyLineJumpFieldText \
	-n buildMemberCompletionItems

# resources -> resources.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/resources.ts \
	-n applyCreateResourceFieldText -n applyResourceSearchFieldText -n applyResourceSearchSelection \
	-n buildDefaultResourceContents -n buildResourceViewerState -n determineCreateResourceDefaultPath \
	-n ensureDirectorySuffix -n findResourceDescriptorByasset_id -n findResourceDescriptorForChunk \
	-n findResourcePanelIndexByasset_id -n focusResourceByAsset -n getActiveResourceViewer \
	-n getCreateResourceBarBounds -n getCreateResourceBarHeight -n getMainProgramSourceForReload \
	-n getResourcePanelWidth -n getSourceForChunk -n isCreateResourceVisible -n isValidCreateResourceCharacter \
	-n listResourcesStrict -n normalizeChunkName -n normalizeChunkReference -n normalizeCreateResourceRequest \
	-n normalizeResourcePath -n openResourceDescriptor -n refreshResourceCatalog -n selectResourceInPanel \
	-n stripExtension -n updateResourceSearchMatches -n appendResourceViewerLines -n trimResourceViewerLines

# ui_render -> ui_render.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/ui_render.ts \
	-n adjustHoverTooltipScroll -n assertMonospace -n buildHoverContentLines -n buildStatusLeftInfo \
	-n clearHoverTooltip -n columnToDisplay -n computeCursorScreenInfo -n draw -n drawActionPromptOverlay \
	-n drawCodeArea -n drawCreateResourceBar -n drawCreateResourceErrorDialog -n drawLineJumpBar \
	-n drawProblemsPanel -n drawRectOutlineColor -n drawReferenceHighlightsForRow -n drawRenameBar \
	-n drawResourcePanel -n drawResourceSearchBar -n drawResourceViewer -n drawRuntimeErrorOverlay \
	-n drawSearchBar -n drawSearchHighlightsForRow -n drawStatusBar -n drawSymbolSearchBar \
	-n drawTopBar -n getCachedHighlight -n getLineJumpBarBounds -n getProblemsPanelBounds \
	-n getRenameBarBounds -n getResourceSearchBarBounds -n getSearchBarBounds -n getStatusMessageLines \
	-n getSymbolSearchBarBounds -n getTabBarTotalHeight -n getVisibleProblemsPanelHeight -n invalidateAllHighlights \
	-n invalidateHighlightsFromRow -n invalidateLine -n invertColorIndex -n isPointInHoverTooltip \
	-n isPointerOverProblemsPanelDivider -n isRenameVisible -n isResourceSearchVisible -n isSearchVisible \
	-n isSymbolSearchVisible -n measureRangeFast -n measureText -n pointerHitsHoverTarget -n renderCodeArea \
	-n renderCreateResourceBar -n renderErrorOverlayText -n renderLineJumpBar -n renderRenameBar \
	-n renderResourceSearchBar -n renderSearchBar -n renderStatusBar -n renderSymbolSearchBar \
	-n renderTabBar -n renderTopBar -n resolveHoverasset_id -n resolveHoverChunkName -n resolvePaletteIndex \
	-n setProblemsPanelHeightFromViewportY -n sliceHighlightedLine -n topMargin -n truncateTextToWidth \
	-n updateHoverTooltip -n updateTabHoverState

# input_handlers -> input_handlers.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/input_handlers.ts \
	-n createInlineFieldEditingHandlers -n handleActionPromptInput -n handleActionPromptPointer \
	-n handleCodeFormattingShortcut -n handleCreateResourceInput -n handleCustomKeybinding -n handleEditorInput \
	-n handleEscapeKey -n handleEscapeShortcut -n handlePointerInput -n handlePointerWheel -n handleResourceViewerInput \
	-n handleTabBarMiddleClick -n handleTabBarPointer -n handleTopBarButtonPress -n handleTopBarPointer \
	-n inlineFieldMetrics -n processInlineFieldEditing -n processInlineFieldPointer -n readPointerSnapshot \
	-n registerPointerClick -n resetPointerClickTracking -n shouldFireRepeat -n toggleEditorFromShortcut

# tabs_nav -> tabs_nav.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/tabs_nav.ts \
	-n applyNavigationEntry -n areNavigationEntriesEqual -n beginNavigationCapture -n cloneNavigationEntry \
	-n completeNavigation -n createNavigationEntry -n goBackwardInNavigationHistory -n goForwardInNavigationHistory \
	-n openDebugOverviewTab -n openDebugPanelTab -n openEventInspectorTab -n openLuaCodeTab -n openObjectInspectorTab \
	-n openResourceViewerTab -n pushNavigationEntry -n withNavigationCaptureSuspended

# utils_editor -> utils_editor.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/utils_editor.ts \
	-n bottomMargin -n buildDebugPanelLines -n buildProjectReferenceContext -n debugPanelTabId \
	-n digitFilter -n findWordLeft -n findWordRight -n getLineRangeForMovement -n lowerBound \
	-n notifyReadOnlyEdit -n pointInRect -n showProblemsPanel -n statusAreaHeight

# search_helpers -> search_helpers.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/console_cart_editor.ts \
	--dest src/bmsx/ide/search_helpers.ts \
	-n isResourceSearchCompactMode -n isSymbolSearchCompactMode -n resourceSearchEntryHeight \
	-n resourceSearchPageSize -n resourceSearchVisibleResultCount -n resourceSearchWindowCapacity \
	-n searchResultEntryHeight -n searchVisibleResultCount -n symbolSearchEntryHeight \
	-n symbolSearchPageSize -n symbolSearchVisibleResultCount -n symbolCatalogDedupKey

# Merge debugger files into debugger.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/debugger_breakpoints.ts \
	--dest src/bmsx/ide/debugger.ts \
	-n hasBreakpoint -n getBreakpointsForChunk -n toggleBreakpoint -n serializeBreakpoints -n restoreBreakpointsFromPayload -n syncRuntimeBreakpoints

node scripts/move_functions.js \
	--source src/bmsx/ide/debugger_controls.ts \
	--dest src/bmsx/ide/debugger.ts \
	-n getDebuggerCommandExecutor -n issueDebuggerCommand

node scripts/move_functions.js \
	--source src/bmsx/ide/debugger_overlay_controller.ts \
	--dest src/bmsx/ide/debugger.ts \
	-n showDebuggerPauseOverlay -n clearDebuggerPauseOverlay -n prepareDebuggerStepOverlay

node scripts/move_functions.js \
	--source src/bmsx/ide/debugger_shortcuts.ts \
	--dest src/bmsx/ide/debugger.ts \
	-n handleDebuggerShortcuts

node scripts/move_functions.js \
	--source src/bmsx/ide/debugger_shortcuts_core.ts \
	--dest src/bmsx/ide/debugger.ts \
	-n evaluateDebuggerShortcuts

node scripts/move_functions.js \
	--source src/bmsx/ide/debugger_ui_state.ts \
	--dest src/bmsx/ide/debugger.ts \
	-n initializeDebuggerUiState

# Merge render files into render.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/render_caret.ts \
	--dest src/bmsx/ide/render.ts \
	-n renderInlineCaret -n drawInlineCaret -n getCaretGlyphForDisplay -n drawCursor

node scripts/move_functions.js \
	--source src/bmsx/ide/render_code_area.ts \
	--dest src/bmsx/ide/render.ts \
	-n renderCodeArea

node scripts/move_functions.js \
	--source src/bmsx/ide/render_error_overlay.ts \
	--dest src/bmsx/ide/render.ts \
	-n renderRuntimeErrorOverlay

node scripts/move_functions.js \
	--source src/bmsx/ide/render_inline_bars.ts \
	--dest src/bmsx/ide/render.ts \
	-n renderCreateResourceBar -n renderSearchBar -n renderResourceSearchBar -n renderSymbolSearchBar -n renderRenameBar -n renderLineJumpBar

node scripts/move_functions.js \
	--source src/bmsx/ide/render_resource_panel.ts \
	--dest src/bmsx/ide/render.ts \
	-n renderResourcePanel

node scripts/move_functions.js \
	--source src/bmsx/ide/render_status_bar.ts \
	--dest src/bmsx/ide/render.ts \
	-n renderStatusBar

node scripts/move_functions.js \
	--source src/bmsx/ide/render_tab_bar.ts \
	--dest src/bmsx/ide/render.ts \
	-n renderTabBar

node scripts/move_functions.js \
	--source src/bmsx/ide/render_top_bar.ts \
	--dest src/bmsx/ide/render.ts \
	-n renderTopBar

# Merge runtime error overlay files into runtime_error_overlay.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/runtime_error_overlay_model.ts \
	--dest src/bmsx/ide/runtime_error_overlay.ts \
	-n cloneRuntimeErrorDetails -n rebuildRuntimeErrorOverlayView -n buildRuntimeErrorOverlayCopyText

node scripts/move_functions.js \
	--source src/bmsx/ide/runtime_error_overlay_navigation.ts \
	--dest src/bmsx/ide/runtime_error_overlay.ts \
	-n navigateRuntimeErrorOverlay

# Merge rename files into rename.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/rename_apply.ts \
	--dest src/bmsx/ide/rename.ts \
	-n applyRename

node scripts/move_functions.js \
	--source src/bmsx/ide/rename_controller.ts \
	--dest src/bmsx/ide/rename.ts \
	-n handleRename

node scripts/move_functions.js \
	--source src/bmsx/ide/rename_cross_file.ts \
	--dest src/bmsx/ide/rename.ts \
	-n renameCrossFile

# Merge reference files into reference.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/reference_navigation.ts \
	--dest src/bmsx/ide/reference.ts \
	-n navigateReferences

node scripts/move_functions.js \
	--source src/bmsx/ide/reference_sources.ts \
	--dest src/bmsx/ide/reference.ts \
	-n getReferenceSources

# Merge text utils files into text_utils.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/text_utils_local.ts \
	--dest src/bmsx/ide/text_utils.ts \
	-n localTextUtils

# Merge input files into input.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/input_controller.ts \
	--dest src/bmsx/ide/input.ts \
	-n handleInput

node scripts/move_functions.js \
	--source src/bmsx/ide/input_helpers.ts \
	--dest src/bmsx/ide/input.ts \
	-n resetKeyPressRecords -n clearKeyPressRecord -n shouldAcceptKeyPress -n isKeyJustPressed -n isModifierPressed -n isKeyPressed -n isKeyTyped

node scripts/move_functions.js \
	--source src/bmsx/ide/player_input_adapter.ts \
	--dest src/bmsx/ide/input.ts \
	-n adaptPlayerInput

# Merge semantic files into semantic.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/semantic_model.ts \
	--dest src/bmsx/ide/semantic.ts \
	-n buildSemanticModel

node scripts/move_functions.js \
	--source src/bmsx/ide/semantic_worker.ts \
	--dest src/bmsx/ide/semantic.ts \
	-n runSemanticWorker

node scripts/move_functions.js \
	--source src/bmsx/ide/semantic_workspace.ts \
	--dest src/bmsx/ide/semantic.ts \
	-n manageSemanticWorkspace

# Merge editor inputs into editor_inputs.ts
node scripts/move_functions.js \
	--source src/bmsx/ide/editor_modal_inputs.ts \
	--dest src/bmsx/ide/editor_inputs.ts \
	-n handleModalInputs

node scripts/move_functions.js \
	--source src/bmsx/ide/inline_text_field.ts \
	--dest src/bmsx/ide/editor_inputs.ts \
	-n handleInlineTextField

# End of migration apply history
