import { IO_BASE, IO_WORD_SIZE, VDP_CMD_ARG_COUNT } from '../memory/map';

export const IO_SYS_BASE_INDEX = 0;
export const IO_SYS_BOOT_CART_INDEX = IO_SYS_BASE_INDEX;
export const IO_SYS_HOST_FAULT_FLAGS_INDEX = IO_SYS_BASE_INDEX + 1;
export const IO_SYS_HOST_FAULT_STAGE_INDEX = IO_SYS_BASE_INDEX + 2;
export const IO_SYS_SIZE = 3;
export const IO_VDP_BASE_INDEX = IO_SYS_BASE_INDEX + IO_SYS_SIZE;
export const IO_VDP_DITHER_INDEX = IO_VDP_BASE_INDEX;
export const IO_VDP_SLOT_PRIMARY_ATLAS_INDEX = IO_VDP_BASE_INDEX + 1;
export const IO_VDP_SLOT_SECONDARY_ATLAS_INDEX = IO_VDP_BASE_INDEX + 2;
export const IO_VDP_RD_SURFACE_INDEX = IO_VDP_BASE_INDEX + 3;
export const IO_VDP_RD_X_INDEX = IO_VDP_BASE_INDEX + 4;
export const IO_VDP_RD_Y_INDEX = IO_VDP_BASE_INDEX + 5;
export const IO_VDP_RD_MODE_INDEX = IO_VDP_BASE_INDEX + 6;
export const IO_VDP_RD_STATUS_INDEX = IO_VDP_BASE_INDEX + 7;
export const IO_VDP_RD_DATA_INDEX = IO_VDP_BASE_INDEX + 8;
export const IO_VDP_CMD_INDEX = IO_VDP_BASE_INDEX + 9;
export const IO_VDP_CMD_ARG0_INDEX = IO_VDP_BASE_INDEX + 10;
export const IO_VDP_CMD_ARG_COUNT = VDP_CMD_ARG_COUNT;
export const IO_VDP_FIFO_INDEX = IO_VDP_CMD_ARG0_INDEX + IO_VDP_CMD_ARG_COUNT;
export const IO_VDP_FIFO_CTRL_INDEX = IO_VDP_FIFO_INDEX + 1;
export const IO_VDP_PMU_BANK_INDEX = IO_VDP_FIFO_CTRL_INDEX + 1;
export const IO_VDP_PMU_X_INDEX = IO_VDP_PMU_BANK_INDEX + 1;
export const IO_VDP_PMU_Y_INDEX = IO_VDP_PMU_BANK_INDEX + 2;
export const IO_VDP_PMU_SCALE_X_INDEX = IO_VDP_PMU_BANK_INDEX + 3;
export const IO_VDP_PMU_SCALE_Y_INDEX = IO_VDP_PMU_BANK_INDEX + 4;
export const IO_VDP_PMU_CTRL_INDEX = IO_VDP_PMU_BANK_INDEX + 5;
export const IO_VDP_PMU_SIZE = 6;
export const IO_VDP_SBX_CONTROL_INDEX = IO_VDP_PMU_BANK_INDEX + IO_VDP_PMU_SIZE;
export const IO_VDP_SBX_FACE0_INDEX = IO_VDP_SBX_CONTROL_INDEX + 1;
export const IO_VDP_SBX_FACE_WORD_COUNT = 30;
export const IO_VDP_SBX_COMMIT_INDEX = IO_VDP_SBX_FACE0_INDEX + IO_VDP_SBX_FACE_WORD_COUNT;
export const IO_VDP_SBX_SIZE = 1 + IO_VDP_SBX_FACE_WORD_COUNT + 1;
export const IO_VDP_SIZE = 12 + IO_VDP_CMD_ARG_COUNT + IO_VDP_PMU_SIZE + IO_VDP_SBX_SIZE;

export const IO_IRQ_BASE_INDEX = IO_VDP_BASE_INDEX + IO_VDP_SIZE;
export const IO_IRQ_FLAGS_INDEX = IO_IRQ_BASE_INDEX;
export const IO_IRQ_ACK_INDEX = IO_IRQ_BASE_INDEX + 1;
export const IO_IRQ_SIZE = 2;

export const IO_DMA_BASE_INDEX = IO_IRQ_BASE_INDEX + IO_IRQ_SIZE;
export const IO_DMA_SRC_INDEX = IO_DMA_BASE_INDEX;
export const IO_DMA_DST_INDEX = IO_DMA_BASE_INDEX + 1;
export const IO_DMA_LEN_INDEX = IO_DMA_BASE_INDEX + 2;
export const IO_DMA_CTRL_INDEX = IO_DMA_BASE_INDEX + 3;
export const IO_DMA_STATUS_INDEX = IO_DMA_BASE_INDEX + 4;
export const IO_DMA_WRITTEN_INDEX = IO_DMA_BASE_INDEX + 5;
export const IO_DMA_SIZE = 6;

export const IO_IMG_BASE_INDEX = IO_DMA_BASE_INDEX + IO_DMA_SIZE;
export const IO_IMG_SRC_INDEX = IO_IMG_BASE_INDEX;
export const IO_IMG_LEN_INDEX = IO_IMG_BASE_INDEX + 1;
export const IO_IMG_DST_INDEX = IO_IMG_BASE_INDEX + 2;
export const IO_IMG_CAP_INDEX = IO_IMG_BASE_INDEX + 3;
export const IO_IMG_CTRL_INDEX = IO_IMG_BASE_INDEX + 4;
export const IO_IMG_STATUS_INDEX = IO_IMG_BASE_INDEX + 5;
export const IO_IMG_WRITTEN_INDEX = IO_IMG_BASE_INDEX + 6;
export const IO_IMG_SIZE = 7;

export const IO_VDP_STATUS_INDEX = IO_IMG_BASE_INDEX + IO_IMG_SIZE;
export const IO_VDP_FAULT_CODE_INDEX = IO_VDP_STATUS_INDEX + 1;
export const IO_VDP_FAULT_DETAIL_INDEX = IO_VDP_STATUS_INDEX + 2;
export const IO_VDP_FAULT_ACK_INDEX = IO_VDP_STATUS_INDEX + 3;
export const IO_VDP_STATUS_SIZE = 4;

export const IO_GEO_BASE_INDEX = IO_VDP_STATUS_INDEX + IO_VDP_STATUS_SIZE;
export const IO_GEO_SRC0_INDEX = IO_GEO_BASE_INDEX;
export const IO_GEO_SRC1_INDEX = IO_GEO_BASE_INDEX + 1;
export const IO_GEO_SRC2_INDEX = IO_GEO_BASE_INDEX + 2;
export const IO_GEO_DST0_INDEX = IO_GEO_BASE_INDEX + 3;
export const IO_GEO_DST1_INDEX = IO_GEO_BASE_INDEX + 4;
export const IO_GEO_COUNT_INDEX = IO_GEO_BASE_INDEX + 5;
export const IO_GEO_CMD_INDEX = IO_GEO_BASE_INDEX + 6;
export const IO_GEO_CTRL_INDEX = IO_GEO_BASE_INDEX + 7;
export const IO_GEO_STATUS_INDEX = IO_GEO_BASE_INDEX + 8;
export const IO_GEO_PARAM0_INDEX = IO_GEO_BASE_INDEX + 9;
export const IO_GEO_PARAM1_INDEX = IO_GEO_BASE_INDEX + 10;
export const IO_GEO_STRIDE0_INDEX = IO_GEO_BASE_INDEX + 11;
export const IO_GEO_STRIDE1_INDEX = IO_GEO_BASE_INDEX + 12;
export const IO_GEO_STRIDE2_INDEX = IO_GEO_BASE_INDEX + 13;
export const IO_GEO_PROCESSED_INDEX = IO_GEO_BASE_INDEX + 14;
export const IO_GEO_FAULT_INDEX = IO_GEO_BASE_INDEX + 15;
export const IO_GEO_SIZE = 16;

export const IO_INP_BASE_INDEX = IO_GEO_BASE_INDEX + IO_GEO_SIZE;
export const IO_INP_PLAYER_INDEX = IO_INP_BASE_INDEX;
export const IO_INP_ACTION_INDEX = IO_INP_BASE_INDEX + 1;
export const IO_INP_BIND_INDEX = IO_INP_BASE_INDEX + 2;
export const IO_INP_CTRL_INDEX = IO_INP_BASE_INDEX + 3;
export const IO_INP_QUERY_INDEX = IO_INP_BASE_INDEX + 4;
export const IO_INP_STATUS_INDEX = IO_INP_BASE_INDEX + 5;
export const IO_INP_VALUE_INDEX = IO_INP_BASE_INDEX + 6;
export const IO_INP_CONSUME_INDEX = IO_INP_BASE_INDEX + 7;
export const IO_INP_SIZE = 8;

export const IO_APU_BASE_INDEX = IO_INP_BASE_INDEX + IO_INP_SIZE;
export const IO_APU_SOURCE_ADDR_INDEX = IO_APU_BASE_INDEX;
export const IO_APU_SOURCE_BYTES_INDEX = IO_APU_BASE_INDEX + 1;
export const IO_APU_SOURCE_SAMPLE_RATE_HZ_INDEX = IO_APU_BASE_INDEX + 2;
export const IO_APU_SOURCE_CHANNELS_INDEX = IO_APU_BASE_INDEX + 3;
export const IO_APU_SOURCE_BITS_PER_SAMPLE_INDEX = IO_APU_BASE_INDEX + 4;
export const IO_APU_SOURCE_FRAME_COUNT_INDEX = IO_APU_BASE_INDEX + 5;
export const IO_APU_SOURCE_DATA_OFFSET_INDEX = IO_APU_BASE_INDEX + 6;
export const IO_APU_SOURCE_DATA_BYTES_INDEX = IO_APU_BASE_INDEX + 7;
export const IO_APU_SOURCE_LOOP_START_SAMPLE_INDEX = IO_APU_BASE_INDEX + 8;
export const IO_APU_SOURCE_LOOP_END_SAMPLE_INDEX = IO_APU_BASE_INDEX + 9;
export const IO_APU_SLOT_INDEX = IO_APU_BASE_INDEX + 10;
export const IO_APU_RATE_STEP_Q16_INDEX = IO_APU_BASE_INDEX + 11;
export const IO_APU_GAIN_Q12_INDEX = IO_APU_BASE_INDEX + 12;
export const IO_APU_START_SAMPLE_INDEX = IO_APU_BASE_INDEX + 13;
export const IO_APU_FILTER_KIND_INDEX = IO_APU_BASE_INDEX + 14;
export const IO_APU_FILTER_FREQ_HZ_INDEX = IO_APU_BASE_INDEX + 15;
export const IO_APU_FILTER_Q_MILLI_INDEX = IO_APU_BASE_INDEX + 16;
export const IO_APU_FILTER_GAIN_MILLIDB_INDEX = IO_APU_BASE_INDEX + 17;
export const IO_APU_FADE_SAMPLES_INDEX = IO_APU_BASE_INDEX + 18;
export const IO_APU_TARGET_GAIN_Q12_INDEX = IO_APU_BASE_INDEX + 19;
export const IO_APU_CMD_INDEX = IO_APU_BASE_INDEX + 20;
export const IO_APU_STATUS_INDEX = IO_APU_BASE_INDEX + 21;
export const IO_APU_EVENT_KIND_INDEX = IO_APU_BASE_INDEX + 22;
export const IO_APU_EVENT_SLOT_INDEX = IO_APU_BASE_INDEX + 23;
export const IO_APU_EVENT_SOURCE_ADDR_INDEX = IO_APU_BASE_INDEX + 24;
export const IO_APU_EVENT_SEQ_INDEX = IO_APU_BASE_INDEX + 25;
export const IO_APU_SELECTED_SOURCE_ADDR_INDEX = IO_APU_BASE_INDEX + 26;
export const IO_APU_ACTIVE_MASK_INDEX = IO_APU_BASE_INDEX + 27;
export const IO_APU_SELECTED_SLOT_REG0_INDEX = IO_APU_BASE_INDEX + 28;
export const IO_APU_SELECTED_SLOT_REG_COUNT = 20;
export const IO_APU_SIZE = 28 + IO_APU_SELECTED_SLOT_REG_COUNT;

export const IO_PAYLOAD_WRITE_PTR_INDEX = IO_APU_BASE_INDEX + IO_APU_SIZE;
export const IO_PAYLOAD_BUFFER_BASE_INDEX = IO_PAYLOAD_WRITE_PTR_INDEX + 1;
export const IO_PAYLOAD_CAPACITY = 16384;
export const IO_SYS_BUS_FAULT_CODE_INDEX = IO_PAYLOAD_BUFFER_BASE_INDEX + IO_PAYLOAD_CAPACITY;
export const IO_SYS_BUS_FAULT_ADDR_INDEX = IO_SYS_BUS_FAULT_CODE_INDEX + 1;
export const IO_SYS_BUS_FAULT_ACCESS_INDEX = IO_SYS_BUS_FAULT_CODE_INDEX + 2;
export const IO_SYS_BUS_FAULT_ACK_INDEX = IO_SYS_BUS_FAULT_CODE_INDEX + 3;
export const IO_APU_FAULT_CODE_INDEX = IO_SYS_BUS_FAULT_ACK_INDEX + 1;
export const IO_APU_FAULT_DETAIL_INDEX = IO_APU_FAULT_CODE_INDEX + 1;
export const IO_APU_FAULT_ACK_INDEX = IO_APU_FAULT_CODE_INDEX + 2;
export const IO_GEO_FAULT_ACK_INDEX = IO_APU_FAULT_ACK_INDEX + 1;
export const IO_SLOT_COUNT = IO_GEO_FAULT_ACK_INDEX + 1;

export const IO_ARG_STRIDE = IO_WORD_SIZE;
export const IO_PAYLOAD_WRITE_PTR_ADDR = IO_BASE + IO_PAYLOAD_WRITE_PTR_INDEX * IO_WORD_SIZE;
export const IO_PAYLOAD_BUFFER_BASE = IO_BASE + IO_PAYLOAD_BUFFER_BASE_INDEX * IO_WORD_SIZE;

export const IO_SYS_BASE = IO_BASE + IO_SYS_BASE_INDEX * IO_WORD_SIZE;
export const IO_SYS_BOOT_CART = IO_BASE + IO_SYS_BOOT_CART_INDEX * IO_WORD_SIZE;
export const IO_SYS_HOST_FAULT_FLAGS = IO_BASE + IO_SYS_HOST_FAULT_FLAGS_INDEX * IO_WORD_SIZE;
export const IO_SYS_HOST_FAULT_STAGE = IO_BASE + IO_SYS_HOST_FAULT_STAGE_INDEX * IO_WORD_SIZE;
export const IO_SYS_BUS_FAULT_CODE = IO_BASE + IO_SYS_BUS_FAULT_CODE_INDEX * IO_WORD_SIZE;
export const IO_SYS_BUS_FAULT_ADDR = IO_BASE + IO_SYS_BUS_FAULT_ADDR_INDEX * IO_WORD_SIZE;
export const IO_SYS_BUS_FAULT_ACCESS = IO_BASE + IO_SYS_BUS_FAULT_ACCESS_INDEX * IO_WORD_SIZE;
export const IO_SYS_BUS_FAULT_ACK = IO_BASE + IO_SYS_BUS_FAULT_ACK_INDEX * IO_WORD_SIZE;
export const IO_VDP_BASE = IO_BASE + IO_VDP_BASE_INDEX * IO_WORD_SIZE;
export const IO_VDP_DITHER = IO_BASE + IO_VDP_DITHER_INDEX * IO_WORD_SIZE;
export const IO_VDP_SLOT_PRIMARY_ATLAS = IO_BASE + IO_VDP_SLOT_PRIMARY_ATLAS_INDEX * IO_WORD_SIZE;
export const IO_VDP_SLOT_SECONDARY_ATLAS = IO_BASE + IO_VDP_SLOT_SECONDARY_ATLAS_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_SURFACE = IO_BASE + IO_VDP_RD_SURFACE_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_X = IO_BASE + IO_VDP_RD_X_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_Y = IO_BASE + IO_VDP_RD_Y_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_MODE = IO_BASE + IO_VDP_RD_MODE_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_STATUS = IO_BASE + IO_VDP_RD_STATUS_INDEX * IO_WORD_SIZE;
export const IO_VDP_RD_DATA = IO_BASE + IO_VDP_RD_DATA_INDEX * IO_WORD_SIZE;
export const IO_VDP_CMD = IO_BASE + IO_VDP_CMD_INDEX * IO_WORD_SIZE;
export const IO_VDP_CMD_ARG0 = IO_BASE + IO_VDP_CMD_ARG0_INDEX * IO_WORD_SIZE;
export const IO_VDP_REG0 = IO_VDP_CMD_ARG0;
export const IO_VDP_REG_SRC_SLOT = IO_VDP_REG0 + 0 * IO_WORD_SIZE;
export const IO_VDP_REG_SRC_UV = IO_VDP_REG0 + 1 * IO_WORD_SIZE;
export const IO_VDP_REG_SRC_WH = IO_VDP_REG0 + 2 * IO_WORD_SIZE;
export const IO_VDP_REG_DST_X = IO_VDP_REG0 + 3 * IO_WORD_SIZE;
export const IO_VDP_REG_DST_Y = IO_VDP_REG0 + 4 * IO_WORD_SIZE;
export const IO_VDP_REG_GEOM_X0 = IO_VDP_REG0 + 5 * IO_WORD_SIZE;
export const IO_VDP_REG_GEOM_Y0 = IO_VDP_REG0 + 6 * IO_WORD_SIZE;
export const IO_VDP_REG_GEOM_X1 = IO_VDP_REG0 + 7 * IO_WORD_SIZE;
export const IO_VDP_REG_GEOM_Y1 = IO_VDP_REG0 + 8 * IO_WORD_SIZE;
export const IO_VDP_REG_LINE_WIDTH = IO_VDP_REG0 + 9 * IO_WORD_SIZE;
export const IO_VDP_REG_DRAW_LAYER = IO_VDP_REG0 + 10 * IO_WORD_SIZE;
export const IO_VDP_REG_DRAW_PRIORITY = IO_VDP_REG0 + 11 * IO_WORD_SIZE;
export const IO_VDP_REG_DRAW_CTRL = IO_VDP_REG0 + 12 * IO_WORD_SIZE;
export const IO_VDP_REG_DRAW_SCALE_X = IO_VDP_REG0 + 13 * IO_WORD_SIZE;
export const IO_VDP_REG_DRAW_SCALE_Y = IO_VDP_REG0 + 14 * IO_WORD_SIZE;
export const IO_VDP_REG_DRAW_COLOR = IO_VDP_REG0 + 15 * IO_WORD_SIZE;
export const IO_VDP_REG_BG_COLOR = IO_VDP_REG0 + 16 * IO_WORD_SIZE;
export const IO_VDP_REG_SLOT_INDEX = IO_VDP_REG0 + 17 * IO_WORD_SIZE;
export const IO_VDP_REG_SLOT_DIM = IO_VDP_REG0 + 18 * IO_WORD_SIZE;
export const IO_VDP_FIFO = IO_BASE + IO_VDP_FIFO_INDEX * IO_WORD_SIZE;
export const IO_VDP_FIFO_CTRL = IO_BASE + IO_VDP_FIFO_CTRL_INDEX * IO_WORD_SIZE;
export const IO_VDP_PMU_BANK = IO_BASE + IO_VDP_PMU_BANK_INDEX * IO_WORD_SIZE;
export const IO_VDP_PMU_X = IO_BASE + IO_VDP_PMU_X_INDEX * IO_WORD_SIZE;
export const IO_VDP_PMU_Y = IO_BASE + IO_VDP_PMU_Y_INDEX * IO_WORD_SIZE;
export const IO_VDP_PMU_SCALE_X = IO_BASE + IO_VDP_PMU_SCALE_X_INDEX * IO_WORD_SIZE;
export const IO_VDP_PMU_SCALE_Y = IO_BASE + IO_VDP_PMU_SCALE_Y_INDEX * IO_WORD_SIZE;
export const IO_VDP_PMU_CTRL = IO_BASE + IO_VDP_PMU_CTRL_INDEX * IO_WORD_SIZE;
export const IO_VDP_SBX_CONTROL = IO_BASE + IO_VDP_SBX_CONTROL_INDEX * IO_WORD_SIZE;
export const IO_VDP_SBX_FACE0 = IO_BASE + IO_VDP_SBX_FACE0_INDEX * IO_WORD_SIZE;
export const IO_VDP_SBX_COMMIT = IO_BASE + IO_VDP_SBX_COMMIT_INDEX * IO_WORD_SIZE;

export const IO_IRQ_BASE = IO_BASE + IO_IRQ_BASE_INDEX * IO_WORD_SIZE;
export const IO_IRQ_FLAGS = IO_BASE + IO_IRQ_FLAGS_INDEX * IO_WORD_SIZE;
export const IO_IRQ_ACK = IO_BASE + IO_IRQ_ACK_INDEX * IO_WORD_SIZE;

export const IO_DMA_BASE = IO_BASE + IO_DMA_BASE_INDEX * IO_WORD_SIZE;
export const IO_DMA_SRC = IO_BASE + IO_DMA_SRC_INDEX * IO_WORD_SIZE;
export const IO_DMA_DST = IO_BASE + IO_DMA_DST_INDEX * IO_WORD_SIZE;
export const IO_DMA_LEN = IO_BASE + IO_DMA_LEN_INDEX * IO_WORD_SIZE;
export const IO_DMA_CTRL = IO_BASE + IO_DMA_CTRL_INDEX * IO_WORD_SIZE;
export const IO_DMA_STATUS = IO_BASE + IO_DMA_STATUS_INDEX * IO_WORD_SIZE;
export const IO_DMA_WRITTEN = IO_BASE + IO_DMA_WRITTEN_INDEX * IO_WORD_SIZE;

export const IO_IMG_BASE = IO_BASE + IO_IMG_BASE_INDEX * IO_WORD_SIZE;
export const IO_IMG_SRC = IO_BASE + IO_IMG_SRC_INDEX * IO_WORD_SIZE;
export const IO_IMG_LEN = IO_BASE + IO_IMG_LEN_INDEX * IO_WORD_SIZE;
export const IO_IMG_DST = IO_BASE + IO_IMG_DST_INDEX * IO_WORD_SIZE;
export const IO_IMG_CAP = IO_BASE + IO_IMG_CAP_INDEX * IO_WORD_SIZE;
export const IO_IMG_CTRL = IO_BASE + IO_IMG_CTRL_INDEX * IO_WORD_SIZE;
export const IO_IMG_STATUS = IO_BASE + IO_IMG_STATUS_INDEX * IO_WORD_SIZE;
export const IO_IMG_WRITTEN = IO_BASE + IO_IMG_WRITTEN_INDEX * IO_WORD_SIZE;
export const IO_VDP_STATUS = IO_BASE + IO_VDP_STATUS_INDEX * IO_WORD_SIZE;
export const IO_VDP_FAULT_CODE = IO_BASE + IO_VDP_FAULT_CODE_INDEX * IO_WORD_SIZE;
export const IO_VDP_FAULT_DETAIL = IO_BASE + IO_VDP_FAULT_DETAIL_INDEX * IO_WORD_SIZE;
export const IO_VDP_FAULT_ACK = IO_BASE + IO_VDP_FAULT_ACK_INDEX * IO_WORD_SIZE;
export const IO_GEO_BASE = IO_BASE + IO_GEO_BASE_INDEX * IO_WORD_SIZE;
export const IO_GEO_SRC0 = IO_BASE + IO_GEO_SRC0_INDEX * IO_WORD_SIZE;
export const IO_GEO_SRC1 = IO_BASE + IO_GEO_SRC1_INDEX * IO_WORD_SIZE;
export const IO_GEO_SRC2 = IO_BASE + IO_GEO_SRC2_INDEX * IO_WORD_SIZE;
export const IO_GEO_DST0 = IO_BASE + IO_GEO_DST0_INDEX * IO_WORD_SIZE;
export const IO_GEO_DST1 = IO_BASE + IO_GEO_DST1_INDEX * IO_WORD_SIZE;
export const IO_GEO_COUNT = IO_BASE + IO_GEO_COUNT_INDEX * IO_WORD_SIZE;
export const IO_GEO_CMD = IO_BASE + IO_GEO_CMD_INDEX * IO_WORD_SIZE;
export const IO_GEO_CTRL = IO_BASE + IO_GEO_CTRL_INDEX * IO_WORD_SIZE;
export const IO_GEO_STATUS = IO_BASE + IO_GEO_STATUS_INDEX * IO_WORD_SIZE;
export const IO_GEO_PARAM0 = IO_BASE + IO_GEO_PARAM0_INDEX * IO_WORD_SIZE;
export const IO_GEO_PARAM1 = IO_BASE + IO_GEO_PARAM1_INDEX * IO_WORD_SIZE;
export const IO_GEO_STRIDE0 = IO_BASE + IO_GEO_STRIDE0_INDEX * IO_WORD_SIZE;
export const IO_GEO_STRIDE1 = IO_BASE + IO_GEO_STRIDE1_INDEX * IO_WORD_SIZE;
export const IO_GEO_STRIDE2 = IO_BASE + IO_GEO_STRIDE2_INDEX * IO_WORD_SIZE;
export const IO_GEO_PROCESSED = IO_BASE + IO_GEO_PROCESSED_INDEX * IO_WORD_SIZE;
export const IO_GEO_FAULT = IO_BASE + IO_GEO_FAULT_INDEX * IO_WORD_SIZE;
export const IO_GEO_REGISTER_ADDRS = [
	IO_GEO_SRC0,
	IO_GEO_SRC1,
	IO_GEO_SRC2,
	IO_GEO_DST0,
	IO_GEO_DST1,
	IO_GEO_COUNT,
	IO_GEO_CMD,
	IO_GEO_CTRL,
	IO_GEO_STATUS,
	IO_GEO_PARAM0,
	IO_GEO_PARAM1,
	IO_GEO_STRIDE0,
	IO_GEO_STRIDE1,
	IO_GEO_STRIDE2,
	IO_GEO_PROCESSED,
	IO_GEO_FAULT,
] as const;
export const IO_GEO_FAULT_ACK = IO_BASE + IO_GEO_FAULT_ACK_INDEX * IO_WORD_SIZE;
export const IO_INP_BASE = IO_BASE + IO_INP_BASE_INDEX * IO_WORD_SIZE;
export const IO_INP_PLAYER = IO_BASE + IO_INP_PLAYER_INDEX * IO_WORD_SIZE;
export const IO_INP_ACTION = IO_BASE + IO_INP_ACTION_INDEX * IO_WORD_SIZE;
export const IO_INP_BIND = IO_BASE + IO_INP_BIND_INDEX * IO_WORD_SIZE;
export const IO_INP_CTRL = IO_BASE + IO_INP_CTRL_INDEX * IO_WORD_SIZE;
export const IO_INP_QUERY = IO_BASE + IO_INP_QUERY_INDEX * IO_WORD_SIZE;
export const IO_INP_STATUS = IO_BASE + IO_INP_STATUS_INDEX * IO_WORD_SIZE;
export const IO_INP_VALUE = IO_BASE + IO_INP_VALUE_INDEX * IO_WORD_SIZE;
export const IO_INP_CONSUME = IO_BASE + IO_INP_CONSUME_INDEX * IO_WORD_SIZE;
export const IO_APU_BASE = IO_BASE + IO_APU_BASE_INDEX * IO_WORD_SIZE;
export const IO_APU_SOURCE_ADDR = IO_BASE + IO_APU_SOURCE_ADDR_INDEX * IO_WORD_SIZE;
export const IO_APU_SOURCE_BYTES = IO_BASE + IO_APU_SOURCE_BYTES_INDEX * IO_WORD_SIZE;
export const IO_APU_SOURCE_SAMPLE_RATE_HZ = IO_BASE + IO_APU_SOURCE_SAMPLE_RATE_HZ_INDEX * IO_WORD_SIZE;
export const IO_APU_SOURCE_CHANNELS = IO_BASE + IO_APU_SOURCE_CHANNELS_INDEX * IO_WORD_SIZE;
export const IO_APU_SOURCE_BITS_PER_SAMPLE = IO_BASE + IO_APU_SOURCE_BITS_PER_SAMPLE_INDEX * IO_WORD_SIZE;
export const IO_APU_SOURCE_FRAME_COUNT = IO_BASE + IO_APU_SOURCE_FRAME_COUNT_INDEX * IO_WORD_SIZE;
export const IO_APU_SOURCE_DATA_OFFSET = IO_BASE + IO_APU_SOURCE_DATA_OFFSET_INDEX * IO_WORD_SIZE;
export const IO_APU_SOURCE_DATA_BYTES = IO_BASE + IO_APU_SOURCE_DATA_BYTES_INDEX * IO_WORD_SIZE;
export const IO_APU_SOURCE_LOOP_START_SAMPLE = IO_BASE + IO_APU_SOURCE_LOOP_START_SAMPLE_INDEX * IO_WORD_SIZE;
export const IO_APU_SOURCE_LOOP_END_SAMPLE = IO_BASE + IO_APU_SOURCE_LOOP_END_SAMPLE_INDEX * IO_WORD_SIZE;
export const IO_APU_SLOT = IO_BASE + IO_APU_SLOT_INDEX * IO_WORD_SIZE;
export const IO_APU_RATE_STEP_Q16 = IO_BASE + IO_APU_RATE_STEP_Q16_INDEX * IO_WORD_SIZE;
export const IO_APU_GAIN_Q12 = IO_BASE + IO_APU_GAIN_Q12_INDEX * IO_WORD_SIZE;
export const IO_APU_START_SAMPLE = IO_BASE + IO_APU_START_SAMPLE_INDEX * IO_WORD_SIZE;
export const IO_APU_FILTER_KIND = IO_BASE + IO_APU_FILTER_KIND_INDEX * IO_WORD_SIZE;
export const IO_APU_FILTER_FREQ_HZ = IO_BASE + IO_APU_FILTER_FREQ_HZ_INDEX * IO_WORD_SIZE;
export const IO_APU_FILTER_Q_MILLI = IO_BASE + IO_APU_FILTER_Q_MILLI_INDEX * IO_WORD_SIZE;
export const IO_APU_FILTER_GAIN_MILLIDB = IO_BASE + IO_APU_FILTER_GAIN_MILLIDB_INDEX * IO_WORD_SIZE;
export const IO_APU_FADE_SAMPLES = IO_BASE + IO_APU_FADE_SAMPLES_INDEX * IO_WORD_SIZE;
export const IO_APU_TARGET_GAIN_Q12 = IO_BASE + IO_APU_TARGET_GAIN_Q12_INDEX * IO_WORD_SIZE;
export const IO_APU_PARAMETER_REGISTER_ADDRS = [
	IO_APU_SOURCE_ADDR,
	IO_APU_SOURCE_BYTES,
	IO_APU_SOURCE_SAMPLE_RATE_HZ,
	IO_APU_SOURCE_CHANNELS,
	IO_APU_SOURCE_BITS_PER_SAMPLE,
	IO_APU_SOURCE_FRAME_COUNT,
	IO_APU_SOURCE_DATA_OFFSET,
	IO_APU_SOURCE_DATA_BYTES,
	IO_APU_SOURCE_LOOP_START_SAMPLE,
	IO_APU_SOURCE_LOOP_END_SAMPLE,
	IO_APU_SLOT,
	IO_APU_RATE_STEP_Q16,
	IO_APU_GAIN_Q12,
	IO_APU_START_SAMPLE,
	IO_APU_FILTER_KIND,
	IO_APU_FILTER_FREQ_HZ,
	IO_APU_FILTER_Q_MILLI,
	IO_APU_FILTER_GAIN_MILLIDB,
	IO_APU_FADE_SAMPLES,
	IO_APU_TARGET_GAIN_Q12,
] as const;
export const IO_APU_CMD = IO_BASE + IO_APU_CMD_INDEX * IO_WORD_SIZE;
export const IO_APU_STATUS = IO_BASE + IO_APU_STATUS_INDEX * IO_WORD_SIZE;
export const IO_APU_FAULT_CODE = IO_BASE + IO_APU_FAULT_CODE_INDEX * IO_WORD_SIZE;
export const IO_APU_FAULT_DETAIL = IO_BASE + IO_APU_FAULT_DETAIL_INDEX * IO_WORD_SIZE;
export const IO_APU_FAULT_ACK = IO_BASE + IO_APU_FAULT_ACK_INDEX * IO_WORD_SIZE;
export const IO_APU_EVENT_KIND = IO_BASE + IO_APU_EVENT_KIND_INDEX * IO_WORD_SIZE;
export const IO_APU_EVENT_SLOT = IO_BASE + IO_APU_EVENT_SLOT_INDEX * IO_WORD_SIZE;
export const IO_APU_EVENT_SOURCE_ADDR = IO_BASE + IO_APU_EVENT_SOURCE_ADDR_INDEX * IO_WORD_SIZE;
export const IO_APU_EVENT_SEQ = IO_BASE + IO_APU_EVENT_SEQ_INDEX * IO_WORD_SIZE;
export const IO_APU_SELECTED_SOURCE_ADDR = IO_BASE + IO_APU_SELECTED_SOURCE_ADDR_INDEX * IO_WORD_SIZE;
export const IO_APU_ACTIVE_MASK = IO_BASE + IO_APU_ACTIVE_MASK_INDEX * IO_WORD_SIZE;
export const IO_APU_SELECTED_SLOT_REG0 = IO_BASE + IO_APU_SELECTED_SLOT_REG0_INDEX * IO_WORD_SIZE;

export const IRQ_DMA_DONE = 1 << 0;
export const IRQ_DMA_ERROR = 1 << 1;
export const IRQ_IMG_DONE = 1 << 2;
export const IRQ_IMG_ERROR = 1 << 3;
export const IRQ_VBLANK = 1 << 4;
export const IRQ_REINIT = 1 << 5;
export const IRQ_NEWGAME = 1 << 6;
export const IRQ_GEO_DONE = 1 << 7;
export const IRQ_GEO_ERROR = 1 << 8;
export const IRQ_APU = 1 << 9;

export const DMA_CTRL_START = 1 << 0;
export const DMA_CTRL_STRICT = 1 << 1;
export const DMA_STATUS_BUSY = 1 << 0;
export const DMA_STATUS_DONE = 1 << 1;
export const DMA_STATUS_ERROR = 1 << 2;
export const DMA_STATUS_CLIPPED = 1 << 3;
export const DMA_STATUS_REJECTED = 1 << 4;

export const IMG_CTRL_START = 1 << 0;
export const IMG_STATUS_BUSY = 1 << 0;
export const IMG_STATUS_DONE = 1 << 1;
export const IMG_STATUS_ERROR = 1 << 2;
export const IMG_STATUS_CLIPPED = 1 << 3;
export const IMG_STATUS_REJECTED = 1 << 4;

export const HOST_FAULT_FLAG_ACTIVE = 1 << 0;
export const HOST_FAULT_FLAG_STARTUP_BLOCKING = 1 << 1;
export const HOST_FAULT_STAGE_NONE = 0;
export const HOST_FAULT_STAGE_STARTUP_AUDIO_REFRESH = 1;

export const BUS_FAULT_NONE = 0;
export const BUS_FAULT_UNMAPPED = 1;
export const BUS_FAULT_UNALIGNED_IO = 2;
export const BUS_FAULT_READ_ONLY = 3;
export const BUS_FAULT_VRAM_RANGE = 4;
export const BUS_FAULT_ACCESS_READ = 1 << 0;
export const BUS_FAULT_ACCESS_WRITE = 1 << 1;
export const BUS_FAULT_ACCESS_U8 = 1 << 8;
export const BUS_FAULT_ACCESS_U16 = 1 << 9;
export const BUS_FAULT_ACCESS_U32 = 1 << 10;
export const BUS_FAULT_ACCESS_WORD = 1 << 11;
export const BUS_FAULT_ACCESS_F32 = 1 << 12;
export const BUS_FAULT_ACCESS_F64 = 1 << 13;

export const INP_CTRL_COMMIT = 1;
export const INP_CTRL_ARM = 2;
export const INP_CTRL_RESET = 3;

export const VDP_SLOT_PRIMARY = 0;
export const VDP_SLOT_SECONDARY = 1;
export const VDP_SLOT_SYSTEM = 2;
export const VDP_SLOT_NONE = 0xffffffff >>> 0;
export const VDP_SLOT_ATLAS_NONE = 0xffffffff >>> 0;
export const VDP_SYSTEM_ATLAS_ID = 254;
export const VDP_RD_MODE_RGBA8888 = 0;
export const VDP_RD_STATUS_READY = 1 << 0;
export const VDP_RD_STATUS_OVERFLOW = 1 << 1;
export const VDP_FIFO_CTRL_SEAL = 1 << 0;
export const VDP_STATUS_VBLANK = 1 << 0;
export const VDP_STATUS_SUBMIT_BUSY = 1 << 1;
// Sticky latch: set when a VDP submit attempt is rejected because the submit path is busy,
// and cleared only when a later VDP submit attempt is accepted.
export const VDP_STATUS_SUBMIT_REJECTED = 1 << 2;
export const VDP_STATUS_FAULT = 1 << 3;
export const VDP_SBX_COMMIT_WRITE = 1;

export const VDP_FAULT_NONE = 0;
export const VDP_FAULT_RD_UNSUPPORTED_MODE = 0x0001;
export const VDP_FAULT_RD_SURFACE = 0x0002;
export const VDP_FAULT_RD_OOB = 0x0003;
export const VDP_FAULT_VRAM_WRITE_UNMAPPED = 0x0101;
export const VDP_FAULT_VRAM_WRITE_UNINITIALIZED = 0x0102;
export const VDP_FAULT_VRAM_WRITE_OOB = 0x0103;
export const VDP_FAULT_VRAM_WRITE_UNALIGNED = 0x0104;
export const VDP_FAULT_VRAM_SLOT_DIM = 0x0105;
export const VDP_FAULT_STREAM_BAD_PACKET = 0x0201;
export const VDP_FAULT_SUBMIT_STATE = 0x0202;
export const VDP_FAULT_CMD_BAD_DOORBELL = 0x0203;
export const VDP_FAULT_SUBMIT_BUSY = 0x0204;
export const VDP_FAULT_DEX_INVALID_SCALE = 0x0301;
export const VDP_FAULT_DEX_INVALID_LINE_WIDTH = 0x0302;
export const VDP_FAULT_DEX_SOURCE_SLOT = 0x0303;
export const VDP_FAULT_DEX_SOURCE_OOB = 0x0304;
export const VDP_FAULT_DEX_OVERFLOW = 0x0305;
export const VDP_FAULT_DEX_UNSUPPORTED_DRAW_CTRL = 0x0306;
export const VDP_FAULT_SBX_SOURCE_OOB = 0x0401;
export const VDP_FAULT_BBU_ZERO_SIZE = 0x0501;
export const VDP_FAULT_BBU_OVERFLOW = 0x0502;
export const VDP_FAULT_BBU_SOURCE_OOB = 0x0503;
