import { PNG } from 'pngjs';

import {
	BIOS_ATLAS_ID,
	generateAtlasAssetId,
	type ImgMeta,
	type RomAsset,
} from '../../src/bmsx/rompack/format';
import { SYSTEM_ROM_NAME } from '../../src/bmsx/core/system';
import {
	commonResPath,
	createAtlasses,
	generateRomAssets,
	getResMetaList,
	getResourcesList,
	setAtlasFlag,
} from './rombuilder';

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

type HostAtlasImage = {
	id: string;
	width: number;
	height: number;
	u: number;
	v: number;
	w: number;
	h: number;
};

type HostAtlasBuild = {
	width: number;
	height: number;
	rgbaBase64: string;
	images: HostAtlasImage[];
};

export const HOST_SYSTEM_ATLAS_TS_PATH = join(process.cwd(), 'src', 'bmsx', 'rompack', 'host_system_atlas.generated.ts');
export const HOST_SYSTEM_ATLAS_CPP_HEADER_PATH = join(process.cwd(), 'src', 'bmsx_cpp', 'rompack', 'host_system_atlas.generated.h');
export const HOST_SYSTEM_ATLAS_CPP_SOURCE_PATH = join(process.cwd(), 'src', 'bmsx_cpp', 'rompack', 'host_system_atlas.generated.cpp');

const GENERATED_FILE_HEADER = [
	'// Generated by scripts/rompacker/host_system_atlas.ts.',
	'// Do not edit by hand.',
	'',
].join('\n');

function getUvExtents(texcoords: readonly number[]): { minU: number; minV: number } {
	let minU = texcoords[0];
	let minV = texcoords[1];
	for (let index = 2; index < 12; index += 2) {
		const u = texcoords[index];
		const v = texcoords[index + 1];
		if (u < minU) minU = u;
		if (v < minV) minV = v;
	}
	return { minU, minV };
}

function requirePositiveDimension(value: number, label: string): number {
	if (!Number.isSafeInteger(value) || value <= 0) {
		throw new Error(`[HostSystemAtlas] ${label} must be a positive integer.`);
	}
	return value;
}

function resolveImageRecord(asset: RomAsset, atlasWidth: number, atlasHeight: number): HostAtlasImage | null {
	if (asset.type !== 'image') {
		return null;
	}
	const meta = asset.imgmeta;
	if (!meta || meta.atlasid !== BIOS_ATLAS_ID) {
		return null;
	}
	if (!meta.texcoords || meta.texcoords.length < 12) {
		throw new Error(`[HostSystemAtlas] Image '${asset.resid}' is missing system-atlas texture coordinates.`);
	}
	const { minU, minV } = getUvExtents(meta.texcoords);
	const width = requirePositiveDimension(meta.width, `${asset.resid}.width`);
	const height = requirePositiveDimension(meta.height, `${asset.resid}.height`);
	return {
		id: asset.resid,
		width,
		height,
		u: Math.round(minU * atlasWidth),
		v: Math.round(minV * atlasHeight),
		w: width,
		h: height,
	};
}

function findAtlasAsset(assets: readonly RomAsset[], atlasAssetId: string): RomAsset {
	const atlasAsset = assets.find(asset => asset.resid === atlasAssetId && asset.type === 'atlas');
	if (!atlasAsset || !atlasAsset.imgmeta || !atlasAsset.buffer || atlasAsset.buffer.length === 0) {
		throw new Error(`[HostSystemAtlas] Atlas '${atlasAssetId}' was not generated.`);
	}
	return atlasAsset;
}

function buildHostAtlasFromAssets(assets: readonly RomAsset[]): HostAtlasBuild {
	const atlasAssetId = generateAtlasAssetId(BIOS_ATLAS_ID);
	const atlasAsset = findAtlasAsset(assets, atlasAssetId);
	const atlasMeta = atlasAsset.imgmeta as ImgMeta;
	const atlasWidth = requirePositiveDimension(atlasMeta.width, `${atlasAssetId}.width`);
	const atlasHeight = requirePositiveDimension(atlasMeta.height, `${atlasAssetId}.height`);
	const atlasPng = PNG.sync.read(Buffer.from(atlasAsset.buffer!));
	if (atlasPng.width !== atlasWidth || atlasPng.height !== atlasHeight) {
		throw new Error(`[HostSystemAtlas] Atlas '${atlasAssetId}' PNG dimensions do not match metadata.`);
	}
	const images = assets
		.map(asset => resolveImageRecord(asset, atlasWidth, atlasHeight))
		.filter((image): image is HostAtlasImage => image !== null)
		.sort((a, b) => a.id.localeCompare(b.id));
	if (images.length === 0) {
		throw new Error('[HostSystemAtlas] No system-atlas images were generated.');
	}
	return {
		width: atlasWidth,
		height: atlasHeight,
		rgbaBase64: Buffer.from(atlasPng.data).toString('base64'),
		images,
	};
}

function splitBase64Literal(value: string, indent: string): string {
	const chunks: string[] = [];
	for (let index = 0; index < value.length; index += 120) {
		chunks.push(`${indent}"${value.slice(index, index + 120)}"`);
	}
	return chunks.join('\n');
}

function renderTypeScriptArtifact(build: HostAtlasBuild): string {
	const imageEntries = build.images.map(image => (
		`\t\t${JSON.stringify(image.id)}: { width: ${image.width}, height: ${image.height}, u: ${image.u}, v: ${image.v}, w: ${image.w}, h: ${image.h} },`
	));
	return GENERATED_FILE_HEADER + [
		'export const HOST_SYSTEM_ATLAS_ARTIFACT = {',
		`\twidth: ${build.width},`,
		`\theight: ${build.height},`,
		`\trgbaBase64: ${JSON.stringify(build.rgbaBase64)},`,
		'\timages: {',
		...imageEntries,
		'\t},',
		'} as const;',
		'',
	].join('\n');
}

function renderCppHeader(): string {
	return GENERATED_FILE_HEADER + [
		'#pragma once',
		'',
		'#include <cstddef>',
		'#include <cstdint>',
		'#include <string_view>',
		'',
		'namespace bmsx {',
		'',
		'struct HostSystemAtlasGeneratedImage {',
		'\tstd::string_view id;',
		'\tstd::int32_t width = 0;',
		'\tstd::int32_t height = 0;',
		'\tstd::uint32_t u = 0;',
		'\tstd::uint32_t v = 0;',
		'\tstd::uint32_t w = 0;',
		'\tstd::uint32_t h = 0;',
		'};',
		'',
		'std::int32_t generatedHostSystemAtlasWidth();',
		'std::int32_t generatedHostSystemAtlasHeight();',
		'std::string_view generatedHostSystemAtlasRgbaBase64();',
		'const HostSystemAtlasGeneratedImage* generatedHostSystemAtlasImages();',
		'std::size_t generatedHostSystemAtlasImageCount();',
		'',
		'} // namespace bmsx',
		'',
	].join('\n');
}

function renderCppSource(build: HostAtlasBuild): string {
	const imageEntries = build.images.map(image => (
		`\tHostSystemAtlasGeneratedImage{std::string_view("${image.id}", ${image.id.length}), ${image.width}, ${image.height}, ${image.u}u, ${image.v}u, ${image.w}u, ${image.h}u},`
	));
	return GENERATED_FILE_HEADER + [
		'#include "rompack/host_system_atlas.generated.h"',
		'',
		'namespace bmsx {',
		'namespace {',
		'',
		`constexpr std::int32_t HOST_SYSTEM_ATLAS_WIDTH = ${build.width};`,
		`constexpr std::int32_t HOST_SYSTEM_ATLAS_HEIGHT = ${build.height};`,
		'constexpr char HOST_SYSTEM_ATLAS_RGBA_BASE64[] =',
		splitBase64Literal(build.rgbaBase64, '\t'),
		';',
		'constexpr HostSystemAtlasGeneratedImage HOST_SYSTEM_ATLAS_IMAGES[] = {',
		...imageEntries,
		'};',
		'',
		'} // namespace',
		'',
		'std::int32_t generatedHostSystemAtlasWidth() { return HOST_SYSTEM_ATLAS_WIDTH; }',
		'std::int32_t generatedHostSystemAtlasHeight() { return HOST_SYSTEM_ATLAS_HEIGHT; }',
		'std::string_view generatedHostSystemAtlasRgbaBase64() {',
		'\treturn std::string_view(HOST_SYSTEM_ATLAS_RGBA_BASE64, sizeof(HOST_SYSTEM_ATLAS_RGBA_BASE64) - 1u);',
		'}',
		'const HostSystemAtlasGeneratedImage* generatedHostSystemAtlasImages() { return HOST_SYSTEM_ATLAS_IMAGES; }',
		'std::size_t generatedHostSystemAtlasImageCount() {',
		'\treturn sizeof(HOST_SYSTEM_ATLAS_IMAGES) / sizeof(HOST_SYSTEM_ATLAS_IMAGES[0]);',
		'}',
		'',
		'} // namespace bmsx',
		'',
	].join('\n');
}

async function writeIfChanged(path: string, contents: string): Promise<boolean> {
	let current = '';
	try {
		current = await readFile(path, 'utf8');
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
			throw error;
		}
	}
	if (current === contents) {
		return false;
	}
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, contents, 'utf8');
	return true;
}

async function writeHostSystemAtlasArtifacts(build: HostAtlasBuild): Promise<boolean> {
	const writes = await Promise.all([
		writeIfChanged(HOST_SYSTEM_ATLAS_TS_PATH, renderTypeScriptArtifact(build)),
		writeIfChanged(HOST_SYSTEM_ATLAS_CPP_HEADER_PATH, renderCppHeader()),
		writeIfChanged(HOST_SYSTEM_ATLAS_CPP_SOURCE_PATH, renderCppSource(build)),
	]);
	return writes.some(Boolean);
}

export async function generateHostSystemAtlasArtifactsFromAssets(assets: readonly RomAsset[]): Promise<boolean> {
	return writeHostSystemAtlasArtifacts(buildHostAtlasFromAssets(assets));
}

export async function ensureHostSystemAtlasArtifacts(): Promise<boolean> {
	setAtlasFlag(true);
	const biosProjectRoot = join(commonResPath, '..');
	const biosVirtualRoot = biosProjectRoot.replace(/^\.\//, '');
	const resMeta = await getResMetaList([commonResPath], SYSTEM_ROM_NAME, {
		extraLuaPaths: [],
		virtualRoot: biosVirtualRoot,
		resolveAtlasId: true,
	});
	const resources = await getResourcesList(resMeta);
	await createAtlasses(resources);
	const assets = await generateRomAssets(resources);
	return generateHostSystemAtlasArtifactsFromAssets(assets);
}
