import { SYSTEM_ROM_NAME } from '../../machine/ts/core/system';
import {
	commonResPath,
	createTextureAtlases,
	getResMetaList,
	getResourcesList,
} from './rombuilder';
import type { Resource, TextureAtlasResource } from './rompacker.rompack';
import { GX_SYSTEM_TEXTURE_GROUP_ID } from './texture_atlas_contract';

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

type HostAtlasImage = {
	id: string;
	width: number;
	height: number;
	u: number;
	v: number;
	w: number;
	h: number;
};

type HostAtlasBuild = {
	width: number;
	height: number;
	rgbaBase64: string;
	images: HostAtlasImage[];
};

export const HOST_SYSTEM_ATLAS_TS_PATH = join(process.cwd(), 'machine', 'ts', 'rompack', 'host_system_atlas.generated.ts');
export const HOST_SYSTEM_ATLAS_CPP_HEADER_PATH = join(process.cwd(), 'machine', 'cpp', 'rompack', 'host_system_atlas.generated.h');
export const HOST_SYSTEM_ATLAS_CPP_SOURCE_PATH = join(process.cwd(), 'machine', 'cpp', 'rompack', 'host_system_atlas.generated.cpp');

const GENERATED_FILE_HEADER = [
	'// Generated by scripts/rompacker/host_system_atlas.ts.',
	'// Do not edit by hand.',
	'',
].join('\n');

function buildHostAtlasFromResources(resources: readonly Resource[]): HostAtlasBuild {
	const atlas = resources.find((resource): resource is TextureAtlasResource => (
		resource.type === 'atlas' && resource.atlasId === GX_SYSTEM_TEXTURE_GROUP_ID
	))!;
	const rgba = atlas.img!.getContext('2d').getImageData(0, 0, atlas.img!.width, atlas.img!.height).data;
	const images: HostAtlasImage[] = [];
	for (let index = 0; index < resources.length; index += 1) {
		const resource = resources[index];
		if (resource.type === 'image' && resource.targetAtlasId === GX_SYSTEM_TEXTURE_GROUP_ID) {
			images.push({
				id: resource.name,
				width: resource.img!.width,
				height: resource.img!.height,
				u: resource.textureU!,
				v: resource.textureV!,
				w: resource.img!.width,
				h: resource.img!.height,
			});
		}
	}
	images.sort((a, b) => a.id.localeCompare(b.id));
	if (images.length === 0) {
		throw new Error('[HostSystemAtlas] No system-atlas images were generated.');
	}
	return {
		width: atlas.img!.width,
		height: atlas.img!.height,
		rgbaBase64: Buffer.from(rgba.buffer, rgba.byteOffset, rgba.byteLength).toString('base64'),
		images,
	};
}

function splitBase64Literal(value: string, indent: string): string {
	const chunks: string[] = [];
	for (let index = 0; index < value.length; index += 120) {
		chunks.push(`${indent}"${value.slice(index, index + 120)}"`);
	}
	return chunks.join('\n');
}

function renderTypeScriptArtifact(build: HostAtlasBuild): string {
	const imageEntries = build.images.map(image => (
		`\t\t${JSON.stringify(image.id)}: { width: ${image.width}, height: ${image.height}, u: ${image.u}, v: ${image.v}, w: ${image.w}, h: ${image.h} },`
	));
	return GENERATED_FILE_HEADER + [
		'export const HOST_SYSTEM_ATLAS_ARTIFACT = {',
		`\twidth: ${build.width},`,
		`\theight: ${build.height},`,
		`\trgbaBase64: ${JSON.stringify(build.rgbaBase64)},`,
		'\timages: {',
		...imageEntries,
		'\t},',
		'} as const;',
		'',
	].join('\n');
}

function renderCppHeader(): string {
	return GENERATED_FILE_HEADER + [
		'#pragma once',
		'',
		'#include <cstddef>',
		'#include <cstdint>',
		'#include <string_view>',
		'',
		'namespace bmsx {',
		'',
		'struct HostSystemAtlasGeneratedImage {',
		'\tstd::string_view id;',
		'\tstd::int32_t width = 0;',
		'\tstd::int32_t height = 0;',
		'\tstd::uint32_t u = 0;',
		'\tstd::uint32_t v = 0;',
		'\tstd::uint32_t w = 0;',
		'\tstd::uint32_t h = 0;',
		'};',
		'',
		'std::int32_t generatedHostSystemAtlasWidth();',
		'std::int32_t generatedHostSystemAtlasHeight();',
		'std::string_view generatedHostSystemAtlasRgbaBase64();',
		'const HostSystemAtlasGeneratedImage* generatedHostSystemAtlasImages();',
		'std::size_t generatedHostSystemAtlasImageCount();',
		'',
		'} // namespace bmsx',
		'',
	].join('\n');
}

function renderCppSource(build: HostAtlasBuild): string {
	const imageEntries = build.images.map(image => (
		`\tHostSystemAtlasGeneratedImage{std::string_view("${image.id}", ${image.id.length}), ${image.width}, ${image.height}, ${image.u}u, ${image.v}u, ${image.w}u, ${image.h}u},`
	));
	return GENERATED_FILE_HEADER + [
		'#include "rompack/host_system_atlas.generated.h"',
		'',
		'namespace bmsx {',
		'namespace {',
		'',
		`constexpr std::int32_t HOST_SYSTEM_ATLAS_WIDTH = ${build.width};`,
		`constexpr std::int32_t HOST_SYSTEM_ATLAS_HEIGHT = ${build.height};`,
		'constexpr char HOST_SYSTEM_ATLAS_RGBA_BASE64[] =',
		splitBase64Literal(build.rgbaBase64, '\t'),
		';',
		'constexpr HostSystemAtlasGeneratedImage HOST_SYSTEM_ATLAS_IMAGES[] = {',
		...imageEntries,
		'};',
		'',
		'} // namespace',
		'',
		'std::int32_t generatedHostSystemAtlasWidth() { return HOST_SYSTEM_ATLAS_WIDTH; }',
		'std::int32_t generatedHostSystemAtlasHeight() { return HOST_SYSTEM_ATLAS_HEIGHT; }',
		'std::string_view generatedHostSystemAtlasRgbaBase64() {',
		'\treturn std::string_view(HOST_SYSTEM_ATLAS_RGBA_BASE64, sizeof(HOST_SYSTEM_ATLAS_RGBA_BASE64) - 1u);',
		'}',
		'const HostSystemAtlasGeneratedImage* generatedHostSystemAtlasImages() { return HOST_SYSTEM_ATLAS_IMAGES; }',
		'std::size_t generatedHostSystemAtlasImageCount() {',
		'\treturn sizeof(HOST_SYSTEM_ATLAS_IMAGES) / sizeof(HOST_SYSTEM_ATLAS_IMAGES[0]);',
		'}',
		'',
		'} // namespace bmsx',
		'',
	].join('\n');
}

async function writeIfChanged(path: string, contents: string): Promise<boolean> {
	let current = '';
	try {
		current = await readFile(path, 'utf8');
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
			throw error;
		}
	}
	if (current === contents) {
		return false;
	}
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, contents, 'utf8');
	return true;
}

async function writeHostSystemAtlasArtifacts(build: HostAtlasBuild): Promise<boolean> {
	const writes = await Promise.all([
		writeIfChanged(HOST_SYSTEM_ATLAS_TS_PATH, renderTypeScriptArtifact(build)),
		writeIfChanged(HOST_SYSTEM_ATLAS_CPP_HEADER_PATH, renderCppHeader()),
		writeIfChanged(HOST_SYSTEM_ATLAS_CPP_SOURCE_PATH, renderCppSource(build)),
	]);
	return writes.some(Boolean);
}

export async function generateHostSystemAtlasArtifactsFromResources(resources: readonly Resource[]): Promise<boolean> {
	return writeHostSystemAtlasArtifacts(buildHostAtlasFromResources(resources));
}

export async function ensureHostSystemAtlasArtifacts(): Promise<boolean> {
	const biosProjectRoot = join(commonResPath, '..');
	const biosVirtualRoot = biosProjectRoot.replace(/^\.\//, '');
	const resMeta = await getResMetaList([commonResPath], SYSTEM_ROM_NAME, {
		extraLuaPaths: [],
		virtualRoot: biosVirtualRoot,
	});
	const resources = await getResourcesList(resMeta);
	await createTextureAtlases(resources);
	return generateHostSystemAtlasArtifactsFromResources(resources);
}
