import { GX_GPU_VRAM_Y_ADDRESS_PERIOD, GX_GPU_VRAM_X_ADDRESS_PERIOD } from '../../machine/ts/spec/gx/vram';

export const GX_SYSTEM_TEXTURE_ASSET_ID = 'gx_system_texture';
export const GX_SYSTEM_TEXTURE_WIDTH = 256;
export const GX_SYSTEM_TEXTURE_HEIGHT = 64;
export const GX_SYSTEM_TEXTURE_X = GX_GPU_VRAM_X_ADDRESS_PERIOD - GX_SYSTEM_TEXTURE_WIDTH;
export const GX_SYSTEM_TEXTURE_Y = GX_GPU_VRAM_Y_ADDRESS_PERIOD - GX_SYSTEM_TEXTURE_HEIGHT;
