import { PSX_VRAM_STAGING_BYTES } from '../../machine/ts/machine/model_registry';

export const RPU_QUAD_VERTEX_STRIDE_BYTES = 0x00000014;
export const RPU_QUAD_VERTEX_COUNT = 4;
export const RPU_QUAD_INSTANCE_STRIDE_BYTES = 0x00000030;
export const RPU_QUAD_INSTANCE_FRAME_CAPACITY = 1024;
export const RPU_QUAD_DRAW_FRAME_CAPACITY = 1024;
export const RPU_QUAD_SURFACE_DESC_COUNT = 3;
export const RPU_QUAD_SURFACE_DESC_BYTES = 0x00000010;
export const RPU_QUAD_PASS_DESC_CAPACITY = 64;
export const RPU_QUAD_PASS_DESC_BYTES = 0x00000024;
export const RPU_QUAD_DRAW_DESC_BYTES = 0x0000002c;
export const RPU_QUAD_STREAM_DESC_BYTES = 0x0000000c;
export const RPU_QUAD_TEXTURE_DESC_BYTES = 0x00000008;
export const TEXTURE_ATLAS_RGBA_BYTES_PER_PIXEL = 4;

export const RPU_QUAD_VERTEX_BYTES = RPU_QUAD_VERTEX_STRIDE_BYTES * RPU_QUAD_VERTEX_COUNT;
export const RPU_QUAD_INSTANCE_VRAM_ADDR = RPU_QUAD_VERTEX_BYTES;
export const RPU_QUAD_SURFACE_DESC_VRAM_ADDR = RPU_QUAD_INSTANCE_VRAM_ADDR + RPU_QUAD_INSTANCE_STRIDE_BYTES * RPU_QUAD_INSTANCE_FRAME_CAPACITY;
export const RPU_QUAD_PASS_DESC_VRAM_ADDR = RPU_QUAD_SURFACE_DESC_VRAM_ADDR + RPU_QUAD_SURFACE_DESC_COUNT * RPU_QUAD_SURFACE_DESC_BYTES;
export const RPU_QUAD_DRAW_DESC_VRAM_ADDR = RPU_QUAD_PASS_DESC_VRAM_ADDR + RPU_QUAD_PASS_DESC_CAPACITY * RPU_QUAD_PASS_DESC_BYTES;
export const RPU_QUAD_STREAM_DESC_VRAM_ADDR = RPU_QUAD_DRAW_DESC_VRAM_ADDR + RPU_QUAD_DRAW_FRAME_CAPACITY * RPU_QUAD_DRAW_DESC_BYTES;
export const RPU_QUAD_TEXTURE_DESC_VRAM_ADDR = RPU_QUAD_STREAM_DESC_VRAM_ADDR + RPU_QUAD_DRAW_FRAME_CAPACITY * 2 * RPU_QUAD_STREAM_DESC_BYTES;
export const RPU_QUAD_TEXTURE_REGION_VRAM_ADDR = RPU_QUAD_TEXTURE_DESC_VRAM_ADDR + RPU_QUAD_DRAW_FRAME_CAPACITY * RPU_QUAD_TEXTURE_DESC_BYTES;
export const RPU_QUAD_TEXTURE_BYTES = PSX_VRAM_STAGING_BYTES - RPU_QUAD_TEXTURE_REGION_VRAM_ADDR;
export const RPU_QUAD_SYSTEM_TEXTURE_SLOT_BYTES = 0x00048000;
export const RPU_QUAD_PRIMARY_TEXTURE_SLOT_BYTES = 0x00068000;
export const RPU_QUAD_SECONDARY_TEXTURE_SLOT_BYTES = RPU_QUAD_TEXTURE_BYTES - RPU_QUAD_SYSTEM_TEXTURE_SLOT_BYTES - RPU_QUAD_PRIMARY_TEXTURE_SLOT_BYTES;
export const RPU_QUAD_MAX_CART_ATLAS_BYTES = RPU_QUAD_SECONDARY_TEXTURE_SLOT_BYTES;
