import { PSX_VRAM_STAGING_BYTES, PSX_VRAM_TEXTURE_BYTES } from '../../machine/ts/machine/model_registry';
import { VRAM_BASE } from '../../machine/ts/machine/memory/map';
import { BIOS_ATLAS_ID } from '../../machine/ts/rompack/format';

export const TEXTURE_ATLAS_RGBA_BYTES_PER_PIXEL = 4;

export const GX_TEXTURE_RESIDENCY_BYTES = PSX_VRAM_TEXTURE_BYTES;
export const GX_TEXTURE_RESIDENCY_BASE_ADDR = VRAM_BASE + PSX_VRAM_STAGING_BYTES;
export const GX_SYSTEM_TEXTURE_RESERVED_BYTES = 0x00048000;
export const GX_CART_TEXTURE_RESIDENCY_BASE_ADDR = GX_TEXTURE_RESIDENCY_BASE_ADDR + GX_SYSTEM_TEXTURE_RESERVED_BYTES;
export const GX_CART_TEXTURE_RESIDENCY_BYTES = GX_TEXTURE_RESIDENCY_BYTES - GX_SYSTEM_TEXTURE_RESERVED_BYTES;
export const GX_CART_ATLAS_ID_LIMIT = BIOS_ATLAS_ID;
