#pragma once

#include "common/types.h"

namespace bmsx {

constexpr u8 COP0_BAD_ADDRESS = 8u;
constexpr u8 COP0_LUA_FAULT_REASON = 9u;
constexpr u8 COP0_STATUS = 12u;
constexpr u8 COP0_CAUSE = 13u;
constexpr u8 COP0_EPC = 14u;
constexpr u8 COP0_EXEC = 15u;

constexpr u32 CPU_STATUS_INTERRUPT_ENABLE_CURRENT = 1u << 0u;
constexpr u32 CPU_STATUS_USER_MODE_CURRENT = 1u << 1u;
constexpr u32 CPU_STATUS_MODE_STACK_MASK = 0x3fu;
constexpr u32 CPU_STATUS_RFE_RESTORE_MASK = 0x0fu;

constexpr u32 CPU_STATUS_SYSTEM_ENTRY = CPU_STATUS_INTERRUPT_ENABLE_CURRENT;
constexpr u32 CPU_STATUS_CART_ENTRY = CPU_STATUS_INTERRUPT_ENABLE_CURRENT | CPU_STATUS_USER_MODE_CURRENT;

constexpr u32 CPU_CAUSE_IRQ = 1u << 10u;
constexpr u32 CPU_CAUSE_NMI = 1u << 16u;
constexpr u32 CPU_CAUSE_CODE_ADDRESS_ERROR_LOAD = 4u << 2u;
constexpr u32 CPU_CAUSE_CODE_ADDRESS_ERROR_STORE = 5u << 2u;
constexpr u32 CPU_CAUSE_CODE_DATA_BUS_ERROR = 7u << 2u;
constexpr u32 CPU_CAUSE_CODE_COPROCESSOR_UNUSABLE = 11u << 2u;
constexpr u32 CPU_CAUSE_CODE_TRAP = 13u << 2u;

constexpr u32 LUA_FAULT_REASON_UNKNOWN = 0u;
constexpr u32 LUA_FAULT_REASON_CALL_NON_FUNCTION = 1u;
constexpr u32 LUA_FAULT_REASON_INDEX_NON_TABLE = 2u;
constexpr u32 LUA_FAULT_REASON_ASSIGN_NON_TABLE = 3u;
constexpr u32 LUA_FAULT_REASON_INDEX_NIL = 4u;
constexpr u32 LUA_FAULT_REASON_METATABLE_LOOP = 5u;
constexpr u32 LUA_FAULT_REASON_ITERATE_NON_TABLE = 6u;
constexpr u32 LUA_FAULT_REASON_XPCALL_HANDLER_NOT_FUNCTION = 7u;
constexpr u32 LUA_FAULT_REASON_EXPLICIT_ERROR = 8u;

} // namespace bmsx
