import { IO_BASE, IO_WORD_SIZE } from './memory_map';

export const IO_WRITE_PTR_INDEX = 0;
export const IO_BUFFER_BASE_INDEX = 1;
export const IO_COMMAND_STRIDE_WORDS = 4;
export const IO_ARG0_OFFSET_WORDS = 1;

export const IO_CMD_PRINT = 1;

export const VM_IO_COMMAND_CAPACITY = 256;
export const IO_SYS_BASE_INDEX = IO_BUFFER_BASE_INDEX + IO_COMMAND_STRIDE_WORDS * VM_IO_COMMAND_CAPACITY;
export const IO_SYS_BOOT_CART_INDEX = IO_SYS_BASE_INDEX;
export const IO_SYS_CART_BOOTREADY_INDEX = IO_SYS_BASE_INDEX + 1;
export const IO_SYS_SIZE = 2;
export const IO_VDP_BASE_INDEX = IO_SYS_BASE_INDEX + IO_SYS_SIZE;
export const IO_VDP_DITHER_INDEX = IO_VDP_BASE_INDEX;
export const IO_VDP_SIZE = 1;
export const VM_IO_SLOT_COUNT = IO_VDP_BASE_INDEX + IO_VDP_SIZE;

export const IO_WRITE_PTR_ADDR = IO_BASE + IO_WRITE_PTR_INDEX * IO_WORD_SIZE;
export const IO_BUFFER_BASE = IO_BASE + IO_BUFFER_BASE_INDEX * IO_WORD_SIZE;
export const IO_COMMAND_STRIDE = IO_COMMAND_STRIDE_WORDS * IO_WORD_SIZE;
export const IO_ARG0_OFFSET = IO_ARG0_OFFSET_WORDS * IO_WORD_SIZE;
export const IO_ARG_STRIDE = IO_WORD_SIZE;

export const IO_SYS_BASE = IO_BASE + IO_SYS_BASE_INDEX * IO_WORD_SIZE;
export const IO_SYS_BOOT_CART = IO_BASE + IO_SYS_BOOT_CART_INDEX * IO_WORD_SIZE;
export const IO_SYS_CART_BOOTREADY = IO_BASE + IO_SYS_CART_BOOTREADY_INDEX * IO_WORD_SIZE;
export const IO_VDP_BASE = IO_BASE + IO_VDP_BASE_INDEX * IO_WORD_SIZE;
export const IO_VDP_DITHER = IO_BASE + IO_VDP_DITHER_INDEX * IO_WORD_SIZE;
