#pragma once

#include "machine/memory/map.h"

namespace bmsx {

/**
 * Runtime I/O memory layout constants.
 *
 * The runtime exposes a memory-mapped register bank.
 * Variable-length VDP submit data lives in CPU RAM and is pushed through
 * the VDP FIFO or submitted via the fixed VDP command doorbell.
 */

// I/O command codes
constexpr int IO_CMD_VDP_CLEAR = 0x10;
constexpr int IO_CMD_VDP_FILL_RECT = 0x11;
constexpr int IO_CMD_VDP_BLIT = 0x12;
constexpr int IO_CMD_VDP_DRAW_LINE = 0x13;
constexpr int IO_CMD_VDP_GLYPH_RUN = 0x14;
constexpr int IO_CMD_VDP_TILE_RUN = 0x15;
constexpr int IO_CMD_VDP_CONFIG_SURFACE = 0x16;

constexpr uint32_t APU_SAMPLE_RATE_HZ = 44100u;
constexpr uint32_t APU_RATE_STEP_Q16_ONE = 0x10000u;
constexpr uint32_t APU_GAIN_Q12_ONE = 0x1000u;

constexpr int IO_SYS_BASE_INDEX = 0;

// System flag: should boot cartridge?
constexpr int IO_SYS_BOOT_CART_INDEX = IO_SYS_BASE_INDEX;
constexpr int IO_SYS_HOST_FAULT_FLAGS_INDEX = IO_SYS_BASE_INDEX + 1;
constexpr int IO_SYS_HOST_FAULT_STAGE_INDEX = IO_SYS_BASE_INDEX + 2;

// Number of system flag slots
constexpr int IO_SYS_SIZE = 3;
constexpr int IO_VDP_BASE_INDEX = IO_SYS_BASE_INDEX + IO_SYS_SIZE;
constexpr int IO_VDP_DITHER_INDEX = IO_VDP_BASE_INDEX;
constexpr int IO_VDP_SLOT_PRIMARY_ATLAS_INDEX = IO_VDP_BASE_INDEX + 1;
constexpr int IO_VDP_SLOT_SECONDARY_ATLAS_INDEX = IO_VDP_BASE_INDEX + 2;
constexpr int IO_VDP_RD_SURFACE_INDEX = IO_VDP_BASE_INDEX + 3;
constexpr int IO_VDP_RD_X_INDEX = IO_VDP_BASE_INDEX + 4;
constexpr int IO_VDP_RD_Y_INDEX = IO_VDP_BASE_INDEX + 5;
constexpr int IO_VDP_RD_MODE_INDEX = IO_VDP_BASE_INDEX + 6;
constexpr int IO_VDP_RD_STATUS_INDEX = IO_VDP_BASE_INDEX + 7;
constexpr int IO_VDP_RD_DATA_INDEX = IO_VDP_BASE_INDEX + 8;
constexpr int IO_VDP_CMD_INDEX = IO_VDP_BASE_INDEX + 9;
constexpr int IO_VDP_CMD_ARG0_INDEX = IO_VDP_BASE_INDEX + 10;
constexpr int IO_VDP_CMD_ARG_COUNT = static_cast<int>(VDP_CMD_ARG_COUNT);
constexpr int IO_VDP_FIFO_INDEX = IO_VDP_CMD_ARG0_INDEX + IO_VDP_CMD_ARG_COUNT;
constexpr int IO_VDP_FIFO_CTRL_INDEX = IO_VDP_FIFO_INDEX + 1;
constexpr int IO_VDP_PMU_BANK_INDEX = IO_VDP_FIFO_CTRL_INDEX + 1;
constexpr int IO_VDP_PMU_X_INDEX = IO_VDP_PMU_BANK_INDEX + 1;
constexpr int IO_VDP_PMU_Y_INDEX = IO_VDP_PMU_BANK_INDEX + 2;
constexpr int IO_VDP_PMU_SCALE_X_INDEX = IO_VDP_PMU_BANK_INDEX + 3;
constexpr int IO_VDP_PMU_SCALE_Y_INDEX = IO_VDP_PMU_BANK_INDEX + 4;
constexpr int IO_VDP_PMU_CTRL_INDEX = IO_VDP_PMU_BANK_INDEX + 5;
constexpr int IO_VDP_PMU_SIZE = 6;
constexpr int IO_VDP_SBX_CONTROL_INDEX = IO_VDP_PMU_BANK_INDEX + IO_VDP_PMU_SIZE;
constexpr int IO_VDP_SBX_FACE0_INDEX = IO_VDP_SBX_CONTROL_INDEX + 1;
constexpr int IO_VDP_SBX_FACE_WORD_COUNT = 30;
constexpr int IO_VDP_SBX_COMMIT_INDEX = IO_VDP_SBX_FACE0_INDEX + IO_VDP_SBX_FACE_WORD_COUNT;
constexpr int IO_VDP_SBX_SIZE = 1 + IO_VDP_SBX_FACE_WORD_COUNT + 1;
constexpr int IO_VDP_CAMERA_VIEW_INDEX = IO_VDP_SBX_CONTROL_INDEX + IO_VDP_SBX_SIZE;
constexpr int IO_VDP_CAMERA_PROJ_INDEX = IO_VDP_CAMERA_VIEW_INDEX + 16;
constexpr int IO_VDP_CAMERA_EYE_INDEX = IO_VDP_CAMERA_PROJ_INDEX + 16;
constexpr int IO_VDP_CAMERA_COMMIT_INDEX = IO_VDP_CAMERA_EYE_INDEX + 3;
constexpr int IO_VDP_CAMERA_SIZE = 16 + 16 + 3 + 1;
constexpr int IO_VDP_SIZE = 12 + IO_VDP_CMD_ARG_COUNT + IO_VDP_PMU_SIZE + IO_VDP_SBX_SIZE + IO_VDP_CAMERA_SIZE;

constexpr int IO_IRQ_BASE_INDEX = IO_VDP_BASE_INDEX + IO_VDP_SIZE;
constexpr int IO_IRQ_FLAGS_INDEX = IO_IRQ_BASE_INDEX;
constexpr int IO_IRQ_ACK_INDEX = IO_IRQ_BASE_INDEX + 1;
constexpr int IO_IRQ_SIZE = 2;

constexpr int IO_DMA_BASE_INDEX = IO_IRQ_BASE_INDEX + IO_IRQ_SIZE;
constexpr int IO_DMA_SRC_INDEX = IO_DMA_BASE_INDEX;
constexpr int IO_DMA_DST_INDEX = IO_DMA_BASE_INDEX + 1;
constexpr int IO_DMA_LEN_INDEX = IO_DMA_BASE_INDEX + 2;
constexpr int IO_DMA_CTRL_INDEX = IO_DMA_BASE_INDEX + 3;
constexpr int IO_DMA_STATUS_INDEX = IO_DMA_BASE_INDEX + 4;
constexpr int IO_DMA_WRITTEN_INDEX = IO_DMA_BASE_INDEX + 5;
constexpr int IO_DMA_SIZE = 6;

constexpr int IO_IMG_BASE_INDEX = IO_DMA_BASE_INDEX + IO_DMA_SIZE;
constexpr int IO_IMG_SRC_INDEX = IO_IMG_BASE_INDEX;
constexpr int IO_IMG_LEN_INDEX = IO_IMG_BASE_INDEX + 1;
constexpr int IO_IMG_DST_INDEX = IO_IMG_BASE_INDEX + 2;
constexpr int IO_IMG_CAP_INDEX = IO_IMG_BASE_INDEX + 3;
constexpr int IO_IMG_CTRL_INDEX = IO_IMG_BASE_INDEX + 4;
constexpr int IO_IMG_STATUS_INDEX = IO_IMG_BASE_INDEX + 5;
constexpr int IO_IMG_WRITTEN_INDEX = IO_IMG_BASE_INDEX + 6;
constexpr int IO_IMG_SIZE = 7;

constexpr int IO_VDP_STATUS_INDEX = IO_IMG_BASE_INDEX + IO_IMG_SIZE;
constexpr int IO_VDP_FAULT_CODE_INDEX = IO_VDP_STATUS_INDEX + 1;
constexpr int IO_VDP_FAULT_DETAIL_INDEX = IO_VDP_STATUS_INDEX + 2;
constexpr int IO_VDP_STATUS_SIZE = 3;

constexpr int IO_GEO_BASE_INDEX = IO_VDP_STATUS_INDEX + IO_VDP_STATUS_SIZE;
constexpr int IO_GEO_SRC0_INDEX = IO_GEO_BASE_INDEX;
constexpr int IO_GEO_SRC1_INDEX = IO_GEO_BASE_INDEX + 1;
constexpr int IO_GEO_SRC2_INDEX = IO_GEO_BASE_INDEX + 2;
constexpr int IO_GEO_DST0_INDEX = IO_GEO_BASE_INDEX + 3;
constexpr int IO_GEO_DST1_INDEX = IO_GEO_BASE_INDEX + 4;
constexpr int IO_GEO_COUNT_INDEX = IO_GEO_BASE_INDEX + 5;
constexpr int IO_GEO_CMD_INDEX = IO_GEO_BASE_INDEX + 6;
constexpr int IO_GEO_CTRL_INDEX = IO_GEO_BASE_INDEX + 7;
constexpr int IO_GEO_STATUS_INDEX = IO_GEO_BASE_INDEX + 8;
constexpr int IO_GEO_PARAM0_INDEX = IO_GEO_BASE_INDEX + 9;
constexpr int IO_GEO_PARAM1_INDEX = IO_GEO_BASE_INDEX + 10;
constexpr int IO_GEO_STRIDE0_INDEX = IO_GEO_BASE_INDEX + 11;
constexpr int IO_GEO_STRIDE1_INDEX = IO_GEO_BASE_INDEX + 12;
constexpr int IO_GEO_STRIDE2_INDEX = IO_GEO_BASE_INDEX + 13;
constexpr int IO_GEO_PROCESSED_INDEX = IO_GEO_BASE_INDEX + 14;
constexpr int IO_GEO_FAULT_INDEX = IO_GEO_BASE_INDEX + 15;
constexpr int IO_GEO_SIZE = 16;

constexpr int IO_INP_BASE_INDEX = IO_GEO_BASE_INDEX + IO_GEO_SIZE;
constexpr int IO_INP_PLAYER_INDEX = IO_INP_BASE_INDEX;
constexpr int IO_INP_ACTION_INDEX = IO_INP_BASE_INDEX + 1;
constexpr int IO_INP_BIND_INDEX = IO_INP_BASE_INDEX + 2;
constexpr int IO_INP_CTRL_INDEX = IO_INP_BASE_INDEX + 3;
constexpr int IO_INP_QUERY_INDEX = IO_INP_BASE_INDEX + 4;
constexpr int IO_INP_STATUS_INDEX = IO_INP_BASE_INDEX + 5;
constexpr int IO_INP_VALUE_INDEX = IO_INP_BASE_INDEX + 6;
constexpr int IO_INP_CONSUME_INDEX = IO_INP_BASE_INDEX + 7;
constexpr int IO_INP_SIZE = 8;

constexpr int IO_APU_BASE_INDEX = IO_INP_BASE_INDEX + IO_INP_SIZE;
constexpr int IO_APU_SOURCE_ADDR_INDEX = IO_APU_BASE_INDEX;
constexpr int IO_APU_SOURCE_BYTES_INDEX = IO_APU_BASE_INDEX + 1;
constexpr int IO_APU_SOURCE_SAMPLE_RATE_HZ_INDEX = IO_APU_BASE_INDEX + 2;
constexpr int IO_APU_SOURCE_CHANNELS_INDEX = IO_APU_BASE_INDEX + 3;
constexpr int IO_APU_SOURCE_BITS_PER_SAMPLE_INDEX = IO_APU_BASE_INDEX + 4;
constexpr int IO_APU_SOURCE_FRAME_COUNT_INDEX = IO_APU_BASE_INDEX + 5;
constexpr int IO_APU_SOURCE_DATA_OFFSET_INDEX = IO_APU_BASE_INDEX + 6;
constexpr int IO_APU_SOURCE_DATA_BYTES_INDEX = IO_APU_BASE_INDEX + 7;
constexpr int IO_APU_SOURCE_LOOP_START_SAMPLE_INDEX = IO_APU_BASE_INDEX + 8;
constexpr int IO_APU_SOURCE_LOOP_END_SAMPLE_INDEX = IO_APU_BASE_INDEX + 9;
constexpr int IO_APU_SLOT_INDEX = IO_APU_BASE_INDEX + 10;
constexpr int IO_APU_RATE_STEP_Q16_INDEX = IO_APU_BASE_INDEX + 11;
constexpr int IO_APU_GAIN_Q12_INDEX = IO_APU_BASE_INDEX + 12;
constexpr int IO_APU_START_SAMPLE_INDEX = IO_APU_BASE_INDEX + 13;
constexpr int IO_APU_FILTER_KIND_INDEX = IO_APU_BASE_INDEX + 14;
constexpr int IO_APU_FILTER_FREQ_HZ_INDEX = IO_APU_BASE_INDEX + 15;
constexpr int IO_APU_FILTER_Q_MILLI_INDEX = IO_APU_BASE_INDEX + 16;
constexpr int IO_APU_FILTER_GAIN_MILLIDB_INDEX = IO_APU_BASE_INDEX + 17;
constexpr int IO_APU_FADE_SAMPLES_INDEX = IO_APU_BASE_INDEX + 18;
constexpr int IO_APU_TARGET_GAIN_Q12_INDEX = IO_APU_BASE_INDEX + 19;
constexpr int IO_APU_CMD_INDEX = IO_APU_BASE_INDEX + 20;
constexpr int IO_APU_STATUS_INDEX = IO_APU_BASE_INDEX + 21;
constexpr int IO_APU_EVENT_KIND_INDEX = IO_APU_BASE_INDEX + 22;
constexpr int IO_APU_EVENT_SLOT_INDEX = IO_APU_BASE_INDEX + 23;
constexpr int IO_APU_EVENT_SOURCE_ADDR_INDEX = IO_APU_BASE_INDEX + 24;
constexpr int IO_APU_EVENT_SEQ_INDEX = IO_APU_BASE_INDEX + 25;
constexpr int IO_APU_SIZE = 26;

constexpr int IO_PAYLOAD_WRITE_PTR_INDEX = IO_APU_BASE_INDEX + IO_APU_SIZE;
constexpr int IO_PAYLOAD_BUFFER_BASE_INDEX = IO_PAYLOAD_WRITE_PTR_INDEX + 1;
constexpr int IO_PAYLOAD_CAPACITY = 16384;

constexpr int IO_SLOT_COUNT = IO_PAYLOAD_BUFFER_BASE_INDEX + IO_PAYLOAD_CAPACITY;

constexpr uint32_t IO_ARG_STRIDE = IO_WORD_SIZE;
constexpr uint32_t IO_PAYLOAD_WRITE_PTR_ADDR = IO_BASE + IO_PAYLOAD_WRITE_PTR_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_PAYLOAD_BUFFER_BASE = IO_BASE + IO_PAYLOAD_BUFFER_BASE_INDEX * IO_WORD_SIZE;

constexpr uint32_t IO_SYS_BASE = IO_BASE + IO_SYS_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_BOOT_CART = IO_BASE + IO_SYS_BOOT_CART_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_HOST_FAULT_FLAGS = IO_BASE + IO_SYS_HOST_FAULT_FLAGS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_SYS_HOST_FAULT_STAGE = IO_BASE + IO_SYS_HOST_FAULT_STAGE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_BASE = IO_BASE + IO_VDP_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_DITHER = IO_BASE + IO_VDP_DITHER_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_SLOT_PRIMARY_ATLAS = IO_BASE + IO_VDP_SLOT_PRIMARY_ATLAS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_SLOT_SECONDARY_ATLAS = IO_BASE + IO_VDP_SLOT_SECONDARY_ATLAS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_RD_SURFACE = IO_BASE + IO_VDP_RD_SURFACE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_RD_X = IO_BASE + IO_VDP_RD_X_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_RD_Y = IO_BASE + IO_VDP_RD_Y_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_RD_MODE = IO_BASE + IO_VDP_RD_MODE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_RD_STATUS = IO_BASE + IO_VDP_RD_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_RD_DATA = IO_BASE + IO_VDP_RD_DATA_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_CMD = IO_BASE + IO_VDP_CMD_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_CMD_ARG0 = IO_BASE + IO_VDP_CMD_ARG0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG0 = IO_VDP_CMD_ARG0;
constexpr uint32_t IO_VDP_REG_SRC_SLOT = IO_VDP_REG0 + 0u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_SRC_UV = IO_VDP_REG0 + 1u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_SRC_WH = IO_VDP_REG0 + 2u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_DST_X = IO_VDP_REG0 + 3u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_DST_Y = IO_VDP_REG0 + 4u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_GEOM_X0 = IO_VDP_REG0 + 5u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_GEOM_Y0 = IO_VDP_REG0 + 6u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_GEOM_X1 = IO_VDP_REG0 + 7u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_GEOM_Y1 = IO_VDP_REG0 + 8u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_LINE_WIDTH = IO_VDP_REG0 + 9u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_DRAW_LAYER_PRIO = IO_VDP_REG0 + 10u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_DRAW_CTRL = IO_VDP_REG0 + 11u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_DRAW_SCALE_X = IO_VDP_REG0 + 12u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_DRAW_SCALE_Y = IO_VDP_REG0 + 13u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_DRAW_COLOR = IO_VDP_REG0 + 14u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_BG_COLOR = IO_VDP_REG0 + 15u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_SLOT_INDEX = IO_VDP_REG0 + 16u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_REG_SLOT_DIM = IO_VDP_REG0 + 17u * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_FIFO = IO_BASE + IO_VDP_FIFO_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_FIFO_CTRL = IO_BASE + IO_VDP_FIFO_CTRL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_PMU_BANK = IO_BASE + IO_VDP_PMU_BANK_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_PMU_X = IO_BASE + IO_VDP_PMU_X_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_PMU_Y = IO_BASE + IO_VDP_PMU_Y_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_PMU_SCALE_X = IO_BASE + IO_VDP_PMU_SCALE_X_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_PMU_SCALE_Y = IO_BASE + IO_VDP_PMU_SCALE_Y_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_PMU_CTRL = IO_BASE + IO_VDP_PMU_CTRL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_SBX_CONTROL = IO_BASE + IO_VDP_SBX_CONTROL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_SBX_FACE0 = IO_BASE + IO_VDP_SBX_FACE0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_SBX_COMMIT = IO_BASE + IO_VDP_SBX_COMMIT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_CAMERA_VIEW = IO_BASE + IO_VDP_CAMERA_VIEW_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_CAMERA_PROJ = IO_BASE + IO_VDP_CAMERA_PROJ_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_CAMERA_EYE = IO_BASE + IO_VDP_CAMERA_EYE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_CAMERA_COMMIT = IO_BASE + IO_VDP_CAMERA_COMMIT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_STATUS = IO_BASE + IO_VDP_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_FAULT_CODE = IO_BASE + IO_VDP_FAULT_CODE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_VDP_FAULT_DETAIL = IO_BASE + IO_VDP_FAULT_DETAIL_INDEX * IO_WORD_SIZE;

constexpr uint32_t IO_IRQ_BASE = IO_BASE + IO_IRQ_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IRQ_FLAGS = IO_BASE + IO_IRQ_FLAGS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IRQ_ACK = IO_BASE + IO_IRQ_ACK_INDEX * IO_WORD_SIZE;

constexpr uint32_t IO_DMA_BASE = IO_BASE + IO_DMA_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_SRC = IO_BASE + IO_DMA_SRC_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_DST = IO_BASE + IO_DMA_DST_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_LEN = IO_BASE + IO_DMA_LEN_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_CTRL = IO_BASE + IO_DMA_CTRL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_STATUS = IO_BASE + IO_DMA_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_DMA_WRITTEN = IO_BASE + IO_DMA_WRITTEN_INDEX * IO_WORD_SIZE;

constexpr uint32_t IO_IMG_BASE = IO_BASE + IO_IMG_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IMG_SRC = IO_BASE + IO_IMG_SRC_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IMG_LEN = IO_BASE + IO_IMG_LEN_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IMG_DST = IO_BASE + IO_IMG_DST_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IMG_CAP = IO_BASE + IO_IMG_CAP_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IMG_CTRL = IO_BASE + IO_IMG_CTRL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IMG_STATUS = IO_BASE + IO_IMG_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_IMG_WRITTEN = IO_BASE + IO_IMG_WRITTEN_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_BASE = IO_BASE + IO_GEO_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_SRC0 = IO_BASE + IO_GEO_SRC0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_SRC1 = IO_BASE + IO_GEO_SRC1_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_SRC2 = IO_BASE + IO_GEO_SRC2_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_DST0 = IO_BASE + IO_GEO_DST0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_DST1 = IO_BASE + IO_GEO_DST1_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_COUNT = IO_BASE + IO_GEO_COUNT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_CMD = IO_BASE + IO_GEO_CMD_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_CTRL = IO_BASE + IO_GEO_CTRL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_STATUS = IO_BASE + IO_GEO_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_PARAM0 = IO_BASE + IO_GEO_PARAM0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_PARAM1 = IO_BASE + IO_GEO_PARAM1_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_STRIDE0 = IO_BASE + IO_GEO_STRIDE0_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_STRIDE1 = IO_BASE + IO_GEO_STRIDE1_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_STRIDE2 = IO_BASE + IO_GEO_STRIDE2_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_PROCESSED = IO_BASE + IO_GEO_PROCESSED_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_GEO_FAULT = IO_BASE + IO_GEO_FAULT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_BASE = IO_BASE + IO_INP_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_PLAYER = IO_BASE + IO_INP_PLAYER_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_ACTION = IO_BASE + IO_INP_ACTION_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_BIND = IO_BASE + IO_INP_BIND_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_CTRL = IO_BASE + IO_INP_CTRL_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_QUERY = IO_BASE + IO_INP_QUERY_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_STATUS = IO_BASE + IO_INP_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_VALUE = IO_BASE + IO_INP_VALUE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_INP_CONSUME = IO_BASE + IO_INP_CONSUME_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_BASE = IO_BASE + IO_APU_BASE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_ADDR = IO_BASE + IO_APU_SOURCE_ADDR_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_BYTES = IO_BASE + IO_APU_SOURCE_BYTES_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_SAMPLE_RATE_HZ = IO_BASE + IO_APU_SOURCE_SAMPLE_RATE_HZ_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_CHANNELS = IO_BASE + IO_APU_SOURCE_CHANNELS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_BITS_PER_SAMPLE = IO_BASE + IO_APU_SOURCE_BITS_PER_SAMPLE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_FRAME_COUNT = IO_BASE + IO_APU_SOURCE_FRAME_COUNT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_DATA_OFFSET = IO_BASE + IO_APU_SOURCE_DATA_OFFSET_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_DATA_BYTES = IO_BASE + IO_APU_SOURCE_DATA_BYTES_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_LOOP_START_SAMPLE = IO_BASE + IO_APU_SOURCE_LOOP_START_SAMPLE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SOURCE_LOOP_END_SAMPLE = IO_BASE + IO_APU_SOURCE_LOOP_END_SAMPLE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_SLOT = IO_BASE + IO_APU_SLOT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_RATE_STEP_Q16 = IO_BASE + IO_APU_RATE_STEP_Q16_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_GAIN_Q12 = IO_BASE + IO_APU_GAIN_Q12_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_START_SAMPLE = IO_BASE + IO_APU_START_SAMPLE_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FILTER_KIND = IO_BASE + IO_APU_FILTER_KIND_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FILTER_FREQ_HZ = IO_BASE + IO_APU_FILTER_FREQ_HZ_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FILTER_Q_MILLI = IO_BASE + IO_APU_FILTER_Q_MILLI_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FILTER_GAIN_MILLIDB = IO_BASE + IO_APU_FILTER_GAIN_MILLIDB_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_FADE_SAMPLES = IO_BASE + IO_APU_FADE_SAMPLES_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_TARGET_GAIN_Q12 = IO_BASE + IO_APU_TARGET_GAIN_Q12_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_CMD = IO_BASE + IO_APU_CMD_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_STATUS = IO_BASE + IO_APU_STATUS_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_EVENT_KIND = IO_BASE + IO_APU_EVENT_KIND_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_EVENT_SLOT = IO_BASE + IO_APU_EVENT_SLOT_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_EVENT_SOURCE_ADDR = IO_BASE + IO_APU_EVENT_SOURCE_ADDR_INDEX * IO_WORD_SIZE;
constexpr uint32_t IO_APU_EVENT_SEQ = IO_BASE + IO_APU_EVENT_SEQ_INDEX * IO_WORD_SIZE;

constexpr uint32_t IRQ_DMA_DONE = 1 << 0;
constexpr uint32_t IRQ_DMA_ERROR = 1 << 1;
constexpr uint32_t IRQ_IMG_DONE = 1 << 2;
constexpr uint32_t IRQ_IMG_ERROR = 1 << 3;
constexpr uint32_t IRQ_VBLANK = 1 << 4;
constexpr uint32_t IRQ_REINIT = 1 << 5;
constexpr uint32_t IRQ_NEWGAME = 1 << 6;
constexpr uint32_t IRQ_GEO_DONE = 1 << 7;
constexpr uint32_t IRQ_GEO_ERROR = 1 << 8;
constexpr uint32_t IRQ_APU = 1 << 9;

constexpr uint32_t APU_CMD_NONE = 0;
constexpr uint32_t APU_CMD_PLAY = 1;
constexpr uint32_t APU_CMD_STOP_SLOT = 2;
constexpr uint32_t APU_CMD_RAMP_SLOT = 3;
constexpr uint32_t APU_SLOT_COUNT = 16;
constexpr uint32_t APU_FILTER_NONE = 0;
constexpr uint32_t APU_FILTER_LOWPASS = 1;
constexpr uint32_t APU_FILTER_HIGHPASS = 2;
constexpr uint32_t APU_FILTER_BANDPASS = 3;
constexpr uint32_t APU_FILTER_NOTCH = 4;
constexpr uint32_t APU_FILTER_ALLPASS = 5;
constexpr uint32_t APU_FILTER_PEAKING = 6;
constexpr uint32_t APU_FILTER_LOWSHELF = 7;
constexpr uint32_t APU_FILTER_HIGHSHELF = 8;
constexpr uint32_t APU_EVENT_NONE = 0;
constexpr uint32_t APU_EVENT_SLOT_ENDED = 1;

constexpr uint32_t VDP_STATUS_VBLANK = 1u << 0u;
constexpr uint32_t VDP_STATUS_SUBMIT_BUSY = 1u << 1u;
// Sticky latch: set when a VDP submit attempt is rejected because the submit path is busy,
// and cleared only when a later VDP submit attempt is accepted.
constexpr uint32_t VDP_STATUS_SUBMIT_REJECTED = 1u << 2u;
constexpr uint32_t VDP_STATUS_FAULT = 1u << 3u;
constexpr uint32_t VDP_SBX_COMMIT_WRITE = 1u;
constexpr uint32_t VDP_CAMERA_COMMIT_WRITE = 1u;

constexpr uint32_t VDP_FAULT_NONE = 0u;
constexpr uint32_t VDP_FAULT_RD_UNSUPPORTED_MODE = 0x0001u;
constexpr uint32_t VDP_FAULT_RD_SURFACE = 0x0002u;
constexpr uint32_t VDP_FAULT_RD_OOB = 0x0003u;
constexpr uint32_t VDP_FAULT_VRAM_WRITE_UNMAPPED = 0x0101u;
constexpr uint32_t VDP_FAULT_VRAM_WRITE_UNINITIALIZED = 0x0102u;
constexpr uint32_t VDP_FAULT_VRAM_WRITE_OOB = 0x0103u;
constexpr uint32_t VDP_FAULT_VRAM_WRITE_UNALIGNED = 0x0104u;

constexpr uint32_t DMA_CTRL_START = 1 << 0;
constexpr uint32_t DMA_CTRL_STRICT = 1 << 1;
constexpr uint32_t DMA_STATUS_BUSY = 1 << 0;
constexpr uint32_t DMA_STATUS_DONE = 1 << 1;
constexpr uint32_t DMA_STATUS_ERROR = 1 << 2;
constexpr uint32_t DMA_STATUS_CLIPPED = 1 << 3;
constexpr uint32_t DMA_STATUS_REJECTED = 1 << 4;

constexpr uint32_t IMG_CTRL_START = 1 << 0;
constexpr uint32_t IMG_STATUS_BUSY = 1 << 0;
constexpr uint32_t IMG_STATUS_DONE = 1 << 1;
constexpr uint32_t IMG_STATUS_ERROR = 1 << 2;
constexpr uint32_t IMG_STATUS_CLIPPED = 1 << 3;
constexpr uint32_t IMG_STATUS_REJECTED = 1 << 4;

constexpr uint32_t HOST_FAULT_FLAG_ACTIVE = 1u << 0u;
constexpr uint32_t HOST_FAULT_FLAG_STARTUP_BLOCKING = 1u << 1u;
constexpr uint32_t HOST_FAULT_STAGE_NONE = 0u;
constexpr uint32_t HOST_FAULT_STAGE_STARTUP_AUDIO_REFRESH = 1u;

constexpr uint32_t GEO_CTRL_START = 1 << 0;
constexpr uint32_t GEO_CTRL_ABORT = 1 << 1;
constexpr uint32_t GEO_STATUS_BUSY = 1 << 0;
constexpr uint32_t GEO_STATUS_DONE = 1 << 1;
constexpr uint32_t GEO_STATUS_ERROR = 1 << 2;
constexpr uint32_t GEO_STATUS_REJECTED = 1 << 3;

constexpr int IO_CMD_GEO_XFORM2_BATCH = 0x20;
constexpr int IO_CMD_GEO_SAT2_BATCH = 0x21;
constexpr int IO_CMD_GEO_OVERLAP2D_PASS = 0x22;
constexpr int IO_CMD_GEO_XFORM3_BATCH = 0x30;
constexpr int IO_CMD_GEO_PROJECT3_BATCH = 0x31;

constexpr uint32_t GEO_INDEX_NONE = 0xffffffffu;
constexpr uint32_t GEO_SHAPE_CONVEX_POLY = 1u << 0u;
constexpr uint32_t GEO_PRIMITIVE_AABB = 1u;
constexpr uint32_t GEO_PRIMITIVE_CIRCLE = 2u;
constexpr uint32_t GEO_PRIMITIVE_CONVEX_POLY = 3u;
constexpr uint32_t GEO_SAT_META_AXIS_MASK = 0xffffu;
constexpr uint32_t GEO_SAT_META_SHAPE_SHIFT = 16u;
constexpr uint32_t GEO_SAT_META_SHAPE_SRC = 0u;
constexpr uint32_t GEO_SAT_META_SHAPE_AUX = 1u;
constexpr uint32_t GEO_OVERLAP2D_MODE_MASK = 0x3u;
constexpr uint32_t GEO_OVERLAP2D_MODE_CANDIDATE_PAIRS = 0x1u;
constexpr uint32_t GEO_OVERLAP2D_MODE_FULL_PASS = 0x2u;
constexpr uint32_t GEO_OVERLAP2D_BROADPHASE_SHIFT = 2u;
constexpr uint32_t GEO_OVERLAP2D_BROADPHASE_MASK = 0x3u << GEO_OVERLAP2D_BROADPHASE_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_BROADPHASE_NONE = 0u << GEO_OVERLAP2D_BROADPHASE_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_BROADPHASE_LOCAL_BOUNDS_AABB = 0x1u << GEO_OVERLAP2D_BROADPHASE_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_CONTACT_POLICY_SHIFT = 4u;
constexpr uint32_t GEO_OVERLAP2D_CONTACT_POLICY_MASK = 0x3u << GEO_OVERLAP2D_CONTACT_POLICY_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_CONTACT_POLICY_CLIPPED_FEATURE = 0u << GEO_OVERLAP2D_CONTACT_POLICY_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_OUTPUT_POLICY_SHIFT = 6u;
constexpr uint32_t GEO_OVERLAP2D_OUTPUT_POLICY_MASK = 0x3u << GEO_OVERLAP2D_OUTPUT_POLICY_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_OUTPUT_POLICY_STOP_ON_OVERFLOW = 0u << GEO_OVERLAP2D_OUTPUT_POLICY_SHIFT;
constexpr uint32_t GEO_OVERLAP2D_SUMMARY_FLAG_OVERFLOW = 1u << 0u;

constexpr uint32_t GEO_FAULT_ABORTED_BY_HOST = 0x0001u;
constexpr uint32_t GEO_FAULT_BAD_RECORD_ALIGNMENT = 0x0002u;
constexpr uint32_t GEO_FAULT_BAD_VERTEX_COUNT = 0x0003u;
constexpr uint32_t GEO_FAULT_SRC_RANGE = 0x0004u;
constexpr uint32_t GEO_FAULT_DST_RANGE = 0x0005u;
constexpr uint32_t GEO_FAULT_DESCRIPTOR_KIND = 0x0006u;
constexpr uint32_t GEO_FAULT_NUMERIC_OVERFLOW_INTERNAL = 0x0007u;
constexpr uint32_t GEO_FAULT_BAD_RECORD_FLAGS = 0x0008u;
constexpr uint32_t GEO_FAULT_RESULT_CAPACITY = 0x0009u;

constexpr uint32_t GEO_FAULT_REJECT_BUSY = 0x8001u;
constexpr uint32_t GEO_FAULT_REJECT_BAD_CMD = 0x8002u;
constexpr uint32_t GEO_FAULT_REJECT_BAD_STRIDE = 0x8003u;
constexpr uint32_t GEO_FAULT_REJECT_DST_NOT_RAM = 0x8004u;
constexpr uint32_t GEO_FAULT_REJECT_MISALIGNED_REGS = 0x8005u;
constexpr uint32_t GEO_FAULT_REJECT_BAD_REGISTER_COMBO = 0x8006u;

constexpr uint32_t INP_CTRL_COMMIT = 1u;
constexpr uint32_t INP_CTRL_ARM = 2u;
constexpr uint32_t INP_CTRL_RESET = 3u;

constexpr uint32_t VDP_SLOT_PRIMARY = 0u;
constexpr uint32_t VDP_SLOT_SECONDARY = 1u;
constexpr uint32_t VDP_SLOT_SYSTEM = 2u;
constexpr uint32_t VDP_SYSTEM_ATLAS_ID = 254u;
constexpr uint32_t VDP_SLOT_NONE = 0xffffffffu;
constexpr uint32_t VDP_SLOT_ATLAS_NONE = 0xffffffffu;
constexpr uint32_t VDP_RD_MODE_RGBA8888 = 0u;
constexpr uint32_t VDP_RD_STATUS_READY = 1u << 0u;
constexpr uint32_t VDP_RD_STATUS_OVERFLOW = 1u << 1u;
constexpr uint32_t VDP_FIFO_CTRL_SEAL = 1u << 0u;

} // namespace bmsx
