#include "machine/firmware/builtin_descriptors.h"

#include <algorithm>
#include <array>

namespace bmsx {
namespace {
constexpr std::array<LuaBuiltinDescriptor, 61> kSystemLuaBuiltinFunctions{{
	LuaBuiltinDescriptor{"define_fsm", "define_fsm(id, blueprint)", ""},
	LuaBuiltinDescriptor{"define_prefab", "define_prefab(definition)", ""},
	LuaBuiltinDescriptor{"define_subsystem", "define_subsystem(definition)", ""},
	LuaBuiltinDescriptor{"define_component", "define_component(definition)", ""},
	LuaBuiltinDescriptor{"define_effect", "define_effect(definition [, opts])", ""},
	LuaBuiltinDescriptor{"inst", "inst(definition_id [, addons])", ""},
	LuaBuiltinDescriptor{"inst_subsystem", "inst_subsystem(definition_id [, addons])", ""},
	LuaBuiltinDescriptor{"oget", "oget(id)", ""},
	LuaBuiltinDescriptor{"rget", "rget(id)", ""},
	LuaBuiltinDescriptor{"subsystem", "subsystem(id)", ""},
	LuaBuiltinDescriptor{"add_space", "add_space(space_id)", ""},
	LuaBuiltinDescriptor{"set_space", "set_space(space_id)", ""},
	LuaBuiltinDescriptor{"get_space", "get_space()", ""},
	LuaBuiltinDescriptor{"attach_component", "attach_component(object_or_id, component_or_type)", ""},
	LuaBuiltinDescriptor{"update_world", "update_world()", "Runs one world/game-logic phase without emitting the presentation VDP stream."},
	LuaBuiltinDescriptor{"draw_world", "draw_world()", "Emits presentation VDP commands for the current world state without running game logic."},
	LuaBuiltinDescriptor{"reset", "reset()", ""},
	LuaBuiltinDescriptor{"configure_ecs", "configure_ecs(nodes)", ""},
	LuaBuiltinDescriptor{"apply_default_pipeline", "apply_default_pipeline()", ""},
	LuaBuiltinDescriptor{"enlist", "enlist(value)", ""},
	LuaBuiltinDescriptor{"delist", "delist(id)", ""},
	LuaBuiltinDescriptor{"grant_effect", "grant_effect(object_id, effect_id)", ""},
	LuaBuiltinDescriptor{"trigger_effect", "trigger_effect(object_id, effect_id [, options])", ""},
	LuaBuiltinDescriptor{"vdp_load_slot", "vdp_load_slot(slot, atlas_id)", "Starts an async atlas load into a VRAM slot; BIOS maps the slot on completion; returns a job id."},
	LuaBuiltinDescriptor{"vdp_load_system_slot", "vdp_load_system_slot()", "Starts an async load of the system atlas into the system VRAM slot; returns a job id."},
	LuaBuiltinDescriptor{"vdp_blit_img_color", "vdp_blit_img_color(imgid, x, y, z, layer, scale_x, scale_y, flip_flags, color, parallax_weight)", "BIOS helper that translates an image id to raw VDP blit register/doorbell packets."},
	LuaBuiltinDescriptor{"vdp_glyph_color", "vdp_glyph_color(glyph, x, y, z, layer, color)", "BIOS helper that emits one raw VDP blit for an already-resolved glyph."},
	LuaBuiltinDescriptor{"vdp_img_rect", "vdp_img_rect(imgid)", "Returns the BIOS-owned atlas rectangle for an image id."},
	LuaBuiltinDescriptor{"vdp_img_slot", "vdp_img_slot(rect)", "Resolves a cached atlas rectangle to the current VDP slot."},
	LuaBuiltinDescriptor{"vdp_img_source", "vdp_img_source(rect)", "Resolves a cached atlas rectangle to a transient VDP slot/u/v/w/h source."},
	LuaBuiltinDescriptor{"vdp_write_source", "vdp_write_source(dst, rect)", "Writes current slot/u/v/w/h payload for a cached atlas rectangle."},
	LuaBuiltinDescriptor{"vdp_pmu_write_bank", "vdp_pmu_write_bank(bank, x, y, scale_x, scale_y, control)", "Programs a VDP PMU bank with raw Q16.16 offset/scale words and a control word."},
	LuaBuiltinDescriptor{"vdp_stream_claim", "vdp_stream_claim(count)", "Low-level software primitive that claims count raw VDP stream entries and returns the packet base address."},
	LuaBuiltinDescriptor{"vdp_stream_finish", "vdp_stream_finish()", "Appends the raw VDP stream terminator word when the frame stream is non-empty."},
	LuaBuiltinDescriptor{"vdp_clear_color", "vdp_clear_color(color)", "Emits raw VDP register/doorbell packets for a clear command."},
	LuaBuiltinDescriptor{"vdp_fill_rect_color", "vdp_fill_rect_color(x0, y0, x1, y1, z, layer, color)", "Emits raw VDP register/doorbell packets for a filled rectangle."},
	LuaBuiltinDescriptor{"vdp_draw_line_color", "vdp_draw_line_color(x0, y0, x1, y1, z, layer, color, thickness)", "Emits raw VDP register/doorbell packets for a line command."},
	LuaBuiltinDescriptor{"rom_data", "rom_data(id)", "Decodes a data entry from the active mapped ROM."},
	LuaBuiltinDescriptor{"irq", "irq(flags)", ""},
	LuaBuiltinDescriptor{"on_irq", "on_irq(mask [, handler])", "Registers a per-bit IRQ handler; pass nil as handler to clear it."},
	LuaBuiltinDescriptor{"on_vdp_load", "on_vdp_load(handler)", "Registers a VDP load notification callback."},
	LuaBuiltinDescriptor{"bool01", "bool01(value)", "Converts a Lua value to 0 or 1; falsy values become 0, truthy values become 1."},
	LuaBuiltinDescriptor{"clear_map", "clear_map(map)", "Clears all keys from a table-style map by setting each key to nil."},
	LuaBuiltinDescriptor{"deep_clone", "deep_clone(value)", "Recursively clones a Lua value, including tables. Note that this does not handle cycles and will error if a cycle is encountered."},
	LuaBuiltinDescriptor{"consume_axis_accum", "consume_axis_accum(accum, speed_num, speed_den)", ""},
	LuaBuiltinDescriptor{"set_velocity", "set_velocity(target, speed_x_num, speed_y_num, speed_den)", ""},
	LuaBuiltinDescriptor{"move_with_velocity", "move_with_velocity(target)", ""},
	LuaBuiltinDescriptor{"rect_overlaps", "rect_overlaps(ax, ay, aw, ah, bx, by, bw, bh)", ""},
	LuaBuiltinDescriptor{"clamp_int", "clamp_int(value, min_value, max_value)", ""},
	LuaBuiltinDescriptor{"div_toward_zero", "div_toward_zero(value, divisor)", ""},
	LuaBuiltinDescriptor{"round_to_nearest", "round_to_nearest(value)", ""},
	LuaBuiltinDescriptor{"rol8", "rol8(value)", ""},
	LuaBuiltinDescriptor{"swap_remove", "swap_remove(array, index)", ""},
	LuaBuiltinDescriptor{"objects_by_type", "objects_by_type(type_name)", "Returns an iterator over active world objects whose type_name matches."},
	LuaBuiltinDescriptor{"all_objects_by_type", "all_objects_by_type(type_name)", "Returns an iterator over all live world objects whose type_name matches."},
	LuaBuiltinDescriptor{"objects_by_tag", "objects_by_tag(tag)", "Returns an iterator over active world objects carrying the given tag."},
	LuaBuiltinDescriptor{"all_objects_by_tag", "all_objects_by_tag(tag)", "Returns an iterator over all live world objects carrying the given tag."},
	LuaBuiltinDescriptor{"find_by_type", "find_by_type(type_name)", "Returns the first active world object matching type_name, or nil."},
	LuaBuiltinDescriptor{"find_any_by_type", "find_any_by_type(type_name)", "Returns the first live world object matching type_name, or nil."},
	LuaBuiltinDescriptor{"find_by_tag", "find_by_tag(tag)", "Returns the first active world object carrying the given tag, or nil."},
	LuaBuiltinDescriptor{"find_any_by_tag", "find_any_by_tag(tag)", "Returns the first live world object carrying the given tag, or nil."},
}};

constexpr std::array<LuaBuiltinDescriptor, 4> kSystemLuaBuiltinGlobals{{
	LuaBuiltinDescriptor{"timeline", "timeline", "Timeline module table (timeline.new, timeline.range, timeline.expand_frames, timeline.build_frame_sequence, timeline.build_pingpong_frames)."},
	LuaBuiltinDescriptor{"eventemitter", "eventemitter", "Event emitter module table (eventemitter, events_of)."},
	LuaBuiltinDescriptor{"scratchbatch", "scratchbatch", "Scratch batch module table (scratchbatch.new; batches support clear, push, get, reserve, for_each, iter)."},
	LuaBuiltinDescriptor{"sorted_scratchbatch", "sorted_scratchbatch", "Sorted scratch batch module table (sorted_scratchbatch.new; batches support clear, push, get, reserve, for_each, iter, set_compare, sort)."},
}};

constexpr std::array<LuaBuiltinDescriptor, 514> kDefaultLuaBuiltinFunctions{{
	LuaBuiltinDescriptor{"assert", "assert(value [, message])", ""},
	LuaBuiltinDescriptor{"error", "error(message [, level])", ""},
	LuaBuiltinDescriptor{"getmetatable", "getmetatable(object)", ""},
	LuaBuiltinDescriptor{"ipairs", "ipairs(t)", ""},
	LuaBuiltinDescriptor{"next", "next(table [, index])", ""},
	LuaBuiltinDescriptor{"pairs", "pairs(t)", ""},
	LuaBuiltinDescriptor{"pcall", "pcall(f, ...)", ""},
	LuaBuiltinDescriptor{"print", "print(...)", ""},
	LuaBuiltinDescriptor{"loadstring", "loadstring(source [, chunkname])", "Compiles a restricted runtime Lua source subset into a chunk function; intended for small generated helpers."},
	LuaBuiltinDescriptor{"load", "load(source [, chunkname [, mode [, env]]])", "Compiles the same restricted runtime Lua source subset as loadstring; only text mode is supported."},
	LuaBuiltinDescriptor{"clock_now", "clock_now()", "Returns the current platform clock value."},
	LuaBuiltinDescriptor{"rawequal", "rawequal(v1, v2)", ""},
	LuaBuiltinDescriptor{"rawget", "rawget(table, index)", ""},
	LuaBuiltinDescriptor{"rawset", "rawset(table, index, value)", ""},
	LuaBuiltinDescriptor{"select", "select(index, ...)", ""},
	LuaBuiltinDescriptor{"setmetatable", "setmetatable(table, metatable)", ""},
	LuaBuiltinDescriptor{"tonumber", "tonumber(value [, base])", ""},
	LuaBuiltinDescriptor{"tostring", "tostring(value)", ""},
	LuaBuiltinDescriptor{"type", "type(value)", ""},
	LuaBuiltinDescriptor{"xpcall", "xpcall(f, msgh, ...)", ""},
	LuaBuiltinDescriptor{"require", "require(moduleName)", ""},
	LuaBuiltinDescriptor{"font_for_each_glyph", "font_for_each_glyph(font, line, fn)", "Runtime font helper that iterates UTF-8 glyph descriptors for a line."},
	LuaBuiltinDescriptor{"font_measure_line_width", "font_measure_line_width(font, line)", "Runtime font helper that measures a UTF-8 text line."},
	LuaBuiltinDescriptor{"table.concat", "table.concat(list [, sep [, i [, j]]])", ""},
	LuaBuiltinDescriptor{"table.insert", "table.insert(list [, pos], value)", ""},
	LuaBuiltinDescriptor{"table.pack", "table.pack(...)", ""},
	LuaBuiltinDescriptor{"table.remove", "table.remove(list [, pos])", ""},
	LuaBuiltinDescriptor{"table.sort", "table.sort(list [, comp])", ""},
	LuaBuiltinDescriptor{"table.unpack", "table.unpack(list [, i [, j]])", ""},
	LuaBuiltinDescriptor{"math.abs", "math.abs(x)", ""},
	LuaBuiltinDescriptor{"math.acos", "math.acos(x)", ""},
	LuaBuiltinDescriptor{"math.asin", "math.asin(x)", ""},
	LuaBuiltinDescriptor{"math.atan", "math.atan(y [, x])", ""},
	LuaBuiltinDescriptor{"math.ceil", "math.ceil(x)", ""},
	LuaBuiltinDescriptor{"math.cos", "math.cos(x)", ""},
	LuaBuiltinDescriptor{"math.deg", "math.deg(x)", ""},
	LuaBuiltinDescriptor{"math.exp", "math.exp(x)", ""},
	LuaBuiltinDescriptor{"math.floor", "math.floor(x)", ""},
	LuaBuiltinDescriptor{"math.fmod", "math.fmod(x, y)", ""},
	LuaBuiltinDescriptor{"math.log", "math.log(x [, base])", ""},
	LuaBuiltinDescriptor{"math.max", "math.max(x, ...)", ""},
	LuaBuiltinDescriptor{"math.min", "math.min(x, ...)", ""},
	LuaBuiltinDescriptor{"math.modf", "math.modf(x)", ""},
	LuaBuiltinDescriptor{"math.sin", "math.sin(x)", ""},
	LuaBuiltinDescriptor{"math.sign", "math.sign(x)", ""},
	LuaBuiltinDescriptor{"math.random", "math.random([m [, n]])", ""},
	LuaBuiltinDescriptor{"math.randomseed", "math.randomseed([seed])", ""},
	LuaBuiltinDescriptor{"math.sqrt", "math.sqrt(x)", ""},
	LuaBuiltinDescriptor{"math.rad", "math.rad(x)", ""},
	LuaBuiltinDescriptor{"math.tan", "math.tan(x)", ""},
	LuaBuiltinDescriptor{"math.tointeger", "math.tointeger(x)", ""},
	LuaBuiltinDescriptor{"math.type", "math.type(x)", ""},
	LuaBuiltinDescriptor{"math.ult", "math.ult(m, n)", ""},
	LuaBuiltinDescriptor{"math.huge", "math.huge", ""},
	LuaBuiltinDescriptor{"math.maxinteger", "math.maxinteger", ""},
	LuaBuiltinDescriptor{"math.mininteger", "math.mininteger", ""},
	LuaBuiltinDescriptor{"easing.linear", "easing.linear(t)", ""},
	LuaBuiltinDescriptor{"easing.ease_in_quad", "easing.ease_in_quad(t)", ""},
	LuaBuiltinDescriptor{"easing.ease_out_quad", "easing.ease_out_quad(t)", ""},
	LuaBuiltinDescriptor{"easing.ease_in_out_quad", "easing.ease_in_out_quad(t)", ""},
	LuaBuiltinDescriptor{"easing.ease_out_back", "easing.ease_out_back(t)", ""},
	LuaBuiltinDescriptor{"easing.smoothstep", "easing.smoothstep(t)", ""},
	LuaBuiltinDescriptor{"easing.pingpong01", "easing.pingpong01(t)", ""},
	LuaBuiltinDescriptor{"easing.arc01", "easing.arc01(t)", ""},
	LuaBuiltinDescriptor{"string.byte", "string.byte(s [, i])", ""},
	LuaBuiltinDescriptor{"string.char", "string.char(...)", ""},
	LuaBuiltinDescriptor{"string.find", "string.find(s, pattern [, init])", ""},
	LuaBuiltinDescriptor{"string.match", "string.match(s, pattern [, init])", ""},
	LuaBuiltinDescriptor{"string.gsub", "string.gsub(s, pattern, repl [, n])", ""},
	LuaBuiltinDescriptor{"string.gmatch", "string.gmatch(s, pattern)", ""},
	LuaBuiltinDescriptor{"string.format", "string.format(format, ...)", ""},
	LuaBuiltinDescriptor{"string.pack", "string.pack(format, ...)", ""},
	LuaBuiltinDescriptor{"string.packsize", "string.packsize(format)", ""},
	LuaBuiltinDescriptor{"string.unpack", "string.unpack(format, s [, pos])", ""},
	LuaBuiltinDescriptor{"string.len", "string.len(s)", ""},
	LuaBuiltinDescriptor{"string.lower", "string.lower(s)", ""},
	LuaBuiltinDescriptor{"string.rep", "string.rep(s, n [, sep])", ""},
	LuaBuiltinDescriptor{"string.sub", "string.sub(s, i [, j])", ""},
	LuaBuiltinDescriptor{"string.upper", "string.upper(s)", ""},
	LuaBuiltinDescriptor{"array", "array(...)", "Returns a Lua array table containing the provided values."},
	LuaBuiltinDescriptor{"wrap_text_lines", "wrap_text_lines(text, max_chars [, first_prefix [, next_prefix]])", "Wraps UTF-8 text on word boundaries when possible and hard-wraps long words while preserving code points."},
	LuaBuiltinDescriptor{"u32_to_f32", "u32_to_f32(value)", "Reinterprets a 32-bit unsigned integer bit pattern as a float32."},
	LuaBuiltinDescriptor{"u64_to_f64", "u64_to_f64(high, low)", "Reinterprets a pair of 32-bit unsigned integers as a float64 bit pattern."},
	LuaBuiltinDescriptor{"os.clock", "os.clock()", ""},
	LuaBuiltinDescriptor{"os.date", "os.date([format [, time]])", ""},
	LuaBuiltinDescriptor{"os.difftime", "os.difftime(t2 [, t1])", ""},
	LuaBuiltinDescriptor{"os.time", "os.time([table])", ""},
	LuaBuiltinDescriptor{"$", "$", "Native host core object."},
	LuaBuiltinDescriptor{"devtools", "devtools", "Devtool-only runtime source inspection table (devtools.list_lua_resources, devtools.get_lua_entry_path, devtools.get_lua_resource_source)."},
	LuaBuiltinDescriptor{"cart_manifest", "cart_manifest", "Flattened cart manifest table, or nil when unavailable."},
	LuaBuiltinDescriptor{"machine_manifest", "machine_manifest", "Flattened machine manifest table."},
	LuaBuiltinDescriptor{"cart_project_root_path", "cart_project_root_path", "Workspace-relative cart project root path, or nil when unavailable."},
	LuaBuiltinDescriptor{"memwrite", "memwrite(base, ...)", "Reserved compiler intrinsic for burst word writes. Lowers directly to a memory-write opcode and is not a first-class Lua value."},
	LuaBuiltinDescriptor{"mem", "mem[addr]", "Reserved memory-mapped 32-bit word space for direct `mem[addr]` reads/writes. Not a first-class Lua value. Invalid or read-only writes raise a fault."},
	LuaBuiltinDescriptor{"mem8", "mem8[addr]", "Reserved memory-mapped byte space for direct `mem8[addr]` reads/writes. Not a first-class Lua value."},
	LuaBuiltinDescriptor{"mem16le", "mem16le[addr]", "Reserved memory-mapped little-endian 16-bit space for direct `mem16le[addr]` reads/writes. Not a first-class Lua value."},
	LuaBuiltinDescriptor{"mem32le", "mem32le[addr]", "Reserved memory-mapped little-endian 32-bit space for direct `mem32le[addr]` reads/writes. Not a first-class Lua value."},
	LuaBuiltinDescriptor{"memf32le", "memf32le[addr]", "Reserved memory-mapped little-endian 32-bit float space for direct `memf32le[addr]` reads/writes. Not a first-class Lua value. Invalid or read-only writes raise a fault."},
	LuaBuiltinDescriptor{"memf64le", "memf64le[addr]", "Reserved memory-mapped little-endian 64-bit float space for direct `memf64le[addr]` reads/writes. Not a first-class Lua value. Invalid or read-only writes raise a fault."},
	LuaBuiltinDescriptor{"sys_boot_cart", "sys_boot_cart", "System register address; write 1 to boot the cart."},
	LuaBuiltinDescriptor{"sys_bus_fault_code", "sys_bus_fault_code", "System register address; sticky mapped bus fault code."},
	LuaBuiltinDescriptor{"sys_bus_fault_addr", "sys_bus_fault_addr", "System register address; address captured for the first sticky mapped bus fault."},
	LuaBuiltinDescriptor{"sys_bus_fault_access", "sys_bus_fault_access", "System register address; access flags captured for the first sticky mapped bus fault."},
	LuaBuiltinDescriptor{"sys_bus_fault_ack", "sys_bus_fault_ack", "System register address; write nonzero to clear the sticky mapped bus fault."},
	LuaBuiltinDescriptor{"sys_bus_fault_none", "sys_bus_fault_none", "Bus fault code meaning no bus fault is latched."},
	LuaBuiltinDescriptor{"sys_bus_fault_unmapped", "sys_bus_fault_unmapped", "Bus fault code for an unmapped mapped-memory access."},
	LuaBuiltinDescriptor{"sys_bus_fault_unaligned_io", "sys_bus_fault_unaligned_io", "Bus fault code for a non-word I/O mapped-memory access."},
	LuaBuiltinDescriptor{"sys_bus_fault_read_only", "sys_bus_fault_read_only", "Bus fault code for a mapped-memory write to a read-only I/O register."},
	LuaBuiltinDescriptor{"sys_bus_fault_vram_range", "sys_bus_fault_vram_range", "Bus fault code for a mapped VRAM access that is not contained in the VRAM aperture."},
	LuaBuiltinDescriptor{"sys_bus_fault_access_read", "sys_bus_fault_access_read", "Bus fault access flag for reads."},
	LuaBuiltinDescriptor{"sys_bus_fault_access_write", "sys_bus_fault_access_write", "Bus fault access flag for writes."},
	LuaBuiltinDescriptor{"sys_bus_fault_access_u8", "sys_bus_fault_access_u8", "Bus fault access flag for byte accesses."},
	LuaBuiltinDescriptor{"sys_bus_fault_access_u16", "sys_bus_fault_access_u16", "Bus fault access flag for little-endian 16-bit accesses."},
	LuaBuiltinDescriptor{"sys_bus_fault_access_u32", "sys_bus_fault_access_u32", "Bus fault access flag for little-endian 32-bit accesses."},
	LuaBuiltinDescriptor{"sys_bus_fault_access_word", "sys_bus_fault_access_word", "Bus fault access flag for Lua word accesses."},
	LuaBuiltinDescriptor{"sys_bus_fault_access_f32", "sys_bus_fault_access_f32", "Bus fault access flag for little-endian 32-bit float accesses."},
	LuaBuiltinDescriptor{"sys_bus_fault_access_f64", "sys_bus_fault_access_f64", "Bus fault access flag for little-endian 64-bit float accesses."},
	LuaBuiltinDescriptor{"sys_host_fault_flags", "sys_host_fault_flags", "System register address; sticky host fault flags published by the host runtime during startup."},
	LuaBuiltinDescriptor{"sys_host_fault_stage", "sys_host_fault_stage", "System register address; host-defined startup fault stage code."},
	LuaBuiltinDescriptor{"sys_host_fault_flag_active", "sys_host_fault_flag_active", "Host fault flag bit indicating that a host fault is currently published."},
	LuaBuiltinDescriptor{"sys_host_fault_flag_startup_blocking", "sys_host_fault_flag_startup_blocking", "Host fault flag bit indicating that the published fault should block startup."},
	LuaBuiltinDescriptor{"sys_host_fault_stage_none", "sys_host_fault_stage_none", "Host fault stage constant meaning no stage is active."},
	LuaBuiltinDescriptor{"sys_host_fault_stage_startup_refresh", "sys_host_fault_stage_startup_refresh", "Host fault stage constant for deferred startup audio refresh failures."},
	LuaBuiltinDescriptor{"sys_host_fault_message", "sys_host_fault_message()", "Returns the current published host fault message as a string, or nil if no host fault message is present."},
	LuaBuiltinDescriptor{"sys_cart_magic_addr", "sys_cart_magic_addr", "Cart ROM magic header address."},
	LuaBuiltinDescriptor{"sys_cart_magic", "sys_cart_magic", "Cart ROM magic header value."},
	LuaBuiltinDescriptor{"sys_cart_rom_size", "sys_cart_rom_size", "Maximum cart ROM size in bytes."},
	LuaBuiltinDescriptor{"sys_ram_size", "sys_ram_size", "Total system RAM size in bytes."},
	LuaBuiltinDescriptor{"sys_max_cycles_per_frame", "sys_max_cycles_per_frame", "Maximum cycles per frame."},
	LuaBuiltinDescriptor{"sys_vdp_dither", "sys_vdp_dither", "VDP dither register; write to this register to control dithering. Values 0=off, 1=PSX, 2=RGB777 output, 3=MSX10"},
	LuaBuiltinDescriptor{"sys_vdp_cmd", "sys_vdp_cmd", "VDP submit register; write a command opcode here after filling the argument bank."},
	LuaBuiltinDescriptor{"sys_vdp_cmd_arg_count", "sys_vdp_cmd_arg_count", "Number of VDP command argument slots."},
	LuaBuiltinDescriptor{"sys_vdp_arg_stride", "sys_vdp_arg_stride", "Word stride between VDP command payload slots."},
	LuaBuiltinDescriptor{"sys_vdp_stream_base", "sys_vdp_stream_base", "RAM base address of the CPU-side VDP command stream buffer."},
	LuaBuiltinDescriptor{"sys_vdp_stream_capacity", "sys_vdp_stream_capacity", "Capacity of the CPU-side VDP command stream buffer."},
	LuaBuiltinDescriptor{"sys_vdp_fifo", "sys_vdp_fifo", "VDP command FIFO write port for direct CPU or DMA streaming."},
	LuaBuiltinDescriptor{"sys_vdp_fifo_ctrl", "sys_vdp_fifo_ctrl", "VDP FIFO control register; write sys_vdp_fifo_ctrl_seal to seal a direct CPU FIFO stream."},
	LuaBuiltinDescriptor{"sys_vdp_fifo_ctrl_seal", "sys_vdp_fifo_ctrl_seal", "VDP FIFO control bit that seals the currently accumulated direct CPU FIFO stream."},
	LuaBuiltinDescriptor{"sys_vdp_pmu_bank", "sys_vdp_pmu_bank", "VDP PMU bank select register."},
	LuaBuiltinDescriptor{"sys_vdp_pmu_x", "sys_vdp_pmu_x", "VDP PMU selected-bank X offset register in signed Q16.16."},
	LuaBuiltinDescriptor{"sys_vdp_pmu_y", "sys_vdp_pmu_y", "VDP PMU selected-bank Y offset register in signed Q16.16."},
	LuaBuiltinDescriptor{"sys_vdp_pmu_scale_x", "sys_vdp_pmu_scale_x", "VDP PMU selected-bank X scale register in signed Q16.16."},
	LuaBuiltinDescriptor{"sys_vdp_pmu_scale_y", "sys_vdp_pmu_scale_y", "VDP PMU selected-bank Y scale register in signed Q16.16."},
	LuaBuiltinDescriptor{"sys_vdp_pmu_ctrl", "sys_vdp_pmu_ctrl", "VDP PMU selected-bank control register."},
	LuaBuiltinDescriptor{"sys_vdp_sbx_control", "sys_vdp_sbx_control", "VDP skybox control register; bit 0 enables SBX sampling."},
	LuaBuiltinDescriptor{"sys_vdp_sbx_faces", "sys_vdp_sbx_faces", "Base address of the VDP skybox face source register window."},
	LuaBuiltinDescriptor{"sys_vdp_sbx_commit", "sys_vdp_sbx_commit", "VDP skybox commit doorbell register."},
	LuaBuiltinDescriptor{"sys_vdp_sbx_commit_write", "sys_vdp_sbx_commit_write", "VDP skybox commit bit."},
	LuaBuiltinDescriptor{"sys_vdp_slot_primary_atlas", "sys_vdp_slot_primary_atlas", "VDP MMIO word containing the atlas id currently resident in the primary slot."},
	LuaBuiltinDescriptor{"sys_vdp_slot_secondary_atlas", "sys_vdp_slot_secondary_atlas", "VDP MMIO word containing the atlas id currently resident in the secondary slot."},
	LuaBuiltinDescriptor{"sys_vdp_atlas_none", "sys_vdp_atlas_none", "Sentinel atlas id meaning no atlas is resident in a VDP slot."},
	LuaBuiltinDescriptor{"sys_vdp_slot_primary", "sys_vdp_slot_primary", "VDP primary source slot id."},
	LuaBuiltinDescriptor{"sys_vdp_slot_secondary", "sys_vdp_slot_secondary", "VDP secondary source slot id."},
	LuaBuiltinDescriptor{"sys_vdp_slot_system", "sys_vdp_slot_system", "VDP system source slot id."},
	LuaBuiltinDescriptor{"sys_vdp_slot_none", "sys_vdp_slot_none", "Sentinel slot id meaning no source."},
	LuaBuiltinDescriptor{"sys_vdp_rd_surface", "sys_vdp_rd_surface", "VDP readback surface selector (0=system, 1=primary, 2=secondary)."},
	LuaBuiltinDescriptor{"sys_vdp_rd_x", "sys_vdp_rd_x", "VDP readback X coordinate (pixels)."},
	LuaBuiltinDescriptor{"sys_vdp_rd_y", "sys_vdp_rd_y", "VDP readback Y coordinate (pixels)."},
	LuaBuiltinDescriptor{"sys_vdp_rd_mode", "sys_vdp_rd_mode", "VDP readback mode register (0=RGBA8888)."},
	LuaBuiltinDescriptor{"sys_vdp_rd_status", "sys_vdp_rd_status", "VDP readback status register; READY/OVERFLOW bits."},
	LuaBuiltinDescriptor{"sys_vdp_rd_data", "sys_vdp_rd_data", "VDP readback data register; read RGBA8888 per access."},
	LuaBuiltinDescriptor{"sys_vdp_status", "sys_vdp_status", "VDP status register; read submit/vblank/fault bits."},
	LuaBuiltinDescriptor{"sys_vdp_fault_code", "sys_vdp_fault_code", "VDP fault-code register for cart-visible device faults."},
	LuaBuiltinDescriptor{"sys_vdp_fault_detail", "sys_vdp_fault_detail", "VDP fault-detail register for cart-visible device faults."},
	LuaBuiltinDescriptor{"sys_vdp_rd_mode_rgba8888", "sys_vdp_rd_mode_rgba8888", "VDP readback mode constant for RGBA8888."},
	LuaBuiltinDescriptor{"sys_vdp_rd_status_ready", "sys_vdp_rd_status_ready", "VDP readback status bit: ready."},
	LuaBuiltinDescriptor{"sys_vdp_rd_status_overflow", "sys_vdp_rd_status_overflow", "VDP readback status bit: overflow."},
	LuaBuiltinDescriptor{"sys_vdp_status_vblank", "sys_vdp_status_vblank", "VDP status bit: VBLANK level."},
	LuaBuiltinDescriptor{"sys_vdp_status_submit_busy", "sys_vdp_status_submit_busy", "VDP status bit: submit path busy."},
	LuaBuiltinDescriptor{"sys_vdp_status_submit_rejected", "sys_vdp_status_submit_rejected", "VDP status bit: most recent submit attempt was rejected."},
	LuaBuiltinDescriptor{"sys_vdp_status_fault", "sys_vdp_status_fault", "VDP status bit: a cart-visible device fault is latched."},
	LuaBuiltinDescriptor{"sys_vdp_fault_none", "sys_vdp_fault_none", "VDP fault code: no fault."},
	LuaBuiltinDescriptor{"sys_vdp_fault_rd_unsupported_mode", "sys_vdp_fault_rd_unsupported_mode", "VDP fault code: unsupported readback mode."},
	LuaBuiltinDescriptor{"sys_vdp_fault_rd_surface", "sys_vdp_fault_rd_surface", "VDP fault code: readback surface is not visible to the device."},
	LuaBuiltinDescriptor{"sys_vdp_fault_rd_oob", "sys_vdp_fault_rd_oob", "VDP fault code: readback coordinate is outside the selected surface."},
	LuaBuiltinDescriptor{"sys_vdp_fault_vram_write_unmapped", "sys_vdp_fault_vram_write_unmapped", "VDP fault code: VRAM write address has no mapped slot."},
	LuaBuiltinDescriptor{"sys_vdp_fault_vram_write_uninitialized", "sys_vdp_fault_vram_write_uninitialized", "VDP fault code: VRAM write hit an uninitialized slot."},
	LuaBuiltinDescriptor{"sys_vdp_fault_vram_write_oob", "sys_vdp_fault_vram_write_oob", "VDP fault code: VRAM write exceeds the selected slot surface."},
	LuaBuiltinDescriptor{"sys_vdp_fault_vram_write_unaligned", "sys_vdp_fault_vram_write_unaligned", "VDP fault code: VRAM write is not 32-bit aligned."},
	LuaBuiltinDescriptor{"sys_vdp_fault_vram_slot_dim", "sys_vdp_fault_vram_slot_dim", "VDP fault code: VRAM slot dimension register cannot be applied."},
	LuaBuiltinDescriptor{"sys_vdp_fault_stream_bad_packet", "sys_vdp_fault_stream_bad_packet", "VDP fault code: FIFO/DMA packet stream is malformed."},
	LuaBuiltinDescriptor{"sys_vdp_fault_submit_state", "sys_vdp_fault_submit_state", "VDP fault code: direct command doorbell does not match submit state."},
	LuaBuiltinDescriptor{"sys_vdp_fault_cmd_bad_doorbell", "sys_vdp_fault_cmd_bad_doorbell", "VDP fault code: command doorbell opcode is not implemented."},
	LuaBuiltinDescriptor{"sys_vdp_fault_submit_busy", "sys_vdp_fault_submit_busy", "VDP fault code: submit path rejected work while busy."},
	LuaBuiltinDescriptor{"sys_vdp_fault_dex_invalid_scale", "sys_vdp_fault_dex_invalid_scale", "VDP fault code: DEX blit scale is invalid."},
	LuaBuiltinDescriptor{"sys_vdp_fault_dex_invalid_line_width", "sys_vdp_fault_dex_invalid_line_width", "VDP fault code: DEX line width is invalid."},
	LuaBuiltinDescriptor{"sys_vdp_fault_dex_source_slot", "sys_vdp_fault_dex_source_slot", "VDP fault code: DEX source slot is not sampleable."},
	LuaBuiltinDescriptor{"sys_vdp_fault_dex_source_oob", "sys_vdp_fault_dex_source_oob", "VDP fault code: DEX source rectangle is zero-sized or out of bounds."},
	LuaBuiltinDescriptor{"sys_vdp_fault_sbx_source_oob", "sys_vdp_fault_sbx_source_oob", "VDP fault code: SBX source rectangle is outside its surface."},
	LuaBuiltinDescriptor{"sys_vdp_fault_bbu_zero_size", "sys_vdp_fault_bbu_zero_size", "VDP fault code: BBU billboard size is zero."},
	LuaBuiltinDescriptor{"sys_vdp_fault_bbu_overflow", "sys_vdp_fault_bbu_overflow", "VDP fault code: BBU billboard FIFO is full."},
	LuaBuiltinDescriptor{"sys_vdp_fault_bbu_source_oob", "sys_vdp_fault_bbu_source_oob", "VDP fault code: BBU source rectangle is outside its surface."},
	LuaBuiltinDescriptor{"sys_vdp_layer_world", "sys_vdp_layer_world", "VDP layer id for world-space rendering."},
	LuaBuiltinDescriptor{"sys_vdp_layer_ui", "sys_vdp_layer_ui", "VDP layer id for UI rendering."},
	LuaBuiltinDescriptor{"sys_vdp_layer_ide", "sys_vdp_layer_ide", "VDP layer id for IDE/overlay rendering."},
	LuaBuiltinDescriptor{"sys_irq_flags", "sys_irq_flags", "IRQ flags register address; read pending IRQ bits."},
	LuaBuiltinDescriptor{"sys_irq_ack", "sys_irq_ack", "IRQ acknowledge register address; write bits to clear."},
	LuaBuiltinDescriptor{"sys_dma_src", "sys_dma_src", "DMA source address register."},
	LuaBuiltinDescriptor{"sys_dma_dst", "sys_dma_dst", "DMA destination address register."},
	LuaBuiltinDescriptor{"sys_dma_len", "sys_dma_len", "DMA transfer length in bytes."},
	LuaBuiltinDescriptor{"sys_dma_ctrl", "sys_dma_ctrl", "DMA control register; write dma_ctrl_start to begin."},
	LuaBuiltinDescriptor{"sys_dma_status", "sys_dma_status", "DMA status register; busy/done/error/clipped/rejected bits."},
	LuaBuiltinDescriptor{"sys_dma_written", "sys_dma_written", "DMA written byte count register."},
	LuaBuiltinDescriptor{"sys_geo_scratch_base", "sys_geo_scratch_base", "Geometry scratch RAM base address."},
	LuaBuiltinDescriptor{"sys_geo_scratch_size", "sys_geo_scratch_size", "Geometry scratch RAM size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_src0", "sys_geo_src0", "GEO source pointer register 0."},
	LuaBuiltinDescriptor{"sys_geo_src1", "sys_geo_src1", "GEO source pointer register 1."},
	LuaBuiltinDescriptor{"sys_geo_src2", "sys_geo_src2", "GEO source pointer register 2."},
	LuaBuiltinDescriptor{"sys_geo_dst0", "sys_geo_dst0", "GEO destination pointer register 0."},
	LuaBuiltinDescriptor{"sys_geo_dst1", "sys_geo_dst1", "GEO destination pointer register 1."},
	LuaBuiltinDescriptor{"sys_geo_count", "sys_geo_count", "GEO record count register."},
	LuaBuiltinDescriptor{"sys_geo_cmd", "sys_geo_cmd", "GEO command doorbell register; write after staging operands."},
	LuaBuiltinDescriptor{"sys_geo_ctrl", "sys_geo_ctrl", "GEO control register; abort-only."},
	LuaBuiltinDescriptor{"sys_geo_status", "sys_geo_status", "GEO status register; busy/done/error/rejected bits."},
	LuaBuiltinDescriptor{"sys_geo_param0", "sys_geo_param0", "GEO command parameter register 0."},
	LuaBuiltinDescriptor{"sys_geo_param1", "sys_geo_param1", "GEO command parameter register 1."},
	LuaBuiltinDescriptor{"sys_geo_stride0", "sys_geo_stride0", "GEO byte stride register for src0."},
	LuaBuiltinDescriptor{"sys_geo_stride1", "sys_geo_stride1", "GEO byte stride register for src1."},
	LuaBuiltinDescriptor{"sys_geo_stride2", "sys_geo_stride2", "GEO byte stride register for src2."},
	LuaBuiltinDescriptor{"sys_geo_processed", "sys_geo_processed", "GEO processed record count register."},
	LuaBuiltinDescriptor{"sys_geo_fault", "sys_geo_fault", "GEO fault register: high 16 bits code, low 16 bits record index."},
	LuaBuiltinDescriptor{"sys_geo_fault_ack", "sys_geo_fault_ack", "GEO fault acknowledge register; write one to clear the fault latch."},
	LuaBuiltinDescriptor{"sys_img_src", "sys_img_src", "IMGDEC source address register."},
	LuaBuiltinDescriptor{"sys_img_len", "sys_img_len", "IMGDEC source length in bytes."},
	LuaBuiltinDescriptor{"sys_img_dst", "sys_img_dst", "IMGDEC destination address register."},
	LuaBuiltinDescriptor{"sys_img_cap", "sys_img_cap", "IMGDEC destination capacity in bytes."},
	LuaBuiltinDescriptor{"sys_img_ctrl", "sys_img_ctrl", "IMGDEC control register; write img_ctrl_start to begin."},
	LuaBuiltinDescriptor{"sys_img_status", "sys_img_status", "IMGDEC status register; busy/done/error bits."},
	LuaBuiltinDescriptor{"sys_img_written", "sys_img_written", "IMGDEC written byte count register."},
	LuaBuiltinDescriptor{"sys_inp_player", "sys_inp_player", "Input Controller player index register (1-based)."},
	LuaBuiltinDescriptor{"sys_inp_action", "sys_inp_action", "Input Controller action-name register; write an action-name string before inp_ctrl_commit."},
	LuaBuiltinDescriptor{"sys_inp_bind", "sys_inp_bind", "Input Controller binding register; write comma-separated button names as a string."},
	LuaBuiltinDescriptor{"sys_inp_ctrl", "sys_inp_ctrl", "Input Controller command register; write inp_ctrl_commit, inp_ctrl_arm, or inp_ctrl_reset."},
	LuaBuiltinDescriptor{"sys_inp_query", "sys_inp_query", "Input Controller query register; write an action expression such as left[p] or jump[jp]."},
	LuaBuiltinDescriptor{"sys_inp_status", "sys_inp_status", "Input Controller query status register; simple action queries return packed inp_status_* bits, complex expressions return 1 or 0."},
	LuaBuiltinDescriptor{"sys_inp_value", "sys_inp_value", "Input Controller value register for simple single-action queries in signed Q16.16."},
	LuaBuiltinDescriptor{"sys_inp_consume", "sys_inp_consume", "Input Controller consume register; write an action name or comma-separated action names string to consume them in order."},
	LuaBuiltinDescriptor{"sys_inp_event_status", "sys_inp_event_status", "Input Controller event FIFO status register."},
	LuaBuiltinDescriptor{"sys_inp_event_count", "sys_inp_event_count", "Input Controller event FIFO queued-entry count register."},
	LuaBuiltinDescriptor{"sys_inp_event_player", "sys_inp_event_player", "Input Controller front-event player register."},
	LuaBuiltinDescriptor{"sys_inp_event_action", "sys_inp_event_action", "Input Controller front-event action string reference register."},
	LuaBuiltinDescriptor{"sys_inp_event_flags", "sys_inp_event_flags", "Input Controller front-event packed inp_status_* flags register."},
	LuaBuiltinDescriptor{"sys_inp_event_value", "sys_inp_event_value", "Input Controller front-event signed Q16.16 value register."},
	LuaBuiltinDescriptor{"sys_inp_event_repeat_count", "sys_inp_event_repeat_count", "Input Controller front-event repeat count register."},
	LuaBuiltinDescriptor{"sys_inp_event_ctrl", "sys_inp_event_ctrl", "Input Controller event FIFO control register; write inp_event_ctrl_pop or inp_event_ctrl_clear."},
	LuaBuiltinDescriptor{"sys_apu_source_addr", "sys_apu_source_addr", "APU audio source address register."},
	LuaBuiltinDescriptor{"sys_apu_source_bytes", "sys_apu_source_bytes", "APU audio source byte length register."},
	LuaBuiltinDescriptor{"sys_apu_source_sample_rate_hz", "sys_apu_source_sample_rate_hz", "APU audio source sample rate register."},
	LuaBuiltinDescriptor{"sys_apu_source_channels", "sys_apu_source_channels", "APU audio source channel count register."},
	LuaBuiltinDescriptor{"sys_apu_source_bits_per_sample", "sys_apu_source_bits_per_sample", "APU audio source bit depth register."},
	LuaBuiltinDescriptor{"sys_apu_source_frame_count", "sys_apu_source_frame_count", "APU audio source frame count register."},
	LuaBuiltinDescriptor{"sys_apu_source_data_offset", "sys_apu_source_data_offset", "APU encoded audio data offset register."},
	LuaBuiltinDescriptor{"sys_apu_source_data_bytes", "sys_apu_source_data_bytes", "APU encoded audio data byte length register."},
	LuaBuiltinDescriptor{"sys_apu_source_loop_start_sample", "sys_apu_source_loop_start_sample", "APU loop start sample register."},
	LuaBuiltinDescriptor{"sys_apu_source_loop_end_sample", "sys_apu_source_loop_end_sample", "APU loop end sample register."},
	LuaBuiltinDescriptor{"sys_apu_slot", "sys_apu_slot", "APU hardware slot register."},
	LuaBuiltinDescriptor{"sys_apu_rate_step_q16", "sys_apu_rate_step_q16", "APU playback step register in Q16.16; apu_rate_step_q16_one means normal speed."},
	LuaBuiltinDescriptor{"sys_apu_gain_q12", "sys_apu_gain_q12", "APU gain register in Q12 fixed point; apu_gain_q12_one means unity gain."},
	LuaBuiltinDescriptor{"sys_apu_start_sample", "sys_apu_start_sample", "APU start offset register in source samples."},
	LuaBuiltinDescriptor{"sys_apu_filter_kind", "sys_apu_filter_kind", "APU filter type register."},
	LuaBuiltinDescriptor{"sys_apu_filter_freq_hz", "sys_apu_filter_freq_hz", "APU filter frequency register in Hz."},
	LuaBuiltinDescriptor{"sys_apu_filter_q_milli", "sys_apu_filter_q_milli", "APU filter Q register in milli-units."},
	LuaBuiltinDescriptor{"sys_apu_filter_gain_millidb", "sys_apu_filter_gain_millidb", "APU filter gain register in milli-decibels."},
	LuaBuiltinDescriptor{"sys_apu_fade_samples", "sys_apu_fade_samples", "APU STOP_SLOT fade duration register in samples at apu_sample_rate_hz."},
	LuaBuiltinDescriptor{"sys_apu_generator_kind", "sys_apu_generator_kind", "APU internal generator kind register; apu_generator_none selects source-DMA playback."},
	LuaBuiltinDescriptor{"sys_apu_generator_duty_q12", "sys_apu_generator_duty_q12", "APU square-generator duty cycle in Q12 fixed point."},
	LuaBuiltinDescriptor{"sys_apu_cmd", "sys_apu_cmd", "APU command doorbell register."},
	LuaBuiltinDescriptor{"sys_apu_status", "sys_apu_status", "APU status register."},
	LuaBuiltinDescriptor{"sys_apu_fault_code", "sys_apu_fault_code", "APU sticky fault-code register."},
	LuaBuiltinDescriptor{"sys_apu_fault_detail", "sys_apu_fault_detail", "APU sticky fault-detail register."},
	LuaBuiltinDescriptor{"sys_apu_fault_ack", "sys_apu_fault_ack", "APU write-one-to-clear sticky fault register."},
	LuaBuiltinDescriptor{"sys_apu_event_kind", "sys_apu_event_kind", "APU event kind register."},
	LuaBuiltinDescriptor{"sys_apu_event_slot", "sys_apu_event_slot", "APU event slot register."},
	LuaBuiltinDescriptor{"sys_apu_event_source_addr", "sys_apu_event_source_addr", "APU event source address register."},
	LuaBuiltinDescriptor{"sys_apu_event_seq", "sys_apu_event_seq", "APU event sequence register."},
	LuaBuiltinDescriptor{"sys_apu_selected_source_addr", "sys_apu_selected_source_addr", "APU active selected-slot source-address register."},
	LuaBuiltinDescriptor{"sys_apu_active_mask", "sys_apu_active_mask", "APU active hardware slot mask register."},
	LuaBuiltinDescriptor{"sys_apu_selected_slot_regs", "sys_apu_selected_slot_regs", "APU selected-slot raw parameter latch read/write window."},
	LuaBuiltinDescriptor{"sys_apu_selected_slot_reg_count", "sys_apu_selected_slot_reg_count", "APU selected-slot raw parameter latch read/write word count."},
	LuaBuiltinDescriptor{"sys_apu_output_queued_frames", "sys_apu_output_queued_frames", "APU AOUT output-ring queued-frame readback register."},
	LuaBuiltinDescriptor{"sys_apu_output_free_frames", "sys_apu_output_free_frames", "APU AOUT output-ring free-frame readback register."},
	LuaBuiltinDescriptor{"sys_apu_output_capacity_frames", "sys_apu_output_capacity_frames", "APU AOUT output-ring capacity readback register."},
	LuaBuiltinDescriptor{"sys_apu_cmd_queued", "sys_apu_cmd_queued", "APU command FIFO queued-command readback register."},
	LuaBuiltinDescriptor{"sys_apu_cmd_free", "sys_apu_cmd_free", "APU command FIFO free-entry readback register."},
	LuaBuiltinDescriptor{"sys_apu_cmd_capacity", "sys_apu_cmd_capacity", "APU command FIFO capacity readback register."},
	LuaBuiltinDescriptor{"sys_rom_system_base", "sys_rom_system_base", "System ROM base address."},
	LuaBuiltinDescriptor{"sys_rom_cart_base", "sys_rom_cart_base", "Cart ROM base address."},
	LuaBuiltinDescriptor{"sys_rom_overlay_base", "sys_rom_overlay_base", "Overlay ROM base address."},
	LuaBuiltinDescriptor{"sys_rom_overlay_size", "sys_rom_overlay_size", "Overlay ROM size in bytes."},
	LuaBuiltinDescriptor{"sys_vram_system_slot_base", "sys_vram_system_slot_base", "VRAM system slot base address."},
	LuaBuiltinDescriptor{"sys_vram_primary_slot_base", "sys_vram_primary_slot_base", "VRAM primary slot slot base address."},
	LuaBuiltinDescriptor{"sys_vram_secondary_slot_base", "sys_vram_secondary_slot_base", "VRAM secondary slot slot base address."},
	LuaBuiltinDescriptor{"sys_vram_framebuffer_base", "sys_vram_framebuffer_base", "VRAM framebuffer base address."},
	LuaBuiltinDescriptor{"sys_vram_staging_base", "sys_vram_staging_base", "VRAM staging buffer base address."},
	LuaBuiltinDescriptor{"sys_vram_system_slot_size", "sys_vram_system_slot_size", "VRAM system slot size in bytes."},
	LuaBuiltinDescriptor{"sys_vram_primary_slot_size", "sys_vram_primary_slot_size", "VRAM primary slot slot size in bytes."},
	LuaBuiltinDescriptor{"sys_vram_secondary_slot_size", "sys_vram_secondary_slot_size", "VRAM secondary slot slot size in bytes."},
	LuaBuiltinDescriptor{"sys_vram_framebuffer_size", "sys_vram_framebuffer_size", "VRAM framebuffer size in bytes."},
	LuaBuiltinDescriptor{"sys_vram_staging_size", "sys_vram_staging_size", "VRAM staging buffer size in bytes."},
	LuaBuiltinDescriptor{"sys_vram_size", "sys_vram_size", "Tracked total VRAM capacity in bytes."},
	LuaBuiltinDescriptor{"irq_dma_done", "irq_dma_done", "IRQ flag for DMA completion."},
	LuaBuiltinDescriptor{"irq_dma_error", "irq_dma_error", "IRQ flag for DMA error."},
	LuaBuiltinDescriptor{"irq_geo_done", "irq_geo_done", "IRQ flag for GEO completion."},
	LuaBuiltinDescriptor{"irq_geo_error", "irq_geo_error", "IRQ flag for GEO error."},
	LuaBuiltinDescriptor{"irq_img_done", "irq_img_done", "IRQ flag for IMGDEC completion."},
	LuaBuiltinDescriptor{"irq_img_error", "irq_img_error", "IRQ flag for IMGDEC error."},
	LuaBuiltinDescriptor{"irq_vblank", "irq_vblank", "IRQ flag for VBLANK entry."},
	LuaBuiltinDescriptor{"irq_reinit", "irq_reinit", "IRQ flag for cart reinitialization events."},
	LuaBuiltinDescriptor{"irq_newgame", "irq_newgame", "IRQ flag for new-game start events."},
	LuaBuiltinDescriptor{"irq_apu", "irq_apu", "IRQ flag for APU voice events."},
	LuaBuiltinDescriptor{"apu_cmd_play", "apu_cmd_play", "APU command: play the handle in the selected slot."},
	LuaBuiltinDescriptor{"apu_cmd_stop_slot", "apu_cmd_stop_slot", "APU command: stop the selected slot."},
	LuaBuiltinDescriptor{"apu_cmd_set_slot_gain", "apu_cmd_set_slot_gain", "APU command: copy sys_apu_gain_q12 into the selected slot current-gain latch."},
	LuaBuiltinDescriptor{"apu_sample_rate_hz", "apu_sample_rate_hz", "APU hardware sample clock in Hz."},
	LuaBuiltinDescriptor{"apu_rate_step_q16_one", "apu_rate_step_q16_one", "APU Q16.16 rate-step value for normal speed."},
	LuaBuiltinDescriptor{"apu_gain_q12_one", "apu_gain_q12_one", "APU Q12 gain value for unity gain."},
	LuaBuiltinDescriptor{"apu_generator_none", "apu_generator_none", "APU generator kind: no internal generator; play source-DMA audio."},
	LuaBuiltinDescriptor{"apu_generator_square", "apu_generator_square", "APU generator kind: square oscillator clocked by the source-rate register."},
	LuaBuiltinDescriptor{"apu_output_queue_capacity_frames", "apu_output_queue_capacity_frames", "AOUT hardware output-ring capacity in PCM frames."},
	LuaBuiltinDescriptor{"apu_command_fifo_capacity", "apu_command_fifo_capacity", "APU command FIFO capacity in queued commands."},
	LuaBuiltinDescriptor{"apu_status_fault", "apu_status_fault", "APU status bit: sticky fault is latched."},
	LuaBuiltinDescriptor{"apu_status_selected_slot_active", "apu_status_selected_slot_active", "APU status bit: selected hardware slot is active."},
	LuaBuiltinDescriptor{"apu_status_busy", "apu_status_busy", "APU status bit: at least one hardware slot is pending or active."},
	LuaBuiltinDescriptor{"apu_status_output_empty", "apu_status_output_empty", "APU status bit: AOUT output ring has no queued PCM frames."},
	LuaBuiltinDescriptor{"apu_status_output_full", "apu_status_output_full", "APU status bit: AOUT output ring is full."},
	LuaBuiltinDescriptor{"apu_status_cmd_fifo_empty", "apu_status_cmd_fifo_empty", "APU status bit: command FIFO has no queued commands."},
	LuaBuiltinDescriptor{"apu_status_cmd_fifo_full", "apu_status_cmd_fifo_full", "APU status bit: command FIFO is full."},
	LuaBuiltinDescriptor{"apu_fault_none", "apu_fault_none", "APU fault code: no fault latched."},
	LuaBuiltinDescriptor{"apu_fault_bad_cmd", "apu_fault_bad_cmd", "APU fault code: unsupported command doorbell value."},
	LuaBuiltinDescriptor{"apu_fault_bad_slot", "apu_fault_bad_slot", "APU fault code: selected slot is outside the hardware slot bank."},
	LuaBuiltinDescriptor{"apu_fault_cmd_fifo_full", "apu_fault_cmd_fifo_full", "APU fault code: command FIFO is full."},
	LuaBuiltinDescriptor{"apu_fault_source_bytes", "apu_fault_source_bytes", "APU fault code: source byte length is zero."},
	LuaBuiltinDescriptor{"apu_fault_source_range", "apu_fault_source_range", "APU fault code: source range is outside readable RAM."},
	LuaBuiltinDescriptor{"apu_fault_source_sample_rate", "apu_fault_source_sample_rate", "APU fault code: source sample-rate register is invalid."},
	LuaBuiltinDescriptor{"apu_fault_source_channels", "apu_fault_source_channels", "APU fault code: source channel-count register is invalid."},
	LuaBuiltinDescriptor{"apu_fault_source_frame_count", "apu_fault_source_frame_count", "APU fault code: source frame-count register is zero."},
	LuaBuiltinDescriptor{"apu_fault_source_data_range", "apu_fault_source_data_range", "APU fault code: encoded source data range exceeds source bytes."},
	LuaBuiltinDescriptor{"apu_fault_source_bit_depth", "apu_fault_source_bit_depth", "APU fault code: source bit-depth register is unsupported."},
	LuaBuiltinDescriptor{"apu_fault_unsupported_format", "apu_fault_unsupported_format", "APU fault code: AOUT source header is not a supported encoded format."},
	LuaBuiltinDescriptor{"apu_fault_output_metadata", "apu_fault_output_metadata", "APU fault code: AOUT encoded source metadata does not match the slot registerfile."},
	LuaBuiltinDescriptor{"apu_fault_output_data_range", "apu_fault_output_data_range", "APU fault code: AOUT encoded source data range is invalid."},
	LuaBuiltinDescriptor{"apu_fault_output_playback_rate", "apu_fault_output_playback_rate", "APU fault code: AOUT playback step is not positive."},
	LuaBuiltinDescriptor{"apu_fault_output_block", "apu_fault_output_block", "APU fault code: AOUT encoded audio block is invalid."},
	LuaBuiltinDescriptor{"apu_filter_none", "apu_filter_none", "APU filter constant: no filter."},
	LuaBuiltinDescriptor{"apu_filter_lowpass", "apu_filter_lowpass", "APU filter constant: lowpass."},
	LuaBuiltinDescriptor{"apu_filter_highpass", "apu_filter_highpass", "APU filter constant: highpass."},
	LuaBuiltinDescriptor{"apu_filter_bandpass", "apu_filter_bandpass", "APU filter constant: bandpass."},
	LuaBuiltinDescriptor{"apu_filter_notch", "apu_filter_notch", "APU filter constant: notch."},
	LuaBuiltinDescriptor{"apu_filter_allpass", "apu_filter_allpass", "APU filter constant: allpass."},
	LuaBuiltinDescriptor{"apu_filter_peaking", "apu_filter_peaking", "APU filter constant: peaking."},
	LuaBuiltinDescriptor{"apu_filter_lowshelf", "apu_filter_lowshelf", "APU filter constant: lowshelf."},
	LuaBuiltinDescriptor{"apu_filter_highshelf", "apu_filter_highshelf", "APU filter constant: highshelf."},
	LuaBuiltinDescriptor{"apu_event_none", "apu_event_none", "APU event kind: no event."},
	LuaBuiltinDescriptor{"apu_event_slot_ended", "apu_event_slot_ended", "APU event kind: slot playback ended."},
	LuaBuiltinDescriptor{"dma_ctrl_start", "dma_ctrl_start", "DMA control bit: start transfer."},
	LuaBuiltinDescriptor{"dma_ctrl_strict", "dma_ctrl_strict", "DMA control bit: strict overflow handling."},
	LuaBuiltinDescriptor{"dma_status_busy", "dma_status_busy", "DMA status bit: busy."},
	LuaBuiltinDescriptor{"dma_status_done", "dma_status_done", "DMA status bit: done."},
	LuaBuiltinDescriptor{"dma_status_error", "dma_status_error", "DMA status bit: error."},
	LuaBuiltinDescriptor{"dma_status_clipped", "dma_status_clipped", "DMA status bit: clipped."},
	LuaBuiltinDescriptor{"dma_status_rejected", "dma_status_rejected", "DMA status bit: start request was rejected and no transfer began."},
	LuaBuiltinDescriptor{"sys_geo_ctrl_abort", "sys_geo_ctrl_abort", "GEO control bit: abort active job."},
	LuaBuiltinDescriptor{"geo_status_busy", "geo_status_busy", "GEO status bit: busy."},
	LuaBuiltinDescriptor{"geo_status_done", "geo_status_done", "GEO status bit: done."},
	LuaBuiltinDescriptor{"geo_status_error", "geo_status_error", "GEO status bit: error."},
	LuaBuiltinDescriptor{"geo_status_rejected", "geo_status_rejected", "GEO status bit: submission was rejected."},
	LuaBuiltinDescriptor{"sys_geo_cmd_xform2_batch", "sys_geo_cmd_xform2_batch", "GEO command opcode for batched 2D affine transforms."},
	LuaBuiltinDescriptor{"sys_geo_cmd_sat2_batch", "sys_geo_cmd_sat2_batch", "GEO command opcode for batched convex polygon SAT tests."},
	LuaBuiltinDescriptor{"sys_geo_cmd_overlap2d_pass", "sys_geo_cmd_overlap2d_pass", "GEO command opcode for the overlap2d coprocessor pass."},
	LuaBuiltinDescriptor{"sys_geo_index_none", "sys_geo_index_none", "GEO sentinel index meaning no destination record."},
	LuaBuiltinDescriptor{"sys_geo_primitive_aabb", "sys_geo_primitive_aabb", "GEO primitive kind for an AABB descriptor."},
	LuaBuiltinDescriptor{"sys_geo_primitive_convex_poly", "sys_geo_primitive_convex_poly", "GEO primitive kind for a convex polygon descriptor."},
	LuaBuiltinDescriptor{"sys_geo_shape_convex_poly", "sys_geo_shape_convex_poly", "GEO descriptor flag for convex polygon shapes."},
	LuaBuiltinDescriptor{"sys_geo_vertex2_bytes", "sys_geo_vertex2_bytes", "GEO shared 2D vertex record size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_vertex2_x_offset", "sys_geo_vertex2_x_offset", "Byte offset of X in a GEO 2D vertex record."},
	LuaBuiltinDescriptor{"sys_geo_vertex2_y_offset", "sys_geo_vertex2_y_offset", "Byte offset of Y in a GEO 2D vertex record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_record_bytes", "sys_geo_xform2_record_bytes", "GEO xform2 command record size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_xform2_record_flags_offset", "sys_geo_xform2_record_flags_offset", "Byte offset of flags in a GEO xform2 record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_record_src_index_offset", "sys_geo_xform2_record_src_index_offset", "Byte offset of source vertex index in a GEO xform2 record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_record_dst_index_offset", "sys_geo_xform2_record_dst_index_offset", "Byte offset of destination vertex index in a GEO xform2 record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_record_aux_index_offset", "sys_geo_xform2_record_aux_index_offset", "Byte offset of matrix index in a GEO xform2 record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_record_vertex_count_offset", "sys_geo_xform2_record_vertex_count_offset", "Byte offset of vertex count in a GEO xform2 record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_record_dst1_index_offset", "sys_geo_xform2_record_dst1_index_offset", "Byte offset of optional AABB index in a GEO xform2 record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_matrix_bytes", "sys_geo_xform2_matrix_bytes", "GEO xform2 matrix record size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_xform2_matrix_m00_offset", "sys_geo_xform2_matrix_m00_offset", "Byte offset of m00 in a GEO xform2 matrix record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_matrix_m01_offset", "sys_geo_xform2_matrix_m01_offset", "Byte offset of m01 in a GEO xform2 matrix record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_matrix_tx_offset", "sys_geo_xform2_matrix_tx_offset", "Byte offset of tx in a GEO xform2 matrix record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_matrix_m10_offset", "sys_geo_xform2_matrix_m10_offset", "Byte offset of m10 in a GEO xform2 matrix record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_matrix_m11_offset", "sys_geo_xform2_matrix_m11_offset", "Byte offset of m11 in a GEO xform2 matrix record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_matrix_ty_offset", "sys_geo_xform2_matrix_ty_offset", "Byte offset of ty in a GEO xform2 matrix record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_aabb_bytes", "sys_geo_xform2_aabb_bytes", "GEO xform2 output AABB record size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_xform2_aabb_min_x_offset", "sys_geo_xform2_aabb_min_x_offset", "Byte offset of min X in a GEO xform2 AABB record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_aabb_min_y_offset", "sys_geo_xform2_aabb_min_y_offset", "Byte offset of min Y in a GEO xform2 AABB record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_aabb_max_x_offset", "sys_geo_xform2_aabb_max_x_offset", "Byte offset of max X in a GEO xform2 AABB record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_aabb_max_y_offset", "sys_geo_xform2_aabb_max_y_offset", "Byte offset of max Y in a GEO xform2 AABB record."},
	LuaBuiltinDescriptor{"sys_geo_xform2_max_vertices", "sys_geo_xform2_max_vertices", "GEO xform2 per-record vertex capacity."},
	LuaBuiltinDescriptor{"sys_geo_sat2_pair_bytes", "sys_geo_sat2_pair_bytes", "GEO sat2 pair record size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_sat2_pair_flags_offset", "sys_geo_sat2_pair_flags_offset", "Byte offset of flags in a GEO sat2 pair record."},
	LuaBuiltinDescriptor{"sys_geo_sat2_pair_shape_a_index_offset", "sys_geo_sat2_pair_shape_a_index_offset", "Byte offset of shape A index in a GEO sat2 pair record."},
	LuaBuiltinDescriptor{"sys_geo_sat2_pair_result_index_offset", "sys_geo_sat2_pair_result_index_offset", "Byte offset of result index in a GEO sat2 pair record."},
	LuaBuiltinDescriptor{"sys_geo_sat2_pair_shape_b_index_offset", "sys_geo_sat2_pair_shape_b_index_offset", "Byte offset of shape B index in a GEO sat2 pair record."},
	LuaBuiltinDescriptor{"sys_geo_sat2_pair_flags2_offset", "sys_geo_sat2_pair_flags2_offset", "Byte offset of secondary flags in a GEO sat2 pair record."},
	LuaBuiltinDescriptor{"sys_geo_sat2_desc_bytes", "sys_geo_sat2_desc_bytes", "GEO sat2 shape descriptor size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_sat2_desc_flags_offset", "sys_geo_sat2_desc_flags_offset", "Byte offset of flags in a GEO sat2 descriptor."},
	LuaBuiltinDescriptor{"sys_geo_sat2_desc_vertex_count_offset", "sys_geo_sat2_desc_vertex_count_offset", "Byte offset of vertex count in a GEO sat2 descriptor."},
	LuaBuiltinDescriptor{"sys_geo_sat2_desc_vertex_offset_offset", "sys_geo_sat2_desc_vertex_offset_offset", "Byte offset of vertex data offset in a GEO sat2 descriptor."},
	LuaBuiltinDescriptor{"sys_geo_sat2_desc_reserved_offset", "sys_geo_sat2_desc_reserved_offset", "Byte offset of reserved word in a GEO sat2 descriptor."},
	LuaBuiltinDescriptor{"sys_geo_sat2_result_bytes", "sys_geo_sat2_result_bytes", "GEO sat2 result record size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_sat2_result_hit_offset", "sys_geo_sat2_result_hit_offset", "Byte offset of hit flag in a GEO sat2 result record."},
	LuaBuiltinDescriptor{"sys_geo_sat2_result_nx_offset", "sys_geo_sat2_result_nx_offset", "Byte offset of normal X in a GEO sat2 result record."},
	LuaBuiltinDescriptor{"sys_geo_sat2_result_ny_offset", "sys_geo_sat2_result_ny_offset", "Byte offset of normal Y in a GEO sat2 result record."},
	LuaBuiltinDescriptor{"sys_geo_sat2_result_depth_offset", "sys_geo_sat2_result_depth_offset", "Byte offset of penetration depth in a GEO sat2 result record."},
	LuaBuiltinDescriptor{"sys_geo_sat2_result_meta_offset", "sys_geo_sat2_result_meta_offset", "Byte offset of metadata in a GEO sat2 result record."},
	LuaBuiltinDescriptor{"sys_geo_sat2_max_poly_vertices", "sys_geo_sat2_max_poly_vertices", "GEO sat2 convex-polygon vertex scratch capacity."},
	LuaBuiltinDescriptor{"sys_geo_overlap_mode_candidate_pairs", "sys_geo_overlap_mode_candidate_pairs", "GEO overlap2d mode for explicit candidate-pair input."},
	LuaBuiltinDescriptor{"sys_geo_overlap_mode_full_pass", "sys_geo_overlap_mode_full_pass", "GEO overlap2d mode for full instance-pair traversal."},
	LuaBuiltinDescriptor{"sys_geo_overlap_broadphase_none", "sys_geo_overlap_broadphase_none", "GEO overlap2d broadphase policy: no device broadphase."},
	LuaBuiltinDescriptor{"sys_geo_overlap_broadphase_local_bounds_aabb", "sys_geo_overlap_broadphase_local_bounds_aabb", "GEO overlap2d broadphase policy: local-bounds AABB."},
	LuaBuiltinDescriptor{"sys_geo_overlap_contact_clipped_feature", "sys_geo_overlap_contact_clipped_feature", "GEO overlap2d contact policy: clipped feature point."},
	LuaBuiltinDescriptor{"sys_geo_overlap_output_stop_on_overflow", "sys_geo_overlap_output_stop_on_overflow", "GEO overlap2d output policy: stop and fault on result overflow."},
	LuaBuiltinDescriptor{"sys_geo_overlap_max_poly_vertices", "sys_geo_overlap_max_poly_vertices", "GEO overlap2d per-piece polygon vertex scratch capacity."},
	LuaBuiltinDescriptor{"sys_geo_overlap_max_clip_vertices", "sys_geo_overlap_max_clip_vertices", "GEO overlap2d clipped-contact vertex scratch capacity."},
	LuaBuiltinDescriptor{"sys_geo_overlap_instance_bytes", "sys_geo_overlap_instance_bytes", "GEO overlap2d instance record size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_overlap_instance_shape_offset", "sys_geo_overlap_instance_shape_offset", "Byte offset of the shape address field in a GEO overlap2d instance record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_instance_tx_offset", "sys_geo_overlap_instance_tx_offset", "Byte offset of the world translation X field in a GEO overlap2d instance record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_instance_ty_offset", "sys_geo_overlap_instance_ty_offset", "Byte offset of the world translation Y field in a GEO overlap2d instance record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_instance_layer_offset", "sys_geo_overlap_instance_layer_offset", "Byte offset of the layer field in a GEO overlap2d instance record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_instance_mask_offset", "sys_geo_overlap_instance_mask_offset", "Byte offset of the mask field in a GEO overlap2d instance record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_pair_bytes", "sys_geo_overlap_pair_bytes", "GEO overlap2d candidate-pair record size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_overlap_pair_instance_a_offset", "sys_geo_overlap_pair_instance_a_offset", "Byte offset of instance A in a GEO overlap2d candidate-pair record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_pair_instance_b_offset", "sys_geo_overlap_pair_instance_b_offset", "Byte offset of instance B in a GEO overlap2d candidate-pair record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_pair_meta_offset", "sys_geo_overlap_pair_meta_offset", "Byte offset of pair metadata in a GEO overlap2d candidate-pair record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_result_bytes", "sys_geo_overlap_result_bytes", "GEO overlap2d result record size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_overlap_result_nx_offset", "sys_geo_overlap_result_nx_offset", "Byte offset of normal X in a GEO overlap2d result record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_result_ny_offset", "sys_geo_overlap_result_ny_offset", "Byte offset of normal Y in a GEO overlap2d result record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_result_depth_offset", "sys_geo_overlap_result_depth_offset", "Byte offset of penetration depth in a GEO overlap2d result record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_result_px_offset", "sys_geo_overlap_result_px_offset", "Byte offset of contact point X in a GEO overlap2d result record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_result_py_offset", "sys_geo_overlap_result_py_offset", "Byte offset of contact point Y in a GEO overlap2d result record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_result_piece_a_offset", "sys_geo_overlap_result_piece_a_offset", "Byte offset of winning piece A in a GEO overlap2d result record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_result_piece_b_offset", "sys_geo_overlap_result_piece_b_offset", "Byte offset of winning piece B in a GEO overlap2d result record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_result_feature_meta_offset", "sys_geo_overlap_result_feature_meta_offset", "Byte offset of feature metadata in a GEO overlap2d result record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_result_pair_meta_offset", "sys_geo_overlap_result_pair_meta_offset", "Byte offset of pair metadata in a GEO overlap2d result record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_summary_bytes", "sys_geo_overlap_summary_bytes", "GEO overlap2d summary record size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_overlap_summary_result_count_offset", "sys_geo_overlap_summary_result_count_offset", "Byte offset of result count in a GEO overlap2d summary record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_summary_exact_pair_count_offset", "sys_geo_overlap_summary_exact_pair_count_offset", "Byte offset of exact-pair count in a GEO overlap2d summary record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_summary_broadphase_pair_count_offset", "sys_geo_overlap_summary_broadphase_pair_count_offset", "Byte offset of broadphase-pair count in a GEO overlap2d summary record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_summary_flags_offset", "sys_geo_overlap_summary_flags_offset", "Byte offset of flags in a GEO overlap2d summary record."},
	LuaBuiltinDescriptor{"sys_geo_overlap_summary_flag_overflow", "sys_geo_overlap_summary_flag_overflow", "Flag bit set when a GEO overlap2d pass overflowed result capacity."},
	LuaBuiltinDescriptor{"sys_geo_overlap_shape_desc_bytes", "sys_geo_overlap_shape_desc_bytes", "GEO overlap2d shape descriptor size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_overlap_shape_kind_offset", "sys_geo_overlap_shape_kind_offset", "Byte offset of primitive kind in a GEO overlap2d shape descriptor."},
	LuaBuiltinDescriptor{"sys_geo_overlap_shape_kind_compound", "sys_geo_overlap_shape_kind_compound", "GEO overlap2d shape kind for compound descriptors."},
	LuaBuiltinDescriptor{"sys_geo_overlap_shape_data_count_offset", "sys_geo_overlap_shape_data_count_offset", "Byte offset of data count in a GEO overlap2d shape descriptor."},
	LuaBuiltinDescriptor{"sys_geo_overlap_shape_data_offset_offset", "sys_geo_overlap_shape_data_offset_offset", "Byte offset of data offset in a GEO overlap2d shape descriptor."},
	LuaBuiltinDescriptor{"sys_geo_overlap_shape_bounds_offset_offset", "sys_geo_overlap_shape_bounds_offset_offset", "Byte offset of bounds offset in a GEO overlap2d shape descriptor."},
	LuaBuiltinDescriptor{"sys_geo_overlap_shape_bounds_bytes", "sys_geo_overlap_shape_bounds_bytes", "GEO overlap2d shape bounds payload size in bytes."},
	LuaBuiltinDescriptor{"sys_geo_overlap_shape_bounds_left_offset", "sys_geo_overlap_shape_bounds_left_offset", "Byte offset of left in a GEO overlap2d shape bounds payload."},
	LuaBuiltinDescriptor{"sys_geo_overlap_shape_bounds_top_offset", "sys_geo_overlap_shape_bounds_top_offset", "Byte offset of top in a GEO overlap2d shape bounds payload."},
	LuaBuiltinDescriptor{"sys_geo_overlap_shape_bounds_right_offset", "sys_geo_overlap_shape_bounds_right_offset", "Byte offset of right in a GEO overlap2d shape bounds payload."},
	LuaBuiltinDescriptor{"sys_geo_overlap_shape_bounds_bottom_offset", "sys_geo_overlap_shape_bounds_bottom_offset", "Byte offset of bottom in a GEO overlap2d shape bounds payload."},
	LuaBuiltinDescriptor{"sys_geo_overlap_aabb_data_count", "sys_geo_overlap_aabb_data_count", "Data-count value for a GEO overlap2d AABB descriptor."},
	LuaBuiltinDescriptor{"sys_geo_overlap_aabb_shape_bytes", "sys_geo_overlap_aabb_shape_bytes", "GEO overlap2d BIOS AABB shape footprint in bytes."},
	LuaBuiltinDescriptor{"sys_geo_overlap_pair_meta_instance_a_shift", "sys_geo_overlap_pair_meta_instance_a_shift", "Bit shift for instance A in GEO overlap2d result pair metadata."},
	LuaBuiltinDescriptor{"sys_geo_overlap_pair_meta_instance_a_mask", "sys_geo_overlap_pair_meta_instance_a_mask", "Mask for instance A in GEO overlap2d result pair metadata after shifting."},
	LuaBuiltinDescriptor{"sys_geo_overlap_pair_meta_instance_b_mask", "sys_geo_overlap_pair_meta_instance_b_mask", "Mask for instance B in GEO overlap2d result pair metadata."},
	LuaBuiltinDescriptor{"sys_geo_sat_meta_axis_mask", "sys_geo_sat_meta_axis_mask", "Mask for the SAT axis index bits in the GEO result meta word."},
	LuaBuiltinDescriptor{"sys_geo_sat_meta_shape_shift", "sys_geo_sat_meta_shape_shift", "Bit shift for the SAT shape selector bits in the GEO result meta word."},
	LuaBuiltinDescriptor{"sys_geo_sat_meta_shape_src", "sys_geo_sat_meta_shape_src", "SAT meta value meaning the winning axis came from shape A."},
	LuaBuiltinDescriptor{"sys_geo_sat_meta_shape_aux", "sys_geo_sat_meta_shape_aux", "SAT meta value meaning the winning axis came from shape B."},
	LuaBuiltinDescriptor{"sys_geo_fault_aborted_by_host", "sys_geo_fault_aborted_by_host", "GEO fault code: active job aborted by host."},
	LuaBuiltinDescriptor{"sys_geo_fault_bad_record_alignment", "sys_geo_fault_bad_record_alignment", "GEO fault code: record or offset alignment was invalid."},
	LuaBuiltinDescriptor{"sys_geo_fault_bad_vertex_count", "sys_geo_fault_bad_vertex_count", "GEO fault code: vertex count was invalid for the record."},
	LuaBuiltinDescriptor{"sys_geo_fault_src_range", "sys_geo_fault_src_range", "GEO fault code: source read range was invalid."},
	LuaBuiltinDescriptor{"sys_geo_fault_dst_range", "sys_geo_fault_dst_range", "GEO fault code: destination write range was invalid."},
	LuaBuiltinDescriptor{"sys_geo_fault_descriptor_kind", "sys_geo_fault_descriptor_kind", "GEO fault code: descriptor kind or reserved bits were invalid."},
	LuaBuiltinDescriptor{"sys_geo_fault_numeric_overflow_internal", "sys_geo_fault_numeric_overflow_internal", "GEO fault code: internal numeric overflow or NaN occurred."},
	LuaBuiltinDescriptor{"sys_geo_fault_bad_record_flags", "sys_geo_fault_bad_record_flags", "GEO fault code: record flags were non-zero or unsupported."},
	LuaBuiltinDescriptor{"sys_geo_fault_result_capacity", "sys_geo_fault_result_capacity", "GEO fault code: result table capacity was exhausted."},
	LuaBuiltinDescriptor{"sys_geo_fault_code_shift", "sys_geo_fault_code_shift", "Bit shift for the fault code field in the GEO fault word."},
	LuaBuiltinDescriptor{"sys_geo_fault_code_mask", "sys_geo_fault_code_mask", "Mask for the fault code field before packing or after shifting."},
	LuaBuiltinDescriptor{"sys_geo_fault_record_index_mask", "sys_geo_fault_record_index_mask", "Mask for the record index field in the GEO fault word."},
	LuaBuiltinDescriptor{"sys_geo_fault_record_index_none", "sys_geo_fault_record_index_none", "GEO fault record-index sentinel used for submit-time rejects."},
	LuaBuiltinDescriptor{"sys_geo_fault_reject_busy", "sys_geo_fault_reject_busy", "GEO reject fault: host started a job while GEO was busy."},
	LuaBuiltinDescriptor{"sys_geo_fault_reject_bad_cmd", "sys_geo_fault_reject_bad_cmd", "GEO reject fault: command was unsupported."},
	LuaBuiltinDescriptor{"sys_geo_fault_reject_bad_stride", "sys_geo_fault_reject_bad_stride", "GEO reject fault: register stride values were invalid."},
	LuaBuiltinDescriptor{"sys_geo_fault_reject_dst_not_ram", "sys_geo_fault_reject_dst_not_ram", "GEO reject fault: destination register pointed outside RAM."},
	LuaBuiltinDescriptor{"sys_geo_fault_reject_misaligned_regs", "sys_geo_fault_reject_misaligned_regs", "GEO reject fault: register pointers were not word-aligned."},
	LuaBuiltinDescriptor{"sys_geo_fault_reject_bad_register_combo", "sys_geo_fault_reject_bad_register_combo", "GEO reject fault: register combination was invalid for the command."},
	LuaBuiltinDescriptor{"img_ctrl_start", "img_ctrl_start", "IMGDEC control bit: start decode."},
	LuaBuiltinDescriptor{"img_status_busy", "img_status_busy", "IMGDEC status bit: busy."},
	LuaBuiltinDescriptor{"img_status_done", "img_status_done", "IMGDEC status bit: done."},
	LuaBuiltinDescriptor{"img_status_error", "img_status_error", "IMGDEC status bit: error."},
	LuaBuiltinDescriptor{"img_status_clipped", "img_status_clipped", "IMGDEC status bit: clipped."},
	LuaBuiltinDescriptor{"img_status_rejected", "img_status_rejected", "IMGDEC status bit: start request was rejected."},
	LuaBuiltinDescriptor{"inp_ctrl_commit", "inp_ctrl_commit", "Input Controller command: commit sys_inp_action plus sys_inp_bind into the chip context."},
	LuaBuiltinDescriptor{"inp_ctrl_arm", "inp_ctrl_arm", "Input Controller command: arm the next VBLANK input sample."},
	LuaBuiltinDescriptor{"inp_ctrl_reset", "inp_ctrl_reset", "Input Controller command: pop the chip context for the current player and clear its actions."},
	LuaBuiltinDescriptor{"inp_status_pressed", "inp_status_pressed", "Input Controller status bit: action is currently pressed."},
	LuaBuiltinDescriptor{"inp_status_justpressed", "inp_status_justpressed", "Input Controller status bit: action was pressed on the sampled frame."},
	LuaBuiltinDescriptor{"inp_status_justreleased", "inp_status_justreleased", "Input Controller status bit: action was released on the sampled frame."},
	LuaBuiltinDescriptor{"inp_status_waspressed", "inp_status_waspressed", "Input Controller status bit: action was pressed inside the sampled buffer window."},
	LuaBuiltinDescriptor{"inp_status_wasreleased", "inp_status_wasreleased", "Input Controller status bit: action was released inside the sampled buffer window."},
	LuaBuiltinDescriptor{"inp_status_consumed", "inp_status_consumed", "Input Controller status bit: action was consumed."},
	LuaBuiltinDescriptor{"inp_status_alljustpressed", "inp_status_alljustpressed", "Input Controller status bit: all bindings were just pressed."},
	LuaBuiltinDescriptor{"inp_status_alljustreleased", "inp_status_alljustreleased", "Input Controller status bit: all bindings were just released."},
	LuaBuiltinDescriptor{"inp_status_allwaspressed", "inp_status_allwaspressed", "Input Controller status bit: all bindings were pressed inside the sampled buffer window."},
	LuaBuiltinDescriptor{"inp_status_guardedjustpressed", "inp_status_guardedjustpressed", "Input Controller status bit: guarded just-pressed accepted this edge."},
	LuaBuiltinDescriptor{"inp_status_repeatpressed", "inp_status_repeatpressed", "Input Controller status bit: repeat pulse fired this sampled frame."},
	LuaBuiltinDescriptor{"inp_status_has_value", "inp_status_has_value", "Input Controller status bit: sys_inp_value contains an action value."},
	LuaBuiltinDescriptor{"inp_event_status_empty", "inp_event_status_empty", "Input Controller event FIFO status bit: FIFO is empty."},
	LuaBuiltinDescriptor{"inp_event_status_full", "inp_event_status_full", "Input Controller event FIFO status bit: FIFO is full."},
	LuaBuiltinDescriptor{"inp_event_status_overflow", "inp_event_status_overflow", "Input Controller event FIFO status bit: at least one event was dropped while full."},
	LuaBuiltinDescriptor{"inp_event_ctrl_pop", "inp_event_ctrl_pop", "Input Controller event FIFO command: pop the front event."},
	LuaBuiltinDescriptor{"inp_event_ctrl_clear", "inp_event_ctrl_clear", "Input Controller event FIFO command: clear queued events and the overflow latch."},
	LuaBuiltinDescriptor{"inp_event_fifo_capacity", "inp_event_fifo_capacity", "Input Controller event FIFO capacity in entries."},
}};

constexpr std::array<LuaBuiltinDescriptor, 0> kDefaultLuaBuiltinGlobals{{
}};


template <typename T, size_t N>
std::span<const T> asSpan(const std::array<T, N>& values) {
	return std::span<const T>(values.data(), values.size());
}

} // namespace

std::span<const LuaBuiltinDescriptor> systemLuaBuiltinFunctions() {
	return asSpan(kSystemLuaBuiltinFunctions);
}

std::span<const LuaBuiltinDescriptor> systemLuaBuiltinGlobals() {
	return asSpan(kSystemLuaBuiltinGlobals);
}

std::span<const LuaBuiltinDescriptor> defaultLuaBuiltinFunctions() {
	return asSpan(kDefaultLuaBuiltinFunctions);
}

std::span<const LuaBuiltinDescriptor> defaultLuaBuiltinGlobals() {
	return asSpan(kDefaultLuaBuiltinGlobals);
}


const LuaBuiltinDescriptor* findDefaultLuaBuiltinDescriptor(std::string_view name) {
	const auto builtins = defaultLuaBuiltinFunctions();
	auto it = std::find_if(builtins.begin(), builtins.end(), [name](const LuaBuiltinDescriptor& descriptor) {
		return descriptor.name == name;
	});
	if (it == builtins.end()) {
		return nullptr;
	}
	return &*it;
}

} // namespace bmsx
